import fs from 'node:fs';
import crypto from 'node:crypto';
const dir='artifacts/review-integrale-2026-10-02/', l=JSON.parse(fs.readFileSync(dir+'VOL-09-ledger.json','utf8'));
const rows:any[]=[];
function add(ch:number,line:number,severity:string,excerpt:string,problem:string,proposal:string){rows.push({id:`V09-${String(rows.length+1).padStart(2,'0')}`,chapter:ch,path:ch?l.chapters[ch-1].path:'wiki/books/moduli/m-tr02-appalti-pnrr-fondi-ue/planning/01-indice-analitico-vol-09.md',line,severity,excerpt,problem,proposal,status:'non applicato'});}
add(1,92,'grave','## Nucleo','Un titolo interrompe una tabella Markdown, lasciando le righe successive senza intestazione. Difetto analogo nel cap.5 r.137 e cap.9 r.209.','Spostare i titoli fuori dalle tabelle e verificare il rendering delle strutture intere.');
add(6,173,'grave','Quiz 3','Titoli di nucleo inseriti dentro unità didattiche: cap.6 dentro quiz2; cap.9 r.151 fra domanda2 e opzioni; cap.12 r.195 fra opzioni C e D; cap.2 r.232 fra domanda e risposta.','Ricostruire la gerarchia dei titoli mantenendo domanda, opzioni, risposta e commento nella stessa unità; non limitarsi al CSS.');
add(3,328,'medio','Fase 4','Titoli aggiunti spezzano fasi e casi: cap.3 fase3; cap.4 r.314 fase4; cap.8 r.80 elenco; cap.13 r.266 simulazione1; cap.14 rr.187 e305 consegna e simulazione9.','Spostare ogni titolo all’inizio effettivo del blocco, rinumerare e riallineare mappa dei nuclei.');
add(13,76,'medio','N-TR02-XX-04','Restano codici provvisori XX nei nuclei (anche rr.84,174).','Sostituire i segnaposto con gli identificatori reali dopo verifica della mappa; eliminare dal testo commerciale gli apparati di audit.');
add(1,110,'medio','Il pagamento riguarda la liquidazione','Confusione fra due fasi della spesa.','Distinguere liquidazione, ordinazione e pagamento e indicare l’ordinamento contabile assunto.');
add(2,48,'grave','classi','Qualificazione e autonomia di acquisto sono promesse ma il testo evita classi, soglie e requisiti: i soli indizi di capacità alle rr.128–134 non permettono di risolvere un caso.','Sviluppare artt.62–63 e allegato II.4 nel testo vigente, livelli, requisiti, acquisti autonomi e obblighi di ricorso a soggetti qualificati, con esempio datato.');
add(2,106,'grave','responsabili di fase','Nomina/requisiti del RUP e articolazione delle fasi restano descrittivi; DEC presentato come eventuale senza distinguere funzione e nomina separata.','Integrare art.15, allegato I.2 e regole DEC con gruppi di fasi corretti, nomina, requisiti, responsabilità e caso di separazione RUP/DEC.');
add(2,147,'medio','RACI','La matrice assegna genericamente valutazione delle offerte ad altri organi e liquidazione alla finanza, senza distinguere attività tecnica, approvazione e competenze dell’ente.','Dichiarare il modello organizzativo, separare valutazione/adozione del provvedimento e motivare A/R per ogni attività.');
add(3,201,'grave','programmazione','Assenti disciplina operativa della programmazione e un esempio: durata, aggiornamento, presupposti di inserimento, CUI e schemi non sono insegnati.','Integrare art.37 e allegato I.5 distinguendo lavori/acquisti, soglie e aggiornamenti; compilare una riga di programma.');
add(3,172,'grave','lotti','La scelta dei lotti non espone la regola e l’onere di motivazione dell’art.58; il calcolo del valore non tratta sistematicamente IVA, opzioni, rinnovi e aggregazione.','Spiegare artt.14 e58 con calcolo numerico e caso di mancata suddivisione motivata.');
add(4,128,'grave','requisiti','Cause automatiche/non automatiche, grave illecito professionale, self-cleaning, avvalimento e RTI sono assenti o solo nominati; mancano condizioni per OEPV/minor prezzo e soccorso istruttorio.','Sviluppare nuclei distinti con artt.94–101 e108, termini, limiti e casi; risolvere un esempio di requisito e uno di soccorso.');
add(4,77,'grave','avvio','La documentazione della gara è descritta senza gli elementi essenziali della decisione di contrarre e dell’affidamento diretto; nessun atto effettivamente compilato.','Integrare art.17 e fornire almeno un atto annotato, distinguendo motivazione, requisiti e oggetto.');
add(4,122,'medio','promessa senza conseguenza','Il rapporto capitolato/contratto può far pensare che un obbligo non ripetuto nel contratto non produca effetti, senza considerare il richiamo e l’incorporazione documentale.','Precisare gerarchia, richiamo e valore dei documenti contrattuali, evitando una regola assoluta.');
add(5,46,'grave','importi','Il capitolo sotto soglia esclude deliberatamente gli importi e non sviluppa procedure, numero di operatori, interesse transfrontaliero, deroghe alla rotazione e controlli semplificati.','Inserire quadro datato degli artt.48–52, soglie UE2026 e nazionali distinte, rotazione con presupposti cumulativi/eccezioni e verifica requisiti sotto40000 euro; aggiungere casi con importi.');
add(5,30,'medio','altri limiti','La definizione di sotto soglia mescola soglia europea e altri limiti interni.','Definire sotto soglia rispetto alle soglie UE e distinguere i limiti nazionali che selezionano la procedura.');
add(6,106,'grave','FVOE','Il flusso digitale non insegna certificazione PAD, pubblicità legale, rapporto PCP/BDNCP/FVOE, adempimenti di trasparenza ed eForms con sufficienti riferimenti e passaggi.','Integrare artt.19–36 e atti ANAC applicabili, una sequenza temporale reale e il significato del lotto per CIG; qualificare la tabella se non cronologica.');
add(7,102,'grave','obblighi','Gli obblighi di acquisto centralizzato, inclusi quelli ICT, sono rinviati alla verifica: non esiste la matrice ente/oggetto/importo/strumento/eccezione promessa.','Sviluppare le pertinenti disposizioni delle leggi488/1999,296/2006 e208/2015 e compilare casi, distinguendo obbligo di parametro e obbligo di strumento.');
add(7,132,'grave','lavori di manutenzione','Il MePA è limitato ai lavori di manutenzione, ma Consip documenta dal2022 il Bando Lavori per tutte le tipologie, incluse nuove opere.','Correggere l’ambito e distinguerlo dallo SDA Lavori di manutenzione; citare la documentazione specifica del bando.');
add(7,111,'grave','accordo quadro','AQ e SDAPA sono spiegati senza durata ordinaria/deroghe, modelli di aggiudicazione, apertura continua e inviti agli ammessi per categoria. ASP non è sciolto.','Integrare artt.32 e59, una tabella di confronto operativa ed espandere Application Service Provider.');
add(8,164,'grave','subappalto','Il capitolo di esecuzione elenca istituti senza insegnare presupposti/limiti di subappalto, modifiche, proroghe, sospensione, penali, collaudo/CRE e CCT; la matrice stessa conserva source-blocker.','Completare artt.119–126 e allegati pertinenti con regole, soggetti, atti, termini ed esempi; verificare le fonti bloccanti prima della chiusura.');
add(8,188,'grave','clausola','La revisione prezzi è trattata come eventualità contrattuale senza esporre obbligatorietà della clausola e meccanismi distinti per lavori/servizi-forniture.','Sviluppare art.60 e allegato II.2-bis nella versione vigente e un calcolo svolto, distinguendo prezzi e altre modifiche.');
add(8,132,'medio','pagamento','Il pagamento segue sempre la verifica della prestazione nella sequenza proposta; manca l’anticipazione.','Dichiarare che la sequenza descrive il saldo/corrispettivo della prestazione e trattare separatamente anticipazione e garanzia ai sensi dell’art.125.');
add(9,203,'grave','accesso','Il caso parte soltanto da una richiesta, senza disponibilità digitale automatica, regime dei primi cinque, oscuramento e rito speciale dell’art.36.','Insegnare artt.35–36 con timeline e presupposti; distinguere accesso e impugnazione dell’aggiudicazione, senza indurre ad attendere il fascicolo oltre i termini.');
add(9,299,'grave','cautelare','Mancano standstill sostanziale/processuale, riparto di giurisdizione, termini del rito appalti, effetti del precontenzioso, presupposti di accordo bonario e arbitrato.','Completare artt.18,210ss.,220 e art.120 CPA nel testo corrente, con eccezioni e casi; precisare le ipotesi di divieto legale di stipula indipendenti da un ordine giudiziale.');
add(9,197,'lieve','sei','Annuncia sei elementi e ne elenca sette.','Allineare il numero all’elenco.');
add(10,53,'grave','architettura','Mancano struttura giuridica RRF/PNRR, missioni/componenti e REPowerEU, CID/accordi operativi, natura performance-based e calendario2026; milestone e target non sono fissati come qualitativi/quantitativi.','Integrare regolamento2021/241, governance e quadro temporale datato; distinguere livelli UE/misura/progetto e compilare un esempio.');
add(10,136,'grave','ReGiS','Il monitoraggio resta una richiesta di coerenza; non spiega soggetti, alimentazione, prevalidazione/validazione, scadenze e controlli.','Descrivere un ciclo operativo con responsabilità e fonte RGS, separando regole comuni e istruzioni della misura.');
add(11,120,'grave','tracciabilità','CIG/CUP sono nominati senza disciplina di conti, comunicazioni, filiera, clausole, fatture e conseguenze; il caso di fattura già pagata senza CIG non espone la specifica regola ostativa.','Integrare legge136/2010 art.3, legge3/2003 art.11 e DL66/2014 art.25, con ambiti/esclusioni e soluzione del caso; mostrare un calcolo di spesa ammissibile.');
add(11,198,'grave','antifrode','La distinzione frode/irregolarità, titolare effettivo, conflitto di interessi e controlli è ridotta a elenchi generici.','Definire gli istituti e collegare artt.22 RRF e61 regolamento finanziario alla documentazione del soggetto attuatore, con caso risolto e fonti correnti.');
add(12,88,'grave','DNSH','I sei obiettivi sono corretti, ma non sono insegnati fondamento, regimi e raccordo della Guida RGS con schede e verifiche ex ante/ex post.','Integrare art.17 regolamento2020/852 e disciplina RRF, identificare edizione della guida/istruzioni applicabili e compilare una scheda con evidenze.');
add(12,129,'grave','CAM','Non emerge con precisione il minimo obbligatorio di specifiche tecniche e clausole contrattuali, distinto dai criteri premianti; nessun decreto/criterio reale sviluppato nel caso arredi.','Integrare art.57c2 e decreto CAM vigente per la categoria, riprodurre un criterio breve con mezzo di prova e verifica; evitare che un requisito obbligatorio diventi soltanto premiale.');
add(13,284,'medio','formazione','La soluzione considera errata la formazione prima del completamento dei test senza fornire dipendenze che lo rendano necessario.','Specificare il vincolo del caso o ammettere formazione parallela ai test quando sostenibile; distinguere dipendenza tecnica da scelta organizzativa.');
add(13,54,'medio','risultato','Risultato coincide col prodotto finale, mentre altri capitoli lo distinguono dall’output; WBS è definita per attività nel cap.1 r.204 e per deliverable qui.','Uniformare output/outcome e convenzione WBS; usare il medesimo progetto per dimostrare le differenze.');
add(13,232,'grave','WBS','Il toolkit PM non contiene una WBS a tre livelli risolta, un Gantt con date/durate o un calcolo del percorso critico; le soluzioni indicano criteri anziché artefatti.','Fornire dataset, artefatti compilati e ragionamento verificabile; associare una fonte metodologica identificabile.');
add(14,169,'grave','soglie','La prudenza sui dati mancanti della traccia è estesa alle norme che il candidato deve sapere; simulazioni senza importi, atti o timeline non verificano competenza specialistica.','Dare i fatti necessari e chiedere l’applicazione del diritto insegnato, con soluzioni complete e rubriche; non sostituire la teoria con inviti a verificare.');
add(14,1,'grave','laboratorio','La matrice dichiara diario e piano30/60/90 presenti nel capitolo14, ma il testo non li contiene; numerose evidenze citano titoli non corrispondenti.','Riallineare matrice e testo sulla presenza effettiva, mantenendo aperti i nuclei mancanti.');
add(0,1,'grave','Appendice A','Le cinque appendici A–E promesse nell’indice analitico non sono nei capitoli né nelle21unità dell’export corrente controllato dal coordinatore.','Produrre le appendici con contenuto effettivo oppure rivedere la promessa editoriale e riallocare i nuclei necessari nel corpo; controllare anche il PDF.');
add(1,1,'grave','quattro profili','Il dossier bandi ha solo tre procedure documentate; RUP avanzato e procurement digitale restano non validati. La lunghezza reale supera ampiamente il piano senza colmare i nuclei sostanziali.','Completare fonti rappresentative e copertura dei profili promessi; sostituire ripetizioni con teoria e prove effettive, senza dichiarare completezza dai soli metadati.');
const sources=[
{chapters:[7],claim:'MePA Lavori comprende nuove opere',url:'https://www.acquistinretepa.it/opencms/opencms/programma_approfondimenti_kit_lavori.html',outcome:'Pagina Consip aperta integralmente nel passaggio pertinente: conferma ambito più ampio della manutenzione.'},
{chapters:[5],claim:'Soglie UE2026 e rotazione',url:'https://www.anticorruzione.it/documents/91439/280912844/Comunicato%2Bdel%2BPresidente%2Bdel%2B5%2Bnovembre%2B2025%2B-%2Bappalti%2Bviaggi%2Bistruzione.pdf/6c1c4e83-fb63-1c69-66e4-31ecc65700df?t=1762769463797',outcome:'Indice di ricerca primario conferma140000/216000 dal1gennaio2026; apertura PDF403. Non certificato l’intero quadro delle soglie.'},
{chapters:[5],claim:'Rotazione ed eccezioni',url:'https://www.anticorruzione.it/documents/91439/a75341a9-396d-d56e-62d9-72fe358be151',outcome:'Estratto indicizzato ANAC riscontra eccezione sotto5000 e inviti non limitati; apertura403. Restano da ricostruire articolo vigente e condizioni cumulative.'},
{chapters:[9],claim:'Accesso speciale art36',url:'https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto:2023-03-31;36~art36!vig=',outcome:'Riscontro primario indicizzato della disponibilità reciproca per primi cinque; apertura testo vigente non riuscita. La lacuna didattica è certa, non certificata ogni decorrenza processuale.'},
{chapters:[12],claim:'Guida DNSH aggiornata nel2024',url:'https://www.rgs.mef.gov.it/_Documenti/VERSIONE-I/CIRCOLARI/2024/22/Circolare-del-14-maggio-2024-n-22.pdf',outcome:'Testo primario indicizzato della circolare22/2024 letto: richiama tassonomia, art17 e aggiornamento REPowerEU; apertura403. Non esclusi successivi atti2026.'}
];
l.status='text-review-complete';l.findings=rows;l.externalClaimsChecked=sources;l.limitations=['Lettura integrale dei14capitoli, quiz e casi; letti integralmente indice analitico, matrice e due dossier di supporto.','Verifiche esterne mirate: numerose fonti primarie hanno risposto403; nessuna certificazione integrale del Codice vigente, dei termini processuali o delle istruzioni2026. Le proposte normative richiedono consolidamento sulle fonti prima dell’applicazione.','PDF in rapporto separato; la lettura testuale non certifica impaginazione.','Nessun libro o fonte modificato.'];
for(const [i,c]of l.chapters.entries()){c.findingIds=rows.filter(r=>r.chapter===i+1).map(r=>r.id);c.externalClaimsChecked=sources.filter(s=>s.chapters.includes(i+1));c.hashMatches=crypto.createHash('sha256').update(fs.readFileSync(c.path)).digest('hex')===c.sha256;}
fs.writeFileSync(dir+'VOL-09-ledger.json',JSON.stringify(l,null,2));
let out='# VOL-09 — Revisione integrale del testo, 2 ottobre 2026\n\n## 1. Sintesi editoriale\n\nLetti integralmente i14capitoli originali, inclusi tutti i quiz, commenti, casi e apparati. Il volume offre un orientamento metodologico coerente, ma non sostiene ancora la preparazione specialistica dichiarata: soglie, termini, requisiti, effetti e soluzioni operative sono spesso sostituiti dall’invito a verificare. Non pubblicabile senza integrazione sostanziale. Nessuna correzione applicata.\n\n## 2. Punti applicati della checklist\n\nApplicati i30punti della skill revisore-editoriale-totale al testo: forma, struttura, coerenza, precisione, teoria, esempi, quiz, fonti, rimandi e apparati. Resa grafica demandata al rapporto PDF. Le chiavi dei quiz sono state risolte e confrontate coi commenti: non individuato il disallineamento sistematico delle lettere segnalato in altri volumi; diversi quesiti sono troppo prevedibili.\n\n## 3. Tabella errori e integrazioni necessarie\n\nRighe riferite ai file originali identificati nel ledger. Grave = lacuna o errore che ostacola la preparazione promessa; medio = intervento locale necessario; lieve = refuso.\n\n| ID | Posizione | Gravità | Descrizione ed estratto | Correzione proposta | Stato |\n|---|---|---|---|---|---|\n';
out+=rows.map(r=>`| ${r.id} | ${r.chapter?'Cap.'+r.chapter:'Indice analitico'}, r.${r.line} | ${r.severity} | «${r.excerpt}»: ${r.problem} | ${r.proposal} | Non applicato |`).join('\n');
out+='\n\n## 4. Osservazioni per capitolo\n\n';for(const[i,c]of l.chapters.entries())out+=`- **${i+1} — ${c.title}**: lettura e quiz completi. ${c.findings.join(' ')}\n`;
out+='\n## 5. Coerenza globale\n\nLa stessa sequenza di rischio, responsabilità, documento ed evidenza ricorre in quasi ogni capitolo e simulazione. Il criterio è utile ma non sostituisce regole, valori, termini e casi svolti. Il piano iniziale di34900parole è ampiamente superato, senza copertura equivalente dei nuclei. I rinvii a VOL01 sono generici e la promessa di cinque appendici è priva di corrispondenti unità nell’export. Fonti finali spesso non identificabili per articolo, versione o URL; nei capitoli9,10,13,14 manca un apparato finale omogeneo.\n\n## 6. Contenuto verificato e da verificare\n\n';out+=sources.map(s=>`- [${s.claim}](${s.url}): ${s.outcome}`).join('\n');
out+='\n\nLetti integralmente indice di modulo, indice analitico, matrice di copertura, dossier v4 e nota dei bandi rappresentativi. Questi ultimi dichiarano ancora blocchi sulle fonti e sui profili avanzati: lo stato complete di alcune righe non supera tali limiti. Restano da consolidare testo vigente del Codice e correttivi, giurisprudenza, PNRR2026, obblighi Consip, tracciabilità, CAM e metodologia PM. Non si qualificano come verificati i particolari normativi proposti soltanto come integrazione.\n\n## 7. Suggerimenti facoltativi\n\nAlternare esempi di lavori, servizi e forniture; fornire un progetto comune numerico che attraversi programmazione, gara, esecuzione e rendicontazione. Separare domande e soluzioni per consentire autovalutazione. Espandere sigle straniere al primo uso e uniformare lessons learned.\n\n## 8. Priorità degli interventi\n\nPrima completare teoria normativa, fonti bloccanti e appendici promesse. Poi costruire atti e soluzioni con dati sufficienti. Ricomporre titoli, tabelle e quiz spezzati; riallineare matrice e rinvii. Infine ridurre ripetizioni e correggere forma e terminologia.\n\n## 9. Giudizio di pubblicabilità\n\n**Da revisionare sostanzialmente prima della pubblicazione.** La correttezza dei consigli generali non basta a preparare le prove dei quattro profili dichiarati.\n\n## 10. Limiti di questa revisione\n\n';out+=l.limitations.map((x:string)=>'- '+x).join('\n');out+='\n\nLedger: `artifacts/review-integrale-2026-10-02/VOL-09-ledger.json`. Tutti i14hash ricontrollati alla chiusura.\n';
out=out.replace(/\bi14/g,'i 14').replace(/\bdei14/g,'dei 14').replace(/\bi30/g,'i 30').replace(/\bdi34900parole/g,'di 34.900 parole').replace(/i14hash/g,'i 14 hash');
fs.writeFileSync('wiki/reviews/audit-integrale-2026-10-02/VOL-09.md',out);console.log({chapters:l.chapters.length,readComplete:l.chapters.filter((c:any)=>c.readComplete).length,hashesMatch:l.chapters.every((c:any)=>c.hashMatches),findings:rows.length});
