import fs from 'node:fs';
import crypto from 'node:crypto';
const lp='artifacts/review-integrale-2026-10-02/VOL-03-ledger.json';
const ledger=JSON.parse(fs.readFileSync(lp,'utf8').replace(/^\uFEFF/,''));
const f:any[]=[];
function add(scope:string,pos:string,quote:string,severity:string,category:string,problem:string,proposal:string,sourceIds:string[]=[]){f.push({id:`V03-${String(f.length+1).padStart(3,'0')}`,scope,position:pos,excerpt:quote,severity,category,description:problem,proposal,sourceIds,status:'da correggere; non applicato'});}
add('fc02/05b','Apertura; mappa articoli; caso Omega; quiz 1','applicabile dal 1 gennaio 2026','bloccante','Normativa','Il TU giustizia tributaria è presentato come disciplina applicabile nel 2026. La decorrenza è stata rinviata al 1 gennaio 2027. Errore propagato dalla source note e dalle matrici.','Rifondare il capitolo sulla disciplina 2026 dei d.lgs.545/546 del1992, coordinata alle modifiche vigenti; ricontrollare tutti i riferimenti, caso e quiz; separare prospetto2027.', ['TU']);
add('fc03/08','CCNL; riga105','il contratto definitivo di riferimento','grave','Aggiornamento','Il testo presenta il2025–2027 soltanto come ipotesi9giugno. Firma definitiva6agosto2026, prima del cut-off dichiarato22agosto. Stesso errore nella source note ARAN.','Aggiornare cronologia e istituti interessati al testo definitivo, conservando distinte decorrenze e contratti precedenti.', ['ARAN']);
add('fc01/09','Nucleo gestione; definizione residui','residui attivi','grave','Contabilità','La definizione accertati non riscossi omette, nel bilancio dello Stato, le somme riscosse non versate.','Integrare entrambe le componenti e un esempio:100accertati,80riscossi,60versati producono40residui(20+20).', ['RGS']);
add('fc02/05','Tabella tutela cautelare riga167','grave o irreparabile','grave','Normativa','La congiunzione alternativa altera il requisito cumulativo della sospensione.','Scrivere grave e irreparabile, collegando fumus e periculum alla fase e alla norma applicabile; ricercare la stessa locuzione nel volume.', ['CAUTELA']);
add('fc02/08','Territorio/status; riga81','vengono vincolate a un altro regime','grave','Dogane','Il vincolo a un altro regime non determina in generale la cessazione della vigilanza sulle merci non unionali.','Allineare al CDU134: mutamento posizione doganale, uscita o distruzione; esplicitare persistenza nei regimi speciali.', ['CDU']);
add('fc02/08','Fonti; riga70','per le disposizioni non superate','grave','Dogane','Formula che lascia indeterminata una sopravvivenza del DPR43/1973 dopo abrogazione.','Indicare abrogazione disposta dal d.lgs.141/2024, distinguendo eventuali vicende pregresse/transitorie puntuali dalla disciplina corrente.', ['DOGANE']);
add('fc02/08','Rettifica della dichiarazione','rettifica','grave','Dogane','La spiegazione arresta la rettifica alla fase anteriore allo svincolo, omettendo la possibilità successiva.','Aggiungere CDU173(3), richiesta entro tre anni e relativi presupposti; distinguere rettifica/invalidamento.', ['RETTIFICA']);
add('fc02/08','Caso componenti elettronici Cina/Turchia','Turchia','grave','Dogane','Il caso orienta alla preferenza di origine senza distinguere la libera pratica nell’unione doganale UE-Turchia per merci industriali.','Riformulare fatti e soluzione distinguendo origine, provenienza, libera pratica e A.TR; verificare eventuali misure legate all’origine.', ['TURCHIA']);
add('fc02/14','Glossario riga144','in proprio nome o per conto altrui','grave','Terminologia','La definizione di dichiarante include indistintamente il rappresentante diretto, in contrasto con la distinzione del cap08.','Definire chi presenta in nome proprio oppure la persona in nome della quale avviene la presentazione; esempio diretto/indiretto.', ['CDU']);
add('fc02/09','Soggetti accise; riga88','detenerli indefinitamente in sospensione','grave','Accise','L’avverbio suggerisce una facoltà di detenzione temporanea in sospensione del destinatario registrato.','Precisare divieto di detenzione in sospensione e momento di esigibilità al ricevimento, distinguendo depositario autorizzato.', ['DEST']);
add('fc02/14','Glossario EMCS riga105','Sistema di controllo della circolazione in sospensione','medio','Accise','Definizione incompleta: dal2023 comprende anche movimenti commerciali tra Stati UE di prodotti già immessi in consumo.','Ampliare definizione e raccordare cap09 a e-DAS/e-SAD, destinatario/speditore certificato.', ['EMCS']);
add('fc02/11','Immobilizzazioni; riga177','Le immobilizzazioni sono iscritte al costo e ammortizzate','grave','Contabilità','Generalizzazione a tutte le immobilizzazioni, incluse quelle finanziarie e terreni.','Limitare l’ammortamento alle immobilizzazioni materiali/immateriali con utilizzazione limitata nel tempo; distinguere costo, ammortamento e svalutazione.');
add('fc02/11','Rimanenze riga175; margini riga209','secondo costo e valore di realizzo','medio','Contabilità','Manca il criterio del minore; margine di struttura non distingue configurazione primaria e secondaria.','Esplicitare minore tra costo e realizzo desumibile dal mercato; indicare formule delle due configurazioni e quella adottata.');
add('fc03/appendice-f','Reati contro PA','Corruzione, concussione, peculato e abuso','grave','Normativa','Abuso figura accanto ai reati senza qualificazione storica o chiarimento: induce a studiare l’abrogato art323 come vigente.','Esplicitare abrogazione legge114/2024 e distinguere le fattispecie vigenti pertinenti, incluso314-bis se nel programma.', ['ABUSO']);
add('fc03/*','Verifica e caso ragionato di chiusura di tutti19file','individuare fonte, ambito e funzione','bloccante','Verifiche','114 domande finali: sei scheletri con risposte identiche in19capitoli; identico caso conclusivo. Non verificano i nuclei dichiarati. Esempio F: obbligazioni e sicurezza sul lavoro sinonimi?','Sostituire con domande effettive per materia, soluzioni applicate e casi autosufficienti; associare ogni verifica a un nucleo reale, senza moltiplicare il conteggio in matrice.');
add('fc03/03','Intero capitolo; raccordo glossario B','previdenza, servizi e prestazioni','bloccante','Copertura','Manca la teoria specialistica promessa per pensioni, ammortizzatori, invalidità, ISEE, contribuzione. Privacy e sportello occupano il posto di requisiti, istituti e distinzioni.','Sviluppare nuclei autonomi: art38, previdenza/assistenza, rapporto contributivo, automaticità, pensioni, sostegni, invalidità, ISEE/DSU; casi e quiz specifici. Dati quantitativi con data/fonte, non omissione generalizzata.');
add('fc03/04','Infortunio, malattia e prestazioni; anche appendice B','Evento dannoso collegato','bloccante','Copertura','Non sono spiegati causa violenta/occasione di lavoro, differenza causale della malattia professionale, prestazioni, premi e automaticità; il glossario non colma il vuoto.','Integrare presupposti e soggetti assicurati, in itinere, malattie tabellate/non, prestazioni economiche/sanitarie, danno biologico e automaticità con limiti.', ['INAIL']);
add('fc03/appendice-a','Poteri, verbale, contraddittorio; confronto appendice E','non deve memorizzare un catalogo indistinto di poteri','bloccante','Copertura','Appendice prevalentemente metodologica: poteri, atti, diffide, rimedi e competenze non insegnati. Appendice E afferma che basta per il profilo vigilanza.','Sviluppare sequenza e basi d.lgs.124/2004 e149/2015 aggiornate, verbali, diffida, conciliazione, recuperi, sanzioni e tutele; oppure ridimensionare esplicitamente promessa ispettiva e fornire destinazione completa.');
add('fc03/02','Organi, indirizzo e gestione','organi','grave','Copertura','L’ordinamento INPS/INAIL è ridotto a categorie; non insegna denominazione/competenze degli organi e vigilanza ministeriale.','Inserire comparazione Presidente,CdA,CIV,DG,revisori, atti/competenze e vigilanza. Separare assetto stabile e nominativi mobili.');
add('fc03/06','Bilancio, patrimonio e controlli','Bilancio dell’ente','grave','Copertura','Nessuno sviluppo sufficiente degli strumenti contabili propri degli EPNE, delle fonti dedicate e delle competenze di adozione/approvazione.','Integrare DPR97/2003, raccordi armonizzazione e regolamenti INPS/INAIL; documenti preventivi/consuntivi e competenze, con esempio leggibile.');
add('fc03/appendice-f','Civile, processo civile, finanze, sicurezza','Elencarli non basta','grave','Copertura','Il testo stesso afferma che elencare soggetti non basta, ma non attribuisce obblighi. Distinzioni civilistiche e tributarie spesso solo nominate; processo previdenziale assente.','Spiegare distinzioni richieste e soggetti/obblighi essenziali81/2008; fornire rinvii esatti al core dove completi; sviluppare il delta INAIL e il rito lavoro/previdenza.');
add('fc03/appendice-b','Voci premio e danno biologico','Concetto richiamato nel sistema INAIL','grave','Glossario','Danno biologico non definito; premio descritto come termine legato al finanziamento. Il lettore non può imparare le due nozioni.','Fornire definizioni sostanziali, presupposto/effetto ed esempio; distinguere automaticità delle prestazioni dall’assenza di istruttoria.', ['INAIL']);
add('fc03/appendice-b','Coppie da non confondere; domanda commissario','Chiamare tutto genericamente "previdenza"','medio','Concetti','Contrapposizione INPS-previdenza/INAIL-assicurazione rischia di escludere INAIL dalla previdenza sociale. Prestazione non diritto automatico è ambiguo.','Presentare l’assicurazione INAIL nel sistema di previdenza/protezione sociale; spiegare automaticità in senso tecnico e accertamento dei presupposti.', ['INAIL']);
add('fc03/appendice-c','Schede CRI, ISTAT, ENEA, ASI; ricorrenze01/10/12','natura giuridica','grave','Perimetro','La prudenza su CRI non comunica il dato giuridico essenziale. Gli enti di ricerca possono essere editorialmente affini, ma il personale amministrativo non diventa per questo Funzioni Centrali.','Dichiarare CRI associazione di diritto privato dal2016; distinguere natura, comparto e percorso editoriale. Inserire CCNQ per enti di ricerca e correggere aperture che includono tutti come EPNE FC.', ['CRI','CCNQ']);
add('fc03/*','Titoli N-FC03-xx e sottotitoli','Applicazione al profilo','grave','Struttura','Segmentazione meccanica interrompe sottotitolo e paragrafo, domanda e soluzione: es.12quiz7,10Da sapere5righe,11caso7. Le sezioni non corrispondono ai concetti della matrice.','Riorganizzare confini in unità semantiche complete; poi riallineare ID, indice e matrice.');
add('fc03/appendice-e','Quando un rinvio è sufficiente; tabella moduli','volume, capitolo e paragrafo','grave','Rinvii','Il testo prescrive rinvii precisi ma offre prevalentemente codici di modulo, senza destinazione per materia. Le promesse di sufficienza non sono comprovate.','Mappare volumi disponibili e paragrafi verificati; indicare fuori perimetro per destinazioni non disponibili. Ridimensionare basta per vigilanza e contratti.');
add('fc02/05b','Ricorso, assistenza, competenza','termini numerici','grave','Copertura','Omissione deliberata di termini essenziali, soglia difesa personale e competenza territoriale rende incompleta la preparazione al processo.','Inserire schema datato di termini/presupposti essenziali con verifiche di applicazione; dati mobili vanno qualificati e aggiornati, non rimossi.');
add('fc02/05a','Reati tributari; responsabilità autore','struttura tipica','grave','Copertura','Fattispecie nominate senza soglie/elementi sufficienti a distinguerle; mancano raccordi chiari sulla responsabilità delle persone giuridiche.','Integrare tabella condotta,dolo,soglia,eventuali cause,tempo applicabile; responsabilità sanzionatoria enti; raccordo riforma2024 e transizioneTU173/2027.');
add('fc02/05','Accertamento, contraddittorio e autotutela','presupposti','grave','Copertura','Metodi analitico/induttivo/sintetico/d’ufficio non sviluppati; contraddittorio e autotutela restano generici, rinvio05↔05B circolare.','Sviluppare condizioni/limiti, garanzie, termini essenziali art6-bis, autotutela10-quater/quinquies con casi ed effetti; definire TCF e accesso collaborativo con quadro datato.');
add('fc02/06','Categorie reddituali e dichiarazioni','regole vigenti','grave','Copertura','I criteri temporali e le modalità di determinazione sono spesso rinviati anziché insegnati; pensioni e cassa allargata non chiarite; dichiarazione tardiva priva del limite essenziale.','Integrare tabella categoria/soggetti/base/criterio temporale; pensioni art49, assimilati50; criteri IRES fondamentali e soglie dichiarative con fonte/data.');
add('fc02/12','Obbligazioni, patologie contrattuali, società','nullità','grave','Copertura','Delegazione, espromissione, accollo e molte patologie/tipi societari nominati senza disciplina distintiva.','Integrare presupposti/effetti ed esempi, responsabilità/onere/prescrizione, solidarietà e responsabilità tipi societari; oppure rinvio esatto a trattazione completa.');
add('fc02/03','Organi AE/ADM','direttore','medio','Copertura','Quadro degli organi omette collegio dei revisori e funzioni, mentre per AdER elenco più completo.','Completare confronto con fonti statutarie; separare organi necessari da uffici e nominativi.');
add('fc01/03','Aree e profili','aree','medio','Copertura','Le quattro aree contrattuali non vengono nominate e spiegate nelle declaratorie essenziali.','Aggiungere Operatori,Assistenti,Funzionari,Elevate professionalità con competenze/accesso; raccordare con CCNL vigente.', ['ARAN']);
add('fc01/05','Segretario generale e strutture missione','Segretario generale','medio','Copertura','Funzione generale troppo generica; non esplicitata durata strutture missione in rapporto al Governo.','Sviluppare d.lgs.303/1999art7–8, compiti e limiti; nominativi/assetti concreti separati dalla disciplina.');
add('fc01/06','Modelli organizzativi','direzioni generali','medio','Copertura','Modelli presentati senza ruolo Segretario generale e limite di coesistenza col dipartimentale.','Integrare d.lgs.300/1999art3/6 e confronto con compiti dei dipartimenti, verificando testo vigente.');
add('fc01/07','Patrocinio; generale/distrettuali','secondo il perimetro stabilito','medio','Copertura','Criterio di competenza e patrocinio obbligatorio/autorizzato insufficienti rispetto alla matrice completo.','Precisare soggetti, competenza processuale/territoriale e fonti; conservare proporzione al profilo amministrativo.');
add('fc01/08','Struttura PIAO','struttura','medio','Copertura','Schema concettuale non insegna le quattro sezioni formali e gli adempimenti fondamentali.','Distinguere mappa didattica da DM132/2022; aggiungere sezioni, durata/aggiornamento, competenze e rimando esatto al core.');
add('fc01/09','Ciclo statale e controlli','rendiconto','grave','Copertura','Delta contabilità Stato incompleto: struttura legge bilancio, documenti programmazione, unità voto, composizione rendiconto e controlli/parificazione.','Integrare scheda specialistica datata e casi; non limitarsi al ciclo generico del core.');
add('fc01/10','Acquisti ministeriali','Consip','medio','Copertura','Obblighi specifici di acquisto centralizzato non sviluppati, soglie/procedure rinviate genericamente.','Esporre delta Ministeri e un rinvio preciso alla teoria del core, con controlli di soglia, strumenti e obblighi applicabili.');
add('fc01/12','Ordine illegittimo; conflitto','coinvolge','medio','Applicazione','Soluzioni comportamentali non esplicitano rimostranza/conferma scritta e limite penale; conflitto richiede astensione oltre segnalazione.','Integrare presupposti delle condotte e rinvii normativi; usare forma verbale coerente nelle istruzioni.');
add('fc03/11','Casi1/3 e mini-atto','documento mancante','medio','Applicazione','Richiesta integrazione all’utente senza previo controllo acquisizione d’ufficio; mini-atto non specifica documento/termine perché traccia non li fornisce.','Aggiungere verifica art18L241/DPR445art43; rendere caso autosufficiente e lasciare condizionati solo i dati davvero ignoti.');
add('fc03/12','Riservatezza; conflitto interessi','non possono essere comunicati per telefono','medio','Coerenza','Divieto assoluto sul mezzo contraddice corretta verifica identità/titolo/canale negli scenari successivi; astensione enunciata ma non resa operativa.','Riferire divieto al canale non autorizzato/non verificato; aggiungere astensione nei casi dovuti.');
add('fc02/07','Fermo','libera disponibilità','medio','Precisione','Descrizione del fermo patrimoniale imprecisa rispetto al divieto di circolazione; tutele/limiti restano poco determinati.','Chiarire effetto proprio e presupposti, distinguendolo da ipoteca/espropriazione; aggiungere schema delle tutele con condizioni.');
add('fc02/10','Pubblicità e estimo','nei casi previsti','medio','Precisione','Efficacia costitutiva dell’iscrizione ipotecaria resta attenuata; procedimenti estimativi alternativi solo nominati.','Esplicitare art2808; per profili Territorio integrare almeno percorso/formula e caso dei metodi promessi o restringere promessa.');
add('fc02/13','Svolgimenti guidati righe291/313/335','**Svolgimento guidato','medio','Markdown','Grassetto aperto in una riga e chiuso sulla successiva; intestazioni incoerenti e numerazione rinvii da ricontrollare.','Chiudere il grassetto nella stessa riga e verificare rendering; mantenere titolo e soluzione uniti.');
add('fc01/*','Mappe BANDO cap09/11/12','Decisione','medio','Coerenza metodo','BANDO rimappato in alcuni capitoli: B Base normativa, A Attori,N Nessi,D Decisioni; cap13FC02 usa D Domande.','Mantenere espansione canonica Bando/Aree/Nuclei/Diario/Output; chiamare diversamente eventuale griglia analitica alternativa.');
add('fc02/13','Mappa BANDO','Domande','medio','Coerenza metodo','La D viene usata come Domande anziché Diario.','Riallineare acronimo e distinguere il protocollo di soluzione.');
add('fc01/*','Quiz/simulazioni soprattutto10–14','Risposta corretta','medio','Verifiche','Molti distrattori caricaturali e risposta corretta più lunga; concentrazione lettereB/C. Soluzioni inline riducono simulazione autonoma.','Rendere plausibili distrattori e uniformare lunghezze, bilanciare chiavi senza alterare commenti; separare fascicolo prova e correzione.');
add('fc03/12','Otto scenari situazionali','Dire che non puoi fare nulla','medio','Verifiche','Chiavi C,B,B,C,B,C,C,C e commenti coerenti, ma alternative troppo evidentemente scorrette.','Inserire condotte plausibili ma incomplete e motivare il confronto; eventuale ranking coerente con bando.');
add('fc01/15','Glossario e apparati','quattro tabelle','lieve','Apparati','Conteggio non allineato alle cinque tabelle; rinvio a glossario per competenza/cassa non fornisce le voci; definizione organo da precisare.','Aggiornare conteggi/rinvii e distinguere organo dall’ente cui si imputano gli effetti; fornire soluzione o destinazione per100domande aperte.');
add('fc03/13','Caso Luca riga254','l\'l\'INAIL','lieve','Refuso','Articolo duplicato; venerdi senza accento. Simulazione10scenari non individua banca di provenienza.','Correggere articolo/accento; indicare gli scenari necessari e la destinazione degli ulteriori quesiti.');
add('fc02/*','Correzione di bozze diffusa','stabilità','medio','Lingua','Accenti/apostrofi incoerenti e sostituzioni errate: Sara per Sarà(cap03), disciplina/funzione/priorità stabilità, operatore necessità, infiltra offerta(cap09).','Correggere in contesto: stabilita, necessita, sottopone a controlli; uniformare è/può/né/perché/qualità. Nessuna sostituzione globale cieca.');
add('fc03/*','Corpo e appendici E/F','prima della pubblicazione','grave','Pulizia editoriale','Source note, wiki, audit, decisioni aperte e istruzioni di redazione sono consegnate al lettore. AppendiceF dice che la scrittura pubblicabile deve ancora decidere il perimetro sociale.','Trasferire backstage nei documenti staff; risolvere perimetro assistente sociale e rendere rinvii leggibili per il candidato.');
add('fc02/*','Corpo cap04/05B/14','source note','grave','Pulizia editoriale','Commenti su consolidamento fonti, review e apertura gap editoriali interrompono il libro.','Sostituire con riferimenti bibliografici utili al lettore; conservare le istruzioni di produzione nei soli file interni.');
add('fc03/appendice-f','Simulazione mista dieci minuti','La seconda propone un inadempimento','grave','Esercizi','La simulazione descrive che cosa dovrebbe chiedere, senza fornire i fatti né vere domande e soluzioni.','Scrivere cinque tracce autosufficienti e correzioni per materia, con rubriche e tempi.');
add('fc03/appendice-c','Tavola confronto operativo','ACI richiama mobilità','lieve','Coerenza','CONI incluso in titolo e prime schede ma omesso nel confronto finale.','Completare riga/periodo CONI mantenendo omogenea la griglia.');
add('fc03/appendice-d','Diario errori documentali','si eliminano dal diario','lieve','Metodo','Eliminazione settimanale degli errori non ripetuti perde lo storico e contrasta con verifica in contesto nuovo del cap13.','Archiviare con stato/data/evidenza di recupero; eliminare solo duplicati, non la traccia.');
const sources:any={
TU:{claim:'Decorrenza TU175 al2027; analogo rinvio TU173 e33',url:'https://www.gazzettaufficiale.it/eli/gu/2026/05/22/117/sg/pdf',locator:'testo che richiama art4 DL200/2025, comma3',result:'contraddice cap05B; conferma prudenza2027 in05A'},
ARAN:{claim:'CCNL FC2025–27 sottoscritto definitivamente6agosto2026',url:'https://www.aranagenzia.it/documento_pubblico/contratto-collettivo-nazionale-di-lavoro-relativo-al-personale-del-comparto-funzioni-centrali-triennio-2025-2027/',locator:'incipit e art2',result:'contraddice capFC03/08 e source note'},
RGS:{claim:'Residui attivi Stato comprendono riscosso non versato',url:'https://www.rgs.mef.gov.it/_Documenti/VERSIONE-I/attivita_istituzionali/formazione_e_gestione_del_bilancio/rendiconto/conto_del_bilancio_e_conto_del_patrimonio/conto_del_bilancio/2017/relazione_illustrativa/Relazione_al_rendiconto_2017.pdf',locator:'1.5.1',result:'definizione istituzionale; fonte storica, non certificazione normativa2026'},
CAUTELA:{claim:'Presupposto danno grave e irreparabile',url:'https://def.giustiziatributaria.gov.it/DocTribFrontend/getPrassiDetail.do?id=%7BB752EE50-1E07-40B8-BF5B-09EA49FA2B4A%7D',locator:'1.10 art47',result:'conferma congiunzione cumulativa; prassi storica'},
CDU:{claim:'Vigilanza134 e dichiarante5(15)',url:'https://eur-lex.europa.eu/legal-content/IT/TXT/PDF/?uri=CELEX%3A02013R0952-20221212',locator:'art134 e5',result:'evidenza disposizioni; HTML protetto da controllo robot'},
DOGANE:{claim:'Riforma2024 e abrogazioneTULD',url:'https://www.attuazione.gov.it/it/approfondimenti/riforme-di-rilievo-del-governo/riforme-governo-meloni/riforma-fiscale/dlgs-in-materia-doganale-e-di-accise/',locator:'sintesi d.lgs141/2024',result:'confermata necessità chiarimento transizione'},
RETTIFICA:{claim:'CDU173(3) rettifica dopo svincolo entro3anni',url:'https://eur-lex.europa.eu/legal-content/IT/ALL/?uri=CELEX%3A62024CJ0889',locator:'citazione173(3) e par27',result:'conferma integrazione'},
TURCHIA:{claim:'A.TR attesta libera circolazione, non origine',url:'https://def.giustiziatributaria.gov.it/DocTribFrontend/getPrassiDetail.do?id=%7B0020469F-0000-C011-AE69-2E953589C2C8%7D&primoPiano=true',locator:'prassi2026 UE-Turchia',result:'caso industriale da correggere'},
DEST:{claim:'Destinatario registrato non detiene in sospensione',url:'https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=21G00198&atto.dataPubblicazioneGazzetta=2021-11-29&tipoDettaglio=multivigenza',locator:'modifica TUA art8',result:'indefinitamente improprio'},
EMCS:{claim:'EMCS include dal2023 movimenti commerciali intraUE ad accisa assolta',url:'https://www.adm.gov.it/portale/ead-daa',locator:'descrizione sistema',result:'glossario parziale'},
ABUSO:{claim:'Art323 abrogato daL114/2024',url:'https://www.normattiva.it/atto/caricaDettaglioAtto?atto.codiceRedazionale=24G00122&atto.dataPubblicazioneGazzetta=2024-08-10&tipoDettaglio=multivigenza',locator:'art1comma1letterab',result:'abuso da qualificare storico'},
INAIL:{claim:'Causa violenta/occasione lavoro; automaticità anche con premio omesso',url:'https://www.inail.it/portale/assicurazione/it/Soggetti_tutelati/Lavoratore-Dipendente-Industria-Artigianato-Terziario-Altre-Attivita/infortunio-sul-lavoro/aggravamento-del-danno-e-revisione-della-rendita-lavoratore-dipendente/prestazioni-economiche.html',additionalUrl:'https://www.inail.it/portale/assicurazione/it/Soggetti_tutelati/Lavoratore-Dipendente-Industria-Artigianato-Terziario-Altre-Attivita/infortunio-sul-lavoro/riconoscimento-dell-infortunio-lavoratore-dipendente.html',locator:'definizione e automaticità',result:'conferma lacune; eccezioni autonome da insegnare'},
CRI:{claim:'CRI privata dal1gennaio2016',url:'https://cri.it/2016/02/23/croce-rossa-ha-cambiato-personalita-giuridica/',locator:'comunicazione istituzionale',result:'inclusione fraEPNE da qualificare'},
CCNQ:{claim:'Perimetri comparti distinti da missione e mansione',url:'https://www.aranagenzia.it/documento_pubblico/contratto-collettivo-nazionale-quadro-per-la-definizione-dei-comparti-e-delle-aree-di-contrattazione-collettiva-nazionale-2025-2027/',locator:'art3 e comparto IstruzioneRicerca',result:'necessario distinguere collocazione editoriale/contrattuale'},
ADER:{claim:'Fino120mila,84rate per richieste2025–26',url:'https://www.agenziaentrateriscossione.gov.it/it/il-gruppo/lagenzia-comunica/novita/Rateizzazione-cosa-cambia-dal-1-gennaio-2025/',locator:'rateizzazione semplice e documentata',result:'affermazione cap07 confermata'}
};
function match(c:any,scope:string){const [mod,ch]=scope.split('/');return c.path.includes('m-'+mod+'-')&&(ch==='*'||c.path.split('/').at(-1).startsWith(ch+'-'));}
for(const c of ledger.chapters){const related=f.filter(x=>match(c,x.scope));c.findings=related.map(x=>x.id);c.externalClaimsChecked=[...new Set(related.flatMap(x=>x.sourceIds))].map((id:any)=>({id,...sources[id]}));if(c.path.includes('/07-riscossione'))c.externalClaimsChecked.push({id:'ADER',...sources.ADER});c.hashVerifiedAtClose=crypto.createHash('sha256').update(fs.readFileSync(c.path)).digest('hex')===c.sha256;c.quizReview='complete';c.readComplete=true;}
ledger.status='text-review-complete';ledger.date='2026-10-02';ledger.findings=f;ledger.externalSources=sources;ledger.limitations=['Lettura integrale dei50capitoli inclusi quiz/casi; non certifica esaustività normativa.','Verifiche web mirate sui claim indicati; alcune fonti storiche o estratti indicizzati.','PDF, front matter e servizi digitali assegnati al coordinatore.','Non svolta verifica integrale dei raw normativi né dei manuali esterni richiamati.'];
fs.writeFileSync(lp,JSON.stringify(ledger,null,2)+'\n');
const rows=f.map(x=>`| ${x.id} | ${x.scope}, ${x.position} | ${x.category} | ${x.severity} | «${x.excerpt}»: ${x.description} | ${x.proposal}${x.sourceIds.length?' Fonti: '+x.sourceIds.join(', ')+'.':''} | Proposta, non applicata |`).join('\n');
const obs=ledger.chapters.map((c:any)=>`| ${c.path.split('/')[3]}/${c.path.split('/').at(-1)} | Integrale; quiz/casi completi | ${c.findings.join(', ')||'Nessun rilievo specifico ulteriore; valgono controlli globali.'} |`).join('\n');
const src=Object.entries(sources).map(([k,v]:any)=>`- **${k}** — ${v.claim}. [Fonte primaria](${v.url}); ${v.locator}. Esito: ${v.result}.${v.additionalUrl?' [Ulteriore riscontro]('+v.additionalUrl+').':''}`).join('\n');
const report=`# Revisione integrale testuale — VOL-03

Data:2ottobre2026. Perimetro:50originali correnti,15M-FC01+16M-FC02+19M-FC03. Skill applicata: revisore-editoriale-totale. Solo rilievi e proposte, nessuna modifica editoriale applicata. Ledger:[VOL-03-ledger.json](../../../artifacts/review-integrale-2026-10-02/VOL-03-ledger.json); note di lettura:[checkpoint](../../../artifacts/review-integrale-2026-10-02/VOL-03-checkpoint.md).

## 1. Sintesi editoriale

**Non pubblicabile nello stato attuale.** Lettura integrale completata dei50capitoli, di tutti i quiz, casi, glossari e apparati interni. Il volume offre strumenti di organizzazione dello studio utilizzabili e molti confronti chiari, ma il grado specialistico è diseguale. Il blocco fiscale contiene errori normativi e definitori; il blocco previdenziale/assicurativo/ispettivo dedica molto spazio al metodo senza sviluppare il contenuto che titolo e indice promettono. Le114verifiche finali EPNE riproducono sei risposte generiche; il caso finale è identico19volte.

Le due correzioni normative prioritarie sono TU175/2024 applicabile dal2027, anziché2026, e firma definitiva delCCNLFunzioniCentrali2025–2027 del6agosto2026. Quest’ultima precede anche il cut-off dichiarato22agosto2026. I problemi sono presenti nelle source note, quindi correggere solo il libro lascerebbe aperta la causa della propagazione.

## 2. Punti applicati della checklist

Applicati1–5(macrostruttura,copertura,promessa,ordine,pubblico),6–15(coerenza,approfondimento,collegamenti,apparati,esempi,prove,fonti),16–21(terminologia,precisione,stile,leggibilità,ripetizioni),22–26e28–30(ortografia,punteggiatura,uniformità,numerazioni,rinvii,rifinitura). Il27è controllato solo a livello sorgente/Markdown; verifica visivaPDF al coordinatore. Nessun punto è considerato superato per sola presenza di un titolo o di un flag completo.

## 3. Tabella errori

Posizioni usano modulo/capitolo e titolo/estratto, ricercabili negli originali. Le linee esplicite riguardano la versioneSHA del ledger. Gravità bloccante=ostacola la promessa editoriale; grave=errore di contenuto o lacuna sostanziale; medio=precisione/usabilità; lieve=bozza.

| ID | Posizione | Categoria | Gravità | Descrizione | Correzione proposta | Stato |
|---|---|---|---|---|---|---|
${rows}

## 4. Osservazioni per capitolo

Tutti i file sotto indicati sono stati letti per intero, non campionati; i blocchi troncati sono stati recuperati. Il ledger conserva percorso completo, SHA256, esitoquiz e rilievi. Nessuna contraddizione sistematica fra lettera corretta e commento dei distrattori è emersa nelle batterie lette. Questo non elimina gli errori sostanziali dei riferimenti e la debolezza delle verifiche EPNE.

| Originale | Lettura/verifica | Rilievi |
|---|---|---|
${obs}

## 5. Coerenza globale

Letti indiciFC01/02/03, indicevolume, matrici didatticheFC01/02/03 e volume, matrice materieFC03. L’indicevolume includeFC01 nel corpo ma non nei metadati module_codes/book_refs. La matricevolume del30luglio conserva29blocker e riferimenti a composizione ormai storica; quellaFC02 dichiara80nuclei completi; quellaFC03 dichiara95completi. Questi documenti non rappresentano in modo coerente la versione corrente. FC03 assegna Q6C1E1 a ogni singolo nucleo, sebbene le sei verifiche siano alla fine del capitolo e generiche. La fonte non può essere una generica indicazione source_refs: serve l’atto/paragrafo che sostiene il concetto.

Promesse non soddisfatte: pensioni, ammortizzatori, invalidità, ISEE/DSU, potestà ispettive, assicurazioneINAIL sostanziale, contabilitàEPNE e parti della fiscalità/processo. La matricevolume segnala inoltre imposta di registro e verticale merceologica/tecnica: definire pubblicamente il perimetro e la destinazione; il fatto che una materia sia stata elencata nel piano non costituisce copertura. Le basi comuni possono restare nelVOL01, ma richiedono un rinvio preciso e verificato; le nozioni specialistiche vanno insegnate qui.

Le note di lettura conservano ulteriori microinterventi: pronomi e accordi, cambi di forma nelle istruzioni, ripetizioni delDecoder e del metodo, riallineamento di rubriche/rinvii e casi. Le tre ancore fiscali già rilevate nell’audit precedente devono essere ricontrollate nel prodotto finale dal coordinatore; non sono ricertificate qui come funzionanti.

## 6. Contenuto da verificare

Riscontri esterni mirati su fonti primarie consultate durante questa revisione:

${src}

Source note lette direttamente, oltre alle matrici: processo-tributario-dlgs-175-2024-aggiornamento-2026-07-18; aran-ccnl-funzioni-centrali-pcm-2022-2026; m-fc03-fonti-ufficiali-enti-epne-2026; bandoRIPAM-INAIL308; INL-vigilanza. Le prime due contengono gli errori temporali rilevati. La notaEPNE ammette fonti di contesto e statuti/regolamenti ancora da verificare: non sostiene una certificazione specialistica conclusa. Il bando campione308,40quesiti/60minuti, è coerente con la source note; non è stato ricertificato integralmente sulPDFufficiale in questo incarico.

Restano verifiche specialistiche dopo riscrittura: aliquote/soglie/fattispecie tributarie, transizioni2024–2027, codificazione fiscale complessiva, articolo124CDU(rimborso/estinzione), disciplina doganale aggiornata, fonti contabili/OIC, ordinamenti degli enti e competenze della vigilanza. Si propone riesame puntuale, non si attribuisce un esito positivo a verifiche non eseguite.

## 7. Suggerimenti facoltativi (non errori)

Conservare le buone griglie fatto-competenza-regola-output e i calcoli espliciti verificati: partita doppia, ponte utile-imponibile, IVA, indici e stima comparativa. Ridurre introduzioni metodologiche ripetute per far spazio a teoria e casi specialistici. Unificare le simulazioni con fascicolo candidato e fascicolo soluzioni. Presentare piani30/60/90 come tre disponibilità alternative oppure chiarire che sono fasi di un unico ciclo90giorni.

## 8. Priorità degli interventi

1. Correggere fonti temporali errate e propagazioni: TU175,CCNL, sospensione, dogane/accise, definizioni contabili.
2. Completare contenuti specialistici promessi, soprattuttoFC03, con nuclei verificabili e rinvii precisi.
3. Sostituire verifiche generiche, completare simulazioni e riallineare matrici sulla prova reale di apprendimento.
4. Rimuovere backstage e normalizzare struttura, acronimoBANDO, ortografia e apparati.
5. Ricomporre prodotto e verificarePDF/link/indici tramite coordinatore; nuova verifica normativa sui passaggi modificati.

## 9. Giudizio di pubblicabilità

**Revisione sostanziale necessaria.** I flag final/text_frozen e gli stati completo non giustificano rilascio. Le criticità riguardano il contenuto da studiare e l’affidabilità delle risposte, prima dell’impaginazione. Questo audit propone interventi; non li applica e non chiude gate della pipeline.

## 10. Limiti di questa revisione

Integrale si riferisce alla lettura dei50originali assegnati e alle verifiche interne di quiz/casi. Non significa certificazione esaustiva di ogni norma, prassi, fontegrezza o collegamento esterno. PDF/frontmatter e apparati di vendita spettano al coordinatore. Le fontiweb sono mirate; alcune attestano definizioni storiche stabili, altre il contratto/disciplina2026. Dove l’accessoHTML era protetto sono usati PDF ufficiali o estratti istituzionali indicizzati, senza dichiarare una lettura integrale del corpus normativo. Tutti i50hash sono ricontrollati alla chiusura; eventuali modifiche successive richiedono riesame differenziale.
`;
fs.mkdirSync('wiki/reviews/audit-integrale-2026-10-02',{recursive:true});
const protectedParts:string[]=[];
let polished=report.replace(/\[[^\]]*\]\([^)]*\)|https?:\/\/\S+|m-fc\S+\.md|\b(?:V03-\d+|fc0\d\/[\w*-]+|FC0\d|M-FC0\d|VOL-?0\d|Q6C1E1|05A|05B|314-bis)\b/g,x=>`§${protectedParts.push(x)-1}§`);
polished=polished.replace(/([a-zàèéìòùA-Z])(\d)/g,'$1 $2').replace(/(\d)([a-zàèéìòùA-Z])/g,'$1 $2').replace(/,(?=[a-zA-ZÀ-ÿ])/g,', ').replace(/:(?=[a-zA-ZÀ-ÿ0-9])/g,': ');
for(const [a,b] of Object.entries({'indicevolume':'indice volume','matricevolume':'matrice volume','source_refs':'source_refs','esitoquiz':'esito quiz','fontiweb':'fonti web','fontegrezza':'fonte grezza','accessoHTML':'accesso HTML','verificarePDF':'verificare PDF','visivaPDF':'visiva PDF','PDFufficiale':'PDF ufficiale','assicurazioneINAIL':'assicurazione INAIL','contabilitàEPNE':'contabilità EPNE','CCNLFunzioniCentrali':'CCNL Funzioni Centrali','acronimoBANDO':'acronimo BANDO','IstruzioneRicerca':'Istruzione e Ricerca','art1comma1letterab':'art. 1, comma 1, lettera b'})) polished=polished.replaceAll(a,b);
polished=polished.replace(/§(\d+)§/g,(_,i)=>protectedParts[Number(i)]);
fs.writeFileSync('wiki/reviews/audit-integrale-2026-10-02/VOL-03.md',polished);
console.log(JSON.stringify({chapters:ledger.chapters.length,readComplete:ledger.chapters.filter((x:any)=>x.readComplete).length,hashesMatch:ledger.chapters.every((x:any)=>x.hashVerifiedAtClose),findings:f.length}));
