import fs from 'node:fs';
import crypto from 'node:crypto';
const dir='artifacts/review-integrale-2026-10-02/';
const l=JSON.parse(fs.readFileSync(dir+'VOL-11-ledger.json','utf8'));
const rows:any[]=[];
function add(ch:number,line:number,category:string,severity:string,excerpt:string,problem:string,proposal:string){rows.push({id:`V11-${String(rows.length+1).padStart(2,'0')}`,chapter:ch,path:ch?l.chapters[ch-1].path:'wiki/books/moduli/m-tr04-ambiente-protezione-civile/planning/01-indice-analitico-vol-11.md',line,category,severity,excerpt,problem,proposal,status:'non applicato'});}
add(1,58,'Ripetizioni','grave','Un ultimo controllo','Lo stesso blocco di cinque paragrafi ricorre cinque volte: righe 58–65, 84–91, 118–125, 153–160 e 171–178. Gonfia il capitolo senza aggiungere apprendimento.','Conservare una sola formulazione e sostituire le ripetizioni con differenze documentate fra i quattro profili e prove esemplificative.');
add(1,162,'Precisione','medio','SNPA','SNPA è presentato come coordinatore distinto dal sistema che invece comprende ISPRA e le agenzie.','Descrivere la composizione del sistema e attribuire a ISPRA la funzione di coordinamento prevista dalla legge n. 132/2016.');
add(1,206,'Apparati','grave','30/60/90','Il piano è un unico percorso di 90 giorni, senza alternative complete per 30 e 60 giorni né quattro adattamenti professionali.','Fornire calendari alternativi, carichi, priorità, prove e soglie di recupero per i profili AMB, PC, EN e LOC.');
add(2,63,'Copertura','grave','D.Lgs. 152','La mappa del decreto omette parti e principi generali; mancano il quadro costituzionale delle competenze, la legge istitutiva del SNPA e lo sviluppo dei LEPTA.','Integrare art. 117, secondo comma, lettera s), e art. 118 Cost.; principi degli artt. 3-bis e seguenti; legge n. 132/2016; espansione e funzione dei LEPTA. Presentare tutte le parti del decreto.');
add(2,88,'Didattica','medio','competenza','I passaggi metodologici si ripetono anche alle righe 232–235; i due mini-esercizi alle righe 172 e 204 non hanno una soluzione completa.','Ridurre le duplicazioni e aggiungere soluzioni con soggetto, fondamento, atto e motivazione.');
add(3,118,'Precisione','grave','verifica preliminare','La verifica preliminare e lo screening VIA sono accostati con terminologia ambigua; la verifica di assoggettabilità a VAS non viene insegnata.','Distinguere art. 6, comma 9, art. 19 e art. 12 del D.Lgs. n. 152/2006, con presupposti, oggetto, esito e casi separati.');
add(3,224,'Esercizi','grave','opera','Il mini-esercizio può indurre a ricavare automaticamente la VIA dalla sola presenza di un’opera in un sito; mancano i fatti che determinano l’assoggettamento.','Precisare tipologia, dimensioni, localizzazione, allegato e condizioni; ammettere la risposta condizionata solo se questi dati sono intenzionalmente omessi.');
add(3,98,'Normativa','medio','può esprimere','Il nuovo art. 25, comma 7-ter, è realmente presente nel quadro 2026; il testo lo parafrasa come facoltà, mentre la disposizione usa esprime, al ricorrere dei suoi presupposti.','Rendere fedelmente condizioni, istanza del proponente e contenuto del giudizio sull’intero ciclo di vita, senza mutare un obbligo condizionato in facoltà.');
add(3,46,'Copertura','grave','VIA e VAS','Mancano uno sviluppo della VIncA, il raccordo con Natura 2000, PAUR e provvedimento unico, riparto delle competenze e principali sequenze temporali.','Integrare i nuclei richiesti dai profili ambientali, con rinvii puntuali agli artt. 7-bis, 27 e 27-bis e al D.P.R. n. 357/1997; inserire un diagramma procedurale datato.');
add(4,110,'Normativa','medio','elenco tassativo','L’elenco dei sette atti AUA è presentato come chiuso, senza la facoltà regionale di individuare ulteriori atti. La stessa semplificazione è nella source note.','Integrare l’art. 3, comma 2, del D.P.R. n. 59/2013 e verificare il territorio scelto per il caso.');
add(4,108,'Precisione','medio','adotta o trasmette','Il ruolo del SUAP non è distinto con sufficiente precisione dall’adozione dell’AUA da parte dell’autorità competente.','Separare adozione dell’autorità competente e rilascio tramite SUAP, ricostruendo il procedimento concretamente applicabile.');
add(4,95,'Copertura','grave','termini','Durata, rinnovo e passaggi dell’AUA, riesame AIA, allegati e regimi delle emissioni sono evitati anziché insegnati. La cautela sui dati mancanti della traccia si estende alle norme da conoscere.','Aggiungere una tabella normativa datata: AUA, AIA e artt. 269–272, ambito, soggetti, termini, modifiche ed effetti. Consolidare anche lo stato di recepimento della direttiva (UE) 2024/1785.');
add(5,148,'Copertura','grave','quattro anni','La durata ordinaria dello scarico è indicata, ma manca il termine per il rinnovo e il raccordo con il regime AUA; poco sviluppati divieti di scarico sul suolo/sottosuolo e pianificazione delle acque.','Completare artt. 103, 104 e 124, precisando regimi speciali, rinnovo e rapporto con AUA; integrare distretto, piano di tutela e obiettivi di qualità.');
add(5,215,'Aggiornamento','medio','indicatori','L’elenco della qualità tecnica del servizio idrico resta ai sei indicatori M1–M6 e omette M0, resilienza idrica, già incluso nella RQTI.','Aggiungere M0 e distinguere macroindicatori, indicatori semplici e relativa funzione, citando la disciplina ARERA corrente.');
add(5,168,'Esempi','grave','campionamento','Il metodo resta descrittivo: nessun confronto numerico svolto fra analisi, limite pertinente, periodo e condizioni di campionamento.','Inserire un dataset didattico con titolo e fonte del limite, verbale di prelievo, risultato e conclusione motivata.');
add(5,207,'Refusi','lieve','program­ma','È presente un carattere di sillabazione invisibile nella parola programma.','Normalizzare il carattere nel sorgente e verificare ricerca, copia e resa del PDF.');
add(6,127,'Copertura','grave','RENTRI','L’aggiornamento delle date è utile, ma non viene insegnato chi è obbligato o escluso dopo la legge n. 199/2025; restano generici termini del registro e responsabilità documentale.','Fornire una matrice soggetti/rifiuti/obblighi/esenzioni, con fonte e data; completare artt. 188, 190 e 193 e un FIR compilato.');
add(6,68,'Copertura','grave','codice EER','Classificazione, caratteristiche HP, end of waste, autorizzazioni degli impianti e Albo sono trattati senza un codice concreto o un percorso completo di qualificazione.','Svolgere almeno un esempio EER e uno con voce a specchio, distinguendo criteri UE/nazionali/caso per caso e titoli degli artt. 208, 212 e 214–216.');
add(7,61,'Precisione','medio','inferiori','La definizione di sito non contaminato esclude letteralmente l’uguaglianza alle CSC o CSR, mentre altre parti del capitolo usano correttamente uguale o inferiore. La stessa semplificazione ricorre nella source note.','Uniformare la definizione all’art. 240 e verificare separatamente la formulazione dei passaggi procedurali; inserire valori esattamente pari alla soglia fra gli esempi.');
add(7,225,'Precisione','medio','altrove','La riparazione complementare è descritta solo come intervento altrove; può interessare anche il sito danneggiato.','Precisare sede e finalità della riparazione complementare secondo l’allegato 3 alla parte sesta.');
add(7,145,'Copertura','grave','procedimento','Dopo i primi adempimenti, termini e competenze del procedimento restano incompleti; l’intervento pubblico è affidato genericamente all’amministrazione competente. Il danno ambientale non distingue compiutamente ambiti oggettivi e soggettivi.','Completare la sequenza degli artt. 242 e 250, responsabilità e limiti degli artt. 298-bis e 303; aggiungere un confronto numerico CSC/CSR e un caso di responsabilità.');
add(8,86,'Copertura','grave','valori limite','Le categorie dei valori dell’aria sono nominate senza definizioni operative né esempi di periodo di mediazione e numero di superamenti.','Definire ciascuna categoria e inserire un confronto svolto per PM10, PM2,5 o NO2, distinguendo diritto nazionale e transizione alla direttiva (UE) 2024/2881.');
add(8,166,'Copertura','grave','classificazione acustica','Mancano classi acustiche, periodi diurni/notturni, criterio differenziale con esclusioni e grandezze di base applicate.','Aggiungere scheda normativa datata e un esempio numerico con livello ambientale/residuo, limiti assoluti e differenziali; spiegare Leq, Lden e Lnight nei rispettivi contesti.');
add(8,217,'Copertura','medio','informazione','La comunicazione del dato è trattata, ma non la disciplina dell’accesso all’informazione ambientale.','Integrare il D.Lgs. n. 195/2005: titolari, assenza di interesse qualificato, termini, modalità ed eccezioni, con rinvio preciso al modulo di procedimento generale.');
add(9,133,'Definizioni','medio','contravvenzione','La definizione resta circolare e non insegna il criterio formale di distinzione dai delitti.','Distinguere specie di pene, natura dell’illecito e conseguenze, usando esempi ambientali correnti.');
add(9,151,'Copertura','grave','procedura estintiva','Mancano termini, misura del pagamento, proroghe e problemi di ammissibilità della procedura della parte sesta-bis; anche la legge n. 689/1981 resta priva di una timeline utilizzabile.','Integrare gli artt. 318-bis e seguenti, linee guida SNPA e orientamenti pertinenti; per la legge n. 689/1981 sviluppare o rinviare puntualmente a termini, difese, pagamento e ordinanza.');
add(9,239,'Esercizi','grave','norma da verificare','Il caso non porta alla qualificazione di una fattispecie concreta: le righe della matrice rinviano sempre alla norma da verificare.','Dare fatti sufficienti e individuare disposizioni, natura dell’illecito, elementi mancanti e conseguenze; coprire almeno acque, rifiuti ed emissioni e distinguere i delitti.');
add(10,105,'Precisione','medio','Prefetto','La competenza del Prefetto è descritta senza esplicitare i presupposti dell’art. 9 relativi agli eventi e alla loro imminenza.','Integrare presupposti e raccordo con Regione, enti locali e direzione tecnica dei soccorsi.');
add(10,147,'Copertura','grave','aree','Non sono sviluppate le diverse aree di emergenza e i principali centri di coordinamento; assenti attivazione e tutele operative del volontariato.','Distinguere aree di attesa, assistenza e ammassamento; spiegare CCS, COM e DiComaC nei rispettivi contesti e artt. 39–40 del Codice, senza imporre un’organizzazione locale universale.');
add(11,120,'Allertamento','grave','massime attivazioni','La tabella e il passaggio alla riga 144 associano il rosso alle massime attivazioni, indebolendo la distinzione fra allerta e fase operativa. Gli indirizzi nazionali prevedono almeno preallarme in caso di rosso, con eventuale intensificazione in base alla situazione.','Indicare le attivazioni minime previste e separarle dalla decisione locale: almeno attenzione per giallo/arancione, almeno preallarme per rosso; motivare ogni livello superiore con scenario e piano.');
add(11,51,'Copertura','grave','rischi','Per il profilo di protezione civile sono insufficienti le specificità dei rischi sismico, vulcanico, maremoto, incendi boschivi e industriale; prevale il metodo generale.','Aggiungere schede di scenario con prevedibilità, monitoraggio, misure e catena operativa; per l’industriale sviluppare il raccordo con D.Lgs. n. 105/2015, PEI e PEE.');
add(11,255,'Casi','medio','Vallechiara','La matrice unisce i due rami alternativi senza una colonna che identifichi lo scenario; nel briefing va resa esplicita la diversa validità temporale del bollettino rispetto alle osservazioni.','Separare i rami o aggiungere scenario e validità; mantenere distinti fatti osservati e previsioni future.');
add(12,121,'Copertura','grave','regimi amministrativi','Le tre etichette dei regimi FER non sono accompagnate da allegati, criteri, autorità, tempi ed effetti; il correttivo 2025 non è identificato.','Consolidare il D.Lgs. n. 190/2024 e i correttivi vigenti, insegnare la lettura degli allegati A–C con due casi e aggiornare il recepimento RED III.');
add(12,200,'Copertura','grave','CER','Il lettore non dispone dei requisiti essenziali di perimetro, impianti, partecipanti e controllo; manca il calcolo dell’energia condivisa.','Integrare art. 31 del D.Lgs. n. 199/2021, TIAD e regole GSE vigenti, distinguendo configurazione e incentivi; svolgere un esempio temporale con immissioni e prelievi.');
add(12,156,'Copertura','grave','efficienza','La trattazione non copre adeguatamente il profilo energia: diagnosi e disciplina degli edifici pubblici sono generiche; manca qualunque calcolo completo di risparmio, costo, emissioni o rendimento.','Integrare quadro vigente su diagnosi/edifici e almeno un dataset con baseline, consumi, investimento, risparmio e indicatore; sviluppare PNIEC, PNACC e strumenti locali nei limiti del bando.');
add(13,123,'Precisione','medio','regime','La distinzione fra regimi DNSH non esplicita sufficientemente il contributo sostanziale rispetto al solo non arrecare danno significativo.','Definire i due regimi della guida applicabile e svolgere la selezione della scheda per l’intervento.');
add(13,147,'Copertura','grave','CAM','Il caso della palestra non identifica alcun decreto o criterio CAM concreto e rimane una matrice generica. Il D.M. 24 novembre 2025 è disponibile e va considerato col relativo regime transitorio.','Identificare decreto vigente e data della procedura; applicare almeno un criterio con mezzo di prova, fase, responsabile e controllo della variante.');
add(13,173,'Copertura','medio','LCA e LCC','Mancano le fasi fondamentali della LCA e un esempio di costo del ciclo di vita, pur essendo strumenti centrali del capitolo.','Esporre obiettivo/campo, inventario, valutazione degli impatti e interpretazione; aggiungere un LCC numerico con ipotesi dichiarate e distinguere costi ed esternalità.');
add(14,199,'Soluzioni','grave','Simulazione 6','La simulazione 6 richiede tabella e nota, ma offre solo prosa; la simulazione 8 richiede una matrice in otto righe, anch’essa non restituita. La prova integrata non assegna compiti e tempi concreti.','Fornire esattamente gli output richiesti, con rubriche che valutino anche formato, responsabilità, termini e verificabilità.');
add(14,83,'Struttura','medio','Da sapere in cinque righe','Paragrafi metodologici interrompono sintesi e simulazioni, anche dopo i titoli delle simulazioni 1, 3, 5 e 8.','Raggruppare il metodo all’inizio e mantenere ciascuna unità composta da consegna, dati, soluzione e griglia.');
add(14,264,'Didattica','grave','soglie','Il richiamo a non inventare dati diventa una rinuncia ad applicare regole e valori che il candidato deve conoscere; il laboratorio raramente verifica una decisione tecnica determinata.','Distinguere fatti mancanti e conoscenze normative; costruire prove con dati sufficienti, scelta motivata della norma e soluzione verificabile.');
add(0,1,'Apparati','grave','Appendici A–E','L’indice analitico promette cinque appendici operative e percorsi per quattro profili; questi materiali non risultano nei quattordici capitoli.','Verificare l’export e produrre le appendici effettive o riallocarne i contenuti, aggiornando in modo coerente la promessa editoriale.');
add(0,1,'Coerenza editoriale','grave','completo','La matrice dichiara 14 nuclei completi e numerose verifiche integrali, mentre permangono lacune sostanziali. L’indice di modulo descrive ancora uno scaffold e contiene una sequenza letterale di escape.','Riallineare matrice, indice e metadati alla copertura reale; le quantità di parole, i sei quiz e i marcatori non provano completezza.');
add(6,142,'Apparati editoriali','medio','audit','Restano istruzioni di controllo al text freeze, codici interni e date di audit nel testo destinato al lettore; il quadro congelato ad agosto va rivalutato alla data editoriale del 2 ottobre 2026.','Separare note interne e informazione al lettore; mantenere una data di aggiornamento leggibile e fonti puntuali, verificando i dati effettivamente mobili.');
const sources=[
{chapters:[3],claim:'Art. 25, comma 7-ter, VIA nel 2026',url:'https://unmig.mase.gov.it/decreto-legge-20-febbraio-2026-n-21/',outcome:'Testo primario indicizzato riscontrato: giudizio sull’intero ciclo di vita e verbo esprime. Non certificato integralmente il testo consolidato di tutta la parte seconda.'},
{chapters:[4],claim:'Ulteriori atti regionali AUA',url:'https://www.normattiva.it/atto/caricaDettaglioAtto?atto.articolo.numero=0&atto.codiceRedazionale=13G00101&atto.dataPubblicazioneGazzetta=2013-05-29',outcome:'Identificata la fonte primaria del D.P.R. n. 59/2013; apertura diretta non riuscita. Il riferimento puntuale proposto è art. 3, comma 2, da acquisire al consolidamento.'},
{chapters:[5],claim:'RQTI include M0',url:'https://www.arera.it/fileadmin/allegati/docs/26/1-26disa.pdf',outcome:'Testo primario indicizzato letto: elenco M0–M6, inclusa resilienza idrica. Confermato anche nella delibera 595/2024/R/idr.'},
{chapters:[6],claim:'FIR digitale dal 16 settembre 2026',url:'https://www.rentri.gov.it/news/fir-chiusura-delle-modalita-operative-di-sicurezza',outcome:'Riscontro primario istituzionale della transizione fino al 15 settembre e obbligo dal 16 settembre per gli iscritti; il dato del capitolo non è stato classificato come errore.'},
{chapters:[6],claim:'MUD 2026, termine 3 luglio',url:'https://www.isprambiente.gov.it/it/servizi/mud-2026',outcome:'Riscontro primario del D.P.C.M. 30 gennaio 2026 e termine del 3 luglio per i dati 2025.'},
{chapters:[9],claim:'D.Lgs. n. 81/2026 e nuovi reati',url:'https://eur-lex.europa.eu/legal-content/IT/TXT/PDF/?uri=NIM%3A202603077',outcome:'Riscontrata la pubblicazione primaria del decreto; data di entrata in vigore del 2 giugno 2026 corroborata dalla banca dati MEF. Non certificata ogni fattispecie o interpretazione giurisprudenziale.'},
{chapters:[11],claim:'Allerta e fasi operative minime',url:'https://www.protezionecivile.gov.it/it/normativa/direttiva-del-pcm-del-12-agosto-2019-0/',outcome:'Letto il passaggio che richiama gli indirizzi del 10 febbraio 2016: attenzione minima per giallo/arancione, preallarme minimo per rosso. Riscontro anche nella pagina istituzionale della Regione Marche sulle procedure di allertamento.'},
{chapters:[11],claim:'Direttiva IT-alert del 12 febbraio 2026',url:'https://www.protezionecivile.gov.it/en/normativa/direttiva-ministro-pcpm-12-febbraio-2026-0/',outcome:'Letti gli artt. 1–2: sperimentazione maremoto/Stromboli fino al 31 dicembre 2026 e applicazione dedicata per precipitazioni intense con obiettivo di dodici mesi. Conferma la distinzione nel capitolo.'},
{chapters:[12],claim:'Obiettivo climatico UE 2040',url:'https://eur-lex.europa.eu/eli/reg/2026/667/oj',outcome:'Il testo primario indicizzato conferma l’obiettivo vincolante di riduzione delle emissioni nette del 90% rispetto al 1990. Apertura integrale bloccata dalla pagina di verifica: non certificati tutti i meccanismi flessibili.'},
{chapters:[13],claim:'CAM edilizia del 24 novembre 2025',url:'https://www.gazzettaufficiale.it/eli/id/2025/12/03/25A06516/SG',outcome:'Riscontrata la pubblicazione del decreto e la disposizione di entrata in vigore dopo sessanta giorni; non è stato ricostruito integralmente il regime transitorio né l’allegato tecnico.'}
];
const support=['wiki/books/moduli/m-tr04-ambiente-protezione-civile/index.md','wiki/books/moduli/m-tr04-ambiente-protezione-civile/planning/01-indice-analitico-vol-11.md','wiki/books/moduli/m-tr04-ambiente-protezione-civile/planning/02-matrice-copertura-didattica.md','wiki/sources/vol-11-ambiente-protezione-civile-sostenibilita-dossier-v4.md','wiki/sources/m-tr04-source-bundle-ambiente-protezione-civile-2026.md',...['aia-aua-emissioni','acque-scarichi-servizio-idrico','rifiuti-rentri-fir-mud','bonifiche-siti-contaminati-danno-ambientale','aria-rumore-monitoraggio-dati','controlli-sanzioni-reati-ambientali','sistema-protezione-civile-pianificazione','allertamento-it-alert-emergenze','clima-energia-rinnovabili-cer-efficienza','dnsh-cam-ciclo-vita-sostenibilita-pa'].map(x=>'wiki/sources/'+x+'-quadro-ufficiale-2026.md'),'wiki/sources/laboratorio-casi-quesiti-sintetici-vol-11-2026.md'];
l.status='text-review-complete';l.findings=rows;l.externalClaimsChecked=sources;l.supportFiles=support.filter(p=>fs.existsSync(p)).map(path=>({path,sha256:crypto.createHash('sha256').update(fs.readFileSync(path)).digest('hex'),readComplete:true}));
l.limitations=['Lettura integrale dei 14 capitoli, di tutti i quiz, commenti e casi. Controllati indice, matrice, dossier, bundle e undici note specifiche. Le ulteriori fonti trasversali richiamate nel frontmatter non sono state tutte rilette integralmente.','Verifiche esterne mirate sui claim elencati; non è una certificazione giuridica integrale di ogni articolo vigente o norma regionale. Alcuni riscontri sono limitati al testo indicizzato ufficiale per problemi di accesso.','Restano da consolidare in particolare recepimenti IED/RED III/efficienza/EPBD, disciplina tecnica completa, giurisprudenza e regimi locali. Le lacune di contenuto sono accertate; le integrazioni normative vanno validate prima di applicarle.','Impaginazione e presenza delle appendici nell’export sono trattate nel rapporto PDF separato. Nessuna correzione applicata al libro.'];
for(const[i,c]of l.chapters.entries()){c.findingIds=rows.filter(r=>r.chapter===i+1).map(r=>r.id);c.externalClaimsChecked=sources.filter(s=>s.chapters.includes(i+1));c.hashMatches=crypto.createHash('sha256').update(fs.readFileSync(c.path)).digest('hex')===c.sha256;}
fs.writeFileSync(dir+'VOL-11-ledger.json',JSON.stringify(l,null,2));
let out='# VOL-11 — Revisione integrale del testo, 2 ottobre 2026\n\n## 1. Sintesi editoriale\n\nLetti integralmente i 14 capitoli originali, inclusi quiz, commenti, casi e apparati. Il volume offre distinzioni utili e un quadro normativo più concreto nei capitoli centrali, ma richiede una revisione sostanziale per sostenere tutti i quattro profili promessi. Errori puntuali, ripetizioni e mancanza di applicazioni determinate impediscono la pubblicazione nello stato attuale. Nessuna modifica applicata.\n\n## 2. Punti applicati della checklist\n\nApplicati i 30 punti della skill revisore-editoriale-totale al testo, con controllo di lingua, struttura, precisione, teoria, esempi, quiz, fonti, rimandi e apparati. Le 84 domande principali sono state risolte: 24 aperte e 60 a scelta multipla. Non individuati disallineamenti sistematici fra lettera corretta e commento; numerosi distrattori sono però troppo facili e le prove verificano spesso prudenza metodologica più che conoscenza specialistica.\n\n## 3. Tabella errori e integrazioni necessarie\n\nRighe riferite ai sorgenti identificati nel ledger. Grave = errore o lacuna che ostacola la preparazione promessa; medio = correzione locale necessaria; lieve = refuso.\n\n| ID | Posizione | Categoria | Gravità | Descrizione | Correzione proposta | Stato |\n|---|---|---|---|---|---|---|\n';
out+=rows.map(r=>`| ${r.id} | ${r.chapter?'Cap. '+r.chapter:'Indice analitico'}, r. ${r.line} | ${r.category} | ${r.severity} | «${r.excerpt}»: ${r.problem} | ${r.proposal} | Non applicato |`).join('\n');
out+='\n\n## 4. Osservazioni per capitolo\n\n';
const observations=['Il capitolo di orientamento va alleggerito eliminando la ripetizione letterale e sostituendola con percorsi reali per i quattro profili.','La mappa istituzionale deve poggiare su competenze, principi e legge istitutiva, prima delle raccomandazioni di metodo.','Distinguere gli screening e completare il raccordo fra valutazioni, autorizzazioni e tutela dei siti Natura 2000.','Occorrono ambiti, durata, rinnovo e procedimento effettivo dei titoli; la variabilità territoriale va gestita con esempi dichiarati.','Buona distinzione fra scarico e rifiuto liquido; da completare rinnovi, qualità delle acque, dati ARERA e confronto analitico.','Le date RENTRI e MUD sono riscontrate; manca il percorso completo che porti da un operatore concreto agli obblighi applicabili.','La separazione fra bonifica e danno ambientale funziona; correggere le definizioni e aggiungere termini e casi numerici.','La qualità del dato è spiegata, ma il candidato non è ancora in grado di risolvere un confronto quantitativo aria o rumore.','Il decreto del 2026 esiste: il problema principale è la scarsa applicazione delle fattispecie e dei termini, non l’assenza dell’aggiornamento.','Il piano è impostato bene sul metodo; completare centri, aree, volontariato e presupposti delle competenze.','Correggere l’associazione fra rosso e massima attivazione; la direttiva IT-alert del 2026 è invece riscontrata.','L’obiettivo climatico 2040 è reale; il profilo energia richiede più disciplina operativa e calcoli svolti.','Distinzioni DNSH/CAM e LCA/LCC utili, ma il caso deve applicare un criterio reale e produrre evidenze specifiche.','Le soluzioni devono rispettare il formato richiesto e arrivare a scelte determinate quando i dati lo permettono.'];
observations.forEach((x,i)=>out+=`- **Capitolo ${i+1}**: ${x}\n`);
out+='\n## 5. Coerenza globale\n\nLa ripetizione di fonte, responsabilità, evidenza e controllo è utile come metodo comune, ma occupa spazio che dovrebbe insegnare regole, termini, grandezze e decisioni. Il volume promette quattro profili: quello energia e quello di protezione civile richiedono maggiori integrazioni specialistiche. Le appendici A–E promesse dall’indice devono essere riconciliate con l’export. La matrice non può considerare un nucleo completo perché contiene sei quiz o supera una soglia di parole.\n\n## 6. Contenuto verificato e da verificare\n\n';
out+=sources.map(s=>`- [${s.claim}](${s.url}): ${s.outcome}`).join('\n');
out+='\n\nLe note interne su AUA, bonifiche e indicatori idrici propagano alcune semplificazioni del capitolo: il successivo intervento deve riallineare anche le fonti editoriali. Le note di energia e aria prescrivono espressamente di evitare tabelle numeriche: tale scelta editoriale va rivista per offrire esempi datati e risolvibili.\n\n## 7. Suggerimenti facoltativi\n\nUsare un piccolo territorio comune per collegare acque, rifiuti, bonifiche e pianificazione, conservando casi indipendenti per l’autovalutazione. Separare domande e soluzioni. Raccogliere i promemoria di metodo in una pagina iniziale e richiamarli senza ripeterli.\n\n## 8. Priorità degli interventi\n\nCorreggere prima allertamento, definizioni e indicatori; completare teoria e fonti mobili. Integrare casi numerici e soluzioni negli output richiesti. Verificare le appendici, ridurre ripetizioni, riallineare matrice e metadati; infine ricontrollare il PDF.\n\n## 9. Giudizio di pubblicabilità\n\n**Da revisionare sostanzialmente prima della pubblicazione.** Il materiale costituisce una base utile, ma non dimostra ancora la copertura autonoma dei quattro profili dichiarati.\n\n## 10. Limiti di questa revisione\n\n';
out+=l.limitations.map((x:string)=>'- '+x).join('\n');out+='\n\nLedger: `artifacts/review-integrale-2026-10-02/VOL-11-ledger.json`. Tutti i 14 hash ricontrollati alla chiusura.\n';
fs.writeFileSync('wiki/reviews/audit-integrale-2026-10-02/VOL-11.md',out);
console.log({chapters:l.chapters.length,readComplete:l.chapters.filter((c:any)=>c.readComplete).length,hashesMatch:l.chapters.every((c:any)=>c.hashMatches),findings:rows.length});
