import fs from 'node:fs';
import crypto from 'node:crypto';
const base='artifacts/review-integrale-2026-10-02/';
const ledger=JSON.parse(fs.readFileSync(base+'VOL-08-ledger.json','utf8'));
const rows:any[]=[];
function add(ch:number,line:number,category:string,severity:string,excerpt:string,problem:string,proposal:string){rows.push({id:`V08-${String(rows.length+1).padStart(2,'0')}`,chapter:ch,path:ch?ledger.chapters[ch-1].path:'wiki/books/moduli/m-tr01-ict-trasformazione-digitale/index.md',line,category,severity,excerpt,problem,proposal,status:'proposto, non applicato'});}
add(0,1,'Stato editoriale','medio','publication-ready','L’indice dichiara la pubblicabilità ma il suo Stato editoriale rinvia ancora agli step 13–24; M-TR02 è descritto come incompleto.','Riconciliare indice, matrice e stato effettivo senza trasformare il metadato in certificazione.');
add(10,35,'Coerenza del metodo','grave','Base; Attori; Nodi; Documenti','BANDO cambia significato nei capitoli 10, 11 (r.35) e 12 (r.47), rispetto a Bando, Aree, Nuclei, Diario, Output usato nel resto della collana.','Ripristinare le cinque voci canoniche e ricollocare attori/documenti al loro interno.');
add(1,1,'Destinazione editoriale','medio','Apparato di verifica dei nuclei','Tutti i capitoli mantengono apparati di tracciabilità e formule rivolte al verificatore, non al candidato.','Conservare la tracciabilità nei file di lavoro; rendere il riepilogo per il lettore una mappa di studio senza linguaggio di audit.');
add(2,137,'Precisione tecnica','medio','rappresentazione','Complemento a due non nominato né mostrato; la virgola mobile è descritta con grandezza invece di esponente e significando.','Dare nomi corretti, intervalli e un esempio breve di rappresentazione e overflow; distinguere il modello dalla precisione effettiva.');
add(3,367,'Precisione tecnica','medio','memoria aggiuntiva','La complessità spaziale è identificata con la sola memoria ausiliaria.','Distinguere spazio totale, spazio dell’input e spazio ausiliario, dichiarando la convenzione degli esercizi.');
add(3,381,'Precisione tecnica','medio','cresce linearmente','O grande è definito come limite superiore ma poi interpretato come crescita esatta, anche nel raddoppio quadratico del quiz 5.','Usare Theta per l’ordine stretto oppure dichiarare il termine dominante e l’ipotesi semplificata del quiz.');
add(3,561,'Fonti','medio','materiali didattici universitari','Le fonti di algoritmi non sono identificabili.','Indicare autore, titolo, edizione o documentazione primaria e sezioni usate.');
add(4,97,'Esempio tecnico','medio','id_ufficio','Lo schema non impone NOT NULL sulla chiave esterna benché ogni pratica debba appartenere a un ufficio; l’esempio Assegnazione a r.169 ragiona inoltre su un attributo non riportato nello schema.','Allineare vincoli e schema alla cardinalità dichiarata; esplicitare gli attributi dell’esempio di normalizzazione.');
add(4,305,'Copertura didattica','grave','livelli di isolamento','L’isolamento è promesso ma mancano i quattro livelli e le anomalie che permettono di distinguerli.','Aggiungere una tabella di livelli/anomalie e una sequenza di due transazioni; segnalare differenze del DBMS scelto.');
add(5,377,'Precisione tecnica','medio','richiesta HTTP','L’incapsulamento presume TCP senza precisare la versione di HTTP.','Dichiarare HTTP/1.1 o HTTP/2 nell’esempio; ricordare HTTP/3 su QUIC.');
add(6,146,'Coerenza tecnica','medio','Livello','La regressione compare fra i livelli di test; a r.415 il capitolo spiega correttamente che è uno scopo trasversale.','Separare livelli e finalità del test in tabella.');
add(6,357,'Esercitazione','medio','veloce','La soluzione dell’esercizio sul requisito misurabile dice cosa specificare ma non formula un requisito verificabile.','Fornire un esempio con soglia e carico dichiarati come ipotetici e relativo test di accettazione.');
add(6,1,'Copertura didattica','medio','API','La progettazione di API resta descrittiva: mancano un payload, codici di risposta e un contratto minimo concreto.','Aggiungere un esempio end-to-end, con autorizzazione, errore e versionamento; spiegare i vincoli REST prima delle scelte implementative.');
add(7,177,'Copertura normativa','grave','strategici, critici e ordinari','Le classi cloud sono nominate senza i criteri di impatto; il regolamento 2024 resta privo di estremi e regime.','Inserire tabella classi/impatti/esempi e riferimento al decreto 21007/24, separando quadro stabile e verifica corrente della qualificazione.');
add(8,287,'Terminologia','medio','STRIDE','Le sei categorie sono elencate in inglese senza spiegazione applicativa.','Tradurre e associare a ciascuna una minaccia e un controllo sul caso della PA.');
add(8,530,'Esercitazione','medio','risposta aperta','Due soluzioni si limitano al criterio generale di correzione.','Mostrare una risposta svolta con asset, minaccia, rischio e controllo motivato.');
add(9,149,'Copertura normativa','grave','verificare','NIS2 è ridotta al richiamo del d.lgs.138/2024 e alla verifica futura: non insegna essenziali/importanti, obblighi di governance, criteri e sequenza delle notifiche; manca il raccordo con legge90/2024.','Sviluppare il nucleo normativo datato con presupposti, soggetti, atti ACN e decorrenze per coorte; distinguere 24/72 ore e relazione finale, GDPR e altri regimi senza universalizzare.');
add(9,86,'Copertura tecnica','grave','crittografia','Per un percorso cyber specialistico la trattazione non rende operative le differenze tra chiavi simmetriche/asimmetriche, firma, hash, certificati e catena di fiducia.','Aggiungere schema delle chiavi, esempi di cifratura/firma, proprietà del digest, PKI/TLS e password hashing, distinguendo concetti da prescrizioni di algoritmo.');
add(9,218,'Qualità dei quiz','medio','NO','Tutte le sei domande dei capitoli 9 e 10 hanno risposta negativa prevedibile; nel 9 la domanda6 confronta una notifica con un evento data breach.','Alternare casi e opzioni plausibili; confrontare incidente cyber e violazione di dati, poi i rispettivi obblighi di notifica.');
add(9,100,'Refuso','lieve','nel ignorare','Preposizione articolata errata.','Sostituire con nell’ignorare.');
add(10,192,'Definizione normativa','grave','quando pertinente','La definizione di open data rende eventuale il formato leggibile meccanicamente e non espone i tre requisiti cumulativi del CAD art.1 l-ter.','Esporre licenza/uso anche commerciale, formato aperto utilizzabile automaticamente con metadati, gratuità o regole di costo ammesse; distinguere dalle esclusioni di pubblicazione.');
add(10,196,'Copertura normativa','medio','possono includere','Gli obblighi HVD sono formulati come possibilità indistinta.','Indicare per quali serie e condizioni sono richiesti API, formato e download massivo secondo regolamento2023/138 e allegato; non generalizzare oltre il campo di applicazione.');
add(10,223,'Rinvio insufficiente','medio','procedure di adesione','Il rinvio al capitolo6 promette procedure e dettagli PDND che quel capitolo non contiene.','Aggiungere una spiegazione sufficiente o rinviare a una sezione effettiva e a documentazione ufficiale puntuale, correggendo la promessa.');
add(10,111,'Refuso','lieve','usare interno','Forma verbale al posto del sostantivo.','Sostituire con uso interno.');
add(11,169,'Copertura normativa','grave','calendario','La compliance non sviluppa definizioni dei ruoli, criteri di rischio, principali obblighi PA né calendario; la legge132/2025 resta un titolo, senza art.14.','Inserire casi classificati, responsabilità del deployer e regole PA; ricostruire il calendario dal testo vigente comprensivo delle modifiche2026 e distinguere obblighi già applicabili/futuri.');
add(11,102,'Copertura didattica','grave','F1','Il profilo data/AI non è sostenuto da algoritmi spiegati né da un calcolo completo di metriche; il cap.3 r.46 promette algoritmi ML nel cap.11.','Aggiungere almeno un metodo supervisionato e uno non supervisionato con esempio e una matrice di confusione svolta con precision/recall/F1; oppure delimitare esplicitamente la promessa del profilo.');
add(12,65,'Copertura normativa ICT','grave','riuso','La scelta sviluppare/acquistare/riusare non espone valutazione comparativa e riuso degli artt.68–69 CAD; il richiamo Consip non spiega gli obblighi specifici ICT.','Sviluppare CAD68–69 e linee guida AgID con una decisione motivata; verificare e integrare legge208/2015 commi512ss. con ambito/eccezioni e rinvio preciso al VOL09.');
add(12,115,'Esercitazione','medio','valore','Nessun esempio numerico consente di calcolare disponibilità, SLA o scostamento, nonostante la promessa misurativa.','Dare un dataset minimo e calcolo svolto con periodo, esclusioni e soglia ipotetica, evitando numeri presentati come obblighi universali.');
add(12,216,'Ruoli','medio','quando previsto','La funzione di direzione dell’esecuzione appare eventuale, senza distinguere esercizio da parte del RUP e nomina separata del DEC.','Spiegare la distinzione e rinviare al presupposto normativo preciso per il DEC distinto dal RUP.');
add(12,263,'Ruoli privacy','medio','validazione','La necessaria validazione del DPO è formulata come potere autorizzativo, in tensione con il cap.10 che ne descrive il ruolo consultivo.','Attribuire la decisione al titolare e qualificare informazione/consulenza/sorveglianza del DPO secondo il caso, senza creare un visto generale obbligatorio.');
add(13,475,'Esercitazione','grave','Caso autonomo','Il caso autonomo ha una rubrica ma non una soluzione modello; lo scritto tecnico a r.445 offre una scaletta senza un elaborato effettivo.','Fornire architettura motivata, alternative, assunzioni, test e criteri di punteggio con esempi di risposte; inserire una simulazione tecnica con artefatti verificabili.');
add(7,238,'Stile e progressione','medio','DevOps','Ripetizioni additive estese nei capitoli7–13; nel10 le definizioni arrivano dopo applicazioni e riprese.','Accorpare i paragrafi che non aggiungono concetti; usare spazio recuperato per teoria, esempi e soluzioni mancanti.');
const sources=[
{chapters:[4],claim:'Livelli di isolamento e anomalie; differenze PostgreSQL esplicite',url:'https://www.postgresql.org/docs/current/transaction-iso.html',outcome:'Conferma integrazione necessaria, non errore delle query esistenti.'},
{chapters:[5],claim:'HTTP/3 usa QUIC',url:'https://www.rfc-editor.org/rfc/rfc9114.html',outcome:'Conferma necessità di dichiarare versione nell’esempio TCP.'},
{chapters:[7],claim:'Classificazione cloud per impatto',url:'https://cloud.italia.it/strategia-cloud-pa/classificazione-di-dati-e-servizi/',outcome:'Definizioni ufficiali disponibili, assenti nel corpo.'},
{chapters:[7],claim:'Regolamento cloud21007/24 e regime agosto2024',url:'https://cloud.italia.it/qualificazione-servizi-cloud/',outcome:'Confermato quadro; catalogo e successive modifiche non certificati integralmente.'},
{chapters:[8],claim:'OWASP Top10 2025 è release finale',url:'https://owasp.org/projects/top-ten',outcome:'Confermato; non segnalato come riferimento futuro.'},
{chapters:[9],claim:'Sequenza notifiche NIS2 e governance',url:'https://www.mimit.gov.it/images/stories/digitale/seminari/23_ottobre_2025/SintesiNIS2.pdf',outcome:'Conferma quadro24/72ore/mese e obblighi governance; documento2025 non certifica tutte le decorrenze delle coorti2026.'},
{chapters:[10],claim:'Definizione CAD dati aperti',url:'https://docs.italia.it/italia/piano-triennale-ict/codice-amministrazione-digitale-docs/it/v2026-04-20/_rst/capo1_sezione1_art1.html',outcome:'Tre requisiti cumulativi confermati, lettera l-ter.'},
{chapters:[11],claim:'Legge132/2025 art14 PA',url:'https://www.gazzettaufficiale.it/atto/serie_generale/caricaArticolo?art.codiceRedazionale=25G00143&art.dataPubblicazioneGazzetta=2025-09-25&art.flagTipoArticolo=0&art.idArticolo=14&art.idGruppo=2&art.idSottoArticolo=1&art.idSottoArticolo1=10&art.progressivo=0&art.versione=1',outcome:'Confermati conoscibilità, tracciabilità, supporto alla decisione umana e misure tecniche/organizzative/formative nel testo originario; Normattiva riporta aggiornamento2026, consultazione intero atto fallita.'},
{chapters:[11],claim:'AI Act calendario modificato2026',url:'https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai',outcome:'La Commissione segnala Omnibus in vigore27luglio2026, alto rischio allegatoIII2dicembre2027 e prodotti2agosto2028; link al testo1744/2026 bloccato da controllo browser. Non certificata ricostruzione articolo per articolo.'},
{chapters:[12],claim:'Percorso comparativo acquisizione/riuso software PA',url:'https://docs.italia.it/italia/developers-italia/lg-acquisizione-e-riuso-software-per-pa-docs/it/stabile/attachments/allegato-e-tabella-sinottica-degli-elementi-necessari-al-percorso-decisionale.html',outcome:'Percorso ufficiale disponibile e non sviluppato nel capitolo.'}
];
ledger.status='text-review-complete';ledger.findings=rows;ledger.externalClaimsChecked=sources;
ledger.limitations=['Lettura integrale dei13capitoli correnti; matrici lette nelle righe canoniche e nei blocchi pertinenti, non integralmente in ogni appendice.','Controlli esterni mirati, non certificazione di ogni fonte, versione tecnica o norma. Atti ACN2026 e testo UE1744/2026 richiedono controllo ulteriore.','PDF separato: questo rapporto non certifica geometria, stampa o leggibilità delle pagine.','Nessun contenuto editoriale modificato; le proposte restano da applicare.'];
for(const [i,c] of ledger.chapters.entries()){c.externalClaimsChecked=sources.filter(s=>s.chapters.includes(i+1));c.findingIds=rows.filter(r=>r.chapter===i+1||r.chapter===0).map(r=>r.id);c.hashMatches=crypto.createHash('sha256').update(fs.readFileSync(c.path)).digest('hex')===c.sha256;}
fs.writeFileSync(base+'VOL-08-ledger.json',JSON.stringify(ledger,null,2));
let out='# VOL-08 — Revisione integrale del testo, 2 ottobre 2026\n\n## 1. Sintesi editoriale\n\nLetti integralmente tutti i 13 capitoli originali di M-TR01, comprese domande, risposte, casi e fonti finali. La struttura è leggibile e gli esempi di SQL, pseudocodice, subnetting e le chiavi dei quiz risultano coerenti. Il volume non è ancora pronto per la pubblicazione: il livello tecnico varia molto e alcuni nuclei normativi centrali sono sostituiti da rinvii alla verifica delle fonti. Nessuna correzione è stata applicata.\n\n## 2. Punti applicati della checklist\n\nApplicati i 30 punti della skill revisore-editoriale-totale al perimetro testuale: forma, sintassi, lessico, coerenza, struttura, contenuto, fonti, didattica, esempi e apparati. Il punto relativo alla resa grafica è demandato al rapporto PDF separato. Non equivale a validazione integrale di tutte le norme né delle appendici delle matrici.\n\n## 3. Tabella errori e integrazioni necessarie\n\nLe righe si riferiscono agli originali identificati con SHA-256 nel ledger. Gravità grave = ostacolo sostanziale alla preparazione promessa; medio = errore locale o miglioramento necessario; lieve = refuso.\n\n| ID | Posizione | Categoria | Gravità | Descrizione ed estratto | Correzione proposta | Stato |\n|---|---|---|---|---|---|---|\n';
out+=rows.map(r=>`| ${r.id} | ${r.chapter?'Cap. '+String(r.chapter).padStart(2,'0'):'Indice modulo'}, r.${r.line} | ${r.category} | ${r.severity} | «${r.excerpt}»: ${r.problem} | ${r.proposal} | Non applicato |`).join('\n');
out+='\n\n## 4. Osservazioni per capitolo\n\n';
for(const [i,c] of ledger.chapters.entries())out+=`- **${String(i+1).padStart(2,'0')} — ${c.title}**: lettura e revisione quiz complete. ${c.findings.join(' ')}\n`;
out+='\n## 5. Coerenza globale\n\nIl metodo BANDO deve mantenere un significato unico. Le note di tracciabilità non devono occupare il testo destinato al candidato. Le ripetizioni su rischio, evidenze, responsabilità e necessità di verifica sono numerose, mentre mancano esempi che dimostrino come applicare la regola. I rinvii alla parte comune sono legittimi solo se individuano una destinazione che contiene davvero il concetto promesso. Il campione di sette bandi offre un buon orientamento, ma non dimostra da solo la copertura di ogni profilo data/AI o cyber specialistico.\n\n## 6. Contenuto verificato e da verificare\n\n';
out+=sources.map(s=>`- [${s.claim}](${s.url}): ${s.outcome}`).join('\n');
out+='\n\nLetti inoltre gli indici di modulo e volume, la nota campione bandi, le cinque note consolidate cloud, IAM/incidenti, dati aperti, AI e procurement; della matrice sono state controllate le righe canoniche e i blocchi pertinenti. Le note stesse dichiarano review ancora necessaria: questo spiega la lacuna, non la risolve. Restano da verificare puntualmente i nuovi atti ACN, il raccordo legge90/2024, obblighi Consip ICT, HVD e interoperabilità europea, ruoli DEC/DPO e tutte le revisioni NIST/FIRST non riscontrate esternamente. Le fonti tecniche e normative non controllate non sono dichiarate aggiornate.\n\n## 7. Suggerimenti facoltativi (non errori)\n\n- Ampliare OOP con incapsulamento, ereditarietà e polimorfismo se richiesto dal profilo; aggiungere i sette livelli OSI, permessi Unix e sincronizzazione soltanto raccordandoli al programma dichiarato.\n- Offrire quiz con distrattori tecnici plausibili e separare fascicolo delle prove da soluzioni, evitando risposte prevedibili o sempre negative.\n- Rendere omogenee le rubriche con descrittori di punteggio e distinguere esempi elementari da prove specialistiche.\n\n## 8. Priorità degli interventi\n\nPrima completare NIS2, AI/compliance, acquisizione/riuso ICT, open data e cloud PA. Poi aggiungere teoria tecnica essenziale e soluzioni svolte. Correggere insieme acronimo BANDO, definizioni, schemi e rinvii. Infine snellire ripetizioni, rimuovere backstage e riallineare indici e matrici.\n\n## 9. Giudizio di pubblicabilità\n\n**Da revisionare prima della pubblicazione.** Base introduttiva valida e numerosi esempi corretti, ma copertura specialistica e normativa non ancora sufficiente alla promessa del volume. Una semplice pulizia di refusi non basta.\n\n## 10. Limiti di questa revisione\n\n';
out+=ledger.limitations.map((x:string)=>'- '+x.replace('dei13capitoli','dei 13 capitoli').replace('ACN2026','ACN 2026')).join('\n');
out+='\n\nLedger: `artifacts/review-integrale-2026-10-02/VOL-08-ledger.json`. Tutti i 13 hash sono stati ricontrollati alla chiusura; nessuna lettura incompleta è conteggiata come completa.\n';
fs.writeFileSync('wiki/reviews/audit-integrale-2026-10-02/VOL-08.md',out);
console.log({chapters:ledger.chapters.length,readComplete:ledger.chapters.filter((c:any)=>c.readComplete).length,hashesMatch:ledger.chapters.every((c:any)=>c.hashMatches),findings:rows.length});
