import fs from 'node:fs';
import crypto from 'node:crypto';
const base='artifacts/review-integrale-2026-10-02/';
const inventory=JSON.parse(fs.readFileSync(base+'pdf/inventory.json','utf8'));
const reports:any={
'VOL-08':{details:[6,63,157,211,223,231],observations:'Scorse tutte le 231 pagine nelle 10 tavole panoramiche. Margini, testatine e numerazione risultano regolari alla scala osservata. Gli esempi SQL ingranditi a pagina 63 mantengono indentazione e simboli leggibili. Il capitolo finale termina con le avvertenze a pagina 231; non è una pagina bianca tecnica.',rows:[
['6–7','Leggibilità','medio','L’indice completo usa testo di circa 6,75 punti, con etichette anche a 6,6 punti: è molto fitto per la consultazione su carta.','Aumentare il corpo e distribuire l’indice su più pagine; verificare una prova in dimensioni reali.'],
['157','Tabelle','medio','La timeline spezza parole senza sillabazione, per esempio Responsa/bile e amministrati/vo. La tabella soprastante ripete quattro volte le medesime intestazioni sulla stessa pagina.','Ridisegnare larghezze e righe, ridurre i campi per tabella e ripetere l’intestazione solo quando utile alla continuazione.'],
['223','Apparati compilabili','grave','Il Diario degli errori ha otto colonne strette, intestazioni spezzate e una sola riga bianca alta pochi millimetri: non consente una compilazione manuale utile.','Fornire una pagina di lavoro con righe alte e più spazio oppure una scheda separata chiaramente accessibile; preservare una struttura leggibile nel volume.'],
['9 e aperture successive; dettaglio 211','Gerarchia','lieve','Il titolo del capitolo compare due volte a distanza ravvicinata, prima in nero e poi in rosso. Il piccolo nastro BANDO occupa la zona intermedia.','Eliminare la duplicazione o distinguere titolo e sottotitolo; conservare una gerarchia editoriale uniforme.'],
['231','Impaginazione','lieve','Una breve avvertenza conclusiva occupa una pagina quasi vuota.','Valutare il recupero alla fine della pagina precedente senza comprimere il testo; mantenere la nuova pagina solo se scelta editoriale intenzionale.']
]},
'VOL-09':{details:[11,68,85,127,168,183,209],observations:'Scorse tutte le 209 pagine nelle 9 tavole panoramiche. Confermata la manifestazione grafica di difetti già individuati nei sorgenti. Il PDF termina a pagina 209 con la checklist del capitolo 14: le appendici A–E promesse nell’indice analitico non sono presenti. I rilievi P09-01, P09-02, P09-03 e P09-04 costituiscono riscontri PDF di rilievi testuali, da non sommare come problemi indipendenti.',rows:[
['11','Tabelle','grave','Dopo il titolo 1.2 Strumenti e applicazioni, le righe Progettazione, Affidamento, Esecuzione e successive sono stampate come un paragrafo con barre verticali, anziché come tabella. Conferma V09-01.','Riparare la struttura Markdown prima di esportare e verificare la continuità dell’intera tabella.'],
['85, 127, 168','Quiz e titoli','grave','A pagina 85 il titolo 6.3 Quiz 3 è inserito sotto QUIZ 2; a pagina 127 un titolo separa domanda e opzioni; a pagina 168 il titolo 12.3 divide le opzioni C e D. Conferma V09-02.','Spostare i titoli all’esterno delle unità domanda/opzioni/soluzione, rinumerare e ricontrollare sommario e flusso di lettura.'],
['183','Segnaposto editoriali','medio','Il codice provvisorio N-TR02-XX-04 è stampato sia nel titolo di sezione sia nel riquadro della verifica. Conferma V09-04.','Sostituire il segnaposto con un titolo destinato al lettore; mantenere i codici di audit nei soli metadati interni.'],
['6–7 e chiusura 209','Apparati mancanti','grave','Il sommario e la chiusura del PDF non contengono le cinque appendici A–E promesse dal progetto editoriale. Conferma il rilievo testuale sulle appendici.','Completare e includere le appendici, oppure riallocare i contenuti indispensabili e correggere coerentemente la promessa editoriale.'],
['6–7','Leggibilità','medio','L’indice completo è composto con testo inferiore a 7 punti, troppo fitto per una consultazione agevole nel formato stampato.','Aumentare il corpo, distribuire le voci e provare la leggibilità in dimensioni reali.'],
['68 e 183','Tabelle','medio','Tabelle brevi sono segmentate in più blocchi sulla stessa pagina, con spazi orizzontali fra gruppi di righe; la continuità visiva è indebolita.','Mantenere una tabella unitaria quando resta sulla stessa pagina; usare separazioni solo per gruppi semanticamente distinti.']
]},
'VOL-11':{details:[6,151,159,163,188,204,206,225],observations:'Scorse tutte le 225 pagine nelle 10 tavole panoramiche. La geometria generale mantiene margini e numerazione regolari alla scala osservata, ma le matrici con molte colonne sono faticose da leggere anche ingrandite. Il PDF termina con quiz e caso ulteriore a pagina 225; ricerca testuale e sommario non individuano appendici. A pagina 159 è visibile anche la formulazione sull’allerta rossa già trattata in V11-29, senza duplicarla fra i rilievi grafici.',rows:[
['188 e 206; anche 204 e 151','Tabelle','grave','Le matrici a nove e undici colonne spezzano quasi ogni parola su più righe, anche DNSH e intestazioni: la ricostruzione dei rapporti fra requisiti ed evidenze diventa molto faticosa. Il corpo della tabella è circa 9,49 punti; il problema principale è la larghezza insufficiente delle colonne.','Convertire le righe in schede, dividere la matrice in due tabelle collegate oppure usare un layout più largo; preservare parole e sigle ed eseguire una prova di stampa.'],
['163; anche 82 e 174 in panoramica','Apparati interni','medio','Il testo pubblico contiene ID di dato operativo, area dell’audit automatico e istruzione da ricontrollare al text freeze. Conferma V11-44.','Rimuovere dal prodotto commerciale le istruzioni interne e sostituirle con data di aggiornamento e riferimento ufficiale leggibili.'],
['6–7 e chiusura 225','Apparati mancanti','grave','Le appendici A–E previste dall’indice analitico non compaiono nel sommario né in coda al PDF. Conferma V11-42.','Produrre e includere le appendici operative oppure rivedere la promessa e collocare i nuclei necessari nei capitoli, aggiornando tutti i rimandi.'],
['6–7','Leggibilità','medio','L’indice usa testo di circa 6,75 punti, con etichette a 6,6 punti; la duplicazione Cap. 1 / Capitolo 01 consuma ulteriore spazio.','Semplificare le etichette, aumentare il corpo e distribuire l’indice su più pagine.'],
['151 e altre tabelle','Continuità delle tabelle','medio','La matrice conclusiva del caso è spezzata in due blocchi sulla stessa pagina, con parole divise senza sillabazione nelle intestazioni.','Mantenere una struttura unitaria e rivedere larghezze e intestazioni prima del nuovo export.']
]}
};
for(const[vol,data]of Object.entries<any>(reports)){
 const item=inventory.find((x:any)=>x.volume===vol);
 const folder=base+'pdf/'+vol+'/'+vol.toLowerCase()+'-interior-kdp';
 const contacts=fs.readdirSync(folder).filter(x=>/^contact-.*\.jpg$/.test(x)).sort().map(x=>folder+'/'+x);
 const actualHash=crypto.createHash('sha256').update(fs.readFileSync(item.file)).digest('hex');
 const findings=data.rows.map((r:any,i:number)=>({id:`P${vol.slice(-2)}-${String(i+1).padStart(2,'0')}`,position:r[0],category:r[1],severity:r[2],description:r[3],proposal:r[4],status:'non applicato'}));
 const ledger={volume:vol,date:'2026-10-02',pdf:item.file,sha256:actualHash,hashMatchesInventory:actualHash===item.sha256,pages:item.pages,contactSheetsViewed:contacts,contactCoverageComplete:true,detailPagesViewed:data.details,detailRenderScale:2,findings,limitations:['Copertura panoramica di tutte le pagine per geometria e ritmo; non equivale alla lettura del testo minuto di ogni pagina rasterizzata.','Lettura puntuale e controllo grafico ingrandito limitati alle pagine elencate; il testo originale completo è documentato nel rapporto separato.','Nessuna prova cartacea, verifica cromatica, certificazione PDF/X o collaudo di tutti i link. Non controllate qui copertine e materiali commerciali esterni.','Metriche automatiche di supporto: nessun oggetto testuale oltre il foglio, nessuna pagina bianca e nessun carattere sostitutivo segnalato nell’inventario; tali esiti non eliminano difetti semantici o di impaginazione.']};
 fs.writeFileSync(base+'PDF-'+vol+'-ledger.json',JSON.stringify(ledger,null,2));
 let out=`# ${vol} — Controllo visivo del PDF, 2 ottobre 2026\n\nPDF: \`${item.file}\`. ${item.pages} pagine; SHA-256 \`${actualHash}\`. Hash coincidente con l’inventario: ${ledger.hashMatchesInventory?'sì':'NO'}.\n\n## Copertura e metodo\n\n${data.observations}\n\nViste tutte le ${contacts.length} tavole, 24 pagine per tavola salvo l’ultima. Ingrandite separatamente a scala 2 le pagine ${data.details.join(', ')}. I numeri riportati sono le pagine fisiche del PDF, coincidenti con la numerazione visibile. Applicata la skill PDF per il controllo visivo.\n\n## Rilievi\n\n| ID | Posizione | Categoria | Gravità | Descrizione | Correzione proposta | Stato |\n|---|---|---|---|---|---|---|\n`;
 out+=findings.map((r:any)=>`| ${r.id} | pp. ${r.position} | ${r.category} | ${r.severity} | ${r.description} | ${r.proposal} | Non applicato |`).join('\n');
 out+='\n\n## Esito e limiti\n\nRichiesto un nuovo export dopo le correzioni. Nessun PDF è stato modificato.\n\n'+ledger.limitations.map(x=>'- '+x).join('\n');
 out+=`\n\nLedger di copertura: \`${base}PDF-${vol}-ledger.json\`. Le tavole esaminate e i dettagli sono conservati negli artefatti dell’audit.\n`;
 fs.writeFileSync('wiki/reviews/audit-integrale-2026-10-02/PDF-'+vol+'.md',out);
 console.log(vol,{pages:item.pages,contacts:contacts.length,details:data.details.length,findings:findings.length,hashMatch:ledger.hashMatchesInventory});
}
