from pathlib import Path
import sys
A=Path(__file__).parent
v,code,slug=sys.argv[1:4]
if code=='M-SA01':
 p=Path(f'wiki/reviews/pipeline/VOL-{v}/18-moduli-{slug}.md')
 with p.open('a',encoding='utf8') as f:f.write('''\n\n## Riesame di produzione del 3 ottobre 2026\n\nProva `vol-07-release-20261003-proof.pdf`. Capitoli osservati nelle pagine 9–141; tabelle contabili e procurement già ingranditi nella prova precedente.\n\n| Asset | Problema | Correzione | Verifica nel Book Studio | Esito |\n| --- | --- | --- | --- | --- |\n| Tabelle native, nessuna immagine raster | Leggibilità e continuazioni dopo ripaginazione | Conservata la tipografia 9,5 pt degli apparati | Panoramica completa della proiezione Book Studio esportata, controlli geometrici senza overflow | Verificato nel perimetro visivo dichiarato |\n\nSeconda passata su precisione e uniformità conclusa. La panoramica non equivale a lettura a piena risoluzione di ogni pagina. Evidenze nel registro VOL-07-production-visual-checkpoint.json.\n''')
 print(p);sys.exit(0)
label={'07':'vol-07-release-20261003','12':'vol-12-final-20261003'}[v]
detail={'M-SA02':'Le tabelle NEWS2 e triage dei capitoli clinici sono state convertite da box appiattiti in tabelle native: pagine 201–202 e 204 lette a piena risoluzione. Restano leggibili fonte, versione, ambito e limiti; gli identificativi di audit sono nel frontmatter.','M-SA03':'Schede comparative e casi della dirigenza sanitaria osservati nelle pagine 315–379. Non sono presenti immagini raster.','M-SA04':'Tre figure originali verificate a piena risoluzione: serie QC a pagina 404, movimento a 423, rumore e contrasto a 424. Testo, etichette, didascalie e raccordi corretti; nessun ritaglio.','M-SP01':'Bando Decoder a pagine 126–129: campi vuoti reali, tre tabelle native, consegna unita al primo blocco. Piano 30/60/90 a pagina 142 leggibile e con spazi ripristinati.','M-SP02':'Tabelle di requisiti, prove e schede dei Vigili del fuoco osservate nelle pagine 181–286. Nessuna immagine raster né tag HTML stampato.','M-SP03':'Apparati dei tre percorsi osservati nelle pagine 288–399: griglie e confronti nativi, nessun asset raster.','M-SP04':'Apparati osservati nelle pagine 401–492; ingrandimenti su punteggio a 416, laboratorio linguistico 449–450 e piani orari 474–475.'}[code]
p=Path(f'wiki/reviews/pipeline/VOL-{v}/18-moduli-{slug}.md')
with p.open('a',encoding='utf8') as f:f.write(f'''\n\n## Riesame di produzione del 3 ottobre 2026\n\nQuesta verifica aggiorna il precedente inventario senza cancellarlo. Prova corrente: `{label}-proof.pdf`; hash e copertura nel registro `VOL-{v}-production-visual-checkpoint.json`.\n\n| Asset | Problema | Correzione | Verifica nel Book Studio | Esito |\n| --- | --- | --- | --- | --- |\n| Apparati di {code} | Verifica del contesto dopo le correzioni editoriali | {detail} | Proiezione Book Studio esportata e controllata in PDF; panoramica di tutte le pagine e dettagli indicati | Verificato nel perimetro dichiarato |\n\nLa seconda passata ha controllato uniformità, margini, proporzioni e raccordi nelle tavole e nei dettagli. Corpo nominale 11 pt e tabelle 9,5 pt; nessun overflow geometrico o asset mancante. Le tavole panoramiche non equivalgono a lettura a piena risoluzione di ogni pagina. Nessun giudizio di pubblicabilità complessiva: promesse digitali e dati editoriali comuni restano aperti.\n''')
print(str(p))
