import { LocalAgentMemory } from '../../src/server/memory/local-agent-memory'
async function main() {
  const result = await LocalAgentMemory.fromConfig().captureConversation({
    scope: 'global', route: 'codex/pubblicabilita-digitale-sito',
    messages: [{ role: 'user', content: 'La cosa importante è che sia tutto corretto e completo per la pubblicazione dei volumi digitali sul sito.' }],
    reply: 'Priorità persistente chiarita: correttezza e completezza dei contenuti digitali sul sito; non subordinare il risultato a KDP, dorsi, scelta ISBN KDP o prova fisica. Verificato il percorso effettivo src/server/book/book-integration-bundle.ts: dodici candidate in artifacts/correzioni-collana-2026-10-02/digital-publication, 348 unità (325 main già nel perimetro originale +23 Ricettario VOL01 fuori dalla revisione integrale precedente), 251 asset, zero fonti/asset mancanti o hash difformi. Il bundle esclude i preliminari di stampa e usa introduzioni digitali; le promesse commerciali dei preliminari PDF non vi sono importate. Non dichiarare tutto corretto in base ai soli PDF. VOL01 digitale ha180blocchi immagine, diversa selezione rispetto alla stampa, da verificare nella resa sito. Corretti tre richiami a source note interne nei moduli R4/R11/R20, updated_at aggiornato, review_required rimasto true; rigenerazione e scansione blocchi senza residui dei pattern cercati. Tutti i gate restano pending:346draft non dimostrano346capitoli incompleti, parser classifica draft il corpo sostanziale esterno a Testo editoriale; riconciliare con evidenze, non promuovere metadati in massa. Report wiki/reviews/correzioni-collana-2026-10-02/DIGITALE.md, indici delivery e wiki allineati al nuovo obiettivo. Chiesta via async la forma effettiva sul sito: capitoli online, PDF scaricabili o entrambi; nessuna risposta ricevuta. Se PDF, criticità preliminari restano pertinenti; se online, priorità23moduli e resa reale sito. Nessuna pubblicazione, import remoto, commit/push o conferma24. La revisione digitale integrale non è completata, questa è verifica di integrità/perimetro e tre correzioni mirate.',
    metadata: { publicationTarget:'digital-website', digitalReleaseReady:false, candidateVolumes:12, digitalUnits:348, assets:251, additionalRicettarioUnits:23, internalReferencesCorrected:3 }
  })
  console.log(result.conversationId)
}
main().catch(error=>{console.error(error);process.exitCode=1})
