from pathlib import Path
import re,json,hashlib,shutil
A=Path('artifacts/correzioni-collana-2026-10-02');B=Path('wiki/books/moduli/m-tr03-tecnico-ingegneristico');R=Path('wiki/reviews/pipeline/VOL-10')
p=Path('wiki/sources/vol-10-tecnico-rettifiche-2026-10-03.md');s=p.read_text(encoding='utf8');s=s.replace('## Collegamenti','''## Procedimento espropriativo: raccordo verificato

La fonte consolidata [[sources/vol-02-scuole-espropri-spl-verifica-2026-10-03]] verifica DPR 327 artt. 8, 9, 12, 13, 23 e 24. Riletti anche gli estratti correnti di 13, 23 e 24: termine della PU espresso o, se assente, cinque anni dall'efficacia; proroghe prima della scadenza, per forza maggiore o giustificate ragioni, complessivamente non oltre quattro anni. Decreto entro efficacia PU, trasferimento condizionato a notifica ed esecuzione; preavviso ordinario di sette giorni, notifica contestuale ammessa dal comma 3. Immissione entro termine perentorio di due anni; verbale e consistenza in contraddittorio, due testimoni non dipendenti del beneficiario se assenza/rifiuto. I termini hanno presupposti e decorrenze distinti.

## Collegamenti''');p.write_text(s,encoding='utf8')
p=next((B/'chapters').glob('05-*.md'));s=p.read_text(encoding='utf8');anchor='## N-TR03-05-07 · Paesaggio e governo del territorio';assert anchor in s
new='''### Tre termini, tre funzioni

Per emanare il decreto servono conformità urbanistica e vincolo, dichiarazione di pubblica utilità e indennità determinata anche provvisoriamente, secondo l'art. 8. La dichiarazione deriva dagli atti previsti dall'art. 12; non si presume dal solo interesse dell'ente ad acquistare un terreno.

L'art. 13 distingue il termine della dichiarazione da quello del vincolo: il decreto di esproprio va emanato entro il termine stabilito nell'atto di pubblica utilità; se manca, entro **cinque anni dall'efficacia** di quell'atto. Prima della scadenza, l'autorità può disporre proroghe per forza maggiore o altre giustificate ragioni, per un periodo complessivo non superiore a **quattro anni**; restano le discipline speciali richiamate dalla norma. Scaduto il termine senza decreto, la dichiarazione diviene inefficace.

Il decreto dispone il trasferimento sotto condizione di successiva **notifica ed esecuzione**. L'avviso di esecuzione precede ordinariamente di almeno sette giorni l'immissione; l'art. 23, comma 3, ammette anche notifica contestuale, con possibile differimento di dieci giorni in caso di opposizione. L'art. 24 richiede esecuzione mediante verbale di immissione nel termine perentorio di **due anni**: non è un ulteriore termine per emanare il decreto. Verbale e stato di consistenza sono redatti in contraddittorio; in assenza o rifiuto intervengono almeno due testimoni non dipendenti del beneficiario.

**Caso:** pubblica utilità efficace dal 1 ottobre 2026 senza termine espresso, senza proroghe o specialità: decreto entro il quinquennio che termina il 1 ottobre 2031. Un decreto emanato il 1 settembre 2031 deve poi essere notificato ed eseguito nel proprio regime. Confondere questa fase con il vincolo apposto anni prima produce una scadenza errata. Il calendario dell'ufficio registra separatamente atto, efficacia, termine ed eventuale proroga.

'''
s=s.replace(anchor,new+anchor);s=s.replace('articoli 9 e 39 per durata e reiterazione del vincolo','articoli 8–9, 12–13, 23–24 e 39 per procedimento, termini e reiterazione del vincolo');p.write_text(s,encoding='utf8')
# Explicit follow-up in matrix and reports, no claim of full source-corpus review.
p=B/'planning/02-matrice-copertura-didattica.md';s=p.read_text(encoding='utf8')+'\nIntegrazione specialistica conclusiva: cap. 5, «Tre termini, tre funzioni», distingue vincolo, efficacia della PU e immissione; DPR 327 artt. 8–9, 12–13, 23–24, con caso datato e rinvio probatorio alla fonte VOL-02.\n';p.write_text(s,encoding='utf8')
p=B/'planning/13-bibbia-del-modulo.md';s=p.read_text(encoding='utf8').replace('riferimenti consolidati e note di review','riferimenti normativi e professionali leggibili; note di review soltanto nello staff').replace('La matrice v4 registra 16 nuclei','La matrice v4 registra 16 righe di materia/perimetro');s+='\n## Riesame del 3 ottobre 2026\n\nDiciotto rilievi applicati e verificati: esempi quantitativi, regole nazionali, transitori e dossier cartaceo autosufficiente. Quattro figure didattiche collegate ai capitoli 3 e 13. Le nuove fonti e il rapporto corrente prevalgono sulle attestazioni storiche; nessuna pubblicabilità del PDF è anticipata. Capitoli legacy fuori dal ciclo 08–12: avvisi di retrofit e squilibrio conservati.\n';s=re.sub(r'^updated_at:.*$','updated_at: 2026-10-03',s,flags=re.M);p.write_text(s,encoding='utf8')
# Evidence acquisition state: scoped reading, not the full Normattiva site/act.
p=A/'norme-vol10/manifest.json';d=json.loads(p.read_text(encoding='utf8'))
partial={('codice','41'):'commi 13–15',('codice','50'):'commi 6–9',('codice','108'):'commi 9–12',('procedimento','19'):'commi 6–6-ter'}
for r in d:
 key=(r['name'],str(r['article']));excluded=r['name']=='civile' or '-' in str(r['article']);r['evidenceValid']=not excluded;r['readComplete']=not excluded and key not in partial;r['readScope']='escluso: contenuto diverso dall’articolo richiesto' if excluded else partial.get(key,'articolo estratto integralmente')
p.write_text(json.dumps(d,ensure_ascii=False,indent=2),encoding='utf8')
p=A/'norme-vol10/manifest-extra.json';d=json.loads(p.read_text(encoding='utf8'))
for r in d:r['readComplete']=True;r['readScope']='articolo estratto integralmente';r['evidenceValid']=True
p.write_text(json.dumps(d,ensure_ascii=False,indent=2),encoding='utf8')
for p in list((B/'chapters').glob('*.md'))+[B/'index.md',B/'planning/02-matrice-copertura-didattica.md',B/'planning/13-bibbia-del-modulo.md',Path('wiki/sources/vol-10-tecnico-rettifiche-2026-10-03.md'),Path('wiki/topics/tecnico-ingegneristico-rettifiche-2026.md')]:
 s=p.read_text(encoding='utf8');s=re.sub(r'^review_required:.*$','review_required: false',s,flags=re.M);s=s.replace('status: revision-in-progress','status: reviewed');p.write_text(s,encoding='utf8')
p=R/'15-moduli-m-tr03-tecnico-ingegneristico.md'
if p.exists() and not (A/'before-text/VOL-10'/p.name).exists():shutil.copy2(p,A/'before-text/VOL-10'/p.name)
s=(R/'14-moduli-m-tr03-tecnico-ingegneristico.md').read_text(encoding='utf8').replace('Correzioni del testo','Audit specialistico conclusivo del testo').replace('Applicato e riesaminato nel testo; PDF da verificare','Verificato e chiuso nel testo').replace('Descrizione | Correzione proposta','Evidenza originaria | Correzione applicata').replace('Concludere audit 15 e freeze 16 tramite CLI;', 'Audit specialistico concluso: nessun errore grave o medio noto aperto nel perimetro; procedere al freeze 16 tramite CLI;');s=s.replace('Tredici gate di capitolo', 'Nessun box Dato operativo rilevato dal CLI. Verificato anche il raccordo espropriativo con fonte consolidata VOL-02; dodici test di regressione export passati. Tredici gate di capitolo');p.write_text(s,encoding='utf8')
files=sorted((B/'chapters').glob('*.md'));source=Path('wiki/sources/vol-10-tecnico-rettifiche-2026-10-03.md').read_text(encoding='utf8');urls=sorted(set(re.findall(r'\]\((https?://[^)]+)\)',source)))
ledger={'volume':'VOL-10','module':'M-TR03','date':'2026-10-03','textVerified':True,'finalVerified':False,'readingCheckpoint':str(A/'VOL-10-reading-checkpoint.json'),'findings':json.loads((A/'VOL-10-applied.json').read_text(encoding='utf8')),'chapterGates':{'passed':13,'blockers':0,'warnings':{'retrofit-dovuto':13,'squilibrio-nuclei':11}},'bodyLinksUnresolved':0,'calculations':str(A/'VOL-10-calculations.json'),'figuresInserted':4,'externalClaimsChecked':urls,'normativeEvidence':[str(A/'norme-vol10/manifest.json'),str(A/'norme-vol10/manifest-extra.json')],'files':[{'path':p.as_posix(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'readComplete':True,'readingScope':'originale integrale e riesame dei delta','quizReview':'complete'} for p in files],'limitations':['PDF aggiornato da verificare: nessuna pubblicabilità finale dichiarata','Articoli e passaggi normativi pertinenti, non interi testi unici o tutti gli allegati','Soglia UE su pagina Commissione; limite urbanistico su estratti ufficiali indicizzati: download non validi dichiarati ed esclusi','Capitoli legacy: retrofit e squilibrio non occultati']}
(A/'VOL-10-ledger.json').write_text(json.dumps(ledger,ensure_ascii=False,indent=2),encoding='utf8');print('15 prepared: 18 findings, 13 chapters, scoped manifests, ledger.')
