from pathlib import Path
import re,json,hashlib,shutil
A=Path('artifacts/correzioni-collana-2026-10-02');B=Path('wiki/books/moduli/m-tr04-ambiente-protezione-civile');V=Path('wiki/books/volumi/vol-11-ambiente-protezione-civile-sostenibilita');R=Path('wiki/reviews/pipeline/VOL-11');R.mkdir(exist_ok=True,parents=True)
sources=['vol-11-ambiente-rettifiche-2026-10-03','vol-11-rifiuti-controlli-rettifiche-2026-10-03','legge-689-procedura-verifica-2026-10-03','vol-11-protezione-civile-verifica-2026-10-03','vol-11-energia-sostenibilita-verifica-2026-10-03']
# Further primary evidence precedes compilation.
p=Path('wiki/sources/'+sources[1]+'.md');s=p.read_text(encoding='utf8')+'''\n## Casi sanzionatori di acque ed emissioni\n\nLetti integralmente anche artt. 133, 137 e 279 del D.Lgs. 152 corrente, raw nel medesimo manifest. Art. 137, comma 1: nuovo scarico industriale senza titolo, fuori AIA, arresto 2 mesi–2 anni oppure ammenda 1.500–10.000; non è la stessa fattispecie dello scarico domestico privo di titolo, art. 133, comma 2. Art. 279: violazione del valore limite, comma 2, contravvenzione; violazione della prescrizione, comma 2-bis, illecito amministrativo, salvi regimi AIA. Il caso 12 contro 10 mg/Nm³ assume dati comparabili e condizioni del titolo, non un limite generale per tutte le sostanze.\n''';p.write_text(s,encoding='utf8')
p=next((B/'chapters').glob('09-*.md'));s=p.read_text(encoding='utf8');anchor='## N-TR04-09-06'
pos=s.index(anchor)
s=s[:pos]+'''### Confronto con acque ed emissioni

**Acque.** Il caso accerta un nuovo scarico di acque reflue industriali senza autorizzazione, fuori dal regime AIA, senza sostanze che integrino l'ipotesi aggravata indicata dall'art. 137, comma 2. Si applica la fattispecie del comma 1: arresto da due mesi a due anni **o** ammenda da 1.500 a 10.000 euro. È una contravvenzione. Se fosse invece uno scarico domestico privo di titolo, il riferimento ordinario sarebbe l'art. 133, comma 2, amministrativo: la parola «scarico» non basta a scegliere la sanzione.

**Emissioni.** Uno stabilimento fuori AIA supera un valore limite dell'autorizzazione: misura validata 12 mg/Nm³, limite 10, identici periodo e condizioni di riferimento, nessuna eccezione pertinente. Il superamento è del 20%; l'art. 279, comma 2, prevede arresto fino a un anno **o** ammenda fino a 10.000 euro. La sola inosservanza di una prescrizione diversa dal limite ricade invece nel comma 2-bis, sanzione amministrativa da 1.000 a 10.000 euro, nei presupposti indicati. Un superamento della qualità dell'aria connesso al superamento emissivo richiede l'ulteriore verifica del comma 5. Il dato al camino non prova automaticamente quel nesso.

In ciascun caso si verificano condotta, titolo, soggetto responsabile, validità del dato e ulteriori fattispecie eventualmente applicabili. Per la procedura estintiva si controllano natura contravvenzionale, pena e assenza del danno o pericolo concreto e attuale richiesti dall'art. 318-bis: nessun automatismo discende dalla sola etichetta «reato ambientale».

'''+s[pos:];p.write_text(s,encoding='utf8')
# Precisely supersede contradicted source guidance, keeping scope visible.
rep={
'aia-aua-emissioni-quadro-ufficiale-2026':('gli atti ambientali tassativamente indicati dalla disciplina',"gli atti ambientali indicati dall'art. 3, comma 1, incluse le voci aggiunte nel testo corrente, e gli ulteriori atti che le Regioni possono individuare ai sensi del comma 2"),
'aria-rumore-monitoraggio-dati-quadro-ufficiale-2026':('Nel manuale non va inserita una tabella numerica destinata a invecchiare:', 'Il riesame del 3 ottobre 2026 richiede esempi numerici datati e verificati, senza presentarli come limiti eterni:'),
'clima-energia-rinnovabili-cer-efficienza-quadro-ufficiale-2026':('Non vanno create tabelle di soglie destinate a invecchiare senza una verifica normativa puntuale.', 'Sono ora inclusi casi e soglie datati, dopo verifica normativa puntuale degli artt. 6–9 e allegati A–C correnti; non si rinuncia a insegnare le regole per il solo rischio di aggiornamenti.')}
for name,(a,b) in rep.items():
 p=Path('wiki/sources/'+name+'.md');s=p.read_text(encoding='utf8');assert a in s;s=s.replace(a,b);s+='\n## Raccordo del 3 ottobre 2026\n\nPer i delta puntuali prevalgono [[sources/vol-11-ambiente-rettifiche-2026-10-03]], [[sources/vol-11-rifiuti-controlli-rettifiche-2026-10-03]] e [[sources/vol-11-energia-sostenibilita-verifica-2026-10-03]], secondo materia. Le attestazioni precedenti non equivalgono a verifica integrale di tutti gli atti correnti.\n';s=re.sub(r'^updated_at:.*$','updated_at: 2026-10-03',s,flags=re.M);p.write_text(s,encoding='utf8')
p=Path('wiki/sources/bonifiche-siti-contaminati-danno-ambientale-quadro-ufficiale-2026.md');s=p.read_text(encoding='utf8')+'\n## Precisazione del 3 ottobre 2026\n\nL’art. 240 usa letteralmente «inferiore» nella definizione: non si altera la citazione. L’uguaglianza non integra il superamento che attiva i passaggi ulteriori; la lettura coordinata e i casi CSC/CSR sono in [[sources/vol-11-rifiuti-controlli-rettifiche-2026-10-03]]. La riparazione complementare può riguardare il sito danneggiato o, se opportuno, altro sito.\n';p.write_text(s,encoding='utf8')
p=Path('wiki/sources/laboratorio-casi-quesiti-sintetici-vol-11-2026.md');s=p.read_text(encoding='utf8')+'\n## Riesame del 3 ottobre 2026\n\nIl laboratorio applica le cinque nuove note di riscontro VOL11: simulazione 6 tabella e nota con confronto acustico, 8 matrice di otto righe, 10 nota e sei azioni con tempi e responsabilità. Appendici A–E nel capitolo 14, effettive e cartacee, con modelli compilati. I calcoli sono didattici e coerenti con capitoli 8, 12 e 13. Le regole note vanno applicate anche quando la consegna non le ricopia; i fatti mancanti non si inventano.\n';p.write_text(s,encoding='utf8')
# Link all source/topic evidence to chapters 14 and topic.
files=sorted((B/'chapters').glob('*.md'))
p=files[-1];s=p.read_text(encoding='utf8')
for key,values in [('source_refs',['sources/'+x for x in sources]),('last_compiled_from',['wiki/sources/'+x+'.md' for x in sources])]:
 m=re.search(r'^'+key+r': (\[.*\])$',s,re.M);a=json.loads(m[1]);a=list(dict.fromkeys(a+values));s=s[:m.start(1)]+json.dumps(a,ensure_ascii=False)+s[m.end(1):]
p.write_text(s,encoding='utf8')
p=Path('wiki/topics/ambiente-rettifiche-2026.md');s=p.read_text(encoding='utf8');s=re.sub(r'^source_refs:.*$','source_refs: '+json.dumps(['sources/'+x for x in sources]),s,flags=re.M);s=re.sub(r'^chapter_refs:.*$','chapter_refs: '+json.dumps([x.as_posix()[5:-3] for x in files]),s,flags=re.M);s+='\n## Applicazione coordinata\n\nLe note su rifiuti/controlli e L. 689 sostengono classificazione, titoli, tracciabilità e sanzioni. La nota protezione civile distingue presupposti delle competenze, aree, volontariato, fasi minime e scenari. Energia/sostenibilità consolida FER, CER, diagnosi, DNSH e CAM con casi risolti. Il laboratorio riusa queste fonti e produce le appendici A–E nello stesso capitolo, senza dipendenze da materiali digitali assenti.\n';p.write_text(s,encoding='utf8')
# Current matrix reflects actual nuclei, not fourteen placeholder first nuclei.
p=B/'planning/02-matrice-copertura-didattica.md';old=p.read_text(encoding='utf8');archive=B/'planning/revisioni-2026-10-03';archive.mkdir(exist_ok=True);(archive/'matrice-precedente.md').write_text(old,encoding='utf8');fm=old.split('---',2)[1];fm=re.sub(r'^updated_at:.*$','updated_at: 2026-10-03',fm,flags=re.M)
rows=[]
for pch in files:
 s=pch.read_text(encoding='utf8');refs=json.loads(re.search(r'^source_refs: (.*)$',s,re.M)[1]);refs=[x for x in refs if 'rettifiche-2026-10-03' in x or 'verifica-2026-10-03' in x]
 for m in re.finditer(r'^## (N-TR04-\d\d-\d\d) · (.+)$',s,re.M):
  tail=s[m.end():];end=re.search(r'^## ',tail,re.M);chunk=tail[:end.start()] if end else tail;hs=re.findall(r'^### (.+)$',chunk,re.M)
  rows.append([m[1],m[2],pch.name[:2],'; '.join(refs),'; '.join(hs[:3]) or 'Spiegazione e applicazioni del nucleo', 'Verificato nel perimetro concorsuale', 'Norme territoriali e fattispecie ulteriori da verificare nel caso concreto'])
matrix='---'+fm+'---\n\n# Copertura effettiva M-TR04 — 3 ottobre 2026\n\n'+str(len(rows))+' nuclei effettivi in 14 capitoli. Le righe descrivono la copertura didattica del testo, non una certificazione integrale di ogni norma o bando. Il precedente scaffold e le attestazioni storiche sono archiviati in `planning/revisioni-2026-10-03/matrice-precedente.md`.\n\n| Nucleo | Contenuto | Capitolo | Fonti del delta | Evidenza didattica | Stato | Limite |\n|---|---|---|---|---|---|---|\n'+''.join('| '+' | '.join(x)+' |\n' for x in rows)+'\n## Apparati e verifiche\n\n84 quesiti finali originari, con soluzioni riesaminate; nuovi casi numerici e dieci simulazioni con formato richiesto. Appendici A–E nel capitolo 14; percorsi AMB/PC/EN/LOC e calendari alternativi nel capitolo 01. Il registro dei 44 rilievi specifica intervento ed evidenza. PDF aggiornato ancora da verificare.\n'
p.write_text(matrix,encoding='utf8')
for p in [B/'index.md',B/'planning/01-indice-analitico-vol-11.md',B/'planning/17-bibbia-del-modulo.md',V/'index.md',V/'planning/01-bibbia-volume.md']:
 s=p.read_text(encoding='utf8').replace('`n-','\n-');s=re.sub(r'^updated_at:.*$','updated_at: 2026-10-03',s,flags=re.M);s=s.replace('Stato: scaffold pronto per scrittura.','Stato: 14 capitoli corretti, con appendici A–E nel capitolo 14; audit e freeze correnti in chiusura.')
 s=s.replace('Compilare il piano editoriale, poi sviluppare il testo con Manual Writer Agent usando il libro principale, il ricettario digitale e le source notes del modulo.','Completare audit e freeze del testo corretto; rigenerare e verificare il PDF prima dei gate di pubblicazione.')
 if '## Appendici\n' in s:s=s.replace('## Appendici\n','## Appendici\n\nLe cinque appendici sono sezioni effettive del capitolo 14, dopo il laboratorio e prima delle verifiche finali.\n')
 s+='\n## Riesame del 3 ottobre 2026\n\nQuattordici capitoli e appendici A–E nel capitolo 14; 44 rilievi dell’audit integrale trattati nel registro corrente. La matrice elenca i nuclei effettivi, con fonti e limiti. Le attestazioni precedenti non sostituiscono il presente riesame né certificano il PDF aggiornato.\n';p.write_text(s,encoding='utf8')
# Exact reading scopes: acquisition is not a claim of complete review.
complete={'ambiente':'3bis 3ter 3quater 3quinquies 3sexies 12 13 14 15 19 25 27 27bis 29octies 103 104 117 121 124 133 137 184ter 188 188bis 190 240 242 250 256 279 303 318bis 318ter 318quater 318quinquies 318sexies 318septies'.split(),'aua':['1','2','3','4','5'],'snpa':['1','6','9'],'natura':['5'],'informazione':['3','5'],'pc':['7','9','12','18','39','40'],'fer':['6','7','8','9'],'cer':['31','32'],'efficienza':['5','8'],'edifici':['6'],'seveso':['20','21'],'sanzioni':['14','16','18'],'danno':['25']}
partial={'6':'commi 9–9-bis','7bis':'commi 2–4','269':'commi 3, 7–8','272':'commi 1–3','193':'commi 1–6','208':'commi 1–2','212':'commi 5 e 8','214':'commi 1–2','216':'commi 1–4'}
p=A/'norme-vol11/manifest.json';d=json.loads(p.read_text(encoding='utf8'))
for r in d:
 name=r['name'];n=str(r['article']);r['evidenceValid']=not(name=='ambiente' and n in ['64','298bis']);r['readComplete']=n in complete.get(name,[]);r['readScope']='articolo estratto integralmente' if r['readComplete'] else (partial.get(n,'acquisito ma non usato come prova di lettura') if name=='ambiente' else 'acquisito ma non usato come prova di lettura')
 if not r['evidenceValid']:r['readScope']='escluso: vuoto o articolo omonimo su materia diversa'
p.write_text(json.dumps(d,ensure_ascii=False,indent=2),encoding='utf8')
p=A/'norme-vol11/manifest-extra.json';extra=json.loads(p.read_text(encoding='utf8'));scopes={'arera-rqti.pdf':'art. 2; 5-bis commi 1–4; passaggi 5-quater, elenco M0–M6','regolamento-sii-cap.pdf':'tabella SST e metodo APAT/CNR IRSA 2090B','camera-ied420.html':'stato parlamentare e pareri settembre 2026','dpcm-rumore.pdf':'tutte le 5 pagine','rentri-esclusioni.html':'esclusioni art. 188-bis e L. 199/2025','arpav-pm10-2025.html':'limiti PM10 giornaliero e annuo','camera-aria435.html':'stato parlamentare settembre 2026','tiad.pdf':'pagina 5, definizioni r–x pertinenti','red3-gu.pdf':'identità e pubblicazione del D.Lgs. 5/2026, non intero fascicolo','energy-infrazioni-20261001.html':'EED incompleta e progetto piano ristrutturazioni','dpc-fasi2016.pdf':'passaggio sulle fasi minime e valutazione locale','cam2025-allegato.pdf':'pagina 84, criterio 2.5.2 completo','cam-circolare2026.pdf':'tutte le 3 pagine','fer-allegatoA-session.html':'sezione I, casi fotovoltaici a–e; non audit di tutte le tecnologie','fer-allegatoB-session.html':'sezione I, casi fotovoltaici a–f','fer-allegatoC-session.html':'sezioni I/II, ripartizione competenze e casi fotovoltaici'}
for r in extra:
 n=Path(r.get('path','')).name;r['evidenceValid']=n in scopes;r['readComplete']=n in ['dpcm-rumore.pdf','cam-circolare2026.pdf'];r['readScope']=scopes.get(n,'escluso: pagina vuota, sessione scaduta o navigazione senza allegato')
p.write_text(json.dumps(extra,ensure_ascii=False,indent=2),encoding='utf8')
checkpoint={'date':'2026-10-03','originalAudit':'artifacts/review-integrale-2026-10-02/VOL-11-ledger.json','baseline':json.loads((A/'VOL-11-baseline.json').read_text(encoding='utf8')),'readingScope':'14 originali integralmente letti nell’audit; 13 invariati, solo cella cap.12 modificata dal root prima del ciclo; delta correnti riletti nelle patch e nelle unità di contesto','files':[{'path':p.as_posix(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'readComplete':True,'quizReview':'complete'} for p in files],'normativeManifests':['norme-vol11/manifest.json','norme-vol11/manifest-extra.json'],'additionalReadScopes':['Costituzione Camera PDF pp. 53–55, art.117 lett.s e concorrenti, art.118','Guida DNSH RGS PDF pp.12–13 e36','Linee guida SNPA classificazione PDF pp.68,72,79,80,88']}
(A/'VOL-11-reading-checkpoint.json').write_text(json.dumps(checkpoint,ensure_ascii=False,indent=2),encoding='utf8')
(A/'VOL-11-progress.json').write_text(json.dumps({'date':'2026-10-03','chaptersApplied':list(range(1,15)),'findingsApplied':list(range(1,45)),'pending':['report14/15','CLI14/15/16','PDF aggiornato']},indent=2),encoding='utf8')
print('Planning/source reconciliation and scoped checkpoint saved;',len(rows),'nuclei.')
