from pathlib import Path
import re,json
B=Path('wiki/books/moduli/m-fc03-enti-non-economici/chapters')
def f(pre):return next(B.glob(pre+'*.md'))
def change(pre,fn):
 p=f(pre);p.write_text(fn(p.read_text(encoding='utf8')),encoding='utf8')
perimetro='''### Natura dell'ente, comparto e percorso di studio

INPS e INAIL sono gli enti guida di questo percorso previdenziale e assicurativo. Le schede di ACI, ENAC e CONI servono a orientare verso le rispettive funzioni. ISTAT, ENEA e ASI sono enti di ricerca: il personale amministrativo rientra nel comparto Istruzione e Ricerca, non nelle Funzioni Centrali per il solo tipo di mansioni. La Croce Rossa Italiana è un'associazione di diritto privato dal 1 gennaio 2016, ai sensi del d.lgs. 178/2012: non è un EPNE ordinario. Le somiglianze tra prove amministrative consentono di riusare alcune materie, ma non mutano natura, contratto o disciplina del reclutamento.

'''
for pre in ['01-','10-','12-','appendice-c']:
 change(pre,lambda s:s.replace('### Apertura editoriale',perimetro+'### Apertura editoriale',1))
change('appendice-c',lambda s:s.replace('La regola è: ENEA amministrativo dentro M-FC03; ENEA ricerca dentro il modulo ricerca.','Per ENEA, anche il profilo amministrativo conserva il comparto Istruzione e Ricerca. Si riusano qui le tecniche di caso e di studio, aggiungendo ordinamento e contratto propri dell’ente; per ricercatori e tecnologi serve inoltre la preparazione scientifica prevista dal bando.').replace('CRI richiede una formulazione prudente. Nel modulo M-FC03 compare come ente di orientamento per bandi amministrativi compatibili, ma non va trattata automaticamente come un EPNE ordinario.','Dal 1 gennaio 2016 CRI è associazione di diritto privato. Compare qui per orientamento comparativo e non come ente pubblico delle Funzioni Centrali.').replace('Organizzazione collegata a soccorso, attività umanitarie, salute, emergenza e rete territoriale; va letta con attenzione sul bando specifico.','Associazione di diritto privato dal 2016, con funzioni umanitarie, di soccorso e rete territoriale.').replace('ACI richiama mobilità','CONI richiama ordinamento sportivo, funzioni istituzionali e amministrazione dello sport; ACI richiama mobilità'))
change('12-',lambda s:s.replace('non possono essere comunicati per telefono, chat, conoscenza personale o semplice urgenza dichiarata.','non possono essere comunicati mediante canali non autorizzati o senza verifica di identità e titolo. Il telefono non è vietato in assoluto: contano la procedura del servizio, l’autenticazione e i dati comunicabili; conoscenza personale e urgenza dichiarata non sostituiscono queste condizioni.').replace('segnala il possibile conflitto quando rilevante e indirizza','segnala il conflitto al responsabile e si astiene nei casi previsti dall’articolo 6-bis della legge 241/1990 e dagli articoli 6–7 del DPR 62/2013; indirizza'))
change('13-',lambda s:s.replace("l'l'INAIL","l'INAIL").replace('venerdi','venerdì').replace('| Situazionale | 10 scenari | Opzione scelta e motivo. |','| Situazionale | Otto quesiti del capitolo 12, più caso del familiare e caso ragionato di chiusura dello stesso capitolo | Per i quiz: opzione e motivo; per i due casi: condotta motivata da confrontare con la soluzione. |'))
change('appendice-d',lambda s:s.replace('si eliminano dal diario','si archiviano nel diario con stato «recuperato», data e prova di soluzione in un contesto nuovo; si eliminano soltanto i duplicati. Non si cancellano'))
def casi(s):
 s=s.replace("Un utente presenta tramite canale digitale una domanda di prestazione, ma nel fascicolo manca un documento necessario per completare l'istruttoria. L'utente contatta l'ente chiedendo se la prestazione sarà concessa.","Il 5 ottobre 2026 un utente presenta una domanda di prestazione. Nel fascicolo manca il dato anagrafico di residenza già detenuto dal Comune, identificato dall’utente. Chiede se il beneficio sarà concesso. L’ufficio deve acquisire il dato d’ufficio, senza imporre un nuovo certificato, e verificare gli ulteriori requisiti.")
 s=s.replace('individuare il documento mancante e stabilire se l\'integrazione sia necessaria per proseguire.','individuare il dato mancante e controllare anzitutto se sia già detenuto dall’ente o da un’altra amministrazione, acquisendolo d’ufficio ai sensi dell’articolo 18 della legge 241/1990 e dell’articolo 43 del DPR 445/2000. Nel caso descritto si acquisisce la residenza dal Comune; non si chiede al cittadino un certificato. Solo per dati non acquisibili d’ufficio si valuta l’integrazione necessaria.')
 s=s.replace("La comunicazione all'utente deve essere chiara: indicare che la domanda risulta incompleta, precisare quale elemento deve essere prodotto, rinviare al canale ufficiale e spiegare che l'esito sarà valutato dopo la verifica dei requisiti.","La comunicazione chiarisce che il dato anagrafico sarà acquisito d’ufficio e che l’esito dipende dalla verifica complessiva dei requisiti. L’utente fornisce soltanto gli elementi indispensabili a reperire il dato.")
 s=s.replace("Un'impresa chiede perché una pratica risulta sospesa. Dalla prima verifica emerge che manca una dichiarazione e che nel fascicolo sono presenti dati relativi a un lavoratore. L'impresa chiede copia completa degli atti.","Il 6 ottobre 2026 l’impresa Alfa chiede notizie della pratica didattica P-18. Manca la dichiarazione sulle lavorazioni effettivamente svolte, non detenuta da amministrazioni pubbliche e necessaria all’istruttoria. La traccia stabilisce un termine di integrazione al 21 ottobre 2026, mediante la funzione «Documenti» del servizio telematico della pratica: è un dato dell’esercizio, non un termine generale INAIL. Il fascicolo contiene dati sanitari di un lavoratore e l’impresa chiede anche copia integrale degli atti.")
 s=s.replace('Sul secondo deve indicare in modo chiaro il documento mancante e il canale corretto.','Sul secondo verifica prima l’acquisizione d’ufficio; qui la dichiarazione sulle lavorazioni deve essere resa dall’impresa, quindi indica documento, necessità, termine del 21 ottobre e funzione «Documenti» stabiliti dalla traccia.')
 s=s.replace('"Con riferimento alla pratica indicata, si comunica che l\'istruttoria richiede l\'integrazione della dichiarazione mancante. L\'invio dovrà avvenire tramite il canale ufficiale previsto dall\'ente.','"Con riferimento alla pratica P-18, si chiede la dichiarazione sulle lavorazioni effettivamente svolte, necessaria all’istruttoria e non acquisibile presso altre amministrazioni. La dichiarazione va trasmessa entro il 21 ottobre 2026 mediante la funzione Documenti del servizio telematico della pratica.')
 s=s.replace('Occorre verificare quale documento manchi, indicare il canale ufficiale per l\'integrazione e registrare l\'attività.','Occorre identificare il dato mancante, verificare prima l’acquisizione d’ufficio e richiedere all’interessato solo quanto non sia acquisibile; si registra l’attività e si indica il canale pertinente.')
 return s
change('11-',casi)
for p in B.glob('*.md'):
 s=p.read_text(encoding='utf8')
 s=re.sub(r'^status:.*$','status: revised_draft',s,flags=re.M);s=re.sub(r'^draft_stage:.*$','draft_stage: revision-in-progress',s,flags=re.M);s=re.sub(r'^review_required:.*$','review_required: true',s,flags=re.M);s=re.sub(r'^updated_at:.*$','updated_at: 2026-10-03',s,flags=re.M)
 s=s.replace('source_refs: [','source_refs: ["sources/epne-previdenza-assicurazione-rettifiche-2026-10-03.md", ',1)
 s=s.replace('topics: [','topics: ["topics/epne-previdenza-assicurazione-rettifiche-2026.md", ',1)
 s=s.replace('last_compiled_from: [','last_compiled_from: [\n  "wiki/sources/epne-previdenza-assicurazione-rettifiche-2026-10-03.md",',1)
 p.write_text(s,encoding='utf8')
print('Perimetro, casi, privacy e stati aggiornati.')
