from pathlib import Path
import re,shutil
root=Path.cwd();base=root/'wiki/books/moduli/m-fc02-agenzie-fiscali/chapters'
def append(relative,body):
 p=root/relative;s=p.read_text(encoding='utf-8');marker='## Rettifica didattica del 3 ottobre 2026'
 if marker not in s:p.write_text(s+'\n'+marker+'\n\n'+body+'\n',encoding='utf-8')
append('wiki/sources/accertamento-contraddittorio-compliance-aggiornamento-2026-07-17.md', '''Articoli 38–41 D.P.R. 600/1973: distinguere rettifica analitica, analitico-induttiva con presunzioni gravi/precise/concordanti, induttiva extracontabile nei presupposti tipizzati, sintetica del reddito complessivo delle persone fisiche e accertamento d'ufficio per omessa/nulla dichiarazione. [Art. 38 vigente nel sistema MEF](https://def.giustiziatributaria.gov.it/DocTribFrontend/executePrintArticolo.do?articolo=Articolo+38&codiceOrdinamento=0000000000000380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000&id=%7B178F0CBC-1969-49F3-974E-7C0E87B9A568%7D): scostamento almeno un quinto e almeno dieci assegni sociali annui, prova contraria e invito/adesione. [Gazzetta 8 ottobre 2024, testi coordinati](https://www.gazzettaufficiale.it/eli/gu/2024/10/08/236/sg/pdf): art. 39 e art. 6-bis L. 212/2000; almeno 60 giorni per controdeduzioni, annullabilità nel perimetro, eccezioni. [Art. 10-quater nel sistema MEF](https://def.finanze.it/DocTribFrontend/getAttoNormativoDetail.do?ACTION=getArticolo&codiceOrdinamento=0000000000000109999900004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000&id=%7B2AD89417-4F8C-4D1C-9C94-99AEE78E7736%7D): limiti del giudicato favorevole e dell'anno dalla definitività per mancata impugnazione. Art. 10-quinquies: autotutela facoltativa anche per atti definitivi o in pendenza di giudizio, non potere di annullare giudicati.''')
append('wiki/sources/adempimento-collaborativo-compliance-fiscale-m-fc02.md', '''Per il regime pieno, art. 7 D.Lgs. 128/2015: soglia dimensionale almeno 500 milioni di euro dal 2026; almeno 100 milioni dal 2028 secondo calendario vigente. Parametro più elevato tra ricavi e volume d'affari nel triennio precedente la domanda. Gruppi con almeno un soggetto sopra soglia e TCF integrato certificato, non automatica ammissione di qualsiasi piccola impresa. Art. 4: sistema di controllo del rischio fiscale e certificazione nei casi prescritti da professionisti indipendenti abilitati. Fonti: [testo coordinato Gazzetta 5 agosto 2024](https://www.gazzettaufficiale.it/eli/gu/2024/08/05/182/sg/pdf), circolare AE 6/E del 6 agosto 2026 ([sistema MEF](https://def.giustiziatributaria.gov.it/DocTribFrontend/getPrassiDetail.do?id=%7B109739A0-0000-CA1D-80E0-9C1A2B0F3FD8%7D)). Distinguere il regime opzionale TCF dai requisiti del regime pieno.''')
append('wiki/sources/irpef-ires-categorie-reddito-impresa-aggiornamento-2026-07-18.md', '''Lettura diretta del raw AKN già acquisito (artt. 45, 49, 51, 54, 66, 109). Consolidati ora i criteri di imputazione e determinazione per rendere autosufficiente FC02/06: capitale per percezione senza deduzione, salve regole speciali; dipendente per cassa allargata al 12 gennaio; pensioni direttamente art. 49, non assimilati art. 50; autonomo per percezione/spese sostenute con deroghe del capo V, incluso raccordo temporale con la ritenuta del sostituto; impresa ordinaria per competenza salvo deroghe e regime minori art. 66 improntato alla cassa. [Art. 51 attuale nel sistema MEF](https://def.giustiziatributaria.gov.it/DocTribFrontend/executePrintArticolo.do?codiceOrdinamento=0000000000000510000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000&id=%7BBDF502CF-444F-4D74-8EDE-8461B0DA4023%7D&idAttoNormativo=%7B31D694E8-4398-4030-873B-FEAF5A6647F9%7D). Nessuna nuova aliquota o soglia reddituale è desunta da esempi inventati.''')
append('wiki/sources/dichiarazioni-versamenti-compensazioni-aggiornamento-2026-07-20.md', '''Art. 2, comma 7, D.P.R. 322/1998, nel raw integrale già acquisito: la dichiarazione presentata entro 90 giorni è valida, salve sanzioni; oltre 90 giorni è omessa ma costituisce titolo per la riscossione dei dati indicati. La scadenza ordinaria del modello è distinta dalla finestra di tardività. Riscontro istituzionale [circolare nel sistema MEF](https://def.finanze.it/DocTribFrontend/getPrassiDetail.do?id=%7B748E084A-FB26-43E8-8689-4A650983FBB4%7D).''')
append('wiki/topics/diritto-tributario-concorsi-agenzie-fiscali.md','''FC02/05 integra metodi di accertamento, termine minimo di contraddittorio e limiti dell'autotutela; FC02/06 confronta criteri temporali reddituali e dichiarazione entro/oltre 90 giorni. Delta consolidati nelle rispettive source notes datati 3 ottobre. Il rinvio a testi vigenti non sostituisce la regola necessaria alla soluzione del caso.''')
append('wiki/topics/riscossione-tributaria-ader.md','''Art. 86 D.P.R. 602/1973: il fermo vieta la circolazione del veicolo e non trasferisce la proprietà. Preavviso 30 giorni, dimostrazione della strumentalità, procedure per veicoli adibiti a trasporto di persone con disabilità, sospensione dopo prima rata e cancellazione dopo pagamento integrale: [AdER, procedure cautelari](https://www.agenziaentrateriscossione.gov.it/it/Per-saperne-di-piu/le-procedure/procedurecautelari/). La proprietà può essere trasferita con il vincolo; non chiamare il fermo divieto assoluto di disposizione.''')
def load(n):
 p=next(base.glob(n+'-*.md'));bk=root/'artifacts/correzioni-collana-2026-10-02/before-text/VOL-03'/p.name
 if not bk.exists():shutil.copy2(p,bk)
 return p,p.read_text(encoding='utf-8')
def save(p,s):
 s=s.replace('status: final','status: revised_draft').replace('draft_stage: text_frozen','draft_stage: revision-in-progress').replace('review_required: false','review_required: true')
 s=re.sub(r'updated_at: [^\n]+','updated_at: 2026-10-03',s,count=1);p.write_text(s,encoding='utf-8')
p,s=load('05');needle='## I poteri istruttori'
s=s.replace(needle,'''## I metodi di accertamento: quale ricostruzione è consentita?

La distinzione automatico/formale/sostanziale descrive il tipo di controllo. Dentro l'accertamento sostanziale occorre scegliere il metodo ammesso dalla legge, in particolare dagli artt. 38–41 D.P.R. 600/1973.

| Metodo | Presupposto e oggetto | Esempio da riconoscere |
| --- | --- | --- |
| Analitico | Rettifica singoli redditi o componenti sulla base di dati e documenti; per l'impresa parte dalle scritture senza disattenderle globalmente. | Una fattura di ricavo esistente non è stata registrata: si rettifica il componente provato. |
| Analitico-induttivo | Ricostruisce singoli componenti anche con presunzioni semplici gravi, precise e concordanti (art. 39, comma 1, lett. d). | Acquisti, giacenze e vendite documentati fondano una ricostruzione motivata dei ricavi; un margine anomalo isolato non basta da solo. |
| Induttivo extracontabile | Nei casi tassativi dell'art. 39, comma 2, come irregolarità gravi che rendono inattendibili le scritture, può prescindere in tutto o in parte da esse e usare presunzioni prive dei requisiti ordinari. | Contabilità complessivamente inattendibile: prima si dimostra il presupposto legale, poi si ricostruisce il reddito. |
| Sintetico | Ricostruisce il reddito complessivo della persona fisica da spese ed elementi di capacità contributiva (art. 38), con condizioni e prova contraria. | Una spesa elevata richiede verifica del finanziamento: risparmi pregressi o somme di terzi possono spiegare la disponibilità. |
| D'ufficio | Opera per dichiarazione omessa o nulla (art. 41), con i poteri ricostruttivi previsti. | Nessuna dichiarazione valida: non si presume arbitrariamente qualsiasi reddito; occorrono elementi utilizzabili e motivazione. |

Nel regime dell'art. 38 verificato al 3 ottobre 2026, il sintetico richiede uno scostamento almeno pari a un quinto del dichiarato e almeno pari a dieci volte l'assegno sociale annuo di riferimento. Non basta superare il solo 20%. Il contribuente può dimostrare diversa provenienza delle risorse, diverso ammontare delle spese o risparmio formatosi in precedenza. L'ufficio invita al confronto e avvia poi il procedimento di adesione previsto dalla norma. Il metodo sintetico non è l'induttivo extracontabile dell'impresa.

**Scelta guidata.** Una società ha contabilità complessivamente attendibile, ma una singola vendita è documentalmente omessa: la rettifica analitica è il punto di partenza. Passare direttamente a una ricostruzione extracontabile globale senza provarne i presupposti sarebbe un salto logico e giuridico.

'''+needle)
s=s.replace('Termini, atti esclusi ed effetti dell\'omissione devono essere verificati sul testo vigente. In prova, se la domanda non richiede il dettaglio numerico, è preferibile spiegare funzione, sequenza ed eccezioni senza improvvisare.', '''L'art. 6-bis assegna **almeno 60 giorni** per le controdeduzioni e, su richiesta, per accedere ed estrarre copia del fascicolo; l'atto non è adottato prima della scadenza assegnata. Nel suo perimetro l'omissione del contraddittorio determina annullabilità, da far valere con gli strumenti di tutela. Sono esclusi gli atti automatizzati, sostanzialmente automatizzati, di pronta liquidazione e di controllo formale individuati dal decreto ministeriale, oltre ai casi motivati di fondato pericolo per la riscossione; vanno rispettate anche le discipline speciali. Il termine serve a difendersi prima dell'atto: non coincide con i 60 giorni ordinari per il ricorso dopo la notifica.''')
s=s.replace('In entrambi i casi occorre verificare i limiti fissati dalla disciplina vigente.', '''L'art. 10-quater esclude l'obbligo in presenza di giudicato favorevole all'amministrazione e dopo un anno dalla definitività dell'atto per mancata impugnazione. Fuori dai casi obbligatori, l'art. 10-quinquies consente l'annullamento o la rinuncia per illegittimità o infondatezza anche durante il giudizio o per atti definitivi; non attribuisce all'ufficio il potere di cancellare un giudicato. **Caso:** un pagamento regolare ignorato è una delle ipotesi tipizzate; l'istanza deve documentarlo, ma non interrompe da sola il termine per ricorrere.''')
s=s.replace('Soglie dimensionali, certificazioni, requisiti di accesso ed effetti premiali sono stati oggetto di interventi recenti. Vanno studiati sul testo vigente quando il bando richiede il dettaglio, soprattutto per profili ACFI e fiscalità internazionale.', '''**Accesso nel 2026.** L'art. 7 D.Lgs. 128/2015 fissa la soglia ordinaria a ricavi o volume d'affari non inferiori a **500 milioni di euro** dal 2026; il calendario vigente prevede 100 milioni dal 2028. Si considera il valore più elevato nel triennio precedente la domanda secondo la disposizione, non il solo utile netto. Il gruppo può accedere alle condizioni specifiche, con almeno un soggetto sopra soglia e un sistema integrato certificato. Il TCF deve essere effettivo e, nei casi prescritti, certificato da professionisti indipendenti abilitati: un manuale interno nominale non basta. Restano le ulteriori vie di accesso previste dall'art. 7. Il regime opzionale per l'adozione del TCF da parte di chi non possiede i requisiti non equivale all'ammissione al regime pieno. Riferimenti: artt. 4 e 7 D.Lgs. 128/2015 e circolare AE 6/E del 6 agosto 2026.''')
save(p,s)
p,s=load('06')
s=s.replace("L'art. 49 collega la categoria al lavoro prestato alle dipendenze e sotto la direzione altrui, oltre alle fattispecie assimilate previste dalla disciplina.","L'art. 49 collega la categoria al lavoro prestato alle dipendenze e sotto la direzione altrui e include direttamente le pensioni e gli assegni equiparati. I redditi assimilati, come specifiche borse di studio o collaborazioni, sono invece tipizzati dall'art. 50: la pensione non va classificata tra questi ultimi.")
needle='### Caso IRPEF: classificare più componenti'
s=s.replace(needle,'''### Determinazione e periodo: la regola cambia con la categoria

| Categoria | Regola di base | Applicazione essenziale |
| --- | --- | --- |
| Fondiari | Determinazione prevalentemente catastale e imputazione legata a possesso, quota e periodo, anche senza percezione, salve le discipline speciali. | Un terreno non produce reddito solo quando il proprietario incassa denaro; per locazioni e mancati canoni si esamina la regola specifica. |
| Capitale | Proventi percepiti nel periodo, senza deduzione dei costi, salve disposizioni specifiche (art. 45). | Interessi incassati a gennaio appartengono in via ordinaria al nuovo periodo; regimi sostitutivi e presunzioni legali vanno poi verificati. |
| Dipendente | Cassa con estensione alle somme corrisposte dal datore entro il 12 gennaio del periodo successivo, se riferite al precedente (art. 51). | Retribuzione di dicembre pagata il 10 gennaio si imputa all'anno precedente; pagata il 15 gennaio al nuovo anno. |
| Autonomo | Differenza fra somme/valori percepiti e spese sostenute nell'attività, con deroghe del capo V (art. 54). | Un compenso ordinario non incassato non segue automaticamente la competenza; ammortamenti e specifiche deroghe impediscono di ridurre tutto a incassi meno bonifici. |
| Impresa | Nel regime ordinario prevale la competenza, salvo deroghe; per imprese minori dell'art. 66 opera un regime improntato alla cassa con componenti regolati separatamente. | Merce consegnata a dicembre e pagata a febbraio produce ordinariamente ricavo a dicembre, se certa e oggettivamente determinabile; il caso va qualificato prima di applicare il criterio. |
| Diversi | Determinazione e imputazione dipendono dalla fattispecie degli artt. 67–71, spesso fondata sulla percezione e con specifici costi deducibili. | Compenso occasionale e plusvalenza immobiliare non si calcolano con un'unica formula generica. |

Per il lavoro autonomo, il testo dell'art. 54 coordina anche il compenso percepito nell'anno successivo a quello in cui il sostituto lo ha corrisposto: l'imputazione segue il periodo in cui per il sostituto sorge l'obbligo di ritenuta. Questa deroga evita di applicare meccanicamente il criterio bancario senza conoscere chi paga e quando.

**Calcolo controllato.** Per un professionista, si assumano soltanto compensi ordinari incassati per 30.000 euro e spese interamente deducibili pagate per 8.000, senza altre componenti o regimi speciali: reddito 22.000. La fattura di 2.000 ancora da incassare non si aggiunge automaticamente. Nell'impresa ordinaria la stessa conclusione sarebbe errata se quel ricavo fosse già di competenza. Le ipotesi rendono risolvibile il calcolo; non autorizzano a dedurre ogni spesa professionale.

'''+needle)
s=s.replace('Una dichiarazione inviata entro la finestra che la legge considera **tardiva ma valida** resta dichiarazione presentata, ferma la disciplina della tardività. Oltre quella finestra è **omessa**; l\'invio successivo può rilevare per gli effetti espressamente previsti, ma non converte automaticamente l\'omissione in presentazione tempestiva o tardiva valida.', '''La dichiarazione dei redditi presentata **entro 90 giorni** dalla scadenza è tardiva ma valida, ferme le sanzioni per il ritardo (art. 2, comma 7, D.P.R. 322/1998). Oltre 90 giorni è considerata omessa, ma resta titolo per riscuotere le imposte sugli imponibili e le ritenute indicati. Un invio al sessantesimo giorno e uno al centesimo hanno quindi qualificazione diversa. Il termine ordinario del modello, eventuali proroghe e il computo concreto si verificano per l'annualità: i 90 giorni non trasformano la scadenza ordinaria in una facoltà di invio senza conseguenze.''')
s=s.replace('Aliquote, scaglioni, soglie, importi, percentuali e termini non sono consolidati in questo capitolo.','Le aliquote e gli importi annuali richiedono la disciplina del periodo; i criteri temporali e la finestra di tardività necessari agli esercizi sono invece esposti qui.')
save(p,s)
p,s=load('07')
s=s.replace('Impedisce la libera disponibilita del veicolo fino alla regolarizzazione o alla definizione del debito','Vieta la circolazione del veicolo finché il fermo resta efficace; non trasferisce la proprietà né coincide con un divieto assoluto di vendita')
needle='### Cosa deve saper dire il candidato'
s=s.replace(needle,'''### Fermo: preavviso, circolazione e tutele

Il preavviso concede 30 giorni per regolarizzare o attivare i rimedi pertinenti prima dell'iscrizione al PRA. Entro quel termine il debitore può dimostrare che il veicolo è strumentale alla propria impresa o professione: non basta chiamarlo genericamente «utile per andare al lavoro». AdER prevede inoltre procedure dedicate ai veicoli adibiti al trasporto di persone con disabilità. Un veicolo sottoposto a fermo non può circolare; la vendita non elimina il vincolo. La sospensione del fermo dopo l'integrale e tempestivo pagamento della prima rata, nelle condizioni previste, consente nuovamente la circolazione; la cancellazione segue l'integrale estinzione del debito della procedura. Sospensione e cancellazione non sono sinonimi.

**Caso.** Un artigiano riceve il preavviso sul furgone usato nell'attività: documenta la strumentalità entro i 30 giorni e presenta l'istanza pertinente. Non continua semplicemente a circolare dopo l'iscrizione confidando che l'uso professionale cancelli da sé il fermo. Riferimenti: art. 86 D.P.R. 602/1973 e istruzioni AdER sulle procedure cautelari.

'''+needle)
save(p,s)
p,s=load('13');s=s.replace('**Svolgimento guidato\n','**Svolgimento guidato**\n').replace('| D - Domande | In quale forma può\' comparire il contenuto? | Quiz secco, quesito situazionale, caso breve, domanda orale, confronto tra istituti, errore da riconoscere. |','| D - Diario | Quale errore devo correggere prima della prossima prova? | Registra il passaggio sbagliato, la regola corretta e un esercizio di verifica. |');save(p,s)
print('V03-029/030/043/045/047 applicati; fonti e topic aggiornati')
