from pathlib import Path
import hashlib,json,re
A=Path('artifacts/correzioni-collana-2026-10-02');B=Path('wiki/books/moduli/m-fc04-giustizia');V=Path('wiki/books/vol-04-giustizia-upp')
for p in [B/'index.md',V/'index.md']:
 t=p.read_text('utf-8').replace('Audit specialistico, freeze e PDF devono essere chiusi nel ciclo corrente; le verifiche del candidato di agosto non attestano la nuova pubblicabilità.','Revisione trasversale e audit specialistico del testo sono chiusi; il nuovo freeze identifica i sorgenti verificati. PDF, preflight e consegna devono essere verificati nel ciclo corrente; le prove di agosto non attestano la nuova pubblicabilità.')
 p.write_text(t,'utf-8')
p=V/'planning/02-matrice-copertura-didattica.md';t=p.read_text('utf-8').replace('Mancano ancora audit15/freeze16 del ciclo corrente e controllo del nuovoPDF; nessuna pubblicabilità attestata da questa matrice.','Audit specialistico 15 completato; freeze 16 documentato nel manifest corrente. Resta il controllo del nuovo PDF e del pacchetto; nessuna pubblicabilità complessiva attestata da questa matrice.');p.write_text(t,'utf-8')
files=sorted(set([*B.glob('chapters/*.md'),*V.glob('front-matter/*.md'),*B.glob('front-matter/*.md'),B/'index.md',V/'index.md',V/'planning/02-matrice-copertura-didattica.md',*Path('wiki/sources').glob('vol-04-*-verifica-2026-10-03.md')]))
data=dict(volume='VOL-04',module='M-FC04',date='2026-10-03',verification='Verifica manuale delle condizioni di freeze; gate deterministico non implementato, stato da chiudere via CLI con evidenza.',files=[dict(path=p.as_posix(),sha256=hashlib.sha256(p.read_bytes()).hexdigest(),date='2026-10-03',status='text-frozen') for p in files],checks=['17 capitoli presenti; 29 ID testuali corretti e verificati; gate13/14/15 superati senza rilievi aperti.','Matrice 14 materie allineata ai contenuti effettivi; nessun nucleo mancante o parziale nel perimetro dichiarato.','84 quiz con quattro alternative, chiavi A/B/C/D21 ciascuna, spiegazioni e sei simulazioni svolte.','Fonti, cut-off, dipendenze, rinvii, passata Humanizer e micro-revisione documentati nei rapporti13–15.'],publicationReady=False,remaining=['PDF','preflight','package','final-confirmation'])
(A/'M-FC04-freeze.json').write_text(json.dumps(data,ensure_ascii=False,indent=2),'utf-8')
text='# Text freeze — M-FC04\n\nData: 3 ottobre 2026. Gate13–15 superati; verifica manuale delle condizioni descritte dal prompt16. Il gate text-freeze non è implementato: la chiusura CLI non va qualificata come validazione automatica.\n\n'+ '\n'.join('- '+c for c in data['checks'])+'\n\n| File | Stato | SHA256 |\n|---|---|---|\n'+'\n'.join('| '+r['path']+' | text-frozen | '+r['sha256']+' |' for r in data['files'])+'\n\nManifest: artifacts/correzioni-collana-2026-10-02/M-FC04-freeze.json. Solo delta controllati da questo punto; modifiche sostanziali riaprono gli audit pertinenti. PDF e distribuzione non attestati.\n'
Path('wiki/reviews/pipeline/VOL-04/16-moduli-m-fc04-giustizia.md').write_text(text,'utf-8')
(A/'VOL-04-progress.json').write_text(json.dumps(dict(date='2026-10-03',chaptersApplied=17,quiz=84,finalSimulations=6,textAudit='passed',textFindingsClosed=29,publicationReady=False,remaining=['PDF','preflight','package','conferma24']),ensure_ascii=False,indent=2),'utf-8')
print('Freeze:',len(files),'file')
