from pathlib import Path
import re,json,hashlib,shutil
A=Path('artifacts/correzioni-collana-2026-10-02');B=Path('wiki/books/moduli/m-tr03-tecnico-ingegneristico');R=Path('wiki/reviews/pipeline/VOL-10')
files=sorted((B/'chapters').glob('*.md'));assert len(files)==13
for p in files:
 s=p.read_text(encoding='utf8');assert 'review_required: false' in s;s=re.sub(r'^draft_stage:.*$','draft_stage: text_frozen',s,flags=re.M);p.write_text(s,encoding='utf8')
p=B/'index.md';s=p.read_text(encoding='utf8').replace('revision-in-progress','text_frozen');s=re.sub(r'^- Stato:.*$','- Stato: tredici capitoli verificati e congelati al 3 ottobre 2026 dopo i diciotto rilievi dell’audit integrale. Gate 14 e 15 superati; freeze 16 manuale documentato con hash. Figure inserite e visionate come asset, PDF aggiornato e gate finali ancora da verificare.',s,flags=re.M).replace('Il precedente freeze è riaperto per le correzioni documentate.','Il testo verificato è identificato dal nuovo manifest; ogni modifica sostanziale riapre i passaggi pertinenti.');p.write_text(s,encoding='utf8')
files += [B/'index.md',B/'planning/02-matrice-copertura-didattica.md',B/'planning/13-bibbia-del-modulo.md',Path('wiki/sources/vol-10-tecnico-rettifiche-2026-10-03.md'),Path('wiki/topics/tecnico-ingegneristico-rettifiche-2026.md')]
checks=['Tredici capitoli presenti e letti integralmente nella baseline; delta riesaminati.','Diciotto rilievi obbligatori applicati e verificati; nessuna riduzione di promessa.','Matrice e indice coerenti; zero rinvii del corpo irrisolti.','Calcoli e soluzioni controllati, relazione di 149 parole nel limite di 250; dossier completo.','Tredici gate di capitolo senza blocker: warning legacy dichiarati (13 retrofit, 11 squilibrio).','Dodici test export passati; quattro figure inserite e visionate come asset.','Audit 14 e 15 passati; fonti consolidate e cut-off 3 ottobre 2026.','Text-freeze non implementato: verifica manuale richiesta dal CLI eseguita.']
manifest={'volume':'VOL-10','module':'M-TR03','date':'2026-10-03','verification':'manuale dopo gate-not-implemented','checks':checks,'files':[{'path':p.as_posix(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'status':'text-frozen'} for p in files],'limitations':['PDF candidato corrente e resa delle figure non certificati; produzione e preflight da completare.','Fonti verificate nel perimetro dichiarato, non interi testi unici né allegati CAM integrali.']}
(A/'M-TR03-freeze.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf8')
p=R/'16-moduli-m-tr03-tecnico-ingegneristico.md'
if p.exists() and not (A/'before-text/VOL-10'/p.name).exists():shutil.copy2(p,A/'before-text/VOL-10'/p.name)
p.write_text('# M-TR03 — Congelamento del testo, 3 ottobre 2026\n\nGate automatico non implementato; verifica manuale prevista dal CLI.\n\n'+'\n'.join('- '+x for x in checks)+'\n\n| File | Stato | SHA-256 |\n| --- | --- | --- |\n'+''.join('| '+x['path']+' | '+x['status']+' | '+x['sha256']+' |\n' for x in manifest['files'])+'\n## Limiti\n\n'+' '.join(manifest['limitations'])+'\n',encoding='utf8')
p=A/'VOL-10-ledger.json';d=json.loads(p.read_text(encoding='utf8'))
for r in d['files']:r['sha256']=hashlib.sha256(Path(r['path']).read_bytes()).hexdigest()
for r in d['findings']:r['status']='Testo verificato e congelato; PDF da verificare'
d['freezeManifest']=str(A/'M-TR03-freeze.json');p.write_text(json.dumps(d,ensure_ascii=False,indent=2),encoding='utf8')
p=Path('wiki/reviews/correzioni-collana-2026-10-02/VOL-10.md');s=p.read_text(encoding='utf8').replace('Applicato e riesaminato nel testo; PDF da verificare','Testo verificato e congelato; PDF da verificare').replace('Concludere audit 15 e freeze 16 tramite CLI;', 'Audit 15 superato e freeze 16 manuale documentato;').replace('Le diciotto correzioni sono applicate e verificate nel testo.', 'Le diciotto correzioni sono applicate, verificate e congelate: `textVerified: true`, `finalVerified: false`.');s=s.replace('Quattro figure didattiche sono inserite','Verificato e integrato anche il raccordo espropriativo con la fonte consolidata VOL-02. Quattro figure didattiche sono inserite');p.write_text(s,encoding='utf8')
print('Manual freeze verified:',len(files),'files; PDF pending.')
