from pathlib import Path
import json,re
B=Path('wiki/books/moduli/m-ir01-scuola/chapters');A=Path('artifacts/correzioni-collana-2026-10-02')
def add(n,txt):
 p=next(B.glob(f'{n:02}-*.md'));t=p.read_text(encoding='utf8');a=t.index('\n## Il Bando Decoder');t=t[:a]+'\n'+txt.strip()+'\n'+t[a:];t=re.sub(r'^updated_at:.*$','updated_at: 2026-10-03',t,flags=re.M);p.write_text(t,encoding='utf8');return str(p).replace('\\','/')
files=[]
files.append(add(2,'''## Ordinamenti: collocare la scuola nel percorso

Il sistema nazionale di istruzione comprende scuole statali e scuole paritarie private o degli enti locali, secondo la legge 62/2000. «Privata» non significa automaticamente «paritaria»: il riconoscimento della parità richiede i presupposti della legge. La scuola esercita autonomia entro gli ordinamenti nazionali; non può creare liberamente un titolo di studio con valore legale né eliminare gli obiettivi comuni del percorso.

La **scuola dell’infanzia**, ordinariamente dai tre ai sei anni, non è obbligatoria. Il **primo ciclo** dura otto anni: cinque di primaria e tre di secondaria di primo grado, con esame conclusivo. Il **secondo ciclo** comprende i percorsi di istruzione secondaria di secondo grado e quelli regionali di istruzione e formazione professionale, indicati con **IeFP**. Licei, istituti tecnici e istituti professionali hanno ordinariamente durata quinquennale; esistono percorsi quadriennali autorizzati e la filiera tecnologico-professionale 4+2, che collega percorsi scolastici e formazione terziaria degli ITS Academy. Non identificare quindi ogni percorso superiore con un identico piano di cinque anni, né gli ITS con un sesto e settimo anno obbligatorio della scuola.

L’obbligo di istruzione decennale, normalmente dai sei ai sedici anni, va distinto dal diritto-dovere all’istruzione e formazione fino ai diciotto anni o al conseguimento di una qualifica almeno triennale entro tale età. Una qualifica IeFP e un diploma quinquennale non sono lo stesso titolo; per accesso a una selezione o prosecuzione degli studi contano tipo di titolo e disciplina pertinente, non la sola età del candidato. I Centri provinciali per l’istruzione degli adulti (**CPIA**) appartengono a un assetto specifico, nel quale i percorsi valorizzano anche crediti e competenze già acquisiti.

Nell’autonomia **didattica** la scuola adatta percorsi, tempi e mediazioni agli alunni, mantenendo gli obiettivi nazionali. Nell’autonomia **organizzativa** dispone in modo flessibile le risorse e l’attività, nei vincoli dell’organico e degli obblighi di servizio. Ricerca e sperimentazione consentono di studiare e migliorare le pratiche; non autorizzano a disapplicare norme sulla valutazione, sulla sicurezza o sul lavoro.

**Caso chiuso.** Un istituto propone un laboratorio interdisciplinare con gruppi di alunni di classi diverse. La proposta non modifica il titolo finale e mantiene obiettivi, monte ore e obblighi di servizio. È un uso possibile dell’autonomia, da progettare e deliberare nelle sedi competenti. Se la stessa proposta dichiarasse che il laboratorio sostituisce l’esame di Stato, il limite sarebbe superato: l’autonomia di una singola scuola non elimina un esame previsto dall’ordinamento.

**Verifica.** Una scuola paritaria è necessariamente statale? No: «paritaria» indica il riconoscimento nel sistema nazionale; la natura del gestore può essere privata o di ente locale. È quindi errato dedurre natura statale, modalità di reclutamento del personale e regime giuridico dal solo riconoscimento di parità.'''))
files.append(add(3,'''## Composizione, competenza e deliberazione

Il D.Lgs. 297/1994 distingue gli organi collegiali; autonomia e norme successive ne completano il quadro. Per risolvere una domanda di competenza occorre separare la presenza nell’organo dalla titolarità di una singola decisione. Il dirigente partecipa a più organi, ma non assorbe per questo le attribuzioni collegiali.

| Organo | Composizione essenziale | Competenza da riconoscere |
| --- | --- | --- |
| Collegio dei docenti | Docenti di ruolo e non di ruolo in servizio, compresi i docenti di sostegno; presiede il DS | Funzionamento didattico, programmazione educativa, adozione dei libri di testo, elaborazione del PTOF |
| Consiglio d’istituto | Rappresentanti di docenti, ATA, genitori e, nella secondaria superiore, studenti; DS membro di diritto | Approvazione PTOF e documenti contabili, regolamento interno, criteri generali di organizzazione |
| Consiglio di classe | Docenti della classe e rappresentanti previsti per il grado | Proposte didattiche e raccordo con le famiglie; valutazione degli alunni nella composizione docente |
| Giunta esecutiva | DS, DSGA, un docente, un ATA e due genitori; nella secondaria superiore uno dei genitori è sostituito da uno studente | Preparazione dei lavori del consiglio e proposta del programma annuale secondo la disciplina contabile |

Il **consiglio d’istituto** ha 14 componenti fino a 500 alunni: sei docenti, un ATA, sei genitori e il DS. Oltre 500 alunni ha 19 componenti: otto docenti, due ATA, otto genitori e il DS. Nella secondaria superiore la rappresentanza dei genitori è ridotta rispettivamente a tre o quattro, con altrettanti studenti. Il presidente è eletto fra i rappresentanti dei genitori; non coincide con il dirigente. Consiglio e giunta durano tre anni scolastici, mentre la rappresentanza studentesca è rinnovata annualmente. La giunta è invece presieduta dal DS e il DSGA svolge funzione di segretario.

Nei **consigli di intersezione** dell’infanzia e **interclasse** della primaria partecipa un genitore per sezione o classe interessata. Nella secondaria di primo grado il consiglio di classe comprende quattro rappresentanti dei genitori; nella secondaria superiore due genitori e due studenti. Le attività di coordinamento didattico spettano alla componente docente. Lo scrutinio non è una riunione nella quale genitori o studenti votano i giudizi dei singoli alunni. La composizione cambia con la funzione esercitata, non per una scelta estemporanea del presidente.

Il collegio propone al DS criteri e soluzioni nelle materie previste, ma una proposta non è l’atto di gestione finale. Per esempio, l’assegnazione dei docenti alle classi richiede il raccordo fra criteri generali, proposte e decisione dirigenziale. Analogamente, il consiglio approva il programma annuale, mentre DS e DSGA svolgono le rispettive funzioni di gestione contabile: nessuno dei due passaggi rende superfluo l’altro.

L’art. 37 richiede, per collegio, consiglio d’istituto e giunta, almeno la metà più uno dei componenti in carica per la validità della seduta. Le deliberazioni seguono la maggioranza assoluta dei voti validamente espressi, salvo regole speciali; in parità prevale il voto del presidente. Non applicare automaticamente questa regola a uno scrutinio, soggetto alla specifica disciplina della valutazione, né confondere componenti nominalmente previsti con quelli effettivamente in carica.

**Esempio.** Un consiglio con 19 componenti in carica si riunisce con nove presenti: manca il quorum strutturale di dieci, anche se tutti e nove concordano. Con dieci presenti la seduta può essere valida; resta da verificare la maggioranza deliberativa e l’eventuale regola speciale della decisione. La verbalizzazione deve consentire di ricostruire presenti, oggetto, votazione ed esito.

**Verifica.** Chi elabora il PTOF? Il collegio, sulla base degli indirizzi del DS. Chi lo approva? Il consiglio. La giunta non sostituisce nessuno dei due. Il quesito è risolto dalla funzione, non dall’idea che l’organo «più importante» decida tutto.'''))
files.append(add(4,'''## Dalle sigle alla procedura: PTOF e Sistema nazionale di valutazione

Il **Piano triennale dell’offerta formativa (PTOF)** è il documento che esprime identità culturale, progettazione curricolare, extracurricolare, educativa e organizzativa della scuola. Ha durata triennale ed è rivedibile annualmente. Non è soltanto il catalogo dei progetti aggiuntivi: collega curricolo, inclusione, fabbisogni di personale e attrezzature, scelte organizzative e miglioramento.

L’art. 3 del D.P.R. 275/1999 stabilisce una sequenza precisa. Il DS definisce gli indirizzi per le attività e le scelte di gestione e amministrazione, promuovendo il raccordo con territorio e componenti scolastiche; il collegio dei docenti elabora il piano; il consiglio d’istituto lo approva. La revisione annuale non consente al singolo ufficio di sostituire unilateralmente il documento deliberato. Le finestre operative comunicate per uno specifico anno non vanno confuse con la natura triennale del piano.

Il **Rapporto di autovalutazione (RAV)** legge contesto, risorse, esiti e processi attraverso dati e valutazioni argomentate. L’**INVALSI**, Istituto nazionale per la valutazione del sistema educativo di istruzione e formazione, fornisce strumenti, indicatori e riferimenti di confronto. Il RAV non coincide con il risultato delle sole prove standardizzate: deve spiegare che cosa quei dati, insieme agli altri disponibili, suggeriscono per la scuola concreta.

Il **Piano di miglioramento (PdM)** trasforma priorità e traguardi in azioni, responsabilità, tempi, risorse e monitoraggio. Il **Sistema nazionale di valutazione (SNV)** del D.P.R. 80/2013 comprende autovalutazione, valutazione esterna, azioni di miglioramento e rendicontazione sociale. Le visite esterne utilizzano nuclei con un dirigente tecnico e due esperti selezionati da INVALSI; non ogni scuola riceve automaticamente una visita nello stesso momento. L’INDIRE, Istituto nazionale di documentazione, innovazione e ricerca educativa, sostiene i processi di miglioramento.

La **rendicontazione sociale** comunica risultati raggiunti in relazione agli obiettivi e alle risorse. Non è il conto consuntivo: quest’ultimo riguarda la gestione contabile. I due documenti possono dialogare, ma dimostrare di avere speso una somma non dimostra da solo di avere migliorato gli apprendimenti. La triennalità SNV 2025–2028 costituisce il riferimento organizzativo corrente richiamato da INVALSI.

**Caso numerico originale.** Nel RAV di una scuola, su 100 alunni osservati con la stessa prova, 35 non raggiungono il criterio minimo di comprensione del testo. Il PdM propone di ridurre la quota dal 35% al 25% entro il termine del percorso. Azione: laboratorio settimanale, formazione dei docenti e prova iniziale/finale confrontabile. Responsabili: gruppo disciplinare per progettazione e somministrazione; DS per raccordo organizzativo. Al termine, 28 su 100 restano sotto il criterio: risultato 28%, miglioramento di sette punti percentuali, traguardo non raggiunto. Non scrivere «miglioramento del 7%»: la diminuzione relativa è 7/35 = 20%. Se cambia il gruppo o la prova, il confronto va qualificato prima di attribuire l’effetto al laboratorio.

**Verifica.** «Abbiamo svolto tutte le dieci attività del PdM» dimostra il raggiungimento del traguardo? Dimostra un’attuazione, da documentare; il traguardo richiede il risultato previsto. Se gli esiti non migliorano, si analizzano partecipazione, adeguatezza delle attività e qualità dei dati, poi si modifica l’intervento.'''))
files.append(add(5,'''## Caso di carriera: trasferimento durante l’anno

**Traccia originale.** Una famiglia chiede il trasferimento della figlia, iscritta alla classe seconda della secondaria di primo grado, dall’istituto Alfa all’istituto Beta per cambio di residenza. Beta conferma la disponibilità ad accogliere l’alunna. La richiesta è firmata da un solo genitore e non chiarisce l’esercizio della responsabilità genitoriale. Nell’allegato è inserita anche una relazione sanitaria. Non risultano ancora il nulla osta della scuola di provenienza né la trasmissione del fascicolo. Il candidato, assistente amministrativo dell’istituto Alfa, deve predisporre una nota istruttoria, senza firmare il provvedimento del dirigente.

La carriera è la sequenza degli atti che documentano iscrizione, frequenza, valutazioni, passaggi e titoli. Un trasferimento non azzera ciò che è già avvenuto e non autorizza a ricopiare i dati senza controllo. L’ufficio verifica identificativi, classe, destinazione, richiesta e titolarità del richiedente; chiarisce il consenso richiesto o l’eventuale situazione documentata di responsabilità esclusiva. Non presume un conflitto familiare dalla sola firma mancante e non richiede indistintamente documenti ulteriori a ogni famiglia.

**Nota istruttoria modello.** «Oggetto: richiesta di trasferimento, alunna identificata nel fascicolo riservato. Acquisita e registrata la richiesta; verificata la corrispondenza con la carriera e la disponibilità comunicata dall’istituto Beta. Da completare: dichiarazione o documentazione pertinente all’esercizio della responsabilità genitoriale e presupposti del rilascio del nulla osta. Si sottopone la pratica al DS per il provvedimento di competenza. Dopo il rilascio, si curano trasmissione protetta dei documenti pertinenti, aggiornamento delle registrazioni di carriera e conferma di ricezione. La documentazione sanitaria è trattata con accesso limitato, separando ciò che serve alla continuità educativa dalla comunicazione ordinaria.»

Il nulla osta e l’accoglienza della scuola destinataria hanno funzioni diverse: il primo riguarda il passaggio dalla scuola di provenienza; la seconda garantisce che esista un’effettiva destinazione. Una telefonata non registrata non basta per ricostruire il flusso. Il fascicolo non viene inviato a una casella personale solo perché il destinatario si qualifica come docente. Occorrono canale istituzionale, destinatario competente e registrazione della trasmissione, secondo le regole documentali della scuola.

**Esito verificabile.** La pratica non è chiusa al semplice invio della richiesta al DS: servono atto, aggiornamenti e riscontro della trasmissione. Non viene invece decisa dall’assistente una variazione del percorso didattico o un riconoscimento discrezionale di competenze. Per le nuove iscrizioni, le date e le modalità annuali sono quelle della nota MIM applicabile: non si trasferiscono al nuovo anno le finestre di una circolare precedente.

**Griglia di autocorrezione, 10 punti.** Due punti per controllo della richiesta e della titolarità; due per distinzione istruttoria/provvedimento; due per nulla osta e destinazione; due per trasmissione e continuità della carriera; due per riservatezza. L’invio indiscriminato della relazione sanitaria o l’adozione di un atto riservato al DS costituiscono errori critici: la risposta va riscritta anche se gli altri passaggi sono corretti.'''))
files.append(add(6,'''## Piano delle attività ATA: proposta, adozione, attuazione

Il piano delle attività del personale **amministrativo, tecnico e ausiliario (ATA)** organizza servizi, compiti, orari e raccordi necessari al funzionamento della scuola. Non è il piano annuale delle attività dei docenti, deliberato nella sede propria, e non è il contratto integrativo d’istituto.

La sequenza dell’art. 53, comma 1, del CCNL Scuola 29 novembre 2007, coordinata con i contratti successivi, è precisa: **il DSGA formula la proposta, sentito il personale ATA; il DS ne verifica la congruenza con l’offerta formativa, espleta le relazioni sindacali previste e adotta il piano; il DSGA ne cura la puntuale attuazione**. Le relazioni si leggono oggi nel CCNL Istruzione e ricerca 2022–2024, firmato il 23 dicembre 2025. Il riferimento del 2007 conserva qui la regola organizzativa compatibile, non rende ancora applicabili in blocco tutte le vecchie disposizioni sindacali.

L’incarico di **Direttore dei servizi generali e amministrativi (DSGA)** si colloca nell’Area dei Funzionari e dell’Elevata qualificazione (**EQ**). L’art. 55 del CCNL 18 gennaio 2024 e l’art. 25 del D.Lgs. 165/2001 collegano autonomia operativa, direttive di massima e obiettivi assegnati. Il DSGA sovrintende ai servizi amministrativo-contabili e generali, organizza e coordina il personale ATA e verifica i risultati. «Autonomia» significa capacità di organizzare il servizio nel proprio ambito; non equivale a sostituire il DS nella titolarità dei rapporti sindacali o nei provvedimenti che la legge gli assegna.

Le aree **Collaboratori, Operatori, Assistenti e Funzionari/EQ** ordinano il personale ATA. Area e profilo non sono sinonimi: fra gli Assistenti, l’assistente amministrativo cura il lavoro amministrativo e contabile nel proprio perimetro, mentre l’assistente tecnico opera nei laboratori e nei servizi tecnici del settore pertinente. Il collaboratore scolastico svolge i servizi generali, di accoglienza, vigilanza e supporto previsti dal profilo. L’Operatore scolastico ha compiti e requisiti propri, inclusi quelli di assistenza previsti dalla declaratoria; non va usato come nuova denominazione indifferenziata di ogni collaboratore. Per attribuire un’attività, si parte dal profilo, dalla formazione e dalla disciplina applicabile, non dalla sola disponibilità della persona.

**Caso originale.** Sono presenti tre assistenti amministrativi e un picco temporaneo di 90 pratiche d’iscrizione, di cui 30 già complete e 60 da controllare. La scuola deve mantenere il servizio ordinario e non sono date risorse per lavoro aggiuntivo. Il DSGA propone: un referente di ricezione e registrazione; un addetto al controllo delle pratiche; un addetto al servizio ordinario con fascia concordata di supporto. Una sola lista di lavoro assegna ogni pratica a una persona; il controllo finale individua pratiche incomplete e richieste di integrazione. Il caso non autorizza a imporre straordinario non previsto né a spostare su un collaboratore compiti amministrativi estranei al profilo.

Il DS verifica la coerenza del piano e i passaggi di relazione sindacale, poi lo adotta. Il DSGA traduce il piano in attività, verifica giornalmente carico ed esiti e segnala lo scostamento. Se dopo cinque giorni sono state definite 50 pratiche e ne sono arrivate altre 20, il residuo è 90 + 20 − 50 = 60. Per comprendere il risultato occorre distinguere pratiche chiuse, in attesa di integrazione e non ancora esaminate: una semplice somma non dimostra il tempo di risposta agli utenti.

**Verifica.** Il piano proposto dal DSGA entra in vigore soltanto perché il personale è stato ascoltato? No: ascolto, proposta, relazioni pertinenti, adozione DS e attuazione DSGA sono passaggi distinti. Il personale non vota un piano che attribuisca al DSGA la competenza del dirigente.'''))
p=next(B.glob('06-*.md'));t=p.read_text(encoding='utf8');t=t.replace('La loro forma, il contenuto puntuale, l\'organo coinvolto e le procedure di approvazione dipendono dalle fonti vigenti e dal contesto della scuola; non vanno inventati in una risposta d\'esame.','La distribuzione concreta dipende dalle esigenze della scuola; proposta, adozione e attuazione seguono invece la sequenza contrattuale spiegata di seguito.');t=t.replace("Non autorizzano, da soli, a ricostruire declaratorie aggiornate, incarichi o assetti della singola istituzione: questi elementi restano mobili e richiedono controllo puntuale.","Il rinnovo del 23 dicembre 2025 e le disposizioni precedenti non sostituite definiscono il quadro corrente; il piano locale ne costituisce l’applicazione.");p.write_text(t,encoding='utf8')
batch={'V06-04':{'change':'Integrati ordinamenti essenziali, organi/composizioni/competenze/quorum e procedimento PTOF/SNV, con casi numerici risolti.','files':files[:3],'evidence':'Consolidati D.Lgs. 297 artt. 5/7/8/10/37, DPR275 art.3 e fonti INVALSI; rilettura del delta, calcoli quorum e 35→28% svolti.','status':'applicato'},'V06-05':{'change':'Caso completo di trasferimento con nota istruttoria e rubrica; piano ATA con proposta DSGA, adozione DS, attuazione DSGA, quadro contrattuale 2025 e aree/profili.','files':files[3:],'evidence':'ARAN CCNL2007 art53 e CCNL2024/2025 letti nei passaggi pertinenti; caso originale con confini di competenza e privacy.','status':'applicato'}}
(A/'VOL-06-batch02.json').write_text(json.dumps(batch,ensure_ascii=False,indent=2),encoding='utf8');print('IR01 capitoli 02–06 integrati.')
