from pathlib import Path
import json
A=Path('artifacts/correzioni-collana-2026-10-02');p=Path('wiki/books/moduli/m-ir02-universita-afam/chapters/12-laboratorio-quattro-profili.md');t=p.read_text()
t=t.replace('una richiesta di riconoscimento crediti è una domanda di beneficio economico:','una richiesta di riconoscimento crediti e una domanda di beneficio economico:')
t=t.replace('**Quiz 3.** In una spesa di progetto di ricerca, la presenza della voce nel budget:\nA. rende sempre la spesa rendicontabile;\nB. elimina ogni controllo documentale;\nC. è un elemento necessario ma non sufficiente;\nD. consente di ignorare il periodo di eleggibilità.\n\n**Risposta corretta: C.** Servono anche coerenza con il progetto, documentazione, periodo, autorizzazione, procedura corretta e regole della fonte finanziatrice.','**Quiz 3.** Un progetto applica il rimborso dei costi reali. Quale criterio guida la verifica di una spesa rispetto al budget?\nA. Ogni scostamento dalla ripartizione iniziale rende il costo sempre inammissibile.\nB. La sola presenza di una riga nel budget rende il costo ammissibile.\nC. Si verifica la conformità al budget, alle variazioni consentite e alle altre condizioni del grant.\nD. La disponibilità di cassa consente qualsiasi riallocazione fra attività.\n\n**Risposta corretta: C.** Il grant stabilisce se e come trasferire risorse o modificare il progetto: non sempre serve mantenere immutata ogni riga iniziale. Restano coerenza, periodo, documentazione e altre condizioni di ammissibilità. A esclude anche variazioni consentite; B confonde previsione e ammissibilità; D confonde liquidità e autorizzazione. Per costi unitari, forfait e somme forfettarie, le evidenze richieste seguono la diversa forma di finanziamento.')
t=t.replace('**Risposta corretta: C.** AFAM ha un quadro proprio, ma opera dentro procedure pubbliche. Il candidato deve usare fonte nazionale, statuto o regolamento locale e istruttoria concreta.','**Risposta corretta: C.** AFAM ha un quadro proprio. Nel caso di istituzione statale si raccorda anche alla disciplina dell’amministrazione pubblica; per un soggetto non statale si verifica il regime applicabile. Fonte nazionale, atto locale e istruttoria restano distinti.')
p.write_text(t,encoding='utf8')
batch={'V06-15':{'change':'Corretta la congiunzione del quiz2, mantenuto il predicato plurale.','files':[str(p).replace('\\','/')],'evidence':'Rilettura sintattica di domanda, opzioni e commento.','status':'applicato'},'V06-16':{'change':'Riformulato quiz3 nel regime dei costi reali: budget e variazioni consentite, ulteriori condizioni del grant; commentati tutti i distrattori e distinti i costi semplificati.','files':[str(p).replace('\\','/')],'evidence':'Confronto con fonte grant consolidata: modifiche secondo accordo; chiaveC coerente con commento.','status':'applicato'}}
(A/'VOL-06-batch07.json').write_text(json.dumps(batch,ensure_ascii=False,indent=2),encoding='utf8');print('Quiz2/3/5 corretti')
