from pathlib import Path
import re,json,hashlib
B=Path('wiki/books/moduli/m-ir02-universita-afam');A=Path('artifacts/correzioni-collana-2026-10-02');R=Path('wiki/reviews/pipeline/VOL-06');C=Path('wiki/reviews/correzioni-collana-2026-10-02')
p=next((B/'chapters').glob('11-*.md'));t=p.read_text(encoding='utf8');t=t.replace('\n## Riferimenti normativi e professionali\n\nL. 508/1999; D.P.R. 132/2003, artt. 4–8; D.P.R. 212/2005, artt. 3, 6 e 8, testo vigente; statuto e regolamenti dell’istituzione.','\nApprofondimenti puntuali: D.P.R. 132/2003, artt. 4–8; D.P.R. 212/2005, artt. 3, 6 e 8, testo vigente.');p.write_text(t,encoding='utf8')
stats=[]
for p in sorted((B/'chapters').glob('*.md')):
 t=p.read_text(encoding='utf8');t=re.sub(r'^review_required:.*$','review_required: false',t,flags=re.M);t=re.sub(r'^draft_stage:.*$','draft_stage: specialist-audit-complete',t,flags=re.M);t='\n'.join(line.rstrip() for line in t.splitlines())+'\n';p.write_text(t,encoding='utf8')
 body=t.split('\n---\n',1)[1];chunks=re.split(r'^### (N-IR02-\d+-\d+[^\n]*)\n',body,flags=re.M)
 nuclei=[{'id':chunks[i].split(' · ')[0],'words':len(re.findall(r'\b[\w’]+\b',chunks[i+1].split('\n## ')[0]))} for i in range(1,len(chunks),2)]
 quiz=len(re.findall(r'Risposta corretta',body.split('## ▣ Verifica',1)[1]));assert quiz>=6 and len(nuclei)==5 and min(n['words'] for n in nuclei)>=600,p
 assert not re.search(r'\[\[(sources|topics|entities|raw|planning|reviews)/|^## Note di review|^## Bozza agente',body,re.M),p
 stats.append({'path':str(p).replace('\\','/'),'words':len(re.findall(r'\b[\w’]+\b',body)),'nuclei':nuclei,'quiz':quiz,'staffLinks':False})
(A/'M-IR02-surface-counts.json').write_text(json.dumps(stats,ensure_ascii=False,indent=2),encoding='utf8')
p=B/'planning/02-matrice-copertura-didattica.md';t=p.read_text(encoding='utf8')
for f in stats:
 n=Path(f['path']).name[:2];t=re.sub(rf'(\| {n}, N-IR02-{n}-01–05[^\n]+\| )Q:\d+',lambda m:m[1]+f"Q:{f['quiz']}",t)
p.write_text(t,encoding='utf8')
p=Path('wiki/sources/prin-2026-bando-mur-programma-rendicontazione.md');t=p.read_text(encoding='utf8')+'\n## Riscontro del 3 ottobre 2026\n\nConfermati titolo, numero e data del D.D. 2298 del 10 aprile 2026 nella pagina ufficiale MUR https://www.mur.gov.it/it/atti-e-normativa/decreto-direttoriale-n-2298-del-10-04-2026 e nel portale https://prin.mur.gov.it/Home . Il capitolo usa soltanto questo identificativo e la distinzione fra edizioni; nessuna nuova attestazione su tutte le condizioni finanziarie o sugli allegati del bando.\n';p.write_text(t,encoding='utf8')
p=Path('wiki/sources/biblioteche-universitarie-cataloghi-sbn-risorse-open-access-2026-08-05.md');t=p.read_text(encoding='utf8');t=t.replace('## Review richiesta','## Perimetro del controllo specialistico').replace('- Bibliotecario catalogatore: verificare terminologia, distinzioni e livello tecnico coerente con 2523/2524.','- Terminologia e distinzioni catalografiche controllate nelle parti indicate nell’integrazione del 3 ottobre; non certificato un record importabile.').replace('- Esperto di risorse elettroniche: verificare ogni esempio di accesso, licenza e document delivery.','- Gli esempi non attribuiscono diritti a licenze reali non esaminate: applicano condizioni dichiarate nella traccia.').replace('- Esperto open access: verificare policy, versione, diritti, embargo, licenza e repository dell\'esempio selezionato.','- Versione, diritti e licenza restano campi da verificare per ogni deposito concreto; nessun embargo universale insegnato.').replace('- Revisore giuridico: controllare ogni richiamo puntuale a diritto d\'autore, privacy e banche dati prima del text freeze.','- Non sono aggiunte soglie di riproduzione o eccezioni giuridiche analitiche: il testo distingue reperibilità, accesso e riuso.').replace('- Redazione: ricontrollare pagine, allegati e tracce delle procedure, perche\' programmi e piattaforme sono mobili.','- Bandi e piattaforme restano esempi datati; non vengono attestati requisiti di selezioni future.');t=t.replace('review_required: true','review_required: false');p.write_text(t,encoding='utf8')
source=R/'14-moduli-m-ir02-universita-afam.md';p=R/'15-moduli-m-ir02-universita-afam.md';arc=C/'archive/pre-correzioni-15-m-ir02.md'
if not arc.exists():arc.write_bytes(p.read_bytes())
t=source.read_text(encoding='utf8').replace('# M-IR02 — Correzioni del 3 ottobre 2026','# M-IR02 — Audit specialistico del 3 ottobre 2026')
t=t.replace('Applicati i rilievi universitari dell\'audit integrale e le quote pertinenti dei rilievi trasversali. Le altre quote restano aperte nel registro di volume.','Riesaminati i rilievi universitari corretti e le quote pertinenti dei rilievi trasversali. Nessun errore grave o medio aperto nel perimetro testuale del modulo. Le quote IR03/04 restano aperte nel registro di volume, fuori da questo audit.')
t=t.replace('## 6. Fonti','## 6. Fonti e controlli eseguiti').replace('Nuovi contenuti scritti dopo il consolidamento.','''Nuovi contenuti scritti dopo il consolidamento. PRIN 2026 D.D. 2298/10 aprile riconfermato nelle pagine ufficiali MUR. Verificati i calcoli: 60.000/5=12.000; canone 12.000×3/12=3.000 e risconto 9.000; interessi 1.200×3/6=600; risultato economico 14.400, cassa 158.000 e quadratura 215.000; 42×80=3.360, base 24.000−4.000 con 10%=2.000; utenti 125−5−8=112. Le forme semplificate mantengono le evidenze pertinenti e non diventano esonero generale dai controlli.

Risolti nuovamente i quiz connessi ai delta nei capitoli 02/03/04/06/07/08/11/12 e controllati i raccordi dei casi bibliotecari/mobilità. Chiavi: 02 B/B/A/B/A/B/B/B; 03 A/B/C/C/B/D/A/A; 04 A/B/B/B/C/B/A/C; 06 B/B/B/C/A/C/B/C; 07 B/C/B/B/B/B/B/A; 08 B/C/B/C/B/C/B/B; 11 B/A/A/A/C/B; 12 B/C/C/B/C/C. Commenti coerenti con le opzioni. Le quattro prove finali evitano risultati inventati e contengono rubrica e limiti del ruolo. Nessun box Dato operativo rilevato dal CLI; soglie ER.GO presentate come esempio datato e ipotesi numeriche esplicite.''')
t=t.replace('Audit specialistico, text freeze, rigenerazione e controllo PDF.','Audit specialistico testuale concluso; seguono text freeze, rigenerazione e controllo PDF.')
t=t.replace('Non attestata; gli altri moduli di VOL06 e i controlli PDF sono ancora in corso.','Testo del modulo idoneo al congelamento nel perimetro dichiarato. Pubblicabilità del volume non attestata: gli altri moduli di VOL06 e i controlli PDF sono ancora in corso.')
t+='\nControlli strutturali effettivi: 12 capitoli, 60 nuclei sopra 600 parole, almeno 6 quiz per capitolo, nessun collegamento staff nel corpo; conteggi aggiornati nel manifest di superficie. Nessun riempitivo introdotto per raggiungere soglie.\n';p.write_text(t,encoding='utf8')
print('IR02 audit15 scritto',sum(x['words'] for x in stats),'parole',sum(x['quiz'] for x in stats),'quiz')
