from pathlib import Path
import re,json
B=Path('wiki/books/moduli/m-ir02-universita-afam/chapters');A=Path('artifacts/correzioni-collana-2026-10-02')
blocks={
(9,2):'''**Dalle regole al record.** Le REICAT sono le Regole italiane di catalogazione: guidano descrizione e accessi alle risorse. ISBD definisce elementi descrittivi, ordine e punteggiatura convenzionale per rendere riconoscibili le informazioni anche fra lingue diverse. UNIMARC è un formato di rappresentazione e scambio dei dati bibliografici; SBNMARC è il protocollo attraverso cui i sistemi cooperano con l'Indice SBN, usando la semantica UNIMARC. Una regola dice che cosa descrivere e come individuarlo; un formato struttura i dati; un protocollo regola lo scambio. Nessuno di questi è il catalogo pubblico stesso.

Il controllo d'autorità, o **authority control**, collega nomi varianti alla medesima identità e distingue gli omonimi mediante qualificazioni e informazioni verificate. La forma autorizzata non elimina la variante: il rinvio permette di cercare anche partendo da quest'ultima. Per esempio, due autori chiamati «Mario Rossi», uno storico e uno biologo, non vanno unificati soltanto perché il nome coincide. Si confrontano dati biografici, opere e fonti; si collega la notizia all'identità corretta. Non si inventano date per rendere univoca una voce.

La **soggettazione** offre accesso al contenuto concettuale: una pubblicazione sulla tutela dei fiumi può essere cercata per argomento anche se «fiumi» non compare nel titolo. Il Nuovo soggettario della Biblioteca nazionale centrale di Firenze fornisce un sistema di indicizzazione e un thesaurus di termini e relazioni. La **classificazione** assegna invece una posizione in uno schema disciplinare; la **collocazione** indica dove reperire l'esemplare. Un numero di classificazione può concorrere alla collocazione, ma le due funzioni non coincidono.

**Record didattico, interamente inventato.** Sul frontespizio si leggono: Elena Verdi, *Le acque della città*, Edizioni Ponte, Bologna, 2024; il volume ha 180 pagine e misura 24 cm. Una scheda preliminare distingue titolo e responsabilità, pubblicazione, descrizione fisica, accesso autorizzato all'autrice, argomento e localizzazione. Il bibliotecario controlla prima se l'edizione sia già descritta, verifica l'identità dell'autrice e assegna accessi coerenti con l'effettivo contenuto. Il solo titolo non basta per dedurre il soggetto: potrebbe trattarsi di urbanistica, idrologia o narrativa.

La biblioteca possiede due copie: ciò richiede due dati di esemplare, non necessariamente due nuove descrizioni della stessa edizione. Una ristampa o una nuova edizione si valuta secondo le regole applicabili, senza fondere automaticamente oggetti diversi. Questo esempio non è un record SBN pronto per l'importazione: insegna a distinguere i livelli prima di applicare codici e campi del sistema.
''',
(9,3):'''**ILL e document delivery.** Il prestito interbibliotecario, spesso indicato come ILL, permette alla biblioteca di richiedere a un'altra istituzione un documento in prestito per l'utente. Il document delivery procura una riproduzione consentita, per esempio di un articolo: non trasferisce necessariamente il volume originale e non autorizza la copia indiscriminata dell'intera opera. In entrambi i casi si controllano disponibilità, regolamenti, diritto d'autore, licenze e condizioni del servizio.

**Caso risolto.** L'utente cerca un articolo identificato da titolo, autori, rivista, anno e pagine. L'OPAC localizza la rivista, ma il fascicolo non è disponibile in sede. La risposta non è «il catalogo non offre il PDF, quindi il servizio è impossibile». Si verificano risorse elettroniche e licenze, eventuale copia ad accesso aperto lecita e possibilità di document delivery. Se serve invece consultare un'intera monografia non disponibile, si valuta l'ILL, nei limiti della biblioteca prestante. Un manoscritto escluso dal prestito può richiedere consultazione in sede o riproduzione autorizzata: non si promette la spedizione.
''',
(10,2):'''Il **tirocinio curriculare** fa parte del percorso formativo; il tirocinio extracurriculare segue un regime distinto, anche regionale, e non si attiva semplicemente riutilizzando il modulo del corso di studio. Nel curriculare si distinguono soggetto promotore, soggetto ospitante, tirocinante, tutor accademico e tutor dell'ospitante. La convenzione regola il rapporto fra enti; il progetto o programma formativo descrive attività, obiettivi, periodo e tutor del singolo percorso. Il registro delle presenze e la documentazione finale attestano lo svolgimento; non sostituiscono l'approvazione preventiva.

**Esempio locale: Università di Bologna, procedura consultata il 3 ottobre 2026.** La pagina istituzionale richiede convenzione e attivazione approvata; prima di accogliere il tirocinante, l'ospitante verifica il registro che attesta l'autorizzazione e la formazione di sicurezza pertinente. Il tutor dell'ospitante firma le presenze e compila la valutazione finale. Coperture e attività devono corrispondere al periodo autorizzato. L'ateneo precisa che non svolge il ruolo di promotore per i tirocini extracurriculari: la pubblicazione di un'offerta non equivale alla sua attivazione.

**Traccia e soluzione.** Una struttura convenzionata propone di far iniziare lunedì uno studente, ma il programma individuale non è ancora approvato. L'ufficio non considera sufficiente la convenzione: completa il percorso autorizzativo e verifica obiettivi, tutor, periodo, sicurezza e coperture prima dell'avvio. Non registra retroattivamente presenze per far apparire regolare un'attività già iniziata. Il placement facilita l'incontro con l'ospitante; non può sostituire con una promessa informale gli atti richiesti.
''',
(10,3):'''Nella mobilità Erasmus+ per studio, il **Learning Agreement** concorda prima della partenza il programma fra studente, istituzione di invio e istituzione ospitante. Distingue attività da svolgere all'estero e riconoscimento nel corso di origine. Il **Transcript of Records**, rilasciato dopo l'attività, documenta insegnamenti, risultati e crediti effettivamente acquisiti. L'accordo programma; il transcript prova l'esito. Le modifiche approvate durante la mobilità si conservano insieme alla versione iniziale.

Le linee guida KA131 prevedono il riconoscimento pieno delle attività concordate e superate, confermate dal transcript, senza imporre nuovi esami per gli stessi risultati. Non occorre una corrispondenza meccanica uno-a-uno fra ciascun insegnamento estero e quello sostituito: il piano può collegare gruppi di risultati formativi. La conversione del voto segue le informazioni e le procedure pertinenti; non si inventa un'equivalenza fra scale soltanto perché i crediti coincidono.

**Caso numerico.** L'accordo approvato prevede tre attività da 6 ECTS ciascuna, da riconoscere complessivamente per 18 CFU nel percorso di origine. Il transcript conferma che tutte e tre sono superate. L'ufficio verifica identità, versione del piano e risultati, poi attiva la registrazione dei **18 crediti** senza chiedere un esame aggiuntivo. Se una delle tre attività non è superata, il transcript documenta 12 ECTS acquisiti: non si registrano automaticamente tutti i 18 previsti. Si applicano le disposizioni concordate per l'incompleto conseguimento, senza ridiscutere arbitrariamente i risultati positivi già coperti dall'accordo.

**Documento atteso.** Una breve nota di riconoscimento identifica accordo e sue variazioni, transcript ricevuto, attività superate, crediti riconosciuti, criterio per i voti e adempimento di registrazione. La semplice attestazione di permanenza all'estero non sostituisce il transcript; il contratto della borsa disciplina il finanziamento e non è il piano accademico.
''',
(12,2):'''**Prova A — Risposta a uno studente, 15 minuti.** Il regolamento didattico riportato nella traccia assegna il riconoscimento di crediti al consiglio di corso. Lo studente presenta una domanda completa e chiede all'operatore di sportello di anticipare per email quanti esami saranno convalidati. La piattaforma indica correttamente che la pratica è ricevuta; non vi è ancora deliberazione. Scrivi una risposta di massimo 120 parole e una nota interna di tre righe.

**Soluzione possibile.** «La domanda risulta ricevuta e completa. Il riconoscimento dei crediti è valutato dal consiglio di corso secondo il regolamento; la ricezione non costituisce già una decisione favorevole. L'ufficio trasmette la pratica all'organo competente e le comunicherà l'esito attraverso il canale istituzionale. Non è ancora possibile anticipare il numero degli esami riconosciuti». Nota: domanda identificata e documentazione controllata; inoltro al consiglio; esito da registrare dopo la deliberazione. Non si chiedono nuovamente documenti già presenti senza motivo e non si trasmette la carriera ad altri studenti.
''',
(12,3):'''**Prova B — Verifica di rendiconto, 20 minuti.** Il contratto della traccia ammette costi effettivi per servizi resi entro il 30 giugno, necessari alle attività approvate, identificabili e conformi alle regole applicabili. Permette la fatturazione successiva se il debito è già sorto nel periodo e l'importo è noto al rendiconto. Il servizio A, da 4.000 euro, è completato il 28 giugno e fatturato il 5 luglio, con verbale e documentazione regolari. Il servizio B, da 3.000 euro, è eseguito il 10 luglio. Sono entrambi pagati. Produci un prospetto ammissibile/escluso e una motivazione.

**Soluzione.** A supera il controllo temporale: l'attività e il debito sono nel periodo e il contratto ammette la fattura successiva. Sulla base delle altre condizioni dichiarate regolari, si propone **4.000 euro** ammissibili. B non supera il requisito temporale: si escludono **3.000 euro**, senza spostare la data del servizio. Il pagamento prova l'uscita monetaria, non l'ammissibilità. La risposta deve citare la clausola fornita, evitando di trasformarla in una regola identica per tutti i bandi.
''',
(12,4):'''**Prova C — Reference e licenza, 15 minuti.** Un utente esterno chiede un articolo identificato. Il catalogo mostra la rivista; la licenza della traccia consente accesso al contenuto elettronico soltanto agli utenti istituzionali autenticati e vieta l'invio diretto del file a esterni. È disponibile un manoscritto accettato dell'articolo in un repository aperto, con licenza che consente la consultazione e la condivisione del collegamento. Formula la risposta e indica due verifiche bibliografiche.

**Soluzione.** Si verifica che titolo, autori e identificatore corrispondano all'articolo richiesto e che la versione depositata sia chiaramente identificata. Si offre il collegamento alla copia lecita nel repository, spiegando che è il manoscritto accettato e non necessariamente il PDF editoriale. Non si condividono credenziali né il file soggetto alla restrizione. La visibilità della notizia in catalogo non annulla la licenza. Se il repository non corrispondesse alla risorsa, si dovrebbe cercare un'altra alternativa consentita invece di dichiarare risolto il bisogno.
''',
(12,5):'''**Prova D — Istruttoria AFAM, 20 minuti.** In un conservatorio statale, il consiglio accademico ha approvato l'indirizzo artistico di un laboratorio. La traccia attribuisce al CdA la deliberazione di bilancio e all'ufficio competente l'istruttoria di acquisto. Il preventivo è 8.000 euro, la disponibilità utilizzabile 6.000 e manca un atto che copra la differenza. Il docente chiede di inviare subito l'ordine. Redigi una nota di massimo 150 parole.

**Soluzione possibile.** «L'indirizzo artistico approvato non costituisce da solo copertura dell'acquisto. A fronte del preventivo di 8.000 euro risultano disponibili 6.000, con differenza di 2.000. Prima dell'ordine occorre sottoporre al soggetto competente una soluzione conforme alle regole di bilancio: reperimento e autorizzazione delle risorse oppure revisione del fabbisogno compatibile con gli obiettivi. Completata la verifica, l'ufficio svolgerà la procedura di acquisto prevista. Non si assume un'obbligazione eccedente la disponibilità sulla sola richiesta del docente». L'istruttore non riscrive il programma artistico e non attribuisce alla delibera accademica l'effetto della variazione contabile.

**Griglia comune alle quattro prove, 10 punti:** qualificazione del problema 2; uso delle fonti o clausole date 2; correttezza della decisione e dei calcoli 3; chiarezza del documento 2; rispetto di competenze e riservatezza 1. Obiettivo didattico: almeno 7 punti. Sono errori critici, da correggere prima di considerare superata la simulazione, inventare un provvedimento, falsificare date o presenze, diffondere credenziali o dati non necessari, impegnare risorse senza il presupposto richiesto. La soglia è propria dell'esercizio e non sostituisce quella di un concorso.
'''}
for cap in [9,10,12]:
 p=next(B.glob(f'{cap:02}-*.md'));t=p.read_text(encoding='utf8')
 for (c,n),block in blocks.items():
  if c==cap:t=re.sub(rf'(^### N-IR02-{cap:02}-{n:02}[^\n]*\n)',lambda m:m[1]+'\n'+block+'\n',t,count=1,flags=re.M)
 if cap in [9,10]:
  t=re.sub(r'^## (Riferimenti[^\n]*?) - (.+)$',lambda m:'## '+m[1]+'\n\n- '+m[2].replace(' - ','\n- '),t,flags=re.M)
 t=re.sub(r'^updated_at:.*$','updated_at: 2026-10-03',t,flags=re.M);t=t.replace('draft_stage: text_frozen','draft_stage: correction-in-progress').replace('review_required: false','review_required: true');p.write_text(t,encoding='utf8')
batch={
'V06-12':{'change':'Spiegati Learning Agreement, Transcript of Records, riconoscimento con caso 18/12 crediti; tirocinio curriculare con ruoli, documenti, attivazione e caso UniBo identificato.','files':[str(next(B.glob('10-*.md'))).replace('\\','/'),'wiki/sources/fonti-ufficiali-m-ir02-universita-afam-2026-07-24.md'],'evidence':'Linee guida ufficiali KA131 e procedura UniBo lette; distinzione accordo/risultati e convenzione/progetto applicata al caso.','status':'applicato'},
'V06-34':{'change':'Separati i titoli bibliografici dal testo delle voci nei capitoli 09 e 10.','files':[str(next(B.glob(f'{c:02}-*.md'))).replace('\\','/') for c in [9,10]],'evidence':'Heading H2 ora autonomi; liste bibliografiche nel corpo. Nuovo PDF da controllare.','status':'applicato'}}
(A/'VOL-06-batch08.json').write_text(json.dumps(batch,ensure_ascii=False,indent=2),encoding='utf8')
(A/'V06-11-24-progress.json').write_text(json.dumps({'V06-11':{'complete':['IR02/09'],'pending':['IR04/06','IR04/07','IR04/08']},'V06-24':{'complete':['IR02/12'],'pending':['IR03/10','IR03/12']}},indent=2),encoding='utf8')
print('IR02 biblioteca/mobilità/laboratorio applicati; trasversali IR03/04 pendenti')
