from pathlib import Path
import re
B=Path('wiki/books/moduli/m-ir03-enti-ricerca/chapters')
blocks={
(6,5):'''**Mini-proposta svolta: qualità di un archivio ambientale.** La traccia offre 600 registrazioni non personali di misure ambientali prodotte da 10 sensori in sei mesi; segnala duplicati e unità non uniformi. Chiede di proporre in otto settimane un metodo riproducibile per valutare e migliorare la qualità. I 600 record e gli otto settimane sono dati assegnati; i passaggi seguenti sono scelte progettuali dichiarate, non fatti già accertati.

**Domanda e obiettivo.** Quanti record consentono confronti attendibili dopo la verifica di identità, tempo e unità? L'obiettivo è consegnare un dataset curato, un dizionario dei dati e un rapporto che quantifichi esclusioni e trasformazioni. L'ipotesi da verificare è che una parte delle anomalie dipenda da duplicazione e conversioni incoerenti; non si afferma prima dell'analisi che la causa sia dimostrata.

**Disegno e strumenti.** Si propone il censimento dei 600 record, senza campionamento, perché il volume è gestibile. La chiave di controllo combina sensore, istante e variabile; eventuali duplicati discordanti restano segnalati, non eliminati scegliendo arbitrariamente il valore preferito. Si conserva il file originale in sola lettura e si usa uno script versionato, per esempio in Python, per controlli e conversioni; si verifica prima la disponibilità dell'ambiente. Citare lo strumento come proposta motivata è corretto; attribuire all'ente una licenza o infrastruttura non documentata sarebbe inventare un fatto.

**Piano.** Settimane 1–2: inventario, dizionario, controllo di accessi e unità. Settimane 3–4: script e registro delle anomalie. Settimane 5–6: revisione indipendente di 60 record scelti con criterio stratificato per sensore e tipo di anomalia; questa verifica non sostituisce il controllo automatico dell'intero insieme. Settimane 7–8: riesecuzione, consegna e rapporto. Il campione di 60 è una scelta proposta, da motivare per l'obiettivo di controllo, non una numerosità statisticamente rappresentativa garantita.

**Successo e limiti.** Ogni record finale deve risalire a quello originario; tutte le conversioni devono essere ricostruibili e le esclusioni motivate. Il rapporto confronta conteggi prima/dopo, segnala valori mancanti e non estende i risultati ad altri sensori o periodi. Il rischio principale è la mancanza della documentazione dell'unità: il dato resta non confrontabile finché non è chiarito, anziché ricevere un'unità ipotizzata. Output atteso: tre file versionati e rapporto di due pagine. La proposta è valutabile prima che esista un risultato positivo.

**Autocorrezione, 10 punti.** Domanda e obiettivo 2; metodo e tracciabilità 3; fattibilità e calendario 2; limiti e rischi 2; chiarezza degli output 1. Controlla soprattutto la distinzione fra dati forniti, assunzioni dichiarate, scelte motivate e risultati da ottenere.
''',
(7,2):'''**Calcolare l'h-index.** Si ordinano i lavori per citazioni decrescenti. L'indice h è il massimo numero per cui esistono almeno h lavori con almeno h citazioni ciascuno. Considera sei lavori con citazioni **18, 11, 7, 4, 3, 1**: il quarto raggiunge quattro, mentre il quinto non raggiunge cinque. Quindi **h = 4**. La somma delle citazioni è 44 e la media è 44/6, circa 7,33: nessuna delle due coincide con h.

Se il primo lavoro passa da 18 a 100 citazioni, h resta 4: l'indicatore non misura l'intero incremento di impatto del lavoro più citato. Se il quinto arriva a cinque citazioni ma il quarto rimane a quattro, riordinando si ottiene 100, 11, 7, 5, 4, 1 e h resta ancora 4. Servono cinque lavori con almeno cinque citazioni per raggiungere h = 5. Questa verifica evita l'errore di guardare soltanto il lavoro in posizione cinque prima di riordinare.

Il numero dipende da banca dati, identificazione degli autori, copertura dei prodotti e data del rilevamento. Disciplina, anzianità della carriera e pratiche di coautorialità influenzano i confronti. Le citazioni non attestano necessariamente approvazione del risultato: anche un lavoro criticato può essere citato. Perciò h non sostituisce la valutazione del contenuto, del contributo individuale e dei criteri della selezione; non esiste una soglia universale che renda automaticamente meritevole un candidato. La definizione risale al lavoro di J. E. Hirsch del 2005; i numeri qui usati sono interamente didattici.
''',
(8,3):'''**Requisito misurabile e accettazione: esempio didattico.** Una piattaforma deve importare 1.000 record di prova, conservando gli identificativi e segnalando quelli incompleti. La traccia richiede tempo massimo di 60 secondi e nessuna perdita di record valido; non sono soglie nazionali. Il set predisposto contiene 980 record validi e 20 privi di un campo obbligatorio. Il requisito è verificabile perché definisce input, condizione, misura e risultato atteso.

Il piano di prova registra versione del software, configurazione, checksum del file di ingresso, orario, durata, record accettati, scarti e motivazioni. Si attende **980 importati e 20 respinti motivatamente**, con totale riconciliato a 1.000. Un'esecuzione in 45 secondi che importa soltanto 975 validi fallisce: la velocità non compensa la perdita. Un'altra con conteggi corretti ma 70 secondi fallisce il requisito temporale. I criteri non si cambiano dopo aver visto l'esito per trasformare un fallimento in successo.

La **verifica** confronta il sistema con queste specifiche; la **validazione** valuta se il servizio è adatto all'uso previsto, per esempio facendo ricostruire a un operatore la ragione degli scarti e ripetere l'importazione corretta. Un log tecnicamente completo ma incomprensibile agli utenti può superare un controllo formale e non soddisfare l'uso reale. Il verbale distingue requisito, prova, risultato, scostamento, responsabile della correzione e nuova prova.

**Riesame del cambiamento.** Dopo una modifica al parser si ripete il set di prova e si controllano anche casi già funzionanti. Si conserva la versione precedente e si predispone il ripristino, con prova di integrità dei dati. Non basta riaccendere il servizio: occorre dimostrare che configurazione, dati e funzioni prioritarie siano nuovamente coerenti. Il tecnologo documenta l'esito; il soggetto competente decide l'accettazione secondo il processo dell'ente.
''',
(10,3):'''Nel principio **Accessible**, i dati e metadati devono essere recuperabili mediante identificativo attraverso un protocollo di comunicazione standardizzato. Il protocollo deve essere aperto, gratuito e universalmente implementabile; può prevedere autenticazione e autorizzazione quando necessario. «Accessibile» non significa quindi «tutti possono scaricare qualsiasi contenuto». Anche quando i dati non sono più disponibili, i metadati dovrebbero restare accessibili secondo il principio A2, nei limiti di protezione applicabili.

Per **Interoperable** si impiegano linguaggi e vocabolari condivisi e riferimenti qualificati: due colonne chiamate entrambe «temperatura», una in kelvin e una in gradi Celsius senza indicazione, non sono interoperabili solo perché i file sono CSV. Per **Reusable** occorrono descrizione, provenienza, condizioni d'uso e standard pertinenti. Un DOI facilita la reperibilità ma non risolve da solo licenza, qualità o significato delle variabili.
''',
(10,4):'''**DMP compilato, progetto didattico «Sensori aperti».** Il progetto raccoglie dati ambientali senza informazioni personali: sensore, istante UTC, temperatura in gradi Celsius e indicatore di qualità. Produce un file originale immutabile, un file curato e uno script di trasformazione. Questi sono dati della simulazione, non una descrizione di un progetto esistente.

**Dati e responsabilità.** Il ricercatore definisce variabili e criteri scientifici; il tecnologo mantiene acquisizione, versioni e controlli; il responsabile del progetto approva le decisioni di condivisione secondo le competenze dell'ente. Un referente dati tiene il DMP versione 1 e annota data, motivo e autore di ogni aggiornamento.

**Formati e qualità.** Tabelle in CSV UTF-8, dizionario in testo leggibile, script con versione e istruzioni di esecuzione. La chiave sensore–istante identifica le osservazioni; il controllo distingue duplicati identici, valori discordanti e campi mancanti. Gli scarti restano nel registro con motivazione; il file originale non viene sovrascritto. Una verifica di checksum segnala alterazioni rispetto alla versione conservata, senza pretendere di dimostrare che la misura fisica fosse corretta.

**Sicurezza e conservazione.** Copie di lavoro su spazio dell'ente con accessi per ruolo; backup giornaliero e prova di ripristino mensile come scelte progettuali esplicite. La traccia assegna cinque anni di conservazione dopo la chiusura: il piano indica chi presidia il deposito e riesamina il termine prima della scadenza. Non è un obbligo universale per tutti i dati scientifici.

**Condivisione.** Il dataset curato e i metadati saranno depositati in un repository istituzionale idoneo con identificatore persistente. L'esercizio assume che l'ente possieda i diritti necessari e autorizzi una licenza CC BY 4.0; la licenza è indicata nel record, insieme a citazione, versione e provenienza. Si verificano prima del deposito eventuali informazioni protette: se un file ricevuto da un partner introduce restrizioni, non lo si ingloba automaticamente nel pacchetto aperto, ma si aggiorna il DMP con un regime distinto.

**Controllo finale.** Un altro componente del gruppo deve poter trovare il record, capire unità e variabili, scaricare la versione autorizzata, rieseguire lo script e ricostruire le esclusioni. Il DMP è completo per questa traccia perché assegna oggetti, ruoli, controlli, tempi e condizioni, invece di limitarsi a scrivere «i dati saranno FAIR».
''',
(11,3):'''**La forma di finanziamento cambia la verifica.** Nei costi effettivi si controllano importi sostenuti e condizioni di ammissibilità. Nei costi unitari si moltiplicano unità effettivamente realizzate e documentate per l'importo applicabile. Nel tasso forfettario si applica la percentuale alla base ammessa, rispettandone le esclusioni. Nella somma forfettaria si verificano attività o risultati contrattualmente previsti: non si ricalcola il contributo sommando le fatture. La forma deriva dall'accordo; il beneficiario non sceglie quella più conveniente a fine progetto.

**Tre calcoli, regole ipotetiche.** Una voce unitaria remunera 35 attività ammesse a 90 euro ciascuna: 35 × 90 = **3.150 euro**, con prova delle unità. Un'altra voce usa il 15% di una base di 18.000 dalla quale il contratto esclude 2.000: (18.000 − 2.000) × 15% = **2.400 euro**; applicarlo all'intero importo darebbe indebitamente 300 euro in più. Un pacchetto lump sum da 25.000 dipende dall'attuazione delle attività definite: una spesa interna di 27.000 non aumenta automaticamente il contributo e una spesa di 23.000 non lo ridetermina da sola. Restano obblighi, controlli e condizioni dell'accordo.

Le forme semplificate non eliminano tutte le evidenze: cambiano quelle rilevanti. Per le unità servono conteggi ammissibili, per il forfait la base, per la somma forfettaria la realizzazione pertinente e gli obblighi non finanziari. La flessibilità del budget può consentire trasferimenti senza amendment entro le condizioni del grant; modifiche sostanziali dell'azione e casi particolari richiedono il percorso di approvazione previsto. Non ogni scostamento è vietato e non ogni modifica è libera.
''',
(11,5):'''Nel dispositivo per la ripresa e resilienza il **DNSH è un requisito obbligatorio delle misure**, ai sensi del regolamento (UE) 2021/241. Non dipende dalla scelta del beneficiario di considerarlo pertinente. Cambiano invece le verifiche, le schede e le evidenze richieste in relazione alla misura e all'intervento. Una semplice dichiarazione non sostituisce i riscontri; la mancanza di un particolare documento non autorizza a dichiarare il principio facoltativo.

Una **milestone** è un traguardo qualitativo; un **target** è un risultato quantitativo. Il pagamento di una fattura non prova di per sé né l'uno né l'altro. Se il target della traccia è 200 utenti formati e il registro contiene 210 righe, di cui 12 duplicati e 8 presenze non ammissibili, gli utenti validi sono 210 − 12 − 8 = **190**: il target non è raggiunto. Si descrive lo scostamento di 10, si conserva il controllo e si propone il recupero consentito dal progetto, senza trasformare righe in persone o modificare il criterio dopo il conteggio.
'''}
for cap in sorted({c for c,n in blocks}):
 p=next(B.glob(f'{cap:02}-*.md'));t=p.read_text(encoding='utf8')
 for (c,n),block in blocks.items():
  if c==cap:t=re.sub(rf'(^### N-IR03-{cap:02}-{n:02}[^\n]*\n)',lambda m:m[1]+'\n'+block+'\n',t,count=1,flags=re.M)
 if cap==6:
  t=t.replace('senza inventare campioni, risultati, software o vincoli di un bando non conosciuto.','distinguendo fatti assegnati, assunzioni esplicite, scelte progettuali e risultati ancora da ottenere.')
  t=t.replace('è corretto indicare categorie e nessi, non inventare assegnazioni, software, deleghe o disponibilità.','è corretto proporre strumenti, campioni e tempi motivati, dichiarando le assunzioni. Non si attribuiscono all’ente assegnazioni, deleghe o disponibilità non documentate.')
  t=t.replace('La prudenza richiede di non inventare risultati, protocolli, campioni o vincoli di una call non fornita.','La prudenza vieta di presentare come fatti risultati o vincoli non forniti; consente di proporre protocolli e campioni come scelte motivate, con limiti espliciti.')
  t=t.replace('Se compaiono campioni, strumenti o tempi non forniti dalla traccia, la prudenza è compromessa.','Se campioni, strumenti o tempi proposti sono presentati come dati già assegnati, la prudenza è compromessa; se sono scelte esplicite, se ne valuta la motivazione e la fattibilità.')
 if cap==11:
  t=t.replace('DNSH, cioè il principio di non arrecare un danno significativo, può essere un vincolo della misura e non una formula da aggiungere a ogni progetto. Quando applicabile,','DNSH, cioè il principio di non arrecare un danno significativo, è obbligatorio nelle misure RRF. Per applicarlo,')
  t=t.replace('Il controllo DNSH, quando richiesto,','Il controllo DNSH, nelle forme richieste dalla misura,')
 t=re.sub(r'^updated_at:.*$','updated_at: 2026-10-03',t,flags=re.M).replace('draft_stage: text_frozen','draft_stage: correction-in-progress').replace('review_required: false','review_required: true')
 p.write_text(t,encoding='utf8')
print('IR03 metodo, metriche, collaudo, DMP e grant applicati')
