from pathlib import Path
import re,json
B=Path('wiki/books/moduli/m-ir03-enti-ricerca/chapters');A=Path('artifacts/correzioni-collana-2026-10-02')
blocks={
(2,2):'''**I due decreti non hanno lo stesso perimetro.** Il D.Lgs. 213/2009 riordina gli enti di ricerca vigilati dal ministero allora denominato dell'istruzione, dell'università e della ricerca. Il D.Lgs. 218/2016 semplifica invece l'attività degli enti nominativamente elencati nell'articolo 1, comprendendo enti sottoposti anche ad altre vigilanze, e conserva le disposizioni speciali richiamate. Non è corretto dire che ogni EPR dipenda dal MUR o che ogni articolo del riordino del 2009 valga indistintamente per tutti.

L'articolo 2 del D.Lgs. 218/2016 collega **libertà e responsabilità della ricerca**. Tutela libertà scientifica, diffusione dei risultati, formazione, mobilità e partecipazione; richiede condotta etica, osservanza delle procedure, uso responsabile delle risorse, protezione dei dati, sicurezza e verificabilità del lavoro. La libertà metodologica non consente di modificare registrazioni per ottenere il risultato atteso. Il diritto di comunicare la ricerca va coordinato con riservatezza, protezione dei risultati e accordi applicabili.

L'articolo 3 riconosce autonomia statutaria e regolamentare: l'ente definisce missione, struttura e regole di funzionamento nel quadro nazionale ed europeo, degli indirizzi ministeriali e delle norme generali compatibili. Lo statuto è quindi uno strumento effettivo di organizzazione, non una semplice presentazione istituzionale. I regolamenti di amministrazione, finanza, contabilità e personale traducono l'autonomia in procedure; non possono cancellare i vincoli posti dalla legge.

**Applicazione.** Un ricercatore propone un metodo nuovo, documentato e coerente con il progetto. L'autonomia scientifica protegge la scelta ragionata; l'amministrazione verifica risorse e atti pertinenti. Se invece viene chiesto di cancellare un risultato negativo o attribuire al progetto una spesa estranea, il problema riguarda integrità e regolarità, non un'ingerenza illegittima nella libertà scientifica.
''',
(2,4):'''**Due assetti reali da confrontare.** Nel CNR lo statuto emanato con provvedimento n. 93/2018 distingue presidente, consiglio di amministrazione, consiglio scientifico e collegio dei revisori; il direttore generale cura la gestione secondo l'assetto statutario. Il presidente rappresenta legalmente l'ente e presiede il CdA. Il CdA esercita le funzioni di indirizzo e amministrazione generale e approva i documenti di bilancio. Il consiglio scientifico svolge funzioni propositive e consultive sulla ricerca: il suo parere non equivale all'approvazione del bilancio. Il DG ne cura la predisposizione e attua gli indirizzi; i revisori controllano la regolarità economico-finanziaria secondo le attribuzioni previste.

L'ISTAT ha un'altra missione e un altro assetto. Lo statuto del 2017, modificato nel 2019, colloca l'istituto sotto la vigilanza della Presidenza del Consiglio dei ministri e tutela l'indipendenza professionale della produzione statistica. Gli organi sono presidente, consiglio, Comitato per l'indirizzo e il coordinamento dell'informazione statistica (COMSTAT) e collegio dei revisori. Il COMSTAT si collega al coordinamento del Sistema statistico nazionale; non è il consiglio scientifico CNR con un nome diverso. Il consiglio ha funzioni strategiche e approva i documenti di bilancio; l'indipendenza tecnica sui metodi statistici non viene sostituita da istruzioni politiche sul risultato da ottenere.

**Caso risolto.** La traccia chiede chi approvi il bilancio del CNR e riporta un parere favorevole del consiglio scientifico. La risposta identifica il CdA quale organo di approvazione: il parere scientifico riguarda gli aspetti di competenza e non sostituisce la deliberazione. Se la domanda riguarda il coordinamento dell'informazione statistica nell'ISTAT, si parte dal COMSTAT e dalle sue attribuzioni, senza importare l'organigramma del CNR. Questi esempi fissano due configurazioni documentate al 3 ottobre 2026; per il concorso si controllano sempre gli atti indicati nel bando.
''',
(3,3):'''**Profilo e livello contrattuale.** Nei percorsi di ricercatore e tecnologo il livello III identifica rispettivamente ricercatore e tecnologo; il II primo ricercatore e primo tecnologo; il I dirigente di ricerca e dirigente tecnologo. Le denominazioni compaiono anche nelle tabelle del CCNL Istruzione e ricerca 2022–2024, firmato il 23 dicembre 2025. Non sono etichette intercambiabili con l'area dei funzionari amministrativi e il numero I non indica il livello iniziale.

Le declaratorie distinguono il contributo all'avanzamento delle conoscenze dalle funzioni tecnologiche e professionali. Nel ricercatore di III livello rileva l'attitudine dimostrata a produrre avanzamenti nel settore; nel primo ricercatore la capacità acquisita di determinare autonomamente avanzamenti significativi. Non basta contare articoli: occorre collegare contributo personale, metodo, risultati e responsabilità. La progressione di livello richiede i presupposti e la procedura applicabili; non deriva automaticamente dagli anni trascorsi.

**Esempio di lettura professionale.** L'ideazione di una domanda, la costruzione del disegno e l'interpretazione dei risultati documentano un apporto scientifico. La gestione di un archivio di dati può concorrere al medesimo progetto, ma va descritta per responsabilità effettive: pulizia, progettazione della struttura, validazione, analisi o coordinamento non sono la stessa attività. Il curriculum deve mostrare ciò che il candidato ha fatto, senza attribuirgli l'intero lavoro del gruppo.
''',
(3,4):'''Per il **tecnologo**, le declaratorie richiamano attività tecniche e professionali nelle strutture dell'ente: nel III livello compiti di analisi, revisione e collaborazione tecnica; nel II capacità autonoma di progettazione, elaborazione e gestione e, secondo le funzioni, coordinamento di competenze. Il tecnologo non è definito dalla sola manutenzione di apparecchi né dalla sola informatica. Può sviluppare un processo, un'infrastruttura, una piattaforma di dati o un servizio tecnico-scientifico. Le eventuali abilitazioni professionali richieste si ricavano dalle funzioni e dalla procedura concreta.

**Grant e project support** descrivono invece una funzione organizzativa. Il lavoro può essere affidato a profili e livelli diversi: la dizione inglese nel titolo di un ufficio non crea una declaratoria contrattuale nazionale autonoma. Nella scheda del bando si annotano separatamente ente, profilo formale, livello o area, attività assegnate e prove. Un bando per tecnologo di III livello dedicato al supporto di progetti resta un bando per quel profilo; un avviso amministrativo con rendicontazione non diventa per ciò solo una selezione da ricercatore.

Le descrizioni funzionali qui richiamate sono riscontrate anche nell'allegato 1 dell'avviso CREA del 2022 sulla mobilità fra profili. Quell'avviso è un esempio documentale storico: i suoi termini e requisiti di partecipazione non si trasferiscono ai concorsi attuali.
''',
(4,2):'''**Un sistema concreto: CNR dal 2025.** Il regolamento di amministrazione, contabilità e finanza emanato con provvedimento n. 201/2024, vigente dal 1° gennaio 2025, adotta la contabilità economico-patrimoniale e il bilancio unico. La contabilità generale rileva costi, proventi, attività e passività; quella analitica attribuisce risorse e risultati a centri e attività. L'autorizzazione preventiva e la rilevazione economica consuntiva restano funzioni diverse.

Il bilancio annuale autorizzatorio comprende **budget economico e budget degli investimenti**, con nota illustrativa. Il primo programma componenti economici; il secondo investimenti e coperture. Il bilancio triennale estende l'orizzonte della programmazione. A consuntivo, lo **stato patrimoniale** descrive attività, passività e patrimonio netto alla chiusura; il **conto economico** riporta costi e proventi di competenza; la **nota integrativa** spiega criteri e contenuti. Il rendiconto finanziario dei flussi di cassa permette di leggere incassi e pagamenti, che non coincidono con il risultato economico.

Il direttore generale predispone i documenti; il presidente li presenta al CdA per l'approvazione, con il parere scientifico e la relazione dei revisori negli ambiti previsti. Non si attribuisce al solo direttore di progetto il potere di approvare il bilancio. Le variazioni seguono le competenze del regolamento: la disponibilità totale dell'ente non autorizza a spostare liberamente somme vincolate.

**Tre assestamenti.** L'ammortamento distribuisce il costo di un bene durevole lungo l'utilità residua. Il risconto rinvia a esercizi futuri la parte di un costo o provento già rilevato che compete a quei periodi. Il rateo integra una quota di costo o provento già maturata, con manifestazione finanziaria successiva. Un pagamento anticipato non dimostra che tutto il costo appartenga all'anno; una quota maturata può dover essere rilevata prima del pagamento. Il regolamento CNR distingue queste scritture all'articolo 25, senza rendere identici tutti i sistemi degli EPR.
''',
(4,5):'''**Caso contabile chiuso, importi didattici.** Un ente applica competenza economica e, per questa traccia, ammortamento lineare per l'intero anno dal 1° gennaio. Cassa iniziale: 80.000 euro, senza debiti né altre attività. Nell'anno riceve un provento di competenza di 50.000 euro, paga servizi integralmente consumati per 20.000 e acquista il 1° gennaio un'apparecchiatura per 30.000, vita utile cinque anni e valore residuo nullo. Il 1° ottobre paga 12.000 euro per dodici mesi di servizio. Al 31 dicembre sono maturati altri 2.000 euro di servizi, da fatturare e pagare nell'anno successivo. IVA e altri eventi sono esclusi dalla traccia.

La cassa finale è 80.000 + 50.000 − 20.000 − 30.000 − 12.000 = **68.000 euro**. Il macchinario genera ammortamento di 30.000/5 = **6.000**, con valore netto di 24.000. Del servizio annuale competono all'anno tre mesi: 12.000 × 3/12 = **3.000**; i restanti **9.000** sono risconto attivo. I servizi già ricevuti per 2.000 richiedono costo e debito per fatture da ricevere: non un rateo automaticamente, perché si tratta di una prestazione già compiuta, non della semplice quota temporale di un rapporto a cavallo d'anno.

Il risultato economico è 50.000 − 20.000 − 6.000 − 3.000 − 2.000 = **19.000 euro**. L'attivo finale è cassa 68.000 + bene netto 24.000 + risconto 9.000 = **101.000**; passivo 2.000 e patrimonio netto iniziale 80.000 + risultato 19.000 quadrano allo stesso importo. L'acquisto da 30.000 riduce subito la cassa, mentre il costo economico dell'anno è 6.000: questo è il punto che la prova verifica.

**Nota istruttoria attesa.** Indicare documenti di acquisto, entrata in uso e vita utile; contratto del servizio anticipato e periodo coperto; evidenza dei servizi da fatturare; prospetto degli assestamenti e riconciliazione. Il caso insegna la distinzione tra competenza e cassa, non fornisce coefficienti ufficiali di ammortamento del CNR.
''',
(5,3):'''**Interesse interferente e astensione.** Ai sensi dell'articolo 7 del D.P.R. 62/2013, il dipendente si astiene dalle decisioni o attività che possono coinvolgere interessi propri e le altre relazioni previste dalla disposizione; opera inoltre l'astensione per gravi ragioni di convenienza. Sull'astensione decide il responsabile dell'ufficio. Nel caso di una fornitura proposta dall'impresa di un familiare, non basta dichiarare che il prezzo è vantaggioso: si rende nota la relazione attraverso il canale previsto e si gestisce l'astensione, documentando la sostituzione o le misure decise. La qualità tecnica del prodotto e l'imparzialità della procedura sono verifiche diverse.

**La specificità degli acquisti di ricerca.** Il D.Lgs. 218/2016, articolo 10, comma 3, sottrae gli acquisti di beni e servizi funzionalmente destinati alla ricerca alle disposizioni dei primi periodi dei commi 450 e 452 della legge 296/2006. È una deroga delimitata, non un'esenzione generale dal Codice dei contratti, dalla digitalizzazione, dai conflitti o da ogni obbligo Consip. Prima di invocarla si documenta il nesso funzionale del bene con la ricerca e si identifica l'obbligo specifico dal quale si ritiene di essere esonerati. Il rinvio al vecchio D.Lgs. 50/2016 ancora presente nel testo dell'articolo va coordinato con il D.Lgs. 36/2023 e la disciplina transitoria.

**Caso.** L'ufficio deve acquistare reagenti per un esperimento e arredi ordinari per una segreteria. Non estende automaticamente ai secondi una deroga motivata per i primi; verifica per ciascun oggetto fonte applicabile, strumenti obbligatori, procedura e documentazione. La dicitura «ente di ricerca» sulla carta intestata non è una motivazione sufficiente.
''',
(5,4):'''**Fascicolo minimo e prova di rimborso.** La richiesta preventiva identifica finalità istituzionale, luogo e date, soggetto, mezzo, costo stimato e risorse; l'autorizzazione deriva dal soggetto competente. Il fascicolo finale collega ordine autorizzato, attività svolta, titoli di viaggio, documenti delle spese, eventuali anticipi e dichiarazioni su rimborsi ricevuti da terzi. Ogni ente specifica moduli, firme, limiti e modalità: i dati seguenti sono condizioni dell'esercizio.

**Traccia.** La missione è autorizzata per il 10–11 maggio; la regola fornita ammette il treno documentato e il pernottamento necessario entro 120 euro, esclude consumazioni del minibar e vieta il doppio rimborso. Sono prodotti biglietto da 80 euro, fattura dell'albergo da 110 e addebito separato minibar da 15. Il dipendente ha ricevuto un anticipo di 100 euro. Tutte le altre condizioni sono regolari. Calcola saldo e motivazione.

**Soluzione.** Spesa ammessa: 80 + 110 = **190 euro**; minibar escluso: **15 euro**; saldo da liquidare dopo l'anticipo: 190 − 100 = **90 euro**. Si annotano esclusione e riconciliazione dell'anticipo, conservando i documenti. Pagare 190 oltre all'anticipo produrrebbe un indebito maggior rimborso. Se manca il titolo di viaggio, non si crea una ricevuta: si verifica la possibilità di integrazione documentale secondo la disciplina applicabile. I 120 euro non sono un massimale nazionale insegnato dal manuale.
''',
(9,3):'''**La regola italiana sulle invenzioni universitarie e degli EPR.** L'articolo 65 del Codice della proprietà industriale, D.Lgs. 30/2005, nel testo vigente verificato il 3 ottobre 2026, attribuisce alla struttura di appartenenza i diritti sull'invenzione industriale conseguita nell'esecuzione dei rapporti indicati dalla norma con università, enti pubblici di ricerca e IRCCS. All'inventore resta il diritto a essere riconosciuto autore. Non si confonde questo riconoscimento con la titolarità economica del brevetto, né si estende automaticamente la disciplina a ogni articolo, software o banca dati.

L'inventore comunica l'invenzione alla struttura; entrambi preservano la novità. Dalla ricezione della comunicazione decorrono **sei mesi** nei quali la struttura deposita la domanda oppure comunica il disinteresse. Può prolungare il termine al massimo di **tre mesi**, previa comunicazione all'inventore, soltanto per completare valutazioni tecniche avviate immediatamente dopo la comunicazione. Se non deposita entro il termine applicabile o comunica il disinteresse, l'inventore può procedere autonomamente. Omettere la comunicazione non permette di appropriarsi liberamente del risultato.

Se partecipano inventori di più strutture, i diritti spettano alle strutture in parti uguali salvo diversa pattuizione. Per la ricerca finanziata in tutto o in parte da terzi intervengono gli accordi previsti dal comma 5: occorre leggerli, senza assumere né che il finanziatore possieda tutto né che sia estraneo ai diritti. La policy locale organizza comunicazione, valutazione e incentivi entro il quadro legislativo.

**Prima domanda: il risultato è brevettabile?** Un'invenzione deve costituire una soluzione tecnica nuova, implicare attività inventiva e avere applicazione industriale. «Nuova» significa non già compresa nello stato della tecnica; «inventiva» significa non evidente per l'esperto del ramo; «industriale» significa fabbricabile o utilizzabile in un'attività industriale, anche agricola. Scoperta scientifica e programma per elaboratore in quanto tale rientrano nelle esclusioni previste: utilità o prestigio della ricerca non bastano. La divulgazione in un convegno prima del deposito può compromettere la novità, perciò la comunicazione interna e il coordinamento dei tempi hanno una funzione concreta.
''',
(9,4):'''La **licenza** consente a un altro soggetto di usare o sfruttare un diritto entro i limiti convenuti, conservandone la titolarità al licenziante. Può essere esclusiva oppure non esclusiva e delimitare territorio, settore d'uso, durata, corrispettivi e obblighi di sviluppo. La **cessione** trasferisce invece la titolarità del diritto ceduto. Non è una distinzione soltanto nominale: dopo una cessione l'ente non conserva automaticamente gli stessi poteri che avrebbe con una licenza non esclusiva.

**Caso risolto.** L'EPR vuole mantenere la titolarità di un brevetto e consentire a due imprese di usarlo in ambiti compatibili. L'ipotesi coerente è una licenza non esclusiva, verificando diritti di terzi, accordi preesistenti e condizioni economiche. Se un'impresa chiede di acquisire il diritto, si tratta di valutare una cessione, con atto e competenze pertinenti. La parola «collaborazione» sul contratto non risolve da sola la questione: si leggono le clausole sugli asset e sui diritti.
'''}
for cap in sorted({c for c,n in blocks}):
 p=next(B.glob(f'{cap:02}-*.md'));t=p.read_text(encoding='utf8')
 for (c,n),block in blocks.items():
  if c==cap:t=re.sub(rf'(^### N-IR03-{cap:02}-{n:02}[^\n]*\n)',lambda m:m[1]+'\n'+block+'\n',t,count=1,flags=re.M)
 t=re.sub(r'^updated_at:.*$','updated_at: 2026-10-03',t,flags=re.M).replace('draft_stage: text_frozen','draft_stage: correction-in-progress').replace('review_required: false','review_required: true').replace('titolo:','title:')
 p.write_text(t,encoding='utf8')
p=next(B.glob('01-*.md'));t=p.read_text(encoding='utf8').replace('Regolamento UE 2018/1046, finanziario','Regolamento (UE, Euratom) 2024/2509, finanziario, applicabile dal 30 settembre 2024 e sostitutivo del 2018/1046');p.write_text(t,encoding='utf8')
print('IR03 blocco giuridico e contabile applicato')
