from pathlib import Path
import re,hashlib,shutil
A=Path('artifacts/correzioni-collana-2026-10-02');R=Path('wiki/raw/correzioni-collana-2026-10-02')
def append(slug,delta,names):
 p=Path('wiki/sources')/(slug+'.md');t=p.read_text(encoding='utf8')+'\n'+delta+'\n'
 for name in names:
  if not (R/name).exists():shutil.copyfile(A/name,R/name)
  t+=f'- `raw/correzioni-collana-2026-10-02/{name}` — SHA256 {hashlib.sha256((R/name).read_bytes()).hexdigest()}.\n'
 p.write_text(re.sub(r'^updated_at:.*$','updated_at: 2026-10-03',t,flags=re.M),encoding='utf8')
append('fonti-ufficiali-m-ir03-enti-ricerca-2026-07-24','''## Consolidamento puntuale del 3 ottobre 2026

Questa integrazione supera i rinvii generici del precedente quadro per i contenuti qui elencati. Non attesta la lettura integrale di tutti i regolamenti degli EPR.

Normattiva, D.Lgs. 213/2009 art. 1 e D.Lgs. 218/2016 artt. 1–3 e 10, testi correnti letti integralmente: https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2009-12-31;213~art1!vig= ; https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2016-11-25;218~art1!vig= (analogamente art2, art3, art10). Il primo riordino riguarda gli enti vigilati dal ministero dell'istruzione, università e ricerca; il secondo include gli enti nominativamente elencati nell'art. 1, anche con vigilanza diversa, salvando discipline speciali. L'art. 2 tutela libertà scientifica, diffusione dei risultati, mobilità, formazione e partecipazione, insieme a responsabilità etiche, finanziarie, sicurezza, dati e verificabilità. L'art. 3 riconosce autonomia statutaria/regolamentare in raccordo con missione, indirizzi e norme generali. L'art. 10 prevede contabilità economico-patrimoniale con regolamento; il comma 3 deroga soltanto ai primi periodi dei commi 450 e 452 L. 296/2006 per beni/servizi funzionali alla ricerca. Non è esenzione generale dal codice dei contratti o dagli altri obblighi di acquisto. Il richiamo testuale al D.Lgs. 50/2016 va coordinato con la successione al D.Lgs. 36/2023, non insegnato come codice corrente. Raccordo con [[sources/vol-09-consip-strumenti-obblighi-2026-10-03]].

Due statuti identificati: CNR, provvedimento 93/2018, PDF https://www.cnr.it/sites/default/files/public/media/amministrazione_trasparente/Provvedimento_93-2018.pdf , letti artt. 4–12, pagine PDF 4–10; pagina vigente https://www.cnr.it/it/statuto . Distinte funzioni di presidente, CdA, consiglio scientifico, revisori e direttore generale; il parere scientifico non approva il bilancio. ISTAT, statuto 2017 modificato nel 2019, https://www.istat.it/it/files/2017/02/STATUTO-ISTAT.pdf , letti artt. 1, 3, 6–8, PDF 1–2 e 6–9. Vigilanza della Presidenza del Consiglio e indipendenza professionale della statistica; organi presidente, consiglio, COMSTAT, revisori. Non trasferire il consiglio scientifico CNR all'ISTAT.

Profili: CCNL Istruzione e ricerca 2022–2024, firmato il 23 dicembre 2025, tabelle C2/C4, PDF 57/59 della raw ARAN già acquisita. Livelli I dirigente di ricerca/dirigente tecnologo, II primo ricercatore/primo tecnologo, III ricercatore/tecnologo. Per declaratorie funzionali II/III letto allegato 1, PDF 4–5, dell'avviso CREA 2022: https://www.crea.gov.it/documents/20126/0/Avviso%2Bmobilit%C3%A0%2Bprofili_RIC_TEC_2022.pdf/12e4211c-cdfb-13f7-7bfd-c09419dca4c3?download=true&t=1647508340483&version=1.0 . Riproduce il riferimento al DPR 171/1991: ricercatore orientato ad avanzamenti delle conoscenze; tecnologo a funzioni tecniche/professionali, progettazione e gestione, con autonomia/coordinamento crescente nel II livello. Non importare requisiti o termini dell'avviso storico in bandi attuali. Il supporto grant è funzione, non quarto profilo contrattuale uniforme. Il tentativo di lettura diretta dell'allegato DPR ha restituito sessione scaduta e non è citato come documento letto.

CNR, regolamento amministrazione, contabilità e finanza, provvedimento 201/2024 vigente dal 1° gennaio 2025: https://www.cnr.it/sites/default/files/public/media/doc_istituzionali/201.pdf ; conferma https://www.cnr.it/it/regolamenti . Letti PDF 6, 8–12, 18–20, 23–24 (artt. 2, 6–16, 25–30, 40–44 nei passaggi usati). Bilancio annuale autorizzatorio: budget economico/investimenti e nota; triennale economico/investimenti; consuntivo: SP, CE e nota, con rendiconto dei flussi e ulteriori documenti. DG predispone, presidente presenta, CdA approva dopo pareri/relazioni pertinenti. Art. 25 distingue ammortamenti, storni e integrazioni: esempi didattici possono usare ipotesi esplicite di vita utile, quota temporale e assenza di IVA; non attribuire coefficienti inventati al CNR. Controlli di revisori, OIV, Corte dei conti, internal audit e controllo di gestione hanno oggetti distinti.

Regolamento finanziario UE: 2024/2509, artt. 279–280, abroga 2018/1046 ed è applicabile dal 30 settembre 2024. Letta pagina PDF 196 della GU (copia istituzionale https://www.regione.marche.it/portals/0/Europa_Estero/Fondi%20europei/FSE/FSE%2B%2021-27/REG%202024-2509%20R%20FINANZIARIO.pdf ; riferimento primario https://eur-lex.europa.eu/eli/reg/2024/2509/oj ). Restano da distinguere disciplina generale e singolo grant; non dedurre rimborso a costi effettivi per ogni azione. Forme AGA e PNRR già consolidate in [[sources/grant-management-horizon-pnrr-2026-08-23]].

Missioni: le simulazioni aggiunte usano condizioni dichiarate nella traccia, senza soglie o firmatari presentati come regola di tutti gli EPR. La pagina CNR della riunione 21 gennaio 2025 conferma aggiornamento manuale, ma il PDF richiesto ha restituito pagina non trovata: escluso dalle fonti consolidate. Conflitto e astensione si raccordano al DPR 62/2013 art. 7 e al codice locale; non occorre attendere danno effettivo per gestire l'interesse interferente.

Collegamenti: [[topics/m-ir03-enti-ricerca-fonti-e-profili]], [[entities/consiglio-nazionale-ricerche]], [[books/moduli/m-ir03-enti-ricerca/index]].
''',['dlgs213-art1-current.html','dlgs218-art1-current.html','dlgs218-art2-current.html','dlgs218-art3-current.html','dlgs218-art10-current.html','cnr-statuto-2018.pdf','istat-statuto-2019.pdf','crea-profili-2022.pdf','cnr-rafc-2025.pdf'])
append('proprieta-intellettuale-trasferimento-2026-08-22','''## Articolo 65 e requisiti di brevetto — controllo del 3 ottobre 2026

Letto integralmente l'art. 65 CPI corrente: https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2005-02-10;30~art65!vig= . Per invenzioni industriali conseguite nell'esecuzione dei rapporti descritti con università, EPR e IRCCS i diritti spettano alla struttura, salvo diritto dell'inventore a essere riconosciuto autore; più strutture hanno quote uguali salvo accordo. Inventore comunica e parti preservano novità. La struttura ha sei mesi dalla comunicazione per depositare o dichiarare disinteresse; proroga massima tre mesi con preventiva comunicazione solo per completare valutazioni tecniche avviate immediatamente. Mancato deposito nel termine o disinteresse consentono deposito autonomo; comunicazione omessa non legittima appropriazione automatica. Ricerca finanziata da terzi in tutto o parte: accordi secondo comma 5. Non estendere la disciplina brevettuale a ogni software, dato o articolo.

UIBM, guida domande di brevetto, https://uibm.mise.gov.it/images/guidabrevetti_new.pdf , lette pp. 2–3: soluzione tecnica nuova, attività inventiva non ovvia per esperto, applicabilità industriale; esclusioni art. 45, scoperte/teorie/programmi in quanto tali. La novità si valuta rispetto a ciò che è stato accessibile al pubblico; una presentazione prima del deposito può comprometterla. Guida utilizzata solo per requisiti, non per tariffe o titolarità riformata. Licenza autorizza uso nei limiti contrattuali conservando titolarità; cessione trasferisce il diritto. Rimangono verifiche su diritti di terzi, territorio, esclusiva, durata, corrispettivo e obblighi di sviluppo.

Collegamenti: [[topics/m-ir03-enti-ricerca-fonti-e-profili]], [[books/moduli/m-ir03-enti-ricerca/chapters/09-proprieta-intellettuale-trasferimento]].
''',['cpi-art65-current.html','uibm-guida-brevetti.pdf'])
append('integrita-pubblicazioni-ricerca-2026-08-22','''## Bibliometria — integrazione del 3 ottobre 2026

Hirsch, *An index to quantify an individual's scientific research output* (2005), abstract e definizione originali https://arxiv.org/abs/physics/0508025 . h è il massimo intero per cui almeno h lavori hanno almeno h citazioni ciascuno. Dataset didattico 18, 11, 7, 4, 3, 1: h=4; il quinto ha tre citazioni. Somma=44 e media circa 7,33 sono indicatori differenti. Sensibilità a banca dati, omonimie, periodo, anzianità, disciplina e coautorialità impedisce equiparazione automatica a qualità o merito; nessuna soglia concorsuale universale. Il caso è originale, non dati di una persona reale. Collegamento [[books/moduli/m-ir03-enti-ricerca/chapters/07-pubblicazioni-valutazione-integrita]].
''',['hirsch-hindex.html'])
print('IR03 fonti consolidate')
