from pathlib import Path
import re,json
B=Path('wiki/books/moduli/m-ir03-enti-ricerca/chapters');A=Path('artifacts/correzioni-collana-2026-10-02');arc=Path('wiki/reviews/correzioni-collana-2026-10-02/archive');arc.mkdir(exist_ok=True)
# Stem, four options, zero-based key, reasoning. Cases outside quizzes remain.
Q={
1:[
('Un bando richiede una nota sulla regolarità di una spesa di progetto. Quale apporto è prioritario?',['Ricercatore: formulare la domanda sperimentale','Amministrativo: ricostruire presupposti, documenti e proposta','Tecnologo: definire il collaudo della piattaforma','Supporto grant: riscrivere unilateralmente l’accordo'],1,'Il verbo della traccia e il documento atteso individuano l’istruttoria amministrativa; il contesto scientifico non cambia il potere richiesto.'),
('Quale documento stabilisce requisiti e prove della selezione concreta?',['Il bando vigente con allegati e avvisi pertinenti','Lo statuto, anche per tutti i titoli di accesso','Un avviso rappresentativo dello stesso profilo','Il programma strategico triennale dell’ente'],0,'Statuto e programmazione orientano il contesto; la lex specialis della procedura assegna requisiti e prove.'),
('Il regolamento finanziario UE che ha sostituito il 2018/1046 è:',['Il regolamento 2021/695 sul programma Horizon','Il regolamento 2021/241 sul dispositivo RRF','Il regolamento 2024/2509','Il regolamento 2016/679'],2,'Il 2024/2509 è il regolamento finanziario generale, applicabile dal 30 settembre 2024; programma, RRF e dati hanno oggetti distinti.'),
('Un ufficio si chiama «grant support». Il nome consente di dedurre:',['Il livello contrattuale III','La laurea richiesta in ogni selezione','Il potere di approvare modifiche contrattuali','La funzione, da collegare al profilo formale del bando'],3,'La funzione non crea da sola profilo, livello, requisiti o poteri uniformi.'),
('Un bando di tecnologo riguarda infrastrutture di dati. Quale preparazione è più pertinente?',['Soltanto bibliometria delle pubblicazioni','Requisiti, qualità dei dati, continuità, test e documentazione','Soltanto ordinamento didattico universitario','Esclusivamente redazione delle determine'],1,'La specialità del bando orienta il lavoro tecnico; gli altri ambiti possono concorrere ma non sostituiscono il nucleo richiesto.'),
('Quale affermazione descrive correttamente il quadro degli EPR?',['Tutti sono vigilati dal MUR','L’autonomia elimina i controlli esterni','Missione, vigilanza e ordinamento si ricostruiscono per ente','Le università e gli EPR hanno gli stessi organi'],2,'Il settore contiene enti con missioni e vigilanze differenti; occorre integrare fonti nazionali e atti del singolo ente.')],
2:[
('Il D.Lgs. 213/2009 e il D.Lgs. 218/2016 hanno:',['Ambiti coincidenti per ogni ente pubblico','Rispettivamente perimetro del riordino degli enti vigilati dal ministero e ambito degli enti elencati nel 218','Il primo solo norme finanziarie e il secondo solo scientifiche','Ambiti limitati alle università statali'],1,'Il 218 include enti con vigilanze diverse; non si estende automaticamente ogni disposizione del 213 a tutti.'),
('Nel CNR un parere del consiglio scientifico sul bilancio sostituisce la deliberazione di:',['Presidente','Collegio dei revisori','CdA','Nessuno: il parere non sostituisce l’approvazione'],3,'Il CdA approva il bilancio; il consiglio scientifico esprime il proprio apporto negli aspetti di competenza.'),
('Nell’ISTAT il COMSTAT si collega soprattutto:',['Al coordinamento dell’informazione statistica','Al collaudo dei beni inventariati','Alla revisione delle singole fatture','Alla rappresentanza legale del CNR'],0,'La sua funzione è propria dell’assetto della statistica ufficiale e non coincide con il consiglio scientifico di un altro ente.'),
('L’autonomia scientifica permette di:',['Ignorare i limiti del finanziamento','Omettere risultati negativi non graditi','Scegliere metodi motivati nel rispetto di integrità e vincoli applicabili','Attribuire spese a un progetto senza documentazione'],2,'Libertà di ricerca e responsabilità procedono insieme; nessuna delle altre condotte deriva dall’autonomia.'),
('Una disposizione locale contrasta con una norma superiore applicabile. Quale criterio è corretto?',['La norma locale prevale perché più vicina al caso','Si ricostruisce il contrasto e si applica la gerarchia pertinente','Si sceglie il testo pubblicato più recentemente, senza altro controllo','Si elimina il contrasto omettendo entrambe le fonti'],1,'Autonomia statutaria e regolamentare opera entro il quadro legislativo; data e prossimità non bastano a stabilire prevalenza.'),
('Chi predispone i documenti di bilancio CNR nell’assetto esaminato?',['Il COMSTAT','Il solo responsabile del progetto interessato','Il direttore generale, nel procedimento previsto','Il consiglio scientifico al posto degli uffici'],2,'Predisposizione gestionale e approvazione del CdA sono fasi distinte, con presentazione del presidente e controlli pertinenti.')],
3:[
('L’ordine dei livelli di ricercatore è:',['I ricercatore, II primo, III dirigente','III ricercatore, II primo, I dirigente','III primo, II ricercatore, I dirigente','II ricercatore e III dirigente'],1,'Il livello III è ricercatore; il II primo ricercatore; il I dirigente di ricerca.'),
('La denominazione di primo tecnologo corrisponde al livello:',['I','III','IV','II'],3,'Il II livello identifica primo tecnologo; dirigente tecnologo è il I.'),
('Quale attività dimostra più direttamente apporto scientifico?',['Formulare e verificare una domanda con metodo e interpretazione motivati','Apporre una firma contabile senza esaminare dati','Gestire soltanto l’invio delle convocazioni','Contare il numero totale di dipendenti del gruppo'],0,'La ricerca richiede contributo conoscitivo documentato; le altre attività possono essere utili ma non provano quel contributo.'),
('Un’attività di progettazione autonoma e gestione tecnico-professionale è coerente con:',['Una funzione esclusivamente di protocollo','Il solo ruolo di revisore contabile','Il percorso del tecnologo, secondo livello e area','Un incarico necessariamente esterno all’EPR'],2,'Le declaratorie tecnologiche comprendono progettazione, elaborazione e gestione; il bando ne precisa il campo.'),
('Un candidato legge un requisito nell’avviso CREA 2022. Per un concorso del 2026 deve:',['Assumerlo vigente per ogni EPR','Controllare bando e disciplina attuali della nuova procedura','Applicarlo solo perché il profilo ha lo stesso nome','Trasferire anche scadenza e modalità di domanda'],1,'Il documento storico aiuta a capire funzioni e lessico; non stabilisce automaticamente requisiti di una nuova selezione.'),
('Profilo e struttura organizzativa si distinguono perché:',['Il profilo è sempre un ufficio','La struttura coincide sempre con un solo livello','La struttura coordina attività e persone, anche di profili diversi','Il profilo indica la sede geografica'],2,'Un laboratorio o ufficio può integrare ricercatori, tecnologi e amministrativi senza annullarne i diversi apporti.')],
4:[
('Nel caso contabile la cassa finale è:',['101.000 euro','19.000 euro','68.000 euro','80.000 euro'],2,'80.000 + 50.000 − 20.000 − 30.000 − 12.000 = 68.000; cassa, attivo e risultato sono grandezze distinte.'),
('Il macchinario da 30.000 euro, cinque anni, genera nella traccia un costo annuo di:',['6.000 euro','30.000 euro','24.000 euro','5.000 euro'],0,'La quota lineare assegnata è 30.000/5; 24.000 è il valore netto finale, non il costo dell’anno.'),
('Il servizio da 12.000 euro pagato il 1° ottobre per dodici mesi determina al 31 dicembre:',['Costo 12.000, nessun risconto','Costo 9.000, risconto 3.000','Rateo passivo 9.000','Costo 3.000, risconto attivo 9.000'],3,'Tre mesi competono all’anno e nove al successivo; la manifestazione finanziaria è già avvenuta.'),
('Servizi già completamente ricevuti, da fatturare, richiedono:',['Omissione fino al pagamento','Costo e debito per fatture da ricevere','Risconto attivo per l’intero importo','Ammortamento della fattura'],1,'La prestazione maturata genera costo e debito; non si qualifica automaticamente come rateo temporale.'),
('Il risultato economico del caso è:',['68.000 euro','21.000 euro','19.000 euro','101.000 euro'],2,'50.000 − 20.000 − 6.000 − 3.000 − 2.000 = 19.000. Omettere il costo da fatturare darebbe 21.000.'),
('Nel CNR il bilancio annuale autorizzatorio comprende:',['Budget economico e degli investimenti con nota illustrativa','Solo movimenti di cassa effettivi','Solo stato patrimoniale e conto economico consuntivi','Solo il rendiconto di ogni grant'],0,'Il preventivo programma e autorizza; il consuntivo e i rendiconti di progetto hanno funzioni diverse.')],
5:[
('Nel caso missione, dopo l’anticipo di 100 euro, il saldo corretto è:',['105 euro','190 euro','205 euro','90 euro'],3,'80 + 110 = 190 ammissibili; escluso minibar 15; sottratto l’anticipo 100 resta 90.'),
('Il dipendente istruisce l’acquisto da un’impresa legata a un interesse familiare. Deve:',['Attendere un danno economico provato','Segnalare la situazione e gestire l’astensione secondo la disciplina','Limitarsi a scegliere il preventivo più basso','Omettere la relazione se il prodotto è scientificamente valido'],1,'Il conflitto riguarda imparzialità, distinta dal prezzo o dalla validità tecnica; il responsabile decide sull’astensione.'),
('La deroga dell’art. 10, comma 3, D.Lgs. 218/2016 riguarda:',['Ogni contratto di qualsiasi EPR','Tutte le forniture informatiche senza condizioni','Specifiche disposizioni per beni e servizi funzionali alla ricerca','Solo le missioni all’estero'],2,'Il rinvio è delimitato ai primi periodi dei commi 450 e 452 L. 296/2006; non cancella codice e altri obblighi.'),
('Quale formulazione è un rilievo di audit verificabile?',['Tre fascicoli privi della prova richiesta dal criterio X; integrare e controllare il processo','L’ufficio lavora male','La pratica sembra sospetta','Occorre maggiore attenzione'],0,'Fatto, criterio e azione rendono verificabile il rilievo; le altre formule non localizzano la non conformità.'),
('Un anticipo di missione è:',['Un rimborso aggiuntivo da non riconciliare','Una prova del costo finale sostenuto','Una somma da riconciliare con il trattamento spettante','Un’autorizzazione per ogni spesa successiva'],2,'Il saldo considera quanto già anticipato; l’anticipo non dimostra ammissibilità né amplia la missione.'),
('Manca un documento di spesa previsto. La prima azione è:',['Ricostruire una ricevuta plausibile','Verificare la lacuna e l’integrazione consentita senza attestare fatti falsi','Approvare perché la missione era autorizzata','Escludere tutte le missioni dello stesso dipendente'],1,'Autorizzazione e prova della spesa sono distinte; l’esito dipende dalla possibilità di integrazione e dalle regole applicabili.')],
6:[
('La proposta sceglie Python, non indicato dalla traccia. È corretto se:',['Lo presenta come strumento proposto e ne verifica fattibilità','Dichiara che l’ente lo usa senza riscontro','Attribuisce risultati già prodotti dallo script non eseguito','Omette ogni motivazione'],0,'Una scelta progettuale esplicita è lecita; inventare infrastrutture disponibili o risultati è altra cosa.'),
('Nel mini-progetto i 600 record sono:',['Una stima scelta dal candidato','Un risultato dell’analisi','Un dato fornito dalla traccia','La soglia minima nazionale di validità'],2,'La traccia assegna 600 record; la proposta deve distinguere questo fatto dalle scelte di metodo.'),
('Il controllo indipendente di 60 record:',['Sostituisce automaticamente l’analisi dell’intero dataset','È una scelta proposta da motivare, senza garanzia automatica di rappresentatività','Dimostra da solo assenza di errori nei restanti 540','Costituisce un obbligo normativo'],1,'La numerosità serve all’obiettivo di verifica dichiarato; inferenze statistiche ulteriori richiederebbero un disegno adeguato.'),
('Una misura ha unità sconosciuta. Il piano corretto prevede:',['Assegnare l’unità più comune','Conservare il numero e cancellare il campo unità','Convertire direttamente tutti i valori','Segnalare e chiarire prima del confronto'],3,'Senza unità non è giustificato confrontare o convertire; la lacuna va conservata e gestita.'),
('Dataset curato e dizionario sono:',['Output del progetto','Impatto sociale già dimostrato','Prova di causalità ambientale','Requisiti di accesso al concorso'],0,'Sono prodotti consegnabili. Gli effetti più ampi richiedono altre evidenze e non si deducono dalla consegna.'),
('Quale conclusione rispetta i limiti della proposta?',['Le anomalie sono sicuramente causate dal produttore','I sensori di ogni territorio hanno gli stessi problemi','I risultati riguardano sensori e periodo osservati','La pulizia dimostra correttezza fisica di ogni misura'],2,'Il perimetro dei dati limita l’inferenza; qualità informatica e accuratezza fisica non coincidono.')],
7:[
('Per citazioni 18, 11, 7, 4, 3, 1, h vale:',['3','4','6','7'],1,'Quattro lavori hanno almeno quattro citazioni; non ce ne sono cinque con almeno cinque.'),
('Se solo il primo lavoro passa da 18 a 100 citazioni, h:',['Diventa 5','Diventa 6','Diventa 100','Resta 4'],3,'Il numero di lavori che supera le soglie determinanti non cambia.'),
('Due h-index ottenuti da banche dati diverse sono:',['Da interpretare considerando copertura, identità e data','Sempre direttamente confrontabili','Prova di errore se non coincidono','Equivalenti al giudizio dei commissari'],0,'Le fonti possono indicizzare prodotti e citazioni diversi; occorre ricostruire il criterio.'),
('Una segnalazione documentata di figura alterata richiede:',['Ritrattazione automatica senza verifica','Accertamento informale della commissione concorsuale','Preservazione delle evidenze e attivazione del canale competente','Eliminazione del file originale'],2,'Segnalazione e accertamento sono fasi distinte; conservare versioni tutela la ricostruzione e le garanzie.'),
('Un errore circoscritto che non compromette i risultati può richiedere:',['Sempre ritrattazione integrale','Una correzione motivata secondo le regole della sede','Cancellazione di ogni versione','Nessuna comunicazione perché involontario'],1,'La misura dipende dall’effetto sull’affidabilità; intenzionalità e ampiezza sono questioni distinte.'),
('La peer review:',['Certifica definitivamente ogni dato originale','Trasferisce agli editori tutta la responsabilità degli autori','È valutazione critica utile, con limiti e possibilità di correzione','Rende superfluo conservare metodi e dati'],2,'Il controllo non è infallibile e non sostituisce tracciabilità o responsabilità dei partecipanti.')],
8:[
('Il test importa 975 validi in 45 secondi su 980 attesi. L’esito è:',['Positivo per la velocità','Negativo per perdita di record validi','Positivo se il file finale si apre','Non valutabile nonostante i requisiti assegnati'],1,'La completezza è requisito autonomo; il rispetto del tempo non compensa cinque validi mancanti.'),
('980 validi importati e 20 scarti corretti in 70 secondi:',['Supera tutti i requisiti','Fallisce la completezza','Fallisce il requisito temporale','Dimostra errore nel dataset'],2,'I conteggi sono corretti, ma la soglia didattica è 60 secondi.'),
('La validazione valuta:',['Idoneità all’uso previsto','Soltanto la presenza di un identificativo','Soltanto la durata di un test','La correttezza del bando di concorso'],0,'La verifica confronta con specifiche; la validazione esamina l’adeguatezza per utenti e impiego.'),
('Dopo una modifica al parser è necessario:',['Testare solo la schermata iniziale','Eliminare il log precedente','Cambiare la soglia per adeguarla al risultato','Ripetere prove pertinenti e controlli di regressione'],3,'Una correzione può alterare casi già funzionanti: serve evidenza sulla nuova versione.'),
('Un checksum permette di controllare:',['La verità scientifica della misura','L’integrità rispetto al file di riferimento','L’assenza di ogni errore di campionamento','La conformità automatica al GDPR'],1,'La corrispondenza binaria non dimostra validità scientifica, metodo o liceità.'),
('Il verbale deve collegare:',['Marca del prodotto e soddisfazione generica','Solo data e firma','Requisito, prova, risultato, scostamento e azione','Solo il numero dei documenti allegati'],2,'La catena rende ricostruibile l’esito e permette la riprova dopo la correzione.')],
9:[
('Nel perimetro dell’art. 65 CPI, i diritti sull’invenzione spettano di regola:',['Alla struttura, con riconoscimento dell’inventore','Sempre all’autore dell’articolo','Sempre al finanziatore esterno','Al primo soggetto che pubblica un abstract'],0,'Titolarità patrimoniale e diritto dell’inventore a essere riconosciuto autore sono distinti; accordi e casi del comma 5 vanno considerati.'),
('La struttura riceve la comunicazione. Il termine ordinario per il deposito è:',['Tre mesi','Dodici mesi','Sei mesi','Trenta giorni'],2,'L’art. 65 prevede sei mesi e una proroga circoscritta, non un termine generale di dodici.'),
('La proroga massima di tre mesi serve:',['A rinviare liberamente la decisione','A completare valutazioni tecniche avviate immediatamente, con previa comunicazione','A evitare la comunicazione all’inventore','A sanare qualsiasi divulgazione già avvenuta'],1,'La proroga ha condizioni specifiche; non è disponibilità indiscriminata del tempo.'),
('Con una licenza non esclusiva il titolare:',['Trasferisce necessariamente il brevetto','Perde ogni facoltà di sfruttamento','Cede automaticamente la proprietà al licenziatario','Autorizza l’uso nei limiti pattuiti mantenendo il diritto'],3,'La cessione trasferisce titolarità; la licenza disciplina facoltà d’uso e può consentire più licenziatari.'),
('Per attività inventiva si intende:',['Qualunque idea utile','Una soluzione non evidente per l’esperto del ramo rispetto allo stato della tecnica','La pubblicazione su una rivista citata','La sola applicazione industriale'],1,'Novità, non ovvietà e applicabilità industriale sono requisiti distinti.'),
('Un risultato è finanziato in parte da un’impresa. Occorre:',['Attribuire sempre tutto all’impresa','Ignorare il finanziamento se l’inventore è dipendente','Leggere gli accordi pertinenti nel quadro dell’art. 65, comma 5','Considerare sufficiente l’elenco degli autori'],2,'Il finanziamento da terzi richiede valutazione contrattuale; nessuno degli automatismi proposti è corretto.')],
10:[
('FAIR Accessible ammette:',['Autenticazione e autorizzazione quando necessarie','Solo download anonimo','Protocollo non documentato scelto informalmente','Assenza di identificatori'],0,'Il protocollo standardizzato può includere controllo degli accessi; FAIR non impone indiscriminata apertura.'),
('Un DOI con file privo di unità e licenza:',['Garantisce riuso corretto','Rende superfluo il dizionario','Aiuta la reperibilità ma non completa la riusabilità','Autorizza ogni uso commerciale'],2,'Identificatore, significato e diritti svolgono funzioni diverse.'),
('Nel DMP del caso, cinque anni di conservazione sono:',['La durata obbligatoria di ogni dato scientifico','Un termine assegnato dalla simulazione','La durata del brevetto','Una conseguenza automatica della licenza CC BY'],1,'Il termine del caso non si generalizza a progetti, dati o norme diversi.'),
('Un partner invia un file soggetto a restrizioni. Il referente deve:',['Includerlo automaticamente nel deposito aperto','Cambiarne nome per rimuovere il vincolo','Considerarlo pubblico perché ricevuto per email','Verificare accordi e aggiornare il regime nel DMP'],3,'Ricezione e possesso del file non attribuiscono tutti i diritti di condivisione.'),
('Due colonne «temperatura» senza unità:',['Non garantiscono interoperabilità nonostante il nome uguale','Sono equivalenti se entrambe numeriche','Sono automaticamente convertibili','Non richiedono metadati se il formato è CSV'],0,'Il formato da solo non definisce il significato dei valori e non permette conversioni sicure.'),
('Il DMP va aggiornato quando:',['È assegnato l’identificatore, poi mai più','Cambia soltanto il titolo del progetto','Cambiano dati, ruoli, obblighi o condizioni di accesso','Si chiude il progetto senza riguardo alle variazioni precedenti'],2,'È un piano dinamico che documenta decisioni e responsabilità nel ciclo di vita dei dati.')],
11:[
('35 unità ammesse a 90 euro danno:',['3.050 euro','3.150 euro','3.500 euro','2.400 euro'],1,'Il contributo per la voce unitaria è 35×90, con prova delle unità e delle condizioni del contratto.'),
('Il 15% di 18.000, esclusi 2.000 dalla base, è:',['2.700 euro','3.000 euro','2.400 euro','2.000 euro'],2,'La base ammissibile è 16.000; il tasso non si applica alle componenti escluse.'),
('Un pacchetto lump sum da 25.000 con costo interno 27.000:',['Non aumenta automaticamente a 27.000','Deve sempre diventare 27.000','Va sempre ridotto a zero','Diventa costo unitario'],0,'Il contributo segue attività e condizioni del grant; non la mera somma dei costi interni.'),
('Per le misure RRF, DNSH è:',['Facoltativo per gli enti di ricerca','Richiesto solo se il candidato lo cita','Sostituito dal pagamento delle fatture','Obbligatorio, con verifiche pertinenti alla misura'],3,'La specificità delle evidenze non rende opzionale il principio orizzontale.'),
('210 righe, 12 duplicati e 8 non ammissibili, target 200:',['Target raggiunto con 210','190 validi, scostamento di 10','198 validi, scostamento di 2','200 validi per arrotondamento'],1,'Si eliminano entrambi i gruppi assegnati dalla traccia: 210−12−8=190.'),
('Una variazione di budget può non richiedere amendment se:',['Il responsabile la preferisce','Il saldo del conto è sufficiente','Rientra nella flessibilità e nelle condizioni dell’accordo','Riguarda sempre meno del 10%'],2,'Non esiste qui una soglia inventata universale; bisogna leggere condizioni e impatto sull’azione.')],
12:[
('Con installazione 15–28 giugno, quattro settimane di misure e una di analisi, si arriva:',['Al 2 agosto','Al 31 luglio per definizione','Al 26 luglio','Al 30 settembre'],0,'Misure 29 giugno–26 luglio, analisi 27 luglio–2 agosto: il deliverable del 31 luglio è a rischio.'),
('Il test importa 978 validi in 48 secondi. L’esito assegnato è:',['Conforme perché rapido','Conforme se si omettono due record dal set','Non conforme per due validi mancanti','Positivo con riserva automaticamente'],2,'Il requisito non ammette perdita di validi; l’esito deve descrivere lo scostamento reale.'),
('I tre costi A, B e C superano il controllo temporale per:',['28.000 euro','25.000 euro','20.000 euro','8.000 euro'],1,'A 5.000 e C 20.000 sono nel periodo secondo le clausole; B 3.000 è fuori.'),
('La fattura A del 5 ottobre per attività del 28 settembre è:',['Sempre esclusa perché successiva','Ammessa solo cambiando la data','Non valutabile nonostante la clausola fornita','Compatibile con la clausola sui debiti sorti nel periodo'],3,'La traccia consente fatturazione successiva: non si confondono data della prestazione e del documento.'),
('La proroga del deliverable richiesta e non approvata:',['Va registrata come richiesta, mantenendo distinta la scadenza vigente','È efficace appena inviata','Proroga automaticamente il progetto','Rende ammissibile il servizio B'],0,'Richiesta, approvazione e effetti contrattuali sono diversi; la modifica non si presume.'),
('Per inviare risultati preliminari al partner occorrono, nella traccia:',['Solo l’appartenenza al partenariato','Solo il consenso del tecnologo','Validazione e autorizzazione del responsabile di progetto','Solo l’assenza di dati personali'],2,'Le condizioni derivano dall’accordo assegnato; assenza di dati personali non elimina altri vincoli.')]
}
keys={}
for cap,qs in Q.items():
 p=next(B.glob(f'{cap:02}-*.md'));t=p.read_text(encoding='utf8');before,old=t.split('## ▣ Verifica',1)
 a=arc/f'IR03-{cap:02}-quiz-pre-correzione.md'
 if not a.exists():a.write_text(old,encoding='utf8')
 tail=''
 m=re.search(r'\n(?:\*\*Caso (?:ragionato|finale|di verifica)|## Riferimenti)',old)
 if m:tail=old[m.start():]
 out='## ▣ Verifica\n\n';keys[str(cap)]=[]
 for i,(stem,options,key,why) in enumerate(qs,1):
  letter='ABCD'[key];keys[str(cap)].append(letter)
  out+=f'**Quiz {i}.** {stem}\n\n'+'\n'.join(f'{l}. {o}' for l,o in zip('ABCD',options))+f'\n\n**Risposta corretta: {letter}.** {why}\n\n'
 p.write_text(before+out+tail,encoding='utf8')
(A/'M-IR03-quiz-keys.json').write_text(json.dumps(keys,indent=2),encoding='utf8')
print('72 quiz IR03 sostituiti; preesistenti archiviati')
