from pathlib import Path
import re,json,hashlib
B=Path('wiki/books/moduli/m-ir04-cultura-beni-culturali');A=Path('artifacts/correzioni-collana-2026-10-02');R=Path('wiki/reviews/pipeline/VOL-06');C=Path('wiki/reviews/correzioni-collana-2026-10-02')
entries=[]
for p in sorted((B/'chapters').glob('*.md')):
 t=p.read_text(encoding='utf8');assert 'review_required: false' in t;t=t.replace('draft_stage: specialist-audit-complete','draft_stage: text_frozen');p.write_text(t,encoding='utf8');entries.append({'path':p.as_posix(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'status':'text-freeze','date':'2026-10-03'})
p=B/'index.md';t=p.read_text(encoding='utf8').replace('status: corrections-applied','status: text_frozen').replace('module_status: editorial_revision','module_status: text_frozen').replace('draft_stage: corrections-applied','draft_stage: text_frozen').replace('Stato: correzioni testuali applicate; audit specialistico e nuovo PDF da completare.','Stato: correzioni e audit specialistico testuale conclusi; nuovo PDF da verificare.').replace('Audit specialistico sul testo corretto, text freeze e verifica del nuovo PDF.','Verifica del nuovo PDF e controlli conclusivi del volume.').replace('#M-IR04--Cultura-e-MiC','#M-IR04 — Cultura e MiC');p.write_text(t,encoding='utf8')
p=B/'planning/02-matrice-copertura-didattica.md';t=p.read_text(encoding='utf8').replace('review_required: true','review_required: false');t+='\nStep 15 passato con zero blocker e warning. Il manifest corrente identifica il testo congelato; la verifica del nuovo PDF resta distinta.\n';p.write_text(t,encoding='utf8')
manifest={'volume':'VOL-06','module':'M-IR04','date':'2026-10-03','files':entries,'checks':['13 capitoli, 65 nuclei almeno 600 parole, 78 quiz disciplinari.','Fonti puntuali e versioni dichiarate, casi e chiavi verificati.','Indice e matrice riconciliati, revisione di copertura e stile dei delta conclusa.','Step15 passato con zero blocker e warning.'],'limitations':['Nuovo PDF ancora da verificare.','Verifiche normative e standard selettive, non certificazione integrale.','I casi non sostituiscono un corso completo di ogni specializzazione professionale.']}
(A/'M-IR04-freeze.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf8')
p=R/'16-moduli-m-ir04-cultura-beni-culturali.md';a=C/'archive/pre-correzioni-16-m-ir04.md'
if p.exists() and not a.exists():a.write_bytes(p.read_bytes())
p.write_text('# M-IR04 — Manifest del testo, 3 ottobre 2026\n\nVerifica manuale; esito del gate CLI registrato separatamente.\n\n'+'\n'.join('- '+x for x in manifest['checks'])+'\n\n| File | Stato | Data | SHA-256 |\n| --- | --- | --- | --- |\n'+'\n'.join('| '+x['path']+' | text-freeze | '+x['date']+' | '+x['sha256']+' |' for x in entries)+'\n\n'+' '.join(manifest['limitations'])+'\n',encoding='utf8')
mapping={11:([6,7,8],'ISAD/ISAAR, REICAT/ISBD/UNIMARC/SBNMARC, authority/soggetto/ILL/DD, master/derivati e controllo di integrità con casi. Completa IR02/09 già applicato.'),25:([2],'Assetto a quattro dipartimenti e DG, funzioni territoriali SABAP/archivi/biblioteche e istituti autonomi.'),26:([3,4,5],'Categorie e tutela interinale, verifica/dichiarazione, alienabilità, termini e uscita; art. 21 e soglie art. 65 aggiornati al 2026.'),27:([3,4],'Usi incompatibili qualificati come vietati, distinti dagli interventi autorizzabili.'),28:([6],'Dati catalografici riconosciuti come metadati descrittivi, con altre categorie e caso di collaudo.'),29:([7],'ISAD/ISAAR e scheda multilivello; diplomatica introduttiva, scarto, versamento e consultabilità con caso.'),30:([9,10,11],'US e sequenza stratigrafica risolta, ritrovamento fortuito, scheda Botticelli e art. 29 applicato.'),31:([12],'Eliminata esclusione assoluta della progettazione dalle prove; distinti profilo amministrativo e architetto.'),32:([13],'Obblighi del lavoratore, incarichi degli addetti, piano locale e caso di pericolo con soluzione.'),33:(list(range(1,14)),'Pulizia accenti e formule interne, gerarchie e riferimenti; conteggi effettivi. IR01 preservato legacy, senza falsa promozione al formato 2.'),35:(list(range(1,14)),'Inventario 50 capitoli e apparati effettivi; eliminate appendici inesistenti promesse, rinvii circoscritti a heading verificati, stati allineati alla fase reale.'),36:(list(range(1,14)),'78 quiz IR04 e 72 IR03 con quesiti disciplinari, casi controllabili, chiavi e commenti coerenti.')}
batch={}
for n,(caps,change) in mapping.items():
 files=[next((B/'chapters').glob(f'{c:02}-*.md')).as_posix() for c in caps]
 if n==11:files.append(next(Path('wiki/books/moduli/m-ir02-universita-afam/chapters').glob('09-*.md')).as_posix())
 if n==36:files += [p.as_posix() for p in Path('wiki/books/moduli/m-ir03-enti-ricerca/chapters').glob('*.md')]
 if n==33:files += [p.as_posix() for p in Path('wiki/books/moduli/m-ir01-scuola/chapters').glob('*.md')]
 if n==35:files += [str(p).replace('\\','/') for p in Path('wiki/books/volumi/vol-06-scuola-universita-ricerca-cultura').rglob('*.md') if p.name in ['index.md','00-scheda-pipeline.md','01-indice-analitico.md','04-inventario-apparati-correzioni-2026-10-03.md']]
 files+=['wiki/sources/fonti-ufficiali-m-ir04-cultura-mic-2026-07-24.md','wiki/reviews/pipeline/VOL-06/15-moduli-m-ir04-cultura-beni-culturali.md']
 batch[f'V06-{n:02}']={'change':change,'files':files,'evidence':'Fonti puntuali e limiti dichiarati; chiavi, termini, casi e rinvii riesaminati. Gate 15 passato. Nuovo PDF e controlli di volume ancora necessari.','status':'applicato'}
(A/'VOL-06-batch10.json').write_text(json.dumps(batch,ensure_ascii=False,indent=2),encoding='utf8')
print('IR04 freeze e ultime 12 correzioni VOL06 registrabili')
