from pathlib import Path
import re,json
B=Path('wiki/books/moduli/m-ir04-cultura-beni-culturali');A=Path('artifacts/correzioni-collana-2026-10-02');arc=Path('wiki/reviews/correzioni-collana-2026-10-02/archive/IR04');arc.mkdir(parents=True,exist_ok=True)
source=Path('wiki/sources/fonti-ufficiali-m-ir04-cultura-mic-2026-07-24.md').read_text(encoding='utf8');assert '50.000' in source and 'ISAD(G)' in source
blocks={
(1,1):'''**Scegliere il percorso professionale.** La medesima amministrazione recluta per funzioni diverse. Per un profilo amministrativo il risultato può essere un'istruttoria con competenza, documenti e proposta; per un archivista una descrizione gerarchica e una valutazione documentale; per un bibliotecario un record, una strategia di ricerca e un servizio; per un archeologo una lettura del contesto e una relazione specialistica. Architetti, restauratori e storici dell'arte possono incontrare prove tecniche proprie. La scheda di studio deve quindi riportare denominazione e codice del posto, titolo richiesto, materie, tipo di prova e prodotto atteso: il nome «MiC» non rende equivalenti i programmi.

**Esercizio risolto.** Una traccia chiede di descrivere un fondo con serie e fascicoli: la priorità è il capitolo 7, con ISAD(G), provenienza e consultabilità; il capitolo 5 serve per il regime del bene, ma non sostituisce la descrizione archivistica. Una traccia chiede invece un'istruttoria sul trasferimento di un dipinto tutelato: si parte dal capitolo 5 e si distingue vendita, spostamento, prestito e uscita dal territorio. Per entrambe serve conoscere l'ufficio competente del capitolo 2. Nel piano personale si annota l'output da esercitare, non soltanto il titolo della materia.''',
(2,2):'''**Assetto ministeriale verificato al 3 ottobre 2026.** Il D.P.C.M. 57/2024 e il D.M. 270/2024 organizzano il MiC in quattro dipartimenti. Il Dipartimento per l'amministrazione generale (DiAG) comprende le direzioni generali Risorse umane e organizzazione; Bilancio, programmazione e monitoraggio; Affari europei e internazionali; Digitalizzazione e comunicazione. Il Dipartimento per la tutela del patrimonio culturale (DiT) comprende le direzioni generali Archeologia, belle arti e paesaggio e Archivi; nell'assetto dipartimentale figura anche la Soprintendenza speciale Archeologia, belle arti e paesaggio di Roma. Il Dipartimento per la valorizzazione del patrimonio culturale (DiVA) comprende la Direzione generale Musei e istituti dotati di autonomia speciale. Il Dipartimento per le attività culturali (DiAC) comprende le direzioni generali Spettacolo, Cinema e audiovisivo, Creatività contemporanea, Biblioteche e istituti culturali.

La ripartizione chiarisce perché «cultura» non equivalga soltanto a musei. Il dipartimento coordina ambiti ampi; la direzione generale esercita le attribuzioni del proprio settore; l'ufficio competente firma l'atto previsto dalla disciplina applicabile. Non si attribuisce un'autorizzazione al dipartimento solo perché il suo nome sembra pertinente. In prova conviene nominare funzione e livello organizzativo; i nomi delle persone che ricoprono gli incarichi non sostituiscono le competenze.''',
(2,3):'''**Tre articolazioni da non confondere.** Le Soprintendenze Archeologia, belle arti e paesaggio (SABAP) operano nella tutela territoriale del rispettivo patrimonio e paesaggio. Le Soprintendenze archivistiche e bibliografiche esercitano la tutela sugli archivi pubblici non statali, sugli archivi privati dichiarati e sui beni librari non statali nel territorio di competenza, tenendo conto degli assetti speciali. Gli Archivi di Stato conservano la documentazione statale versata, assicurano studio e consultazione e svolgono le funzioni previste sugli archivi statali correnti e di deposito. Un archivio comunale non diventa perciò un ufficio dell'Archivio di Stato e non viene trasferito automaticamente lì dopo trent'anni.

**Caso.** Il Comune propone lo scarto di fascicoli del proprio archivio; il museo statale progetta una nuova sala; un'amministrazione periferica statale prepara il versamento dei propri affari conclusi. La prima pratica richiede il percorso di tutela archivistica e l'autorizzazione allo scarto; la seconda coinvolge l'istituto museale e le ulteriori competenze di tutela eventualmente interessate; la terza richiede il raccordo con l'Archivio di Stato e le regole di versamento. La parola «periferico» non identifica un'autorità unica per i tre casi.''',
(2,4):'''**Autonomia e tutela restano distinte.** L'autonomia speciale di un museo attribuisce poteri di organizzazione e gestione nei limiti delle norme e dello statuto dell'istituto. Non sottrae il patrimonio al Codice né trasforma il direttore nell'autorità competente per qualsiasi vincolo territoriale. Un museo può programmare una mostra e curarne il progetto scientifico, ma prestiti, lavori su beni tutelati, sicurezza e bilancio seguono le rispettive competenze. La relazione amministrativa deve quindi separare la decisione culturale, l'atto gestionale e il controllo di tutela, indicando chi assume ciascuno.''',
(3,2):'''**Le categorie dell'articolo 10.** Il comma 1 riguarda cose mobili e immobili appartenenti a Stato, Regioni, altri enti pubblici e persone giuridiche private senza fine di lucro, compresi gli enti ecclesiastici civilmente riconosciuti, che presentano interesse artistico, storico, archeologico o etnoantropologico. Il comma 2 qualifica direttamente determinate raccolte pubbliche, archivi e singoli documenti pubblici e raccolte librarie pubbliche, con la specifica eccezione bibliotecaria richiamata dalla disposizione. Per queste categorie la dichiarazione dell'articolo 13 non è necessaria.

Il comma 3 comprende invece categorie per le quali occorre la dichiarazione, fra cui cose di interesse particolarmente importante appartenenti a soggetti diversi da quelli del comma 1, archivi privati di interesse storico particolarmente importante e raccolte librarie private di eccezionale interesse culturale. Esistono inoltre categorie fondate sul rapporto con la storia e sull'eccezionale interesse per il patrimonio nazionale: non tutto dipende dall'età.

Per le categorie del comma 1 e del comma 3, lettere a ed e, il comma 5 esclude opere di autore vivente o eseguite da non oltre settant'anni; per la lettera d-bis opera il diverso limite cinquantennale. Non si deve estendere questo criterio a ogni bene: l'archivio pubblico del comma 2 è tutelato anche per documenti recenti. Un quadro centenario di una persona fisica non diventa automaticamente bene culturale solo perché supera settant'anni; un archivio comunale non deve attendere quel compleanno per essere tutelato.''',
(3,3):'''**Verifica e dichiarazione: presupposti ed effetti.** L'articolo 12 riguarda le cose dei soggetti indicati dall'articolo 10, comma 1, di autore non più vivente e risalenti a oltre settant'anni. In attesa della verifica si applica il regime di tutela previsto dalla parte seconda del Codice. L'esito positivo accerta l'interesse e produce gli effetti della dichiarazione; quello negativo esclude il regime culturale, ma per beni demaniali occorre considerare separatamente eventuali altri interessi pubblici che impediscono la sdemanializzazione. La verifica non è un permesso di eseguire qualsiasi opera.

La dichiarazione dell'articolo 13 accerta l'interesse richiesto per le categorie del comma 3 dell'articolo 10. L'avvio è comunicato dal soprintendente al proprietario, possessore o detentore; la comunicazione identifica la cosa, illustra gli elementi emersi e permette osservazioni per un termine non inferiore a trenta giorni. Dall'avvio derivano gli effetti cautelari indicati dall'articolo 14. La dichiarazione è adottata dal Ministero e va distinta dalla fase istruttoria. Nel caso di un bene privato si deve indicare quale categoria richiede il provvedimento, evitando la formula inesatta «tutti i privati sono tutelati automaticamente».''',
(4,3):'''**Una proposta di valorizzazione deve superare il controllo di compatibilità.** L'articolo 20 vieta usi incompatibili con il carattere storico o artistico del bene o pregiudizievoli alla sua conservazione. Non basta chiamare «culturale» un evento per renderlo lecito. Se il progetto prevede fissaggi che danneggiano una superficie decorata o carichi incompatibili con la conservazione, la proposta deve essere modificata o abbandonata; un'autorizzazione non trasforma un uso vietato in un uso ammissibile. Diverso è il caso di un intervento astrattamente compatibile che richieda l'autorizzazione dell'articolo 21 e relative prescrizioni. In una risposta scritta sono quindi distinti giudizio sulla compatibilità, titolo necessario e condizioni esecutive.''',
(5,2):'''**Termini della verifica.** Nel testo vigente al 3 ottobre 2026 l'articolo 12 prevede la conclusione entro novanta giorni dal ricevimento della richiesta; in caso d'inerzia interviene il direttore generale competente nei successivi trenta giorni secondo i commi 10 e 10-bis. Non ne segue una libera disponibilità automatica della cosa allo scadere del primo termine. Prima dell'esito continua il regime interinale previsto dalla norma. La scheda istruttoria registra soggetto proprietario, categoria, autore non vivente, datazione oltre settant'anni, documentazione identificativa e richiesta: la sola frase «immobile vecchio» non prova i presupposti.''',
(5,4):'''**Autorizzazione, denuncia e comunicazione nell'articolo 21.** La legge 17 marzo 2026, n. 40 ha abrogato la lettera b del comma 1 sullo spostamento. Nel testo vigente lo spostamento di beni culturali va preventivamente denunciato al soprintendente, che entro trenta giorni può prescrivere le misure necessarie a evitare danni durante il trasporto. Per gli archivi correnti dello Stato e degli enti e istituti pubblici il comma 3 prevede la comunicazione al Ministero. Occorre distinguere questi adempimenti dalle autorizzazioni ancora richieste per rimozione o demolizione, smembramento di collezioni e scarto, nei rispettivi casi previsti dal comma 1.

Opere e lavori di qualunque genere su beni culturali richiedono l'autorizzazione del soprintendente ai sensi del comma 4. Il mutamento di destinazione d'uso è comunicato per il controllo dell'articolo 20. Un trasferimento per mostra può inoltre richiedere il titolo proprio del prestito: la denuncia di spostamento non assorbe gli altri procedimenti. Nel fascicolo vanno separati oggetto di ciascun atto, autorità, documenti e prescrizioni, anziché scrivere genericamente «serve il nulla osta».''',
(5,5):'''**Vendita, prelazione e uscita definitiva.** L'articolo 54 elenca beni culturali demaniali inalienabili, fra cui raccolte museali, archivi e determinate aree archeologiche; sono previste eccezioni tipizzate, come trasferimenti fra enti territoriali, da non estendere alle vendite a privati. Gli altri immobili culturali demaniali possono essere alienati con autorizzazione alle condizioni dell'articolo 55. L'uscita dal demanio conseguente all'alienazione autorizzata non cancella la tutela culturale.

Gli atti che trasferiscono la proprietà, in tutto o in parte, sono denunciati entro trenta giorni ai sensi dell'articolo 59; il trasferimento della detenzione è denunciato per i beni mobili. La denuncia deve contenere tutti gli elementi prescritti. La prelazione dell'articolo 60 opera sulle alienazioni onerose e sui conferimenti, non indistintamente su donazioni e successioni. Il termine ordinario è sessanta giorni dalla ricezione della denuncia; per denuncia omessa, tardiva o incompleta, l'articolo 61 prevede centottanta giorni dalla conoscenza di tutti gli elementi richiesti. Durante il termine ordinario l'atto è sospensivamente condizionato e non si consegna il bene.

Per l'uscita definitiva dal territorio, l'articolo 65 distingue divieti, casi soggetti ad attestato e casi da documentare con dichiarazione di non assoggettamento. Un bene già tutelato non può essere esportato liberamente perché il prezzo è basso. Per cose non comprese nei divieti, di autore non vivente e oltre settant'anni, nel regime generale rileva oggi la soglia superiore a 50.000 euro; per i libri resta la soglia superiore a 13.500 euro. Esistono categorie senza soglia economica, e archivi/documenti privati hanno un regime specifico. Sotto soglia non significa assenza di adempimenti o possibilità di dichiarare un valore fittizio. L'attestato di libera circolazione dell'articolo 68 dura cinque anni; il rilascio o diniego interviene entro quaranta giorni dalla presentazione della cosa. L'eventuale esportazione fuori dall'Unione richiede anche il controllo della disciplina specifica pertinente.

**Caso risolto.** Un privato vende a titolo oneroso un dipinto già dichiarato di interesse culturale. La vendita è denunciata entro trenta giorni; la prelazione segue il termine ordinario di sessanta se la denuncia è completa e tempestiva. Il compratore non può equiparare la denuncia di vendita a un attestato per l'uscita definitiva, né usare la soglia di 50.000 euro per sottrarre alla tutela un bene già dichiarato. Sono tre questioni diverse: trasferimento giuridico, consegna e uscita dal territorio.''',
(6,3):'''**Uno standard governa significato e forma dei dati.** Un identificativo collega in modo stabile la scheda al bene; il vocabolario controllato evita che sinonimi o grafie separino artificialmente oggetti simili; un campo con datazione documenta anche l'incertezza e la fonte dell'attribuzione. «Autore ignoto» non equivale a campo dimenticato: il primo è un risultato conoscitivo dichiarato, il secondo può essere un errore di compilazione. Una scheda ICCD, una descrizione archivistica ISAD(G) e un record bibliografico non sono modelli intercambiabili: il modello dipende dall'oggetto e dalle relazioni che devono essere conservate.

**Esempio originale.** Un museo descrive un vaso con identificativo locale M-27, materiale ceramico, provenienza documentata dal deposito D e cronologia proposta al II secolo con motivazione bibliografica. La fotografia digitale V27-master.tif ha un proprio identificativo, data di acquisizione e collegamento a M-27. Correggere la datazione del vaso non richiede di rinominare arbitrariamente ogni file; occorre aggiornare la descrizione mantenendo le relazioni e la storia della modifica.''',
(6,4):'''**Master, derivati e controllo d'integrità.** Il master conserva la qualità prevista dal progetto ed è custodito con controlli e copie adeguati; il derivato serve a un uso, per esempio la consultazione sul web, con dimensione e formato compatibili con quel servizio. Una miniatura non sostituisce il master. I parametri di acquisizione sono scelti sul bene e sul progetto, non copiati indistintamente da un altro fondo. Le linee guida ICDP del giugno 2022 distinguono queste esigenze e prevedono verifiche fin dall'avvio.

L'impronta di controllo, o checksum, permette di confrontare i bit del file in momenti diversi. Se cambia senza una trasformazione autorizzata, occorre indagare e recuperare una copia verificata; la sola coincidenza dell'impronta non prova che la fotografia raffiguri il bene giusto. Servono quindi due controlli: integrità informatica e corrispondenza documentale. Il registro annota file, impronta, algoritmo, data del controllo, esito e operatore o processo. Una migrazione pianificata modifica i bit e deve documentare originale, nuovo oggetto e relazione; non si considera automaticamente corruzione.

**Collaudo didattico.** Sono consegnate 100 immagini, 100 schede e una lista d'impronte. Due immagini sono associate al bene sbagliato; un file non coincide con l'impronta di consegna. Il lotto non supera il collaudo solo perché il numero dei file è esatto. Si correggono le due associazioni verificando gli originali documentali; si esamina e sostituisce il file alterato con una copia valida, poi si ripetono i controlli e si registra l'esito. La disponibilità online arriva dopo verifica di qualità, legami e diritti.''',
(7,1):'''**Prime nozioni di diplomatica.** La diplomatica studia forma e formazione del documento, mettendo in relazione atto, soggetti e testimonianza documentaria. L'autore dell'azione giuridica, il destinatario e chi materialmente scrive possono essere persone differenti. L'originale è il documento prodotto nella forma originaria; una copia può essere semplice o munita delle forme di autenticazione pertinenti, e il suo valore va valutato nel contesto. Data, luogo, sottoscrizioni, sigilli e formule aiutano a ricostruire come il documento è stato formato. Non garantiscono da soli che ogni fatto narrato sia vero: autenticità del documento e attendibilità del contenuto sono problemi distinti. In una scheda si descrive ciò che è osservabile e si separa un'attribuzione motivata da una supposizione.''',
(7,3):'''**Descrivere in più livelli con ISAD(G).** Le quattro regole sono: procedere dal generale al particolare; fornire informazioni pertinenti al livello; collegare ogni descrizione a quella immediatamente superiore; non ripetere ai livelli inferiori quanto è già comune e descritto sopra. Fondo, serie, fascicolo e documento indicano livelli diversi, non quattro sinonimi di contenitore. ISAAR(CPF) serve a descrivere il soggetto produttore, ente, persona o famiglia, e le sue relazioni; il produttore non coincide necessariamente con l'istituto che oggi conserva il fondo.

**Descrizione originale risolta.** Fondo: «Comune di Valleverde», estremi 1900–1980, produttore Comune, conservatore archivio comunale. Serie: «Deliberazioni della Giunta», estremi 1946–1960, collegata al fondo. Unità: «Registro delle deliberazioni 1952», segnatura locale GV/12, consistenza un registro, collegata alla serie. Al fondo si descrive la storia istituzionale comune; nell'unità si danno anno e caratteristiche specifiche senza ricopiare quella storia. Se il registro contiene un allegato, lo si descrive e collega secondo il livello necessario, senza inventare una nuova serie. L'esempio è una scheda leggibile, non un tracciato informatico da importare.

**Verifica orale.** Spostando fisicamente il registro in un deposito esterno cambia il conservatore o la localizzazione, non per questo il produttore Comune. Riordinare per argomento tutti i documenti di enti diversi cancellerebbe provenienza e relazioni: la ricerca tematica si costruisce con strumenti di accesso, non distruggendo il contesto del fondo.''',
(7,5):'''**Scarto, versamento e consultazione.** Lo scarto elimina documentazione secondo valutazione, strumenti e autorizzazione previsti; non coincide con il trasferimento fisico al deposito né con la selezione per una mostra. L'articolo 21 sottopone ad autorizzazione lo scarto nei casi indicati, compresi archivi pubblici. La mancanza di spazio non sostituisce il procedimento. L'articolo 41 dispone il versamento agli archivi competenti dei documenti statali relativi ad affari esauriti da oltre trent'anni, con le eccezioni stabilite e possibilità di anticipazione nelle condizioni previste. Il termine riguarda la conclusione dell'affare, non una regola generale «trent'anni dalla data di qualunque foglio».

La consultabilità degli articoli 122–123 parte dalla libera consultazione degli archivi storici, ma distingue i documenti riservati relativi alla politica interna/estera, con limite di cinquant'anni; quelli con particolari dati personali e provvedimenti penali, ordinariamente quarant'anni; quelli relativi a salute, vita sessuale o rapporti riservati familiari, settant'anni. Per lo studio storico è possibile l'autorizzazione anticipata del Ministero dell'interno secondo la procedura prevista. L'autorizzazione a uno studioso non rende il documento liberamente consultabile da chiunque e non autorizza automaticamente la diffusione online dei dati.

**Caso.** Nel 2026 un ricercatore chiede un fascicolo del 1990 contenente dati sulla salute. Sono trascorsi 36 anni: non basta che il fascicolo sia in archivio storico per considerarlo liberamente consultabile. Si valuta l'eventuale procedimento di autorizzazione anticipata e si distinguono consultazione, riproduzione e diffusione. Non si sostituisce questa disciplina con un generico accesso amministrativo, che ha presupposti e finalità propri.''',
(8,2):'''**Regole, formati e punti di accesso.** REICAT è il codice italiano di catalogazione; ISBD disciplina la presentazione degli elementi descrittivi; UNIMARC rappresenta i dati in un formato utilizzabile dai sistemi; SBNMARC è il protocollo di colloquio con l'Indice SBN e usa semantica UNIMARC. Nessuno di questi è semplicemente il nome del catalogo della singola biblioteca. La catalogazione partecipata verifica se la notizia esiste e collega gli esemplari, evitando duplicazioni.

L'authority control distingue identità e forme del nome: varianti dello stesso autore vengono collegate, omonimi vengono distinti con informazioni attendibili. La soggettazione rappresenta il contenuto con termini controllati, per esempio nel quadro del Nuovo soggettario; la classificazione colloca l'opera in uno schema concettuale; la collocazione permette di trovare l'esemplare fisico. Un numero di scaffale non sostituisce l'analisi del contenuto.

**Record didattico originale.** Opera immaginaria: Marta Neri, «Giardini storici e memoria urbana», edizione 2024, editore e luogo da verificare sul documento, 180 pagine. I campi già accertati si registrano; quelli non disponibili non si inventano. L'accesso per autore collega l'identità di Marta Neri, distinguendola da un'omonima; il soggetto riguarda i giardini storici nel contesto urbano, formulato secondo il linguaggio adottato; collocazione locale GIA 24 identifica l'esemplare. Non si assegna un ISBN fittizio e non si presenta questa scheda come notizia autentica SBN. Se emerge una seconda edizione con contenuto modificato, si verifica la relazione fra edizioni invece di fondere automaticamente tutti gli esemplari.''',
(8,4):'''**ILL e document delivery.** Il prestito interbibliotecario (ILL) procura tramite un'altra biblioteca il documento fisico ammesso al servizio; il document delivery (DD) procura una riproduzione consentita, per esempio di un articolo. Durata, costi, esclusioni e modalità dipendono dal servizio e dai diritti: non esiste un diritto universale a ricevere qualsiasi documento integralmente.

**Caso risolto.** Una lettrice cerca un articolo preciso e il catalogo localizza la rivista in un'altra biblioteca. Il bibliotecario verifica citazione, annata, fascicolo e pagine, poi disponibilità elettronica, licenza e possibilità di DD. Per una monografia intera non posseduta valuta invece ILL e condizioni. La risposta comunica quale servizio è possibile e quali limiti restano; non promette il PDF solo perché compare una notizia bibliografica.''',
(9,1):'''**Leggere una sequenza stratigrafica.** L'unità stratigrafica (US) identifica l'esito riconoscibile di un'azione o trasformazione. Un deposito o una muratura costituiscono un'unità materiale positiva; un taglio documenta una rimozione e costituisce un'unità negativa. Non è «terra mancante senza importanza»: registra un evento. Il numero assegnato identifica l'unità, ma non ne stabilisce da solo l'età.

**Esercizio originale.** La traccia dà tre relazioni: il taglio US 12 incide il deposito US 10; US 13 riempie il taglio; nessun altro rapporto è documentato. La successione relativa dal più antico al più recente è 10 → 12 → 13. Il riempimento non precede il vuoto che occupa. Il diagramma rappresenta relazioni di anteriorità/posteriorità, non anni di calendario: per la datazione assoluta servono ulteriori evidenze. Descrizione, fotografia, disegno e rapporti osservati permettono di controllare l'interpretazione.''',
(9,2):'''**Ritrovamento fortuito: articolo 90.** Chi scopre fortuitamente cose di interesse culturale ne fa denuncia entro ventiquattro ore al soprintendente, al sindaco oppure all'autorità di pubblica sicurezza e provvede alla conservazione temporanea lasciandole nelle condizioni e nel luogo del ritrovamento. Solo per cose mobili la cui custodia non sia altrimenti assicurabile è ammessa la rimozione nelle condizioni previste, fino alla visita dell'autorità. Non è un invito a pulire, scavare o ricostruire autonomamente il reperto. L'articolo 91 attribuisce allo Stato le cose ritrovate nel sottosuolo o sui fondali, secondo il regime dei beni immobili o mobili.

**Caso.** Durante lavori emerge un oggetto con apparente interesse archeologico. La risposta amministrativa documenta luogo, momento e circostanze, attiva immediatamente la segnalazione prevista e protegge il contesto evitando alterazioni. Il termine di ventiquattro ore non è un'autorizzazione a continuare a manomettere il sito fino alla scadenza. L'eventuale spostamento per custodia deve rientrare nell'eccezione legale, non nella comodità del cantiere.''',
(10,1):'''**Una scheda storico-artistica concreta.** Sandro Botticelli, «Nascita di Venere», circa 1485, tempera su tela, 172,5 × 278,5 cm, Gallerie degli Uffizi, inventario 1890 n. 878. Questi sono dati della scheda istituzionale. La composizione mostra Venere sulla conchiglia, sospinta dai venti e accolta sulla riva: il titolo tradizionale non obbliga a descrivere la scena come l'istante della nascita. Il contorno delle figure e il ritmo dei capelli e dei panneggi organizzano la lettura. Il richiamo al mondo classico si inserisce nella cultura del Rinascimento fiorentino. La committenza medicea è indicata come probabile dagli Uffizi: va mantenuto questo grado di certezza, senza trasformarlo in documento certo.

**Orientamento cronologico.** «Quattrocento» indica il XV secolo; circa 1485 precede il Cinquecento e il pieno sviluppo del Barocco seicentesco. Rinascimento e Barocco non sono etichette ricavate dal solo soggetto mitologico: vanno collegati a tempo, ambiente, linguaggio e funzione. Per una scheda d'esame si procede da autore/data/tecnica alla descrizione di ciò che si vede, poi al contesto e alle interpretazioni sostenute. La misura del dipinto non prova la committenza, e il soggetto antico non rende antica l'opera.

**Mini-prova.** Correggi: «Affresco seicentesco di autore anonimo, certamente commissionato dai Medici». Soluzione: attribuzione a Botticelli, circa 1485, tempera su tela; committenza medicea probabile. Il metodo consiste nel separare errore materiale, errore cronologico e certezza eccessiva, non nel sostituire una descrizione suggestiva con un'altra.''',
(11,1):'''**Le definizioni dell'articolo 29.** La conservazione si realizza con studio, prevenzione, manutenzione e restauro coordinati e programmati. La prevenzione limita situazioni di rischio nel contesto; la manutenzione controlla le condizioni e mantiene integrità, efficienza funzionale e identità; il restauro interviene direttamente sul bene per recuperarne l'integrità materiale e i valori culturali. Non si distinguono semplicemente per costo o spettacolarità. Lo studio precede e accompagna la scelta, mentre la documentazione permette di valutare effetti e continuità della cura.

**Classificare un caso.** Controllare una perdita d'acqua nella copertura per evitare che raggiunga una raccolta appartiene alla gestione preventiva del rischio; controlli e interventi programmati sul bene rientrano nella manutenzione secondo natura dell'attività; un intervento diretto per recuperare integrità e leggibilità richiede valutazione di restauro. La classificazione non autorizza chiunque a intervenire: restauro e manutenzione di beni mobili e superfici decorate, ai sensi del comma 6, competono ai restauratori qualificati; per i beni architettonici restano le regole sulle professioni abilitate. Il custode registra e segnala un distacco, non lo incolla di propria iniziativa.''',
(12,1):'''**Adattare la prova al profilo.** Per un assistente o funzionario amministrativo questo capitolo insegna istruttoria, documenti, competenze e controllo degli atti. Per un architetto il bando può richiedere rilievo, analisi del degrado, progetto di conservazione, compatibilità e gestione tecnica del cantiere: tali prestazioni non vanno escluse in astratto. Il programma delimita profondità e prodotto richiesti. La conoscenza amministrativa è comune al lavoro pubblico, ma non sostituisce la preparazione professionale propria del progettista.

**Doppia consegna sullo stesso edificio.** La traccia propone una rampa presso un palazzo tutelato. Il candidato amministrativo redige una nota che identifica bene e vincoli, elaborati mancanti, uffici competenti, titoli necessari e sequenza delle decisioni. Il candidato architetto può dover confrontare alternative progettuali, documentare impatto sulla materia storica, accessibilità, reversibilità ove pertinente, fattibilità e motivazione della scelta. Non bastano le parole «rispettare il vincolo»: occorre spiegare quale trasformazione si propone e quale effetto produce. Non si inventano dimensioni, pendenze o soluzioni strutturali senza dati della traccia e norme tecniche pertinenti.''',
(13,3):'''**Lavoratore, addetto e piano locale.** L'articolo 20 del D.Lgs. 81/2008 impone al lavoratore di prendersi cura della sicurezza propria e altrui secondo formazione, istruzioni e mezzi ricevuti; osservare le disposizioni; segnalare immediatamente pericoli e carenze; non rimuovere dispositivi né eseguire manovre estranee alle competenze. Nell'urgenza si agisce entro competenze e possibilità per ridurre il pericolo grave e incombente. Non si insegna quindi né passività assoluta né intervento improvvisato.

L'addetto incaricato per le emergenze ha compiti e formazione specifici; il personale di accoglienza non acquista automaticamente quelle qualifiche. Il piano locale definisce canali di allarme, ruoli, percorsi, assistenza e raccordo con i soccorsi. Prima del servizio il lavoratore deve conoscere le istruzioni che lo riguardano. La capienza non si deduce dall'abitudine o dal numero dei biglietti venduti: si rispettano le condizioni autorizzate e le disposizioni del sito.

**Caso situazionale risolto.** In una sala un visitatore segnala odore di bruciato e un passaggio d'uscita ingombro. L'operatore comunica subito luogo e fatti al referente previsto, attiva quanto gli compete secondo il piano e orienta il pubblico con indicazioni coerenti. Non minimizza per evitare di interrompere la visita, non entra in un locale tecnico per tentare riparazioni e non diffonde istruzioni contraddittorie. Se deve assistere una persona con difficoltà, applica i compiti assegnati e coinvolge gli addetti, senza promettere manovre per cui non è formato. Dopo l'evento registra fatti, tempi e comunicazioni separandoli dalle ipotesi sulla causa. La qualità della risposta si valuta su tempestività, chiarezza, rispetto dei ruoli e protezione delle persone.'''
}
for p in sorted((B/'chapters').glob('*.md')):
 t=p.read_text(encoding='utf8');c=int(p.name[:2]);saved=arc/p.name
 if not saved.exists():saved.write_text(t,encoding='utf8')
 t=re.sub(r'^## (N-IR04-)',r'### \1',t,flags=re.M)
 for (ch,n),body in blocks.items():
  if ch!=c:continue
  m=re.search(rf'^### N-IR04-{c:02}-{n:02}[^\n]*\n',t,re.M);assert m,(c,n)
  t=t[:m.end()]+'\n'+body+'\n\n'+t[m.end():]
 t=t.replace("Infine indica che gli interventi materiali e gli usi incompatibili possono richiedere autorizzazioni, prescrizioni o modifiche del progetto.","Infine distingue gli usi incompatibili, vietati dall'articolo 20, dagli interventi ammissibili soggetti ad autorizzazione e prescrizioni dell'articolo 21. Il progetto va modificato quando l'uso proposto è incompatibile.")
 t=t.replace('I metadati devono essere distinti dai dati catalografici, anche se spesso si sovrappongono o dialogano con essi.','I dati catalografici costituiscono metadati descrittivi: identificano e descrivono il bene o la risorsa. A essi si affiancano metadati tecnici, amministrativi, strutturali e di conservazione.')
 if c==12:
  t=t.replace('La commissione non chiede al candidato di progettare un restauro, dirigere un cantiere o applicare istruzioni operative di sicurezza. Può però chiedere','Per i profili amministrativi la prova può chiedere').replace('La commissione premia chi sa ordinare il ragionamento e non scivola nella progettazione tecnica.','La risposta deve corrispondere al profilo: istruttoria per quello amministrativo, analisi e progetto quando richiesti a quello tecnico.').replace('Il candidato non deve dare istruzioni di progettazione, di esecuzione dei lavori o di sicurezza. Deve invece descrivere il cantiere come fase amministrativa e gestionale','Nel percorso amministrativo si descrive il cantiere come fase amministrativa e gestionale')
 if c==11:t=t.replace('La commissione non si aspetta istruzioni operative su materiali, tecniche o dosaggi.','Nel percorso amministrativo qui trattato non si forniscono istruzioni esecutive su materiali o dosaggi; una selezione per restauratori può richiedere conoscenze e prove tecniche proprie.').replace('Una risposta buona non descrive “come si fa” un intervento tecnico; spiega “perché” e “quando” l’amministrazione deve valutare, documentare, autorizzare, coordinare e controllare.','La risposta amministrativa spiega perché e quando valutare, documentare, autorizzare, coordinare e controllare; la prova tecnica richiede anche il sapere professionale indicato dal bando.')
 if c==13:t=t.replace('In questo capitolo, la vigilanza e\' trattata in chiave amministrativa. Non servono istruzioni di intervento fisico, protocolli emergenziali, soglie di capienza o dettagli tecnici non consolidati.','La vigilanza comprende osservazione, prevenzione, segnalazione e compiti assegnati dal piano locale. Occorre conoscere le istruzioni di emergenza pertinenti al proprio ruolo, senza inventare soglie o manovre universali.')
 p.write_text(t,encoding='utf8')
print('IR04: integrazioni in 13 capitoli; originali archiviati')
