from pathlib import Path
import re,json
B=Path('wiki/books/moduli/m-ir04-cultura-beni-culturali/chapters');A=Path('artifacts/correzioni-collana-2026-10-02')
# Options are complete; the explanation is independent of option order.
Q={
1:[
('Una prova richiede un inventario di fondo, serie e fascicoli. Il sapere specialistico prioritario è:',['Descrizione archivistica','Allestimento museale','Contabilità delle collezioni','Analisi strutturale'],0,'Il prodotto richiesto rappresenta documenti e loro relazioni gerarchiche.'),
('Il codice del posto nel bando serve principalmente a:',['Stabilire la sede della prova per ogni concorso','Individuare il profilo e il relativo programma','Sostituire il requisito di accesso','Attribuire l’autorizzazione alla tutela'],1,'Profili nella stessa amministrazione possono avere requisiti, materie e prove differenti.'),
('Per una vendita di dipinto tutelato il candidato amministrativo deve anzitutto:',['Calcolare il numero di visitatori','Decidere una nuova attribuzione artistica','Distinguere regime del bene e adempimenti del trasferimento','Scegliere il materiale di imballaggio'],2,'La qualificazione giuridica orienta denuncia, eventuale prelazione e ulteriori procedimenti.'),
('Il catalogo indica che una biblioteca possiede un libro. Ne segue:',['Disponibilità immediata al prestito','Diritto a ricevere copia integrale','Identità fra catalogo e inventario archivistico','Necessità di verificare condizioni di accesso e servizio'],3,'Localizzazione e condizioni del servizio sono informazioni diverse.'),
('Una selezione per architetti MiC può richiedere:',['Solo conoscenze identiche al profilo amministrativo','Analisi e progetto tecnico previsti dal programma','Solo accoglienza del pubblico','Esclusivamente catalogazione bibliografica'],1,'Il perimetro della prova tecnica dipende dal profilo e dal bando.'),
('Per costruire il piano di studio è più utile abbinare:',['Ogni materia a un output richiesto dalla prova','Ogni materia a un uguale numero di giorni','Ogni ufficio al cognome del direttore','Ogni capitolo a una sola domanda mnemonica'],0,'Allenare il prodotto atteso rende verificabile la preparazione specifica.')],
2:[
('Nell’assetto verificato nel 2026, la DG Archivi afferisce a:',['DiAG','DiAC','DiT','DiVA'],2,'La Direzione generale Archivi appartiene al Dipartimento per la tutela del patrimonio culturale.'),
('La DG Musei afferisce a:',['DiVA','DiT','DiAC','DiAG'],0,'La valorizzazione del patrimonio culturale comprende la DG Musei.'),
('Per la tutela dell’archivio comunale è pertinente:',['La sola biblioteca statale più vicina','La soprintendenza archivistica competente','Il dipartimento cinema','Qualsiasi museo autonomo'],1,'Si tratta di archivio pubblico non statale; le competenze archivistiche non si confondono con quelle SABAP.'),
('Il versamento di documentazione di un ufficio periferico dello Stato richiama:',['La consegna obbligatoria al Comune','La vendita al museo locale','Il deposito presso qualsiasi privato','Il raccordo con l’Archivio di Stato competente'],3,'Il circuito statale di conservazione segue le regole di versamento, diverse da quelle degli archivi comunali.'),
('L’autonomia speciale di un museo:',['Elimina le autorizzazioni di tutela','Coincide con indipendenza dal Codice','Attribuisce funzioni gestionali nei limiti normativi','Trasferisce ogni competenza territoriale al direttore'],2,'Autonomia gestionale e poteri di tutela sono piani distinti.'),
('La DG Biblioteche e istituti culturali si colloca in:',['DiAC','DiAG','DiVA','DiT'],0,'Rientra nel Dipartimento per le attività culturali; non va dedotto il dipartimento dal solo termine patrimonio.')],
3:[
('Un archivio comunale contiene atti recenti. Per l’art. 10, comma 2:',['Occorre attendere settant’anni per tutti gli atti','La categoria è tutelata senza attendere quel limite','Serve la dichiarazione richiesta agli archivi privati','Solo gli atti esposti al pubblico sono tutelati'],1,'Gli archivi pubblici sono una categoria ex lege; il limite non va esteso indiscriminatamente.'),
('Un dipinto centenario di persona fisica:',['È automaticamente culturale per l’età','È escluso perché privato','Va valutato rispetto alla categoria e alla dichiarazione richiesta','Può essere tutelato solo dopo acquisizione statale'],2,'Età e proprietà non sostituiscono i presupposti della dichiarazione.'),
('Per la verifica art. 12 su cose del comma 1, i requisiti temporali comprendono:',['Autore non vivente e oltre settant’anni','Autore vivente e oltre cinquant’anni','Solo oltre trent’anni','Qualsiasi bene acquistato da un ente pubblico'],0,'L’art. 12 individua un ambito preciso; non è una verifica generale di ogni cosa.'),
('La verifica positiva dell’interesse culturale:',['Libera il bene dalla tutela','Rende automaticamente autorizzata ogni opera','Determina il prezzo di vendita','Produce gli effetti della dichiarazione'],3,'Accerta l’interesse culturale; gli interventi conservano i propri procedimenti.'),
('Un uso pregiudizievole alla conservazione ai sensi dell’art. 20:',['È ammissibile con un canone maggiore','È vietato','È libero se temporaneo','Dipende soltanto dal consenso del proprietario'],1,'Il divieto non è superato dalla finalità promozionale o dalla durata ridotta.'),
('La verifica negativa su una cosa demaniale:',['Elimina anche ogni diverso interesse pubblico','Equivale a concessione edilizia','Esclude il regime culturale ma richiede distinta valutazione degli altri interessi demaniali','Impone automaticamente la vendita'],2,'Esito culturale e permanenza di altri vincoli demaniali non coincidono.')],
4:[
('Un evento aumenta la conoscenza del bene ma danneggia superfici storiche. La valorizzazione:',['Non giustifica l’uso incompatibile','Prevale perché amplia il pubblico','Rende irrilevante l’art. 20','È sempre autorizzata se gratuita'],0,'Conoscenza e fruizione devono essere compatibili con la tutela.'),
('L’autorizzazione paesaggistica e il titolo edilizio:',['Sono due nomi dello stesso atto','Si sostituiscono reciprocamente','Hanno oggetti distinti e vanno verificati entrambi quando necessari','Dipendono soltanto dall’età del fabbricato'],2,'L’interesse paesaggistico non coincide con la conformità edilizia.'),
('Una barriera informativa può essere ridotta con:',['Sola vendita online del biglietto','Mediazione comprensibile e strumenti accessibili','Esclusione degli utenti inesperti','Sostituzione di ogni originale con una fotografia'],1,'L’accessibilità comprende comprensione e uso del servizio, oltre agli aspetti fisici.'),
('La tutela si basa anche sulla conoscenza perché:',['Basta rendere famoso il bene','Il prezzo determina ogni vincolo','La comunicazione sostituisce l’istruttoria','Occorre identificare caratteristiche e valori da proteggere'],3,'La decisione di tutela richiede una base conoscitiva adeguata.'),
('Un progetto compatibile richiede lavori sul bene tutelato. Si deve:',['Verificare l’autorizzazione art. 21 e le prescrizioni','Considerarlo libero per la compatibilità','Richiedere soltanto il consenso del pubblico','Trattarlo come una denuncia di vendita'],0,'Compatibilità e titolo per eseguire i lavori sono verifiche diverse.'),
('Il paesaggio, nel ragionamento amministrativo, va considerato:',['Soltanto come veduta gradevole','Solo se privo di attività umane','Come territorio e valori tutelati, con regole sulle trasformazioni','Come sinonimo di museo all’aperto'],2,'La valutazione non si riduce al gusto estetico individuale.')],
5:[
('Lo spostamento ordinario di bene culturale nel testo vigente dell’art. 21 segue:',['Autorizzazione della lettera b ancora vigente','Denuncia preventiva e possibile prescrizione entro trenta giorni','Denuncia successiva entro sessanta giorni','Nessun adempimento se non cambia proprietario'],1,'La legge 40/2026 ha abrogato la lettera b; restano gli altri procedimenti eventualmente necessari.'),
('La denuncia del trasferimento di proprietà ex art. 59 è presentata entro:',['Novanta giorni','Sessanta giorni','Trenta giorni','Centottanta giorni'],2,'Il termine della denuncia non coincide con quello della prelazione.'),
('La prelazione ordinaria su denuncia completa e tempestiva si esercita entro:',['Sessanta giorni','Trenta giorni','Quaranta giorni','Cinque anni'],0,'I centottanta giorni riguardano le specifiche ipotesi di denuncia omessa, tardiva o incompleta.'),
('Un bene già dichiarato culturale vale 20.000 euro. Per l’uscita definitiva:',['È libero perché sotto 50.000','Basta una ricevuta di vendita','È sufficiente la denuncia di spostamento','Il divieto pertinente non è eliminato dal valore ridotto'],3,'Le soglie non sottraggono al divieto i beni già compresi nelle categorie tutelate.'),
('Per i libri nel regime a soglia dell’art. 65 vigente, rileva il valore superiore a:',['50.000 euro come ogni cosa','13.500 euro','5.000 euro','100.000 euro'],1,'La disciplina attuale distingue la soglia libraria da quella generale di 50.000 euro.'),
('L’attestato di libera circolazione ex art. 68 ha validità di:',['Trenta giorni','Un anno','Cinque anni','Dieci anni'],2,'Validità del titolo e termine di rilascio o diniego di quaranta giorni sono diversi.')],
6:[
('Autore e titolo nella scheda sono:',['Metadati descrittivi','Solo dati estranei ai metadati','Esclusivamente metadati tecnici','Impronte crittografiche'],0,'La descrizione catalografica appartiene alla categoria dei metadati descrittivi.'),
('La miniatura web rispetto al master:',['Lo sostituisce se si apre correttamente','Ha sempre identica informazione','Ha una funzione d’accesso e non ne sostituisce la conservazione','Prova automaticamente la correttezza dei diritti'],2,'I derivati sono prodotti per usi specifici; conservazione e accesso hanno esigenze diverse.'),
('Un checksum coincide ma l’immagine raffigura un altro oggetto. Il controllo:',['È comunque superato','Richiede anche verifica della corrispondenza documentale','Dimostra che la scheda è corretta','Può omettere il confronto con l’identificativo'],1,'L’integrità dei bit non certifica la corretta associazione al bene.'),
('Una migrazione autorizzata produce nuovi bit. Occorre:',['Cancellare la storia del master','Trattarla sempre come corruzione','Mantenere segreto il nuovo formato','Documentare trasformazione e relazione fra oggetti'],3,'Una variazione pianificata e tracciata è distinta dall’alterazione imprevista.'),
('I metadati strutturali di un libro digitalizzato descrivono:',['Ordine e relazioni fra le parti','Solo il proprietario del copyright','Solo il nome del fotografo','Solo la datazione dell’opera'],0,'Servono a ricostruire la struttura dell’oggetto, distinta da diritti e dati tecnici.'),
('Cento file e cento schede con due associazioni errate:',['Sono accettabili perché il conteggio torna','Richiedono soltanto compressione','Non superano il controllo di corrispondenza','Possono essere pubblicati senza ulteriori controlli'],2,'La completezza numerica non garantisce qualità e correttezza delle relazioni.')],
7:[
('ISAD(G) richiede anzitutto una descrizione:',['In ordine alfabetico di ogni foglio','Dal generale al particolare con collegamenti','Separata da qualsiasi fondo','Identica per ogni livello'],1,'I livelli devono rappresentare contesto e posizione senza ripetizioni inutili.'),
('ISAAR(CPF) riguarda:',['Solo gli edifici di deposito','La codifica delle immagini','I soggetti produttori e le loro relazioni','Il termine legale dello scarto'],2,'Enti, persone e famiglie sono descritti come soggetti collegati alla documentazione.'),
('Spostare un registro comunale in deposito esterno cambia necessariamente:',['La localizzazione, non il produttore storico','Il Comune che lo ha prodotto','La serie di appartenenza','La data di formazione'],0,'Collocazione fisica e provenienza archivistica sono distinte.'),
('Lo scarto di archivio pubblico motivato da carenza di spazio:',['È libero se approvato dall’addetto','Coincide con il versamento','Si esegue eliminando i fogli più vecchi','Richiede il procedimento e l’autorizzazione pertinenti'],3,'Il bisogno logistico non sostituisce valutazione e titolo previsti.'),
('Il termine ordinario art. 41 per documentazione statale riguarda affari esauriti da oltre:',['Settanta anni','Trenta anni','Quaranta anni','Cinquanta anni'],1,'Il riferimento è alla conclusione dell’affare e restano le eccezioni della norma.'),
('Un fascicolo del 1990 con dati sanitari richiesto nel 2026:',['È libero perché trascorsi trenta anni','È pubblicabile integralmente perché storico','Richiede valutazione del limite settantennale e dell’eventuale autorizzazione anticipata','È sempre distrutto dopo quaranta anni'],2,'Consultazione, autorizzazione anticipata e diffusione dei dati hanno discipline distinte.')],
8:[
('REICAT è:',['Un codice di catalogazione','Il nome del catalogo di ogni biblioteca','Un servizio di prestito','Un formato immagine'],0,'Le regole catalografiche non coincidono con un catalogo o un formato tecnico.'),
('Due persone hanno lo stesso nome. L’authority control serve a:',['Fonderle per abbreviare il catalogo','Attribuire loro lo stesso ISBN','Distinguere identità mediante informazioni attendibili','Scegliere chi è più famoso'],2,'La stringa uguale non dimostra identità della persona.'),
('La collocazione di un esemplare indica principalmente:',['La tesi del libro','Dove reperire l’esemplare nella raccolta','La licenza di riuso','La nazionalità dell’autore'],1,'Classificazione e soggettazione rappresentano invece contenuti secondo criteri propri.'),
('Un articolo non disponibile localmente può essere richiesto come riproduzione tramite:',['ILL in ogni circostanza','Authority control','Soggettazione','DD, verificando condizioni e diritti'],3,'Il document delivery riguarda la riproduzione consentita; ILL il prestito del documento.'),
('UNIMARC e SBNMARC sono rispettivamente:',['Formato dei dati e protocollo di colloquio con l’Indice','Due editori','Due sezioni della biblioteca','Due licenze aperte'],0,'La distinzione separa rappresentazione dei dati e interazione fra sistemi.'),
('Manca il luogo di edizione del libro in esame. Il catalogatore:',['Lo inventa dal cognome dell’autore','Usa la città della biblioteca','Verifica il documento e applica le regole per il dato non disponibile','Copia quello di un’altra edizione senza verifica'],2,'La completezza non si ottiene inserendo dati privi di evidenza.')],
9:[
('US 12 taglia US 10 ed è riempita da US 13. L’ordine più antico→recente è:',['12, 10, 13','10, 12, 13','13, 12, 10','10, 13, 12'],1,'Il deposito precede il taglio e il taglio precede il suo riempimento.'),
('Un’unità negativa registra:',['Un errore nella numerazione','Un oggetto privo di valore','Un’azione di asportazione riconoscibile','Sempre un deposito naturale'],2,'Il taglio è una testimonianza dell’azione che ha rimosso materiale.'),
('Il numero identificativo US 13 prova che l’unità è del XIII secolo?',['No, identifica l’unità e non la data assoluta','Sì, per convenzione nazionale','Solo se il terreno è urbano','Solo quando è un riempimento'],0,'La cronologia richiede rapporti ed evidenze ulteriori, non il numero di scheda.'),
('Il ritrovamento fortuito ex art. 90 va denunciato entro:',['Trenta giorni','Sessanta giorni','Sette giorni','Ventiquattro ore'],3,'La denuncia avviene a soprintendente, sindaco o autorità di pubblica sicurezza.'),
('Il reperto mobile può essere rimosso dal rinvenitore:',['Per facilitarne la pulizia','Quando la custodia non è altrimenti assicurabile, nelle condizioni di legge','Ogni volta che intralcia i lavori','Soltanto dopo averne stabilito il prezzo'],1,'L’eccezione di custodia non autorizza scavo o manipolazioni arbitrarie.'),
('Le cose culturali rinvenute nel sottosuolo ex art. 91:',['Sono sempre del proprietario del fondo','Sono dell’impresa che scava','Appartengono allo Stato nel regime pertinente','Diventano comunali dopo ventiquattro ore'],2,'La proprietà del terreno non attribuisce automaticamente la proprietà del ritrovamento.')],
10:[
('La Nascita di Venere degli Uffizi è:',['Tempera su tela, circa 1485','Affresco del Seicento','Olio su tavola del Settecento','Scultura ellenistica'],0,'Tecnica, supporto e cronologia sono dati catalografici da distinguere.'),
('La committenza medicea nella scheda istituzionale è:',['Esclusa','Provata dalla misura della tela','Probabile, da non trasformare in certezza','Dedotta dal numero d’inventario'],2,'Il grado di certezza della fonte va conservato nella risposta.'),
('Il soggetto classico di un’opera rinascimentale:',['La rende automaticamente antica','Va distinto dall’epoca di esecuzione','La colloca nel Barocco','Esclude qualunque funzione moderna'],1,'Tema rappresentato e data dell’opera sono dimensioni differenti.'),
('Una scheda ragionata dovrebbe separare:',['Solo prezzo e notorietà','Solo titolo e dimensioni','Opinione e gusto senza fonti','Dati, osservazione e interpretazione motivata'],3,'La separazione permette di controllare gli errori e le attribuzioni incerte.'),
('Un percorso museale accessibile richiede anche:',['Mediazione e comprensibilità dei contenuti','Eliminazione delle informazioni scientifiche','Accesso senza alcun limite conservativo','Sola riduzione del prezzo'],0,'La fruizione culturale comprende comprensione e servizi per pubblici diversi.'),
('Un condition report è utile soprattutto per:',['Sostituire l’autorizzazione al prestito','Attribuire definitivamente l’opera','Documentare lo stato e confrontarlo nel tempo','Stabilire sempre il valore economico'],2,'La documentazione conservativa rende osservabili cambiamenti e responsabilità.')],
11:[
('L’art. 29 collega conservazione a:',['Solo restauro quando compare danno','Studio, prevenzione, manutenzione e restauro coordinati','Sola esposizione al pubblico','Solo sorveglianza del custode'],1,'La conservazione è programmata e non coincide con un intervento isolato.'),
('La prevenzione interviene principalmente su:',['Firma del catalogatore','Prezzo del bene','Situazioni di rischio nel contesto','Ordine alfabetico degli autori'],2,'Ridurre i rischi anticipa il danno, senza attendere un restauro.'),
('La manutenzione mira a mantenere:',['Integrità, efficienza funzionale e identità del bene','Soltanto valore assicurativo','Solo colore originario presunto','Qualsiasi uso desiderato dal proprietario'],0,'La definizione non autorizza alterazioni dettate da preferenze estetiche.'),
('Restauro e manutenzione dei beni mobili culturali e superfici decorate competono:',['A chiunque abbia esperienza informale','Sempre al personale di vigilanza','Solo al direttore amministrativo','Ai restauratori qualificati secondo la disciplina'],3,'La classificazione dell’attività non sostituisce la qualificazione professionale richiesta.'),
('Un custode osserva un distacco. Deve:',['Riattaccarlo per evitare attese','Registrare e segnalare attivando le competenze previste','Scegliere un adesivo generico','Ometterlo se il pubblico non lo vede'],1,'La tempestività non autorizza interventi tecnici improvvisati.'),
('La documentazione prima e dopo l’intervento permette di:',['Eliminare ogni incertezza storica','Sostituire ogni controllo successivo','Confrontare condizioni e ricostruire scelte ed effetti','Evitare l’identificazione del bene'],2,'La tracciabilità sostiene la continuità conservativa e il controllo delle decisioni.')],
12:[
('La stessa traccia su una rampa in palazzo tutelato richiede al profilo architetto:',['L’approfondimento tecnico previsto dal bando','Solo una nota identica a quella amministrativa','Nessuna valutazione di alternative','Solo il numero dei visitatori'],0,'La distinzione dei ruoli non esclude la progettazione quando è parte della prova.'),
('Per il profilo amministrativo, una nota istruttoria deve individuare:',['La soluzione strutturale senza dati','Solo la finalità dell’evento','Vincoli, elaborati, competenze e titoli necessari','Il materiale più economico senza confronto'],2,'L’istruttoria rende controllabile la sequenza delle decisioni.'),
('La compatibilità di una trasformazione va motivata rispetto a:',['Preferenza personale del progettista','Valori e caratteristiche del bene, effetti e alternative','Numero di pagine del progetto','Sola convenienza economica'],1,'La motivazione collega conoscenza del bene e scelta, non solo opportunità.'),
('Un titolo edilizio ottenuto su immobile tutelato:',['Assorbe sempre l’art. 21','Elimina il vincolo culturale','Consente qualunque variante','Non sostituisce automaticamente gli altri titoli necessari'],3,'Edilizia, paesaggio e tutela culturale hanno presupposti e oggetti distinti.'),
('Se la traccia non dà dimensioni e condizioni strutturali, la risposta:',['Indica gli accertamenti necessari senza inventare dati','Sceglie valori convenzionali dichiarandoli reali','Omette ogni verifica','Considera l’intervento certamente fattibile'],0,'Una proposta motivata distingue dati, ipotesi e informazioni mancanti.'),
('Le prescrizioni dell’autorizzazione nel cantiere:',['Sono meri suggerimenti estetici','Valgono solo fino all’apertura','Devono essere trasferite agli atti esecutivi e controllate','Sono sostituite dal consenso dell’impresa'],2,'La fase esecutiva deve rispettare le condizioni della decisione autorizzativa.')],
13:[
('Il lavoratore rileva un pericolo. L’art. 20 richiede:',['Attesa della fine del turno','Segnalazione immediata e condotta coerente con formazione e istruzioni','Intervento tecnico senza limiti','Comunicazione soltanto ai visitatori'],1,'Tempestività e rispetto delle competenze devono operare insieme.'),
('L’operatore di accoglienza è automaticamente addetto a tutte le emergenze?',['Sì, se lavora in museo','Sì, se conosce l’edificio','No, compiti e formazione specifici vanno distinti','No, quindi non ha obblighi di segnalazione'],2,'La distinzione degli incarichi non elimina gli obblighi di ogni lavoratore.'),
('Odore di bruciato in sala: la prima risposta organizzativa è:',['Comunicare luogo e fatti attraverso il piano e attuare i propri compiti','Cercare il guasto nel quadro elettrico','Attendere la conferma di un visitatore esperto','Continuare la visita per evitare allarme'],0,'Non si confonde la segnalazione tempestiva con una riparazione estranea al ruolo.'),
('La capienza applicabile si ricava:',['Dai biglietti venduti quel giorno','Dalla capienza del museo vicino','Dall’abitudine degli operatori','Dalle condizioni autorizzate e disposizioni del sito'],3,'Un numero improvvisato non sostituisce il limite pertinente alla struttura.'),
('Dopo un’anomalia il registro dovrebbe distinguere:',['Solo persone simpatiche e difficili','Fatti osservati, tempi e comunicazioni dalle ipotesi','Solo il nome del turno','Opinioni senza data'],1,'La ricostruzione deve essere verificabile e non trasformare supposizioni in fatti.'),
('L’assistenza a utenti con difficoltà in emergenza deve seguire:',['Improvvisazione individuale','La soluzione più rapida comunque eseguibile','Compiti assegnati, piano e raccordo con gli addetti','Esclusione preventiva di quegli utenti'],2,'L’accessibilità deve essere organizzata e compatibile con formazione e sicurezza.')]
}
keys={}
for c,qs in Q.items():
 p=next(B.glob(f'{c:02}-*.md'));t=p.read_text(encoding='utf8');m=re.search(r'^#{2,3} ▣ Verifica[^\n]*\n',t,re.M);assert m,p
 before=t[:m.start()];old=t[m.end():];tail='';r=re.search(r'^## Riferimenti[^\n]*\n',old,re.M)
 if r:tail=old[r.start():]
 out='## ▣ Verifica\n\n';keys[str(c)]=[]
 for i,(stem,options,key,why) in enumerate(qs,1):
  letter='ABCD'[key];keys[str(c)].append(letter);out+=f'**Quiz {i}.** {stem}\n\n'+'\n'.join(f'{l}. {o}' for l,o in zip('ABCD',options))+f'\n\n**Risposta corretta: {letter}.** {why}\n\n'
 p.write_text(before+out+tail,encoding='utf8')
(A/'M-IR04-quiz-keys.json').write_text(json.dumps(keys,indent=2),encoding='utf8')
print('78 quiz IR04 disciplinari sostituiti')
