from pathlib import Path
import re,json
B=Path('wiki/books/moduli/m-sa02-professioni-sanitarie')
S=Path('wiki/sources')
def addsource(name,text):
 p=S/(name+'.md');s=p.read_text(encoding='utf-8');s=re.sub(r'^updated_at:.*$', 'updated_at: 2026-10-03',s,flags=re.M);p.write_text(s+'\n## Integrazione concettuale verificata il 3 ottobre 2026\n\n'+text+'\n',encoding='utf-8')
addsource('arresto-cardiaco-bls-iss-snlg-2026', 'La lettura mirata del PDF ISS-SNLG acquisito (sezione sul riconoscimento telefonico, pp. 165–166) conferma che respirazione agonale/gasping e valutazioni prolungate possono ritardare il riconoscimento e l’allerta. Nel testo didattico: persona non responsiva con respiro assente o anormale, attivazione immediata della risposta, compressioni e DAE secondo formazione e istruzioni del sistema di emergenza. Non si usa il gasping come prova di respirazione normale.')
addsource('als-adulto-erc-irc-2025','Nel PDF ERC/IRC 2025, quadro ALS e algoritmo: fibrillazione ventricolare e tachicardia ventricolare senza polso sono ritmi defibrillabili; asistolia e attività elettrica senza polso non lo sono. La ricerca delle cause reversibili comprende ipossia, ipovolemia, alterazioni metaboliche/elettrolitiche, ipotermia, trombosi coronarica/polmonare, tamponamento, pneumotorace iperteso e tossici. Distinzione concettuale, senza dosi, energie o sequenza operativa autonoma.')
addsource('puerperio-neonato-supporto-vitale-oms-irc-iss','La linea ERC/IRC 2025 acquisita, introduzione p. 3 e sezioni di valutazione, fonda la priorità della transizione respiratoria: aerazione polmonare e ventilazione efficace sostengono l’adattamento cardiocircolatorio. Il testo distingue questa fisiologia dall’arresto adulto e collega respirazione, frequenza cardiaca, tono e risposta al supporto. Apgar è descrittivo e non giustifica attesa prima di intervenire su una compromissione riconosciuta.')
addsource('emergenze-ostetriche-eclampsia-sepsi-tromboembolia-itoss','Definizioni consolidate: eclampsia come crisi convulsiva nel contesto della malattia ipertensiva ostetrica, non attribuibile ad altre cause; la diagnosi differenziale rimane necessaria. Riferimento ISS: https://www.epicentro.iss.it/itoss/pdf/Dossier-ipertensione-gravidanza-2016.pdf. Il dossier sepsi acquisito, pp. 5–6, definisce la sepsi materna attraverso infezione e disfunzione d’organo durante gravidanza, parto, post-aborto o puerperio: la febbre isolata non basta e la sua assenza non esclude la condizione. Sono definizioni, non recepimento dei regimi terapeutici storici dei dossier.')
addsource('emergenze-ostetriche-distocia-spalla-prolasso-funicolo-protocolli-italiani','Definizioni ricontrollate nelle pagine RCOG il 3 ottobre 2026: https://www.rcog.org.uk/guidance/browse-all-guidance/green-top-guidelines/shoulder-dystocia-green-top-guideline-no-42/ e https://www.rcog.org.uk/guidance/browse-all-guidance/green-top-guidelines/umbilical-cord-prolapse-green-top-guideline-no-50/. La distocia richiede manovre aggiuntive per liberare la spalla dopo la nascita della testa; il prolasso è discesa del cordone attraverso la cervice accanto o oltre la parte presentata a membrane rotte. Nel capitolo entrano riconoscimento e rischio, non una sequenza di manovre.')
p=B/'chapters/05-valutazione-clinica-triage-urgenza-emergenza.md';s=p.read_text(encoding='utf-8')
s=s.replace('### Dal supporto di base alla risposta avanzata', '''La combinazione da riconoscere è **mancata risposta e respirazione assente o anormale**. Il gasping, cioè respiri agonici irregolari, non è respirazione normale e non rassicura. Si attiva subito il sistema di emergenza; la valutazione non deve trasformarsi in un'attesa della certezza diagnostica. Il supporto di base comprende compressioni toraciche, ventilazioni secondo formazione e contesto e uso precoce del DAE seguendone le istruzioni. Durante analisi ed eventuale scarica occorre impedire il contatto con la persona.

L'ALS distingue due gruppi: **fibrillazione ventricolare e tachicardia ventricolare senza polso**, defibrillabili; **asistolia e attività elettrica senza polso**, non defibrillabili. «Non defibrillabile» non significa non trattabile: proseguono rianimazione, trattamento avanzato e ricerca della causa. Le cause reversibili includono ipossia, ipovolemia, alterazioni metaboliche ed elettrolitiche, ipotermia, trombosi coronarica o polmonare, tamponamento cardiaco, pneumotorace iperteso e tossici. Il team le ricerca sulla base del contesto, senza ritardare il supporto.

**Caso.** Un adulto crolla, non risponde e presenta pochi respiri irregolari. Il gasping non permette di concludere che respiri normalmente: la risposta corretta riconosce il sospetto arresto, attiva aiuto e DAE e avvia il supporto previsto. Se il DAE non consiglia la scarica, non si conclude che l'emergenza sia cessata: si seguono le istruzioni e si continua la risposta.

### Dal supporto di base alla risposta avanzata''')
s=s.replace('### Team, trasferimento e famiglia','''La differenza fisiologica centrale è l'avvio della respirazione dopo la nascita: l'aerazione dei polmoni e una ventilazione efficace sostengono il passaggio alla circolazione extrauterina. La compromissione neonatale è spesso legata a questa transizione; perciò la ventilazione ha un ruolo decisivo e non va sostituita da una trasposizione del ragionamento sui ritmi dell'adulto. Il team valuta respirazione, frequenza cardiaca e tono e controlla se il supporto produce una risposta. Il punteggio di Apgar descrive le condizioni a tempi definiti, ma non è un requisito da attendere prima di assistere un neonato compromesso.

**Caso.** Dopo la nascita il neonato è ipotonico e non respira efficacemente. Il candidato collega il dato a una transizione respiratoria inadeguata, richiede il team preparato, protegge dal raffreddamento e descrive la priorità del supporto ventilatorio e della rivalutazione secondo algoritmo neonatale. Aspettare il successivo punteggio di Apgar o applicare automaticamente l'algoritmo adulto sono errori di ragionamento.

### Team, trasferimento e famiglia''')
s=s.replace('ItOSS documenta tre aree di rischio materno:', '''L'**eclampsia** è la comparsa di crisi convulsive nel contesto della malattia ipertensiva ostetrica, non spiegate da altre cause. Può manifestarsi in gravidanza, durante il parto o nel puerperio. Cefalea intensa, disturbi visivi ed epigastralgia sono segnali di allarme; non sono però necessari perché si verifichi una crisi e non sostituiscono la diagnosi differenziale neurologica e metabolica.

La **sepsi materna** comporta una disfunzione d'organo dovuta a infezione nel corso della gravidanza, del parto, dopo un aborto o nel puerperio. Febbre e infezione non sono sinonimi di sepsi; viceversa, l'assenza di febbre non la esclude. Alterazioni dello stato mentale, dispnea, compromissione circolatoria o riduzione della diuresi nel contesto infettivo richiedono attenzione immediata. Il tromboembolismo venoso comprende trombosi venosa profonda ed embolia polmonare: dolore e gonfiore monolaterale di un arto o dispnea improvvisa con dolore toracico orientano il sospetto, senza confermarlo da soli.

ItOSS documenta tre aree di rischio materno:''')
s=s.replace('Distocia di spalla e prolasso di funicolo sono emergenze ostetriche', '''Nella **distocia di spalla**, dopo la nascita della testa una spalla rimane bloccata e occorrono manovre ostetriche aggiuntive per completare il parto. La difficoltà non va affrontata aumentando indiscriminatamente la trazione: richiede riconoscimento e intervento coordinato di personale addestrato. I rischi comprendono danno neonatale e materno.

Nel **prolasso di funicolo**, a membrane rotte, il cordone scende attraverso la cervice accanto o oltre la parte fetale presentata. La compressione può compromettere il flusso ematico fetale; alterazioni improvvise della frequenza cardiaca fetale dopo la rottura delle membrane rendono urgente la valutazione. La presentazione del cordone e il prolasso non sono termini intercambiabili.

Distocia di spalla e prolasso di funicolo sono emergenze ostetriche''')
p.write_text(s,encoding='utf-8')
# Repair an empty source heading left by insertion.
p=S/'presa-in-carico-cronicita-pdta-territorio-agenas.md';s=p.read_text(encoding='utf-8').replace('## Uso editoriale\n\n## Modelli','## Modelli');p.write_text(s,encoding='utf-8')
p=S/'premal-definizioni-caso-risposta-segnale-epidemiologico.md';s=p.read_text(encoding='utf-8');s=s.replace('## Definizione di caso: due livelli da non confondere\n\n## Termini','## Termini');p.write_text(s,encoding='utf-8')
files=[*list((B/'chapters').glob('06-*.md')),*list((B/'chapters').glob('08-*.md')),S/'presa-in-carico-cronicita-pdta-territorio-agenas.md',S/'premal-definizioni-caso-risposta-segnale-epidemiologico.md',S/'programmi-screening-oncologici-dati-passi-iss.md']
for p in files:
 s=p.read_text(encoding='utf-8');s=re.sub(r'^updated_at:.*$', 'updated_at: 2026-10-03',s,flags=re.M);s=re.sub(r'^review_required:.*$', 'review_required: true',s,flags=re.M)
 if '/chapters/' in p.as_posix():s=re.sub(r'^draft_stage:.*$', 'draft_stage: revision-in-progress',s,flags=re.M)
 p.write_text(s,encoding='utf-8')
batch={}
for n,desc,paths in [(20,'Integrate definizioni, riconoscimento, ritmi ALS e cause reversibili, fisiologia NLS e casi risolti; definite le emergenze ostetriche.', [str(B/'chapters/05-valutazione-clinica-triage-urgenza-emergenza.md')]),(21,'Esposti standard e funzioni DM77 con rinvio SA01 e distinzione fra programmazione e attuazione.',[str(B/'chapters/06-prevenzione-continuita-presa-in-carico.md'),str(S/'presa-in-carico-cronicita-pdta-territorio-agenas.md')]),(22,'Corretta interpretazione degli scarti PASSI: causa non dimostrata e incompatibilità con il solo arrotondamento.',[str(B/'chapters/08-igiene-pubblica-epidemiologia-screening.md'),str(S/'programmi-screening-oncologici-dati-passi-iss.md'),str(B/'planning/03-batteria-esercizi-epidemiologia-screening.md')]),(23,'Distinta definizione di caso da definizione di focolaio.',[str(B/'chapters/08-igiene-pubblica-epidemiologia-screening.md')]),(24,'Aggiunti programmi oncologici nazionali e termini PREMAL, con varianti regionali e distinzione dei ruoli.',[str(B/'chapters/08-igiene-pubblica-epidemiologia-screening.md'),str(S/'premal-definizioni-caso-risposta-segnale-epidemiologico.md')])]:
 batch[f'V07-{n:02}']={'change':desc,'files':[p.replace('\\','/') for p in paths],'evidence':'Rilettura del delta e riscontro nelle fonti ufficiali consolidate. Revisione step 15 e nuovo PDF pendenti.','status':'applicato'}
Path('artifacts/correzioni-collana-2026-10-02/VOL-07-batch04.json').write_text(json.dumps(batch,ensure_ascii=False,indent=2),encoding='utf-8')
