from pathlib import Path
import re
S=Path('wiki/sources')
def add(name,text):
 p=S/(name+'.md'); s=p.read_text(encoding='utf8')
 s=re.sub(r'^updated_at:.*$','updated_at: 2026-10-03',s,flags=re.M)
 p.write_text(s+'\n## Integrazione verificata il 3 ottobre 2026\n\n'+text+'\n',encoding='utf8')
add('qualita-biosicurezza-laboratorio-tslb','''Il manuale OMS sul QMS, capitoli 6–8 (in particolare pp. 83 e 87–90), sostiene la distinzione tra dispersione delle misure ripetute, scostamento sistematico e controllo indipendente della prestazione. La calibrazione stabilisce la relazione segnale-valore; il controllo verifica il comportamento del sistema e non serve a correggere artificialmente i risultati per farli rientrare. Il grafico di Levey–Jennings colloca risultati successivi rispetto a media e deviazioni standard; trend e shift richiedono valutazione anche prima di una singola uscita estrema. Le regole di accettazione dipendono dal piano QC validato: non si trasferisce la semplice regola didattica ±2 SD del manuale OMS a ogni metodo.

La sintesi disciplinare distingue misura di analiti tramite principi ottici o elettrochimici, identificazione microbiologica tramite coltura/rilevazione molecolare, conta e morfologia ematologica, reazione antigene-anticorpo. Sono principi introduttivi: sensibilità analitica, interferenze, cross-reattività e vitalità non si deducono dalla sola positività. Preparazione istologica e citologica preserva struttura e rappresentatività, senza assegnare diagnosi al TSLB.

La [edizione INL gennaio 2026 del D.Lgs. 81/2008](https://www.ispettorato.gov.it/files/2026/01/TU-81-08-Ed.-Gennaio-2026.pdf), copia valida acquisita in `wiki/raw/correzioni-collana-2026-10-02/inl-dlgs81-gennaio2026.pdf`, è stata consultata agli artt. 268 e 275 (pp. PDF 242 e 245–246). Gruppi 1–4 distinguono capacità patogena, gravità, diffusione e disponibilità di profilassi/cure. Per uso deliberato dei gruppi 2/3/4, livelli minimi di contenimento 2/3/4; materiali potenzialmente contaminati almeno livello 2; agenti non classificati il cui uso può provocare grave rischio almeno livello 3. La valutazione OMS non deroga agli obblighi del Titolo X e degli allegati XLVI–XLVII.

Il manuale OMS di biosicurezza distingue cappe biologiche I (persona/ambiente), II (anche prodotto), III (contenimento chiuso); il banco a flusso laminare per il prodotto e la cappa chimica non sono equivalenti a una cappa biologica. La filtrazione HEPA non costituisce protezione universale dai vapori chimici. Detersione rimuove materiale, disinfezione inattiva microrganismi in un ambito definito, sterilizzazione è un processo validato per eliminare microrganismi vitali comprese spore. Non introdotti tempi o concentrazioni universali.

[D.P.R. 254/2003, art. 2](https://www.gazzettaufficiale.it/atto/serie_generale/caricaArticolo?art.codiceRedazionale=003G0282&art.dataPubblicazioneGazzetta=2003-09-11&art.flagTipoArticolo=0&art.idArticolo=2&art.idGruppo=1&art.idSottoArticolo=1&art.idSottoArticolo1=10&art.progressivo=0&art.versione=1): distinti rifiuti non pericolosi, pericolosi non infettivi, pericolosi infettivi e particolari gestioni (farmaci, citotossici/citostatici e altre categorie). La collocazione in laboratorio non rende da sola infettivo ogni rifiuto. Lettura puntuale delle categorie, non attestazione di tutte le regole del ciclo rifiuti e del D.Lgs. 152/2006.''')
add('radioprotezione-qualita-immagine-apparecchiature-dlgs-101-2020','''La dosimetria introduttiva è riferita ai manuali IAEA [Quality Assurance Programme for Computed Tomography, Pub. 1557](https://pub.iaea.org/MTCD/Publications/PDF/Pub1557_web.pdf) e [TECDOC 1985](https://www-pub.iaea.org/MTCD/Publications/PDF/TE-1985web.pdf). CTDIvol (mGy) è un indice standardizzato basato su fantoccio; DLP (mGy·cm) combina indice e lunghezza, con somma delle serie quando pertinente. Il prodotto kerma-area, spesso chiamato DAP, è espresso in Gy·cm²; non è una dose cutanea individuale. Gli indici non si convertono automaticamente in dose efficace o rischio personale. Reazioni tissutali: soglia e gravità dose-dipendente; effetti stocastici: probabilità dose-dipendente, modello prudenziale senza soglia per radioprotezione. Tempo, distanza e schermatura sono principi, non autorizzano calcoli universali in geometrie reali.

Consultato il [D.Lgs. 101/2020 riprodotto dalla Protezione civile](https://www.protezionecivile.gov.it/en/normativa/dlgs-n101-del-31-luglio-2020/), artt. 146 e 166. Per lavoratori esposti: 20 mSv/anno dose efficace; dose equivalente 20 cristallino, 500 pelle mediata su 1 cm², 500 estremità. Popolazione: 1 mSv efficace, 15 cristallino, 50 pelle. Sono limiti per le categorie e condizioni normative, non valori da applicare al paziente. Il testo di quella pagina è originario: il confronto con modifiche e testo consolidato resta un punto del successivo audit normativo; la tabella non è certificata soltanto da questa acquisizione.

Il [D.M. 14 gennaio 2021, allegato](https://www.gazzettaufficiale.it/atto/serie_generale/caricaArticolo?art.codiceRedazionale=21A01353&art.dataPubblicazioneGazzetta=2021-03-16&art.flagTipoArticolo=1&art.idArticolo=1&art.idGruppo=0&art.idSottoArticolo=1&art.idSottoArticolo1=10&art.progressivo=0&art.versione=1), sezioni D.1–D.4, prescrive regolamento di sicurezza, valutazione dei dispositivi impiantati, etichette safe/conditional/unsafe, organizzazione delle emergenze e verifica della gravidanza. Rischi da campo statico (oggetti ferromagnetici), RF (riscaldamento/ustioni), gradienti (rumore e stimolazione), criogeni (ipossia e sovrapressione in caso di rilascio) sono distinti. La RM non usa radiazioni ionizzanti; ciò non elimina rischi e valutazione rischio-beneficio. La gravidanza, anche nell'imaging ionizzante, richiede giustificazione e ottimizzazione dedicate, non diniego automatico né esenzione dai controlli.''')
add('dispositivi-medici-ivd-vigilanza-rischio-tecnologico-2026','''L'incidente grave comprende conseguenze effettive o possibili, dirette o indirette: morte, grave deterioramento temporaneo o permanente della salute, grave minaccia per la salute pubblica. Il D.M. 31 marzo 2022 recepisce tali definizioni per la rete. Restano corretti i termini degli operatori dei D.M. 1° luglio 2025: tempestivamente entro dieci giorni per grave, facoltà entro trenta per non grave; non si sostituiscono con i diversi termini dei fabbricanti.

Fonti ufficiali consultate: [Ministero, classi MDR](https://www.salute.gov.it/new/it/tema/dispositivi-medici/procedure-di-valutazione-della-conformita-dei-dispositivi-medici/) (contenuto indicizzato: apertura diretta bloccata), [Commissione, quadro IVDR e classi](https://health.ec.europa.eu/medical-devices-vitro-diagnostics/transitional-provisions_en), [Commissione, UDI](https://health.ec.europa.eu/medical-devices-topics-interest/unique-device-identifier-udi_it), [INFARMED, definizioni vigilanza](https://www.infarmed.pt/web/infarmed/entidades/dispositivos-medicos/vigilancia-de-dispositivos-medicos). MDR: I, IIa, IIb, III; IVDR: A, B, C, D. La classificazione deriva da destinazione e regole dell'allegato VIII del rispettivo regolamento, non da prezzo o complessità apparente. UDI-DI identifica fabbricante/modello; UDI-PI identifica produzione, ad esempio lotto o seriale. UDI non sostituisce etichetta né inventario locale. FSCA è l'azione del fabbricante per prevenire/ridurre un incidente grave; FSN è la comunicazione relativa a tale azione agli utilizzatori/clienti. I tentativi di aprire i PDF consolidati EUR-Lex hanno restituito challenge, non un regolamento acquisito: nessuna falsa attestazione di lettura integrale.''')
