from pathlib import Path
import re,json,hashlib,datetime
B=Path('wiki/books/moduli');R=Path('wiki/reviews/pipeline/VOL-07');A=Path('artifacts/correzioni-collana-2026-10-02')
for name in ['premal-definizioni-caso-risposta-segnale-epidemiologico','programmi-screening-oncologici-dati-passi-iss','deontologia-biologo-farmacista-psicologo-2026','governo-clinico-appropriatezza-hta-qualita-accreditamento','sicurezza-cure-responsabilita-consenso-leggi-24-219']:
 p=Path('wiki/sources')/(name+'.md');s=p.read_text(encoding='utf8')
 s=s.replace('Lette per questi claim passaggi','Letti per questi claim i passaggi')
 s=s.replace('Il nucleo resta `parziale` finché manca la review epidemiologica indipendente.','Il precedente vincolo di review è superato dal riesame automatico del 3 ottobre 2026: calcoli, limiti inferenziali e definizioni sono verificati nel report 15 M-SA02 corrente.')
 s=s.replace('Il pacchetto di review è pronto, ma non ancora eseguito: il nucleo `SA02-06` resta `parziale` finché la batteria quantitativa e lo scenario non ricevono una review epidemiologica indipendente e non viene effettuato il controllo di versione prepubblicazione.','Batteria quantitativa e scenario sono stati riesaminati il 3 ottobre 2026: 96/112 = 85,7%, attacco 24/96 = 25%, RR A = 13 e RR B = 1; definizione di caso didattica, associazione e causalità sono distinte. Il flusso PREMAL è confrontato con gli artt. 4–5 del decreto. Esito nel report 15 M-SA02 corrente; non si validano procedure territoriali escluse dal manuale.')
 s=s.replace('Bloccata per uso clinico-operativo finché non sono acquisite linee guida e buone pratiche pertinenti e non interviene review umana.','L’uso clinico-operativo in casi reali è fuori dal perimetro del manuale. Il riesame automatico giuridico dei claim concorsuali è documentato nel report 15 M-SA02 del 3 ottobre 2026.')
 s+='\n## Esito editoriale corrente\n\nRiesame automatico dei claim recepiti nei capitoli concluso il 3 ottobre 2026 nei report 15 M-SA02/M-SA03 pertinenti. Questa attestazione aggiorna i rinvii storici a future review; non amplia il perimetro a procedure locali o a tutti gli articoli del corpus. Le fonti mobili mantengono versione e ambito dichiarati.\n'
 s=re.sub(r'^review_required:.*$','review_required: false',s,flags=re.M);p.write_text(s,encoding='utf8')
for code,m in [('M-SA02','m-sa02-professioni-sanitarie'),('M-SA03','m-sa03-dirigenza-medica-sanitaria')]:
 files=sorted((B/m/'chapters').glob('*.md')); entries=[{'path':str(p).replace('\\','/'),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'status':'text-freeze','date':'2026-10-03'} for p in files]
 assert all('review_required: false' in p.read_text(encoding='utf8') for p in files)
 manifest={'volume':'VOL-07','module':code,'date':'2026-10-03','gate':'text-freeze','verification':'manuale; gate non implementato, nessun verde automatico simulato','files':entries,'checks':['Capitoli canonici presenti; assenza SA02/02 intenzionale.','Delta audit integrale applicati e riesaminati; nessun errore testuale noto aperto nel modulo.','Rinvii per profilo precisi; nessun rinvio a wiki nel corpo pubblico.','Humanizer e micro-revisione sui delta; audit15 passed zero warning.','SA02/05 densità e copertura passed; 2 DO coerenti.','Fonti, cut-off, esempi e soluzioni distinti; norme verificate selettivamente.'],'limitations':['Non è freeze di VOL-07 nel suo complesso: SA01/SA04 e apparati hanno stato separato.','PDF nuovi e controllo visivo ancora necessari.']}
 (A/f'{code}-freeze.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf8')
 p=R/f'16-moduli-{m}.md';arc=R/'archive'/('pre-correzioni-'+p.name)
 if p.exists() and not arc.exists():arc.write_bytes(p.read_bytes())
 t=f'# {code} — Manifest di congelamento del testo, 3 ottobre 2026\n\nVerifica manuale eseguita perché il CLI restituisce `gate-not-implemented` per `text-freeze`. Non è dichiarato un gate automatico implementato. Il successivo comando `--accept` documenta questa verifica sostanziale.\n\n'+ '\n'.join('- '+x for x in manifest['checks'])+'\n\n| File | Stato | Data | SHA-256 |\n| --- | --- | --- | --- |\n'+ '\n'.join('| '+e['path']+' | text-freeze | '+e['date']+' | '+e['sha256']+' |' for e in entries)+'\n\nLimiti: '+' '.join(manifest['limitations'])+'\n\nManifest JSON: `artifacts/correzioni-collana-2026-10-02/'+code+'-freeze.json`. Una modifica sostanziale richiede riapertura dei gate; non modificare il run-state a mano.\n'
 p.write_text(t,encoding='utf8')
print('Manifest SA02/SA03 scritti; source note pertinenti riconciliate con riesame corrente.')
