from pathlib import Path
import re,json,hashlib
B=Path('wiki/books/moduli'); V=Path('wiki/books/volumi/vol-07-sanita-amministrativa-professioni-sanitarie/planning');R=Path('wiki/reviews/pipeline/VOL-07')
mods=['m-sa01-sanita-amministrativa','m-sa02-professioni-sanitarie','m-sa03-dirigenza-medica-sanitaria','m-sa04-tecnici-sanitari-prevenzione']
def save(p,s):
 s=re.sub(r'^updated_at:.*$','updated_at: 2026-10-03',s,flags=re.M);s=re.sub(r'^review_required:.*$','review_required: true',s,flags=re.M);p.write_text(s,encoding='utf8')
def archive(p):
 q=R/'archive'/('pre-correzioni-'+p.name);q.parent.mkdir(exist_ok=True)
 if not q.exists():q.write_bytes(p.read_bytes())
p=B/mods[1]/'planning/03-batteria-esercizi-epidemiologia-screening.md';s=p.read_text(encoding='utf8')
s=s.replace('**Quesito:** stimare quale quota della copertura totale è attribuita alla componente organizzata.','**Quesito:** calcolare il rapporto numerico fra le due stime e indicare quali condizioni servono per interpretarlo come quota organizzata del totale.')
s=s.replace('**Interpretazione:** è un rapporto fra due stime di prevalenza, utile didatticamente. Non è una probabilità individuale né una misura di efficacia del programma.','**Interpretazione:** il calcolo è corretto come rapporto numerico. Per leggerlo come quota organizzata del totale occorre verificare che le stime condividano popolazione, denominatore, periodo, pesi e definizioni compatibili. Lo scarto fra componenti e totale rilevato nell’esercizio precedente impedisce di dare questa equivalenza per dimostrata. Non è una probabilità individuale né una misura di efficacia del programma.');save(p,s)
topic=Path('wiki/topics/sanita-amministrativa-professioni-sanitarie.md');s=topic.read_text(encoding='utf8')
s+='''\n## Raccordo delle correzioni del 3 ottobre 2026\n\nLe integrazioni sono applicate al testo e sottoposte al riesame di modulo; non equivalgono ancora a un nuovo freeze o a un controllo dei PDF. Registro analitico: [[reviews/correzioni-collana-2026-10-02/VOL-07]].\n\n- SA01: privacy/accesso, FSE/dossier, bilancio economico-patrimoniale, ammortamento, procurement, NSO, FEFO e riordino. Fonti: [[sources/documentazione-sanitaria-accesso-fse-dossier-privacy]], [[sources/contabilita-budget-aziende-sanitarie]], [[sources/procurement-farmaci-dispositivi-flussi-nsis]].\n- SA02: responsabilità/consenso, fondamenti assistenziali e ICA, NEWS2 e triage, BLS/ALS/NLS ed emergenze ostetriche nel perimetro concorsuale, standard DM 77, dati PASSI/PREMAL e procedure TPALL. Fonti: [[sources/sicurezza-cure-responsabilita-consenso-leggi-24-219]], [[sources/premal-definizioni-caso-risposta-segnale-epidemiologico]], [[sources/programmi-screening-oncologici-dati-passi-iss]], [[sources/tpall-aia-campionamenti-acque-aria-suolo-rifiuti-alimenti]].\n- SA03: obbligo inglese/informatica e griglie concorsuali nazionali, NSG/NSIS con indicatori, RCA/FMEA, caso differenziale e codice CNOP effettivamente vigente. Fonti: [[sources/dirigenza-sanitaria-concorsi-ccnl-2026]], [[sources/governo-clinico-appropriatezza-hta-qualita-accreditamento]].\n- SA04: principi analitici, QC, biosicurezza nazionale, dosimetria, RM e vigilanza MDR/IVDR. Fonti: [[sources/qualita-biosicurezza-laboratorio-tslb]], [[sources/radioprotezione-qualita-immagine-apparecchiature-dlgs-101-2020]], [[sources/dispositivi-medici-ivd-vigilanza-rischio-tecnologico-2026]].\n\nEntità collegate: [[entities/azienda-sanitaria]]. I collegamenti dei capitoli sono mantenuti nelle quattro matrici e nel registro per ID. Gli apparati originali di qualità dell’immagine e il grafico QC restano da inserire e verificare.\n''';save(topic,s)
for i,m in enumerate(mods):
 p=B/m/'planning/02-matrice-copertura-didattica.md';s=p.read_text(encoding='utf8');archive(p) if False else None
 s=re.sub(r'^status:.*$','status: revision_in_progress',s,flags=re.M)
 intro='''\n## Stato corrente dopo l’audit integrale\n\nLe attestazioni di chiusura nelle righe precedenti descrivono la baseline di agosto. Sono riaperte per i delta dell’audit integrale: il registro del 3 ottobre prevale su quella baseline. Le correzioni sono applicate, ma audit specialistico, nuovo freeze e PDF devono essere chiusi tramite CLI. Nessuna riga viene promossa soltanto perché il file esiste.\n\n'''
 details=[ 'SA01/04–10: V07-01–14, con ampliamento della copertura ai fondamenti SSN e integrazioni INT preservate.', 'SA02/01: quadro DPR 220; /03: responsabilità e consenso; /04: assistenza e ICA; /05: NEWS2, triage e principi emergenze; /06: standard DM 77; /08: PASSI, screening e PREMAL; /09: procedure amministrative/penali, sicurezza, AIA/AUA e alimenti; /10: casi con esito per profilo. Nuove domande e soluzioni sono effettivamente presenti.', 'SA03/01: DPR 483 e art. 37; /02: NSG/NSIS e cruscotto quantitativo; /03: autonomia medica chiarita; /04: SIMES/RCA/FMEA; /06: differenziale ragionato; /07: CNOP vigente. La fonte NSG ora contiene una copia ufficiale valida e distingue metodologia da risultati annuali.', 'SA04/01: DPR 220 e art. 37; /02: principi disciplinari, precisione/esattezza, calibrazione/QC, contenimento, cappe e rifiuti; /03: indicatori di dose, effetti, limiti e rischi RM; /04: classi, UDI, incidente grave e FSCA/FSN. V07-39 apparati e grafico di V07-35 ancora pendenti; la copertura dell’applicazione visiva resta parziale fino al loro inserimento.' ][i]
 s+=intro+details+'\n\nEvidenza: [[reviews/correzioni-collana-2026-10-02/VOL-07]] e report correnti degli step 14–15.\n';save(p,s)
p=V/'02-matrice-copertura-didattica.md';s=p.read_text(encoding='utf8');s=s.replace('41 nuclei didattici completi','45 righe di copertura dopo le quattro integrazioni SA01, il cui stato va letto nelle matrici correnti');s=s.replace('Questa matrice aggrega lo stato finale','Questa matrice aggrega lo stato di lavoro');s=re.sub(r'^status:.*$','status: revision_in_progress',s,flags=re.M);s+='\n## Riconciliazione del 3 ottobre 2026\n\nIl totale conta 12 righe SA01, 8 SA02, 15 SA03 e 10 SA04: 45 righe, non 45 attestazioni di pubblicabilità. Le attestazioni precedenti al nuovo audit sono storiche. Correzioni testuali V07-01–38 e V07-40–41 applicate; V07-39 e il grafico QC V07-35 restano agli apparati. Report, fonti e matrici di modulo conservano i limiti del confronto normativo. Nuovi freeze e PDF ancora necessari.\n';save(p,s)
p=V/'03-mappa-fonti-specialistiche.md';s=p.read_text(encoding='utf8');s=s.replace('Inventario operativo completo dell’','Inventario storico dell’')
s=s.replace('Inventario operativo completo dell\'`OUTPUT A` del dossier.', 'Inventario di acquisizione originario del luglio 2026, conservato per tracciabilità.')
s=s.replace('Tutte le aree didattiche restano parziali: la scrittura è bloccata fino alla chiusura dei gap registrati nella matrice M-SA02.','Questa frase descriveva il gate di luglio. Lo stato corrente è quello del CLI e dei report 14–15, riaperti dopo l’audit integrale; non esiste un blocco generale della scrittura deducibile da questo inventario storico.')
s+='''\n## Fonti correnti e riscontri di ottobre\n\nLe righe `da_acquisire` della tabella sono un piano storico, non una dichiarazione di assenza attuale. I profili TSLB/TSRM sono consolidati in [[sources/profili-professionali-tslb-tsrm-dm-745-746]], DPR 483/484 e CCNL Area Sanità in [[sources/dirigenza-sanitaria-concorsi-ccnl-2026]], radioprotezione in [[sources/radioprotezione-qualita-immagine-apparecchiature-dlgs-101-2020]], HTA/NSG in [[sources/governo-clinico-appropriatezza-hta-qualita-accreditamento]]. I corpus bandi SA03/SA04 sono quelli dichiarati nelle matrici correnti. Privacy, responsabilità, consenso, epidemiologia e biosicurezza hanno ricevuto delta puntuali. Le categorie dottrinali o giurisprudenziali senza fonte acquisita non diventano automaticamente promesse di copertura.\n\nIl nuovo registro correzioni traccia claim, file ed evidenze per ID. Nessuna risposta challenge/HTML antiautomazione viene classificata come fonte valida. La verifica delle norme è selettiva sui claim insegnati, non una certificazione di ogni atto del corpus.\n''';save(p,s)
spec=Path('wiki/reviews/correzioni-collana-2026-10-02/V07-39-specifica-apparati.md');spec.write_text(spec.read_text(encoding='utf8')+'''\n## Apparato aggiuntivo V07-35: controllo qualità\n\nDestinazione SA04/02, dopo tabella «Leggere una serie di controllo». Levey–Jennings originale: asse x sedute 1–8, asse y z da −3 a +4, valori 0; 0,5; 1; 1,5; 2; 2,5; 3; 3,5. Linee media, ±1, ±2, ±3, nero/grigio leggibile. Nessuna fascia verde/rossa o verdetto universale di accettazione.\n\nDidascalia: «Serie didattica di controllo: andamento crescente rispetto alla media. I valori standardizzati permettono di osservare il trend; le decisioni dipendono dalle regole del piano QC.» Domanda e soluzione sono già nel testo immediatamente seguente: non serve duplicarle nella figura. Il grafico non simula un risultato di un paziente.\n''',encoding='utf8')
print('Topic, matrici, mappa storica e specifica QC aggiornati; nessun gate dichiarato concluso.')
