from pathlib import Path
import re,shutil
p=Path('wiki/books/moduli/m-sp01-forze-ordine/chapters/10-checklist-finale.md');t=p.read_text(encoding='utf8');a=Path('wiki/reviews/correzioni-collana-2026-10-02/archive/pre-correzioni-sp01-10.md');assert not a.exists();shutil.copyfile(p,a)
t=t.replace('una scadenza scaduta','un termine decorso')
t=t.replace('La domanda si presenta solo dopo aver controllato requisiti, binario, scadenze, prove e documenti.','Prima dell’invio controlla requisiti, binario, termine e adempimenti; prepara le prove anche mentre attendi il calendario.')
t=t.replace('I dati mobili, come date, punteggi, soglie, documenti e strumenti ammessi, richiedono sempre la dicitura “Verifica sul bando”.','Distingui dato verificato, dato non ancora pubblicato, dato dubbio e voce non applicabile; registra sempre l’atto e la data del controllo.')
t=t.replace('La decisione finale è “go” solo se non restano criticità bloccanti e se le criticità correggibili hanno un’azione precisa.','Decidi separatamente se puoi presentare domanda e se il tuo investimento di preparazione è sostenibile.')
t=t.replace('requisito mancante, binario errato, impossibilità di documentare una dichiarazione, preparazione incompatibile con il tempo disponibile o rischio amministrativo non governato.','requisito mancante o termine decorso per l’accesso; preparazione incompatibile con il tempo disponibile per la sola scelta strategica. I due esiti vanno registrati separatamente.')
t=t.replace('eventuali certificazioni, ricevute e informazioni personali devono essere disponibili e coerenti.','eventuali certificazioni già richieste e informazioni personali devono essere disponibili e coerenti. La ricevuta di quella domanda si controlla soltanto dopo l’invio.')
t=t.replace('Per questo il candidato deve chiudere il nucleo di ammissibilità prima di pianificare lo scritto.','Il controllo di ammissibilità è prioritario; la pianificazione dello scritto può procedere in parallelo mentre si chiarisce un dato, senza rendere dichiarazioni incerte.')
t=t.replace('Nel binario base la commissione può cercare solidità, ordine espositivo e padronanza dei fondamentali.','Se il concorso base prevede un orale, la preparazione comprende solidità e ordine espositivo. Non tutti i percorsi lo prevedono: nel bando Carabinieri 3.081 del 2026 l’art. 6 elenca scritto, prove fisiche, accertamenti e titoli, senza un distinto orale.')
t=t.replace('La soglia verde richiede che il candidato abbia un piano orale, una tabella titoli, una verifica della lingua, una cartellina logistica e un calendario aggiornato.','La soglia verde riguarda le sole voci applicabili: piano orale se previsto, titoli se valutati, lingua secondo il bando, cartellina e calendario quando pubblicato. Una fase esclusa dalla procedura riceve “N/A — non applicabile” con il riferimento che lo dimostra.')
t=t.replace('Prima si chiudono i blocchi amministrativi, poi le prove, poi il consolidamento.','Gli adempimenti con scadenza hanno priorità; studio e consolidamento procedono in parallelo quando non impediscono di rispettarla.')
t=t.replace('Perché l’orale va preparato prima di superare lo scritto?','Se l’orale è previsto, perché conviene iniziare a prepararlo prima di superare lo scritto?')
new='''## N-SP01-15-05 · Due decisioni distinte e un piano di recupero

La checklist produce due decisioni: ammissibilità della domanda e sostenibilità della preparazione. La prima riguarda condizioni previste dal bando; la seconda riguarda tempo, competenze, costi e priorità personali. Una simulazione insufficiente può far scegliere di non investire in quel concorso, ma non introduce un requisito di ammissione che il bando non prevede. Viceversa, una preparazione eccellente non sostituisce un titolo richiesto entro un termine già decorso. Tenere separate le due schede evita di usare un colore come se fosse una norma.

Nella scheda di accesso, verde significa requisito verificato e adempimento eseguito o tempestivamente eseguibile. Giallo indica un punto da chiarire o completare prima del termine pertinente. Rosso indica un ostacolo accertato: per esempio, titolo mancante quando il bando lo richiede già alla scadenza, oppure termine di invio superato senza domanda valida. Il dubbio non diventa automaticamente esclusione: rimane “da chiarire”, con la domanda precisa e il riferimento da verificare. Non autorizza però a dichiarare come certo un dato che non lo è. Il candidato deve distinguere la propria verifica preliminare dalla decisione dell’amministrazione.

Nella scheda di preparazione, verde indica output sufficientemente stabili rispetto alle regole note; giallo una debolezza recuperabile con un programma concreto; rosso un obiettivo che il candidato ritiene insostenibile nel tempo disponibile. Questi colori descrivono il piano personale. Con 25 giorni, una materia nuova e 6 ore settimanali disponibili, il candidato può scegliere di rinunciare strategicamente oppure partecipare senza fare affidamento sull’esito. In entrambi i casi non scrive “sono giuridicamente escluso” soltanto perché non ha ancora svolto simulazioni. Quantifica invece il lavoro e il costo dell’alternativa.

La voce N/A serve quando una fase o un adempimento non si applica. Deve avere una ragione controllabile: “orale non previsto dall’articolo sulle prove”, “titoli non valutati in questa procedura”, “contributo non previsto dalle istruzioni di domanda”. Non si usa N/A per una pagina non letta. Se un calendario sarà comunicato con un avviso futuro, lo stato corretto è “non ancora pubblicato”, con il canale e la data di successivo controllo. Un dato già acquisito resta “verificato al…” e si monitora per eventuali modifiche: non occorre cancellare ogni giorno la verifica precedente.

Anche il momento del controllo conta. Prima dell’invio verifica il possesso dei requisiti alle date prescritte, la correttezza delle dichiarazioni, il canale e la scadenza. Subito dopo verifica invio, ricevuta, eventuale protocollo e copia effettivamente trasmessa. La ricevuta non può essere un requisito preliminare alla sua stessa produzione. Prima della prova controlla documento, convocazione e atti richiesti in quella fase. Dopo un annullamento e nuovo invio conserva la ricevuta corrente, distinguendola da quella della domanda annullata. In ogni passaggio il risultato deve essere dimostrabile con l’evidenza pertinente.

Considera Anna: possiede i requisiti, ha una domanda pronta, il bando non prevede orale e il calendario deve ancora essere pubblicato. Le simulazioni sono deboli. La scheda di accesso può essere verde; orale è N/A; calendario è in attesa di avviso; preparazione è gialla o rossa secondo il recupero realistico. Non si aggiungono un orale inesistente o una ricevuta prima dell’invio per rendere la checklist apparentemente completa. Anna decide se investire, invia se sceglie di partecipare e controlla subito la ricevuta. Se invece le mancasse il titolo richiesto già alla scadenza, il problema sarebbe di accesso e lo studio non lo risolverebbe.

Il piano di recupero associa a ogni voce una consegna e una data. “Entro mercoledì verifico l’articolo sui titoli e correggo la dichiarazione prima dell’invio” riguarda un adempimento; “entro domenica svolgo due test cronometrati, classifico gli errori e rifaccio i dieci quesiti sbagliati” riguarda la prestazione. Non subordinare tutto lo studio alla pubblicazione del calendario, né sacrificare una scadenza certa per una simulazione aggiuntiva. Il calendario personale deve proteggere entrambe le attività e rendere visibile quale prevale in caso di conflitto.

Concludi con due frasi motivate: “posso/non posso ancora presentare una domanda coerente con le regole verificate” e “scelgo/non scelgo di investire in questa preparazione”. Per ogni sospensione indica il dato mancante, il modo per ottenerlo e il termine oltre il quale la decisione va riesaminata. Una checklist utile non promette l’idoneità futura: rende espliciti ciò che hai verificato, ciò che resta da accertare e ciò che dipende da una tua scelta.

'''
t=re.sub(r'## N-SP01-15-05.*?(?=## Caso guidato)',lambda _:new,t,flags=re.S)
# Replace repetitive compressed control tables with the one reusable writing sheet.
t=re.sub(r'\| Elemento \| Dati essenziali \| Verifica o azione \|\n\| ---.*?(?=\n\n)','',t,flags=re.S)
t=t.replace('Compila questa griglia su un bando reale o simulato. Non inserire valori che non hai verificato nel testo ufficiale.','Compila una scheda per ciascun punto da verificare. Non inserire valori non controllati.\n\n**Voce e fase del controllo:** __________________________________\n\n**Regola, articolo e data di verifica:** __________________________\n\n**Stato:** verificato / da chiarire / non ancora pubblicato / N/A\n\n**Evidenza disponibile:** ______________________________________\n\n**Azione e termine:** _________________________________________\n\n**Effetto:** accesso alla procedura / preparazione personale')
t=t.replace('### Checklist finale go/no-go','### Checklist finale distinta per decisione\n\nPrima dell’invio: requisiti, dichiarazioni, termine e canale.\n\nDopo l’invio: stato corrente, ricevuta e copia della domanda.\n\nPrima della prova: convocazione, documento e atti richiesti.\n\nPreparazione: output, tempo disponibile, costi e recupero.\n\nVoci assenti dalla procedura: N/A motivato. Avviso futuro: in attesa di pubblicazione.')
t=t.replace('La decisione “go” richiede assenza di criticità rosse.','La decisione di accesso richiede assenza di ostacoli accertati.')
# Replace the misleading quiz 4 with a closed case.
t=re.sub(r'4\. Quando una criticità è rossa\?.*?(?=\n5\.)','''4. Il bando non prevede orale; il calendario sarà pubblicato in seguito. Anna possiede i requisiti ma ottiene risultati deboli nelle simulazioni. Quale lettura è corretta?

A. È esclusa perché non ha un piano orale.
B. È esclusa perché non conosce ancora la data della prova.
C. Deve segnare verde ogni campo, senza motivarlo.
D. Orale N/A, calendario in attesa, preparazione da recuperare: questi dati non provano un difetto dei requisiti di accesso.

**Risposta corretta: D.** N/A è corretto per una fase assente e l’avviso futuro non è un documento dimenticato. La preparazione debole riguarda la strategia; non crea l’esclusione affermata da A o B. C cancella distinzioni necessarie.
''',t,flags=re.S)
t=t.replace('Segna alcuni punti in rosso: programma non mappato, titoli non verificati, simulazioni assenti, piano orale inesistente. L’esito è no-go per il secondo concorso, almeno in questa finestra.','Segna come criticità strategiche il programma non mappato e le simulazioni assenti; verifica separatamente se siano previsti titoli e orale. Sceglie di non investire nel secondo concorso in questa finestra. È una rinuncia strategica, non un’accertata esclusione per mancanza di requisiti.')
t=t.replace('In soglia rossa, superare lo scritto non basta.','Le criticità di preparazione richiedono recupero; soltanto l’inosservanza di una condizione prevista dalla procedura può avere l’effetto selettivo stabilito dal bando.')
p.write_text(t,encoding='utf8');print('SP01/10 corrected')
