from pathlib import Path
import re
p=Path('wiki/books/moduli/m-sp02-vigili-fuoco/chapters/03-la-preselezione.md');t=p.read_text(encoding='utf8');a=Path('wiki/reviews/correzioni-collana-2026-10-02/archive/pre-correzioni-sp02-03.md')
if not a.exists():a.write_text(t,encoding='utf8')
def rep(a,b):
 global t
 assert a in t,a[:70]
 t=t.replace(a,b)
def span(a,b,v):
 global t
 i=t.index(a);j=t.index(b,i);t=t[:i]+v+'\n\n'+t[j:]
rep('Undici parole che riscrivono il piano di studio di chiunque le legga davvero.','Questa regola orienta il piano di studio.')
rep('Questo capitolo serve a starci dentro spendendo il minimo indispensabile, e a non spendere un\'ora di più.','Questo capitolo aiuta a preparare il filtro di accesso insieme alle prove successive, con verifiche regolari delle lacune.')
rep('che sono le due aree su cui nessun altro materiale di preparazione concorsuale ti aiuta.','selezionando materiali pertinenti al programma e al livello richiesto.')
span('In questo capitolo il metodo BANDO serve soprattutto','## N-SP02-04-01','''Il metodo BANDO collega contenuti, esercitazioni e calendario. Un buon risultato in simulazione orienta il carico di studio, ma non garantisce la posizione nella graduatoria reale e non giustifica l’abbandono dei richiami.''')
rep('diecimila-per-mille','dieci candidati per posto')
span('Questo ha una conseguenza operativa netta:','### Le regole di accesso','''La soglia effettiva dipende dai risultati degli altri candidati e non è nota prima della prova. Un margine osservato in simulazione è quindi un indicatore personale, non una garanzia di ammissione. Distribuisci il tempo fra lacune teoriche, esercizio e preparazione motorio-attitudinale, mantenendo richiami anche quando i risultati migliorano.

La distinzione fra punteggio finale e filtro evita due errori: trascurare la preselettiva perché non attribuisce punti e rimandare ogni altra preparazione finché non sia terminata. La soluzione è un piano parallelo con controlli periodici, non una soglia immaginaria oltre la quale smettere di studiare.''')
span('Intorno alla prova ci sono adempimenti','**La prova può svolgersi in sedi decentrate**','''Gli adempimenti formali accompagnano la preparazione dei contenuti. La pubblicazione istituzionale ha valore di notifica: non attendere una comunicazione individuale come unico segnale.

**Esempio aggiornato della tornata 2026.** Il diario ufficiale del **28 settembre 2026** ha fissato la preselezione del concorso a 400 posti il **14 e 15 ottobre**, all’Ergife Palace Hotel di Roma, con turni distinti per cognome. Prevede una lettera di partecipazione inviata all’indirizzo e-mail indicato nella domanda, da presentare insieme al documento; se non ricevuta, il diario disciplina la stampa in sede prima del check-in. La lettera non sostituisce il controllo della pubblicazione ufficiale.

Il diario annuncia ulteriori comunicazioni per il **7 ottobre**, successivo al controllo di questo capitolo del 3 ottobre. Non sono qui anticipate informazioni che potranno comparire in quell’avviso. Il 15 settembre indicato nel bando originario riguardava una comunicazione, non coincideva di per sé con il giorno dell’esame. Nel tuo calendario registra sempre documento, data di pubblicazione e passaggio che aggiorna.''')
span('**La correzione avviene con procedimenti automatizzati.**','Un ultimo aggancio','''**Il diario acquisito prevede un tablet fornito dall’organizzazione**, associato al candidato mediante la procedura di identificazione, lettera e braccialetto con codice. Le istruzioni d’uso vengono fornite in sede. Al termine occorre seguire il check-out e la restituzione del dispositivo con conferma dell’invio: una modalità automatizzata non implica un foglio a lettura ottica. Non dedurre dal diario funzioni dell’interfaccia che non descrive.

Il risultato è approvato con decreto del Capo del Dipartimento; l’avviso su inPA segnala l’elenco degli ammessi disponibile sul sito istituzionale. Il controllo degli esiti è un’attività distinta dalla corretta conclusione della propria sessione.''')
span('Il bando aggiunge un dettaglio di struttura','### Le quattro cose','''Il bando dispone che i quesiti siano raggruppati e ordinati secondo le quattro tipologie. Questo non basta a stabilire che l’ordine testuale dell’elenco coincida necessariamente con quello dei blocchi sul tablet, né che sia consentita ogni forma di navigazione fra domande. Per il budget di tempo occorrono numero, durata e istruzioni effettive; prima puoi esercitare le aree separatamente e misurare i tuoi tempi.''')
span('Sapremo tutto questo dall\'**avviso','### Una conseguenza della correzione automatizzata','''Nel diario del 28 settembre acquisito per questo capitolo sono definite sede, turni e uso del tablet; non si ricavano da quel documento numero dei quesiti, durata, penalità o pubblicazione di una banca dati. Verifica le successive comunicazioni. «Non indicato nel documento letto» non significa «non sarà previsto».

### Rispondere o omettere: il calcolo necessario

Definisci **G** come punti per risposta corretta, **P** come entità positiva della penalità per errore, **O** come punteggio dell’omissione e **p** come probabilità stimata di correttezza. Il valore atteso di una risposta è **E = pG − (1 − p)P**. Per confrontarla con l’omissione serve E > O: quando G + P è positivo, la condizione diventa **p > (P + O)/(G + P)**. Un’omissione penalizzata va rappresentata con O negativo.

Esempio didattico, senza attribuire questi valori al bando VVF: risposta esatta +1, errore −0,1, omissione zero, quattro opzioni equiprobabili. Con p = 0,25 il valore atteso è 0,25 − 0,075 = **0,175**. La sola presenza di una penalità non rende negativo ogni tentativo casuale. Con errore −1 e omissione zero la soglia sarebbe invece p > 0,5. Per una scelta sensata servono i valori reali e una stima ragionevole della probabilità; l’aspettativa media non garantisce il risultato del singolo quesito.

Se viene pubblicata una banca dati ufficiale, lavorare sui quesiti non elimina la comprensione: occorre saper distinguere varianti, negazioni, dati e ragioni delle risposte. Se non è disponibile, le esercitazioni commerciali restano materiale di allenamento e non diventano per questo la banca ufficiale. Puoi iniziare sessioni a tempo su ipotesi dichiarate, modificandole quando arrivano le istruzioni; non presentare la durata scelta per allenarti come durata dell’esame.''')
span('Significa che non esiste una valutazione del ragionamento:','## N-SP02-04-03','''La macchina corregge la risposta acquisita secondo i criteri della procedura; non ricostruisce ciò che intendevi selezionare. Perciò la corretta gestione del dispositivo è parte della prova. Leggi le istruzioni sull’identificazione, la selezione della risposta, l’eventuale modifica e la consegna; se un’operazione non è descritta, non presumere che funzioni come un’app usata a casa.

Il diario del 28 settembre richiede il tablet dell’organizzazione e vieta dispositivi personali e materiali non ammessi. In simulazione puoi allenare lettura su schermo, controllo della selezione e gestione del tempo, ma non certificare la conformità a un’interfaccia ancora non conosciuta. L’esercizio provvisorio deve dichiarare che cosa sta misurando.

> **Verifica sul bando.** Tipologie e meccanismo di ammissione derivano dal D.D. 2488 del 2 luglio 2026; sede, turni e tablet dal diario del 28 settembre. Le ulteriori comunicazioni annunciate per il 7 ottobre non erano ancora disponibili al controllo del 3 ottobre.''')
rep('Delle quattro tipologie, questa è la prima delle due che non trovi trattate altrove nella tua preparazione concorsuale. Nessun manuale per concorsi pubblici ti prepara alla storia d\'Italia postunitaria, perché nessun altro concorso di questa famiglia la chiede.','La storia d’Italia postunitaria richiede un percorso specifico se non è già presente nella tua preparazione. Un materiale scolastico o concorsuale pertinente può aiutarti: confrontane contenuti e livello con il programma, senza presumere copertura dal solo titolo.')
rep('Un quesito a risposta multipla non può chiedere un\'interpretazione storiografica, perché non esiste una risposta univoca a «quali furono le cause profonde di». Può chiedere, e nella pratica chiede, **fatti verificabili e discreti**: una data, un nome, un atto, una successione, un\'attribuzione.','Un quesito può verificare **fatti, successioni e relazioni causali**, purché formuli un problema con una risposta corretta riconoscibile. Date e nomi sono punti di appoggio, ma comprendere il contesto aiuta a non confondere eventi vicini.')
rep('Studi ciò che è **riconoscibile**, non ciò che è raccontabile. La domanda che ti fai davanti a ogni pagina non è «ho capito questo passaggio?», ma **«che cosa, di questa pagina, può diventare una domanda con quattro opzioni?»**.','Comprendi il passaggio e verifica poi se sai riconoscerlo fra alternative plausibili. Chiediti sia «perché questo evento si colloca qui?» sia «quale confusione potrebbe produrre un distrattore?»')
span('C\'è infine una regola di economia','## N-SP02-04-04','''Organizza richiami progressivi: dopo una prima lettura, ricostruisci la sequenza senza appunti, risolvi quesiti e spiega perché una data alternativa appartiene a un altro evento. Quando una famiglia di errori diminuisce, puoi ridurre il carico di nuovo studio e mantenere richiami distanziati. Un risultato personale non rivela però la futura soglia di ammissione.

### Mini-esercizio di controllo

Costruisci una scheda con quattro campi: evento, collocazione, precedente rilevante, conseguenza. Aggiungi una possibile confusione e il criterio che la risolve. La scheda è utile soltanto se sai rispondere senza rileggerla. Se ricordi la data ma non distingui il fatto da un evento vicino, il richiamo non è ancora stabile.

Nella sessione seguente cambia la forma della domanda: prima chiedi la successione di due eventi, poi il collegamento fra evento e istituzione, poi la distinzione fra entrata in vigore e approvazione di un atto. Il riuso della stessa conoscenza con richieste diverse verifica comprensione e memoria senza trasformare lo studio in sola ripetizione della lettera corretta.''')
rep('Se il perimetro non è dato, l\'unico criterio ragionevole è quello della **struttura del quesito**.','Se manca un programma analitico, combina il livello dichiarato, i concetti fondamentali e la **struttura del quesito**.')
rep('Se stai imparando la dimostrazione, sei fuori perimetro.','Approfondisci il ragionamento quanto serve a capire condizioni e limiti della relazione: una formula ricordata senza unità o ipotesi produce errori anche nei quesiti elementari.')
rep('**parti dai quesiti**, non dalla teoria.','usa anche **quesiti diagnostici**, accanto alla teoria.')
rep('Le due sere non sono sprecate in assoluto — sono sprecate rispetto a un cancello che non assegna punti.','Il tempo necessario dipende dalla lacuna: riconoscere una formula non dimostra che sai scegliere l’area corretta o convertire le unità.')
rep('Se ti accorgi di stare studiando *perché* una cosa è così, e non *che* cosa è, sei uscito dal perimetro.','Chiedersi *perché* una classificazione sia corretta aiuta a rispondere quando cambiano gli esempi; il limite è la pertinenza, non il divieto di comprendere.')
rep('Usali come raccolte di quesiti — che è il loro impiego utile — e non come definizione del perimetro.','Usali per spiegazioni ed esercizi, controllando accuratezza e pertinenza; il loro indice non sostituisce il programma ufficiale.')
rep('È l\'unico tratto della preselettiva che ti resterà utile dopo.','Anche logica, lingua e competenze digitali possono avere utilità professionale; il loro peso nello studio va ricavato dalle prove e dalle tue lacune.')
span('Il consiglio è di natura diversa dal contenuto:','### Informatica:','''Per il piano misura errori e tempi sul tuo livello iniziale. Non si può affermare che la logica migliori sempre più rapidamente della storia: la resa dipende dal problema, dalla preparazione e dalla qualità dell’esercizio. Una serie risolta ricordando il risultato non vale come capacità di individuare la regola di una serie nuova.''')
rep('Trattalo per quello che è nel tuo caso — una porzione di un cancello — e non aprire un corso di lingua.','Verifica con un test iniziale quanto riesci a comprendere e quali strutture devi riprendere. Una lacuna linguistica significativa richiede un lavoro coerente con i tempi disponibili.')
span('**Primo errore da evitare.**','## Errori tipici','''**Primo controllo.** Sara svolge un test diagnostico sulle quattro tipologie e annota errori e tempi. La familiarità scolastica con chimica e fisica è un’ipotesi da verificare, non una prova di copertura. L’acquaticità va preparata in sicurezza insieme allo studio: non si aspetta il superamento della preselettiva per iniziare.

**Distribuzione.** Le ore di studio seguono le lacune rilevate: cronologia e relazioni per la storia, definizioni e applicazioni per le scienze, esercizio sui ragionamenti non acquisiti, attività pratiche e brevi letture per informatica e inglese. Queste ultime non sono automaticamente residuali o tardive. Ogni settimana Sara confronta il registro degli errori con quello precedente.

**Simulazione provvisoria.** Prima delle istruzioni complete può scegliere, per esempio, una sessione di venti quesiti in venticinque minuti. Scrive in testa «parametri didattici, non formato ufficiale». Una volta pubblicati numero, durata e punteggi reali, adatta il test e il calcolo di convenienza della risposta. Il diario del 28 settembre le consente già di preparare gli aspetti organizzativi del tablet e del viaggio.

**Mantenimento.** Se una materia diventa stabile, Sara riduce le nuove sessioni e mantiene richiami brevi. Non smette definitivamente in base a una soglia personale: la graduatoria dipenderà anche dai risultati altrui. Il criterio di revisione del piano è l’evidenza degli errori, insieme al calendario, non la convinzione che ciò che non dà punti finali non meriti cura.''')
rep('**«Comincio a fare simulazioni a tempo da subito».** Finché non conosci numero di quesiti, durata e penalità per errore, stai simulando una prova immaginaria. Prima il contenuto, la strategia dopo l\'avviso sulle modalità.','**«Una simulazione provvisoria è già la prova ufficiale».** Puoi allenarti a tempo su ipotesi esplicite; devi adattare formato e punteggio alle istruzioni effettive quando sono disponibili.')
rep('Nessuno ti scrive.','L’eventuale lettera individuale di partecipazione prevista dal diario non sostituisce il controllo degli avvisi.')
rep('È la ragione per cui la strategia di risposta — in particolare la scelta se rispondere o omettere — non può essere impostata prima di quell\'avviso.','Puoi studiare strategie condizionate a valori ipotetici, ma la scelta concreta richiede i punteggi effettivi e il confronto fra valore atteso e omissione.')
rep('**2.** Il 15 settembre 2026 che cosa accade, esattamente? Correggi l\'affermazione «il 15 settembre si svolge la preselettiva».','**2.** Distingui la comunicazione inizialmente prevista per il 15 settembre dal diario del 28 settembre. **Riscontro:** quest’ultimo fissa turni il 14–15 ottobre e tablet; annuncia ulteriori comunicazioni il 7 ottobre, ancora future alla verifica del 3 ottobre.')
rep('perché la terza in particolare impedisce di impostare fin d\'ora la strategia di risposta?','perché i valori effettivi sono necessari per applicare la strategia di risposta?')
rep('quale criterio usi per decidere quando smettere?','quale criterio usi per passare da nuovo studio a mantenimento?')
span('## In sintesi','*Fonti:','''## In sintesi

La preselezione determina l’accesso senza concorrere al voto finale. Prepara tutte le tipologie e mantieni richiami; il margine delle simulazioni non garantisce la posizione reale. Per scegliere fra risposta e omissione confronta il valore atteso con il punteggio dell’omissione. Il diario del 28 settembre 2026 prevede tablet e turni del 14–15 ottobre; non sostituire con ipotesi le informazioni demandate a successive comunicazioni.''')
t=t.replace('Dati verificati al 10 agosto 2026.','Diario ufficiale del 28 settembre 2026. Riscontro al 3 ottobre 2026.')
t=t.replace('N-SP02-04-','N-SP02-03-');t=t.replace('review_required: false','review_required: true');t=re.sub(r'^updated_at:.*$','updated_at: 2026-10-03',t,flags=re.M);p.write_text(t,encoding='utf8');print('SP02/03 corretto')
