from pathlib import Path
import re,json
B=Path('wiki/books/moduli/m-sp02-vigili-fuoco/chapters');A=Path('artifacts/correzioni-collana-2026-10-02')
comments={
1:["Le tre prove motorio-attitudinali attribuiscono fino a novanta punti. La preselezione consente l’accesso ma non entra nel voto finale; tema di diritto e colloquio motivazionale non sono le prove di merito descritte da quel bando.","Il D.Lgs. 139/2006 riguarda funzioni e compiti; il D.Lgs. 217/2005 riguarda il personale. Diario, domanda e banca dati hanno funzioni procedurali o didattiche e non sostituiscono la disciplina istituzionale.","Una specialità ha requisiti e programma propri. Recenza del bando o assenza di preselezione non consentono di trasferire quel contenuto a ogni ruolo direttivo.","Il Corpo esercita proprie funzioni e partecipa a un sistema con più soggetti. Né il territorio regionale né una situazione bellica fanno coincidere la singola struttura con l’intero sistema.","Qualifica e ruolo identificano destinatari, funzioni e disciplina della selezione. Materiale consigliato, quantità di pagine e testimonianze non individuano il requisito formale.","I regimi sanitari sono distinti e ciascuno richiede il proprio accertamento. Non esiste una conclusione generale basata sulla sola esclusione da un altro ruolo, né una facoltà del candidato di attribuirsi idoneità."],
5:["Il bando ordinario descrive il percorso assunto come riferimento; la specialità informatica è un confronto distinto. Il concorso da vigile e il volontariato hanno requisiti e funzioni differenti.","L’abilitazione richiesta va controllata separatamente dalla laurea. Le patenti o il servizio civile non sostituiscono quel requisito professionale, anche quando possono avere altri effetti in una procedura.","Nel bando considerato i titoli rilevano per la preferenza a parità, senza sanare prove insufficienti. Non cambia il principio a seconda della prova scritta o del possesso della laurea.","Il contenuto professionale della specialità richiede un confronto specifico. Non si può presumere riuso totale né limitarne automaticamente l’esclusione al solo orale o alla sola preselezione.","L’articolo 2 del D.M. 166/2019 richiede una valutazione riferita alle funzioni. Non attribuisce idoneità automatica in base all’età o a una scelta del candidato.","Elaborati e schemi devono essere prodotti e corretti: mostrano se il modello è motivato e la soluzione regge. Pagine, ore online e numero di manuali descrivono risorse utilizzate, non il risultato della prova."],
6:["La destinazione deve esistere, coprire l’oggetto dichiarato e consentire l’output richiesto. Nominare un libro, essere brevi o citare una materia giuridica non dimostra queste condizioni.","L’uso di file e applicazioni non coincide con la disciplina giuridica del documento. Copertina, quantità di capitoli e firma del manuale non identificano il contenuto da recuperare.","Posti, riserve e requisiti inquadrano la partecipazione; le materie vengono poi trasformate in output. Partire soltanto da inglese o palestra lascia ignote condizioni che possono essere decisive.","La decisione e le modalità seguono la disciplina e gli avvisi della procedura. Il solo numero di candidati o una scelta del manuale non sostituiscono la comunicazione ufficiale.","Una data può cambiare finestra del certificato, viaggio e sequenza di studio. Correggere soltanto la cifra o il titolo lascia attività fondate su una scadenza superata.","La formula descrive il silenzio della fonte letta. Va distinta da documento non reperito o dato non ancora controllato; non autorizza a stimare una risposta e presentarla come ufficiale."],
7:["Il controllo dei requisiti e una rilevazione sicura definiscono il punto di partenza. Massimali, soli quiz o viaggio non sostituiscono la verifica complessiva richiesta dal primo ciclo.","Nel bando campione ogni modulo deve raggiungere 21. Un punteggio elevato altrove o un titolo non compensa la componente insufficiente, neppure per l’acquaticità.","Le prime produzioni fanno emergere errori di modello, calcolo e forma. Attendere tutto il programma li rinvia; collocarle dopo l’orale o eliminarle impedisce di allenare lo scritto.","Un elaborato corretto espone dati, ipotesi, procedimento e controllo sotto vincolo. Pagine, manuali ed evidenziature non mostrano se il candidato sa consegnare una soluzione.","La revisione confronta risultati e obiettivi per riallocare tempo e attività. Non serve a celebrare ore, impone automaticamente un cambio di concorso o consente di stimare i posti futuri.","Le conseguenze dipendono dal dato cambiato: una convocazione può modificare logistica e certificati, i punteggi la strategia. Il semplice aggiornamento del registro o del titolo non esaurisce il controllo."],
8:["Il filtro deve essere superato per accedere alle prove. Possedere una riserva non lo rende irrilevante e il candidato non può eliminare una fase richiesta.","Una componente sotto soglia impedisce il superamento: la fragilità va considerata insieme a sicurezza e ripetibilità. Preferenza personale e durata dell’esercizio non stabiliscono da sole la priorità.","Occorre verificare titolo, classe, eventuale equiparazione e abilitazione. Esperienza o invio telematico non trasformano un titolo affine in uno formalmente ammesso.","L’elaborato corretto dimostra come la conoscenza diventa soluzione. Manuali, ore ed evidenziature non attestano modello, unità, controllo e conclusione.","La condizione resta aperta e collegata a fonte, azione e termine. Ignorarla o stimarla equivale a cancellare il controllo; rinunciare è una decisione diversa, non il significato di stato condizionato.","La checklist organizza evidenze e adempimenti; l’accertamento sanitario resta agli organi competenti in ogni ruolo. Non cambia natura passando dal binario operativo a quello direttivo o tecnico."]}
allkeys={}
for no,cs in comments.items():
 p=next(B.glob(f'{no:02}-*.md'));t=p.read_text(encoding='utf8');start=t.index(f'## ▣ Verifica {no:02}.A');end=t.index('## In sintesi',start);block=t[start:end]
 rows=list(re.finditer(r'(?m)^(\d+)\. (.*?)(?=^\d+\. |\Z)',block,re.S));assert len(rows)==6,(no,len(rows))
 out=f'## ▣ Verifica {no:02}.A · Quiz ragionati\n\n';ks=[]
 for i,m in enumerate(rows):
  s=m.group(2);key=re.search(r'Risposta corretta: ([ABCD])',s)[1];pre=s.split('**Risposta corretta:')[0].strip()
  if '\n   - A.' in pre:
   q=pre.split('\n')[0];opts=re.findall(r'^   - [ABCD]\. (.*)$',pre,re.M)
  else:
   q,rest=pre.split(' A. ',1);opts=re.split(r'; [BCD]\. ','A. '+rest);opts[0]=opts[0][3:];opts[-1]=opts[-1].rstrip('.')
  assert len(opts)==4,(no,i,opts)
  opts=[x.replace('Mai, automaticamente','No, non automaticamente') for x in opts]
  correct=opts[ord(key)-65];desired=(i+no)%4;opts.remove(correct);opts.insert(desired,correct);newkey='ABCD'[desired];ks.append(newkey)
  out+=f'**{i+1}. {q}**\n\n'+'\n'.join(f'{letter}. {op}' for letter,op in zip('ABCD',opts))+f'\n\n**Risposta corretta: {newkey}.** {cs[i]}\n\n'
 t=t[:start]+out+t[end:];p.write_text(t,encoding='utf8');allkeys[f'{no:02}']=ks
for no in ['02','03','04']:
 p=next(B.glob(no+'-*.md'));t=p.read_text(encoding='utf8');allkeys[no]=re.findall(r'Risposta corretta: ([ABCD])',t)
(A/'M-SP02-quiz-keys.json').write_text(json.dumps(allkeys,ensure_ascii=False,indent=2),encoding='utf8')
print('Chiavi e commenti specifici riscritti',allkeys)
