from pathlib import Path
import re,shutil
p=next(Path('wiki/books/moduli/m-sp03-magistratura-avvocatura-notariato/chapters').glob('05-*.md'));a=Path('wiki/reviews/correzioni-collana-2026-10-02/archive/pre-correzioni-sp03-05.md');assert not a.exists();shutil.copyfile(p,a);t=p.read_text(encoding='utf8')
t=t.replace('Il tema teorico organizza istituti e problemi: deve avere una tesi, non solo definizioni.','Il tema teorico organizza istituti e problemi secondo il verbo della consegna; una tesi e una controtesi servono quando esiste una questione da discutere.')
t=t.replace('una traccia con soggetti che chiedono di realizzare un effetto giuridico richiede l\'atto.','una traccia con soggetti che chiedono un effetto giuridico può richiedere un atto, un parere o una valutazione. Decide il comando espresso: la presenza dei soggetti è soltanto un indizio.')
t=t.replace('| Tema senza fatti individuali | Tema teorico | Tesi e mappa degli istituti |','| Tema senza fatti individuali | Esposizione teorica secondo la consegna | Mappa degli istituti e delle questioni |')
t=t.replace('| Parti che chiedono un effetto negoziale | Atto notarile | Schema dell\'atto e clausole |','| Comando espresso di redigere un atto | Atto notarile | Schema dell’atto e clausole |')
t=re.sub(r'Prima della stesura completa, la tesi deve reggere.*?(?=\n\n)', 'Prima della stesura completa, distingui due consegne. “Illustri i requisiti del testamento olografo” richiede un’esposizione ordinata di autografia, data e sottoscrizione, con le distinzioni pertinenti: non impone di inventare una disputa. “Discuta i limiti della tutela dell’affidamento” richiede invece di individuare il problema interpretativo, esaminare le alternative rilevanti e motivare la conclusione. La controdomanda serve in questo secondo caso. L’assenza di un contrasto non rende debole una spiegazione precisa quando è proprio ciò che la traccia domanda.',t,flags=re.S)
t=t.replace('Il terzo è la gestione delle obiezioni. Un tema teorico maturo non finge che esista una sola frase giusta. Mostra il nodo, presenta l\'alternativa rilevante e spiega perché una via è preferibile nel contesto della traccia.','Il terzo è il controllo delle distinzioni e, se la traccia pone una questione controversa, delle obiezioni. Si presenta l’alternativa rilevante e si spiega la scelta senza creare controversie artificiali intorno a una regola pacifica.')
t=t.replace('Il criterio principale è la tenuta della tesi. Dopo la lettura, deve essere possibile dire: "Questo tema sostiene che...". Se il tema consente solo di dire "parla di...", manca la prestazione richiesta.','Il criterio principale è la corrispondenza alla consegna. Se è richiesta una discussione, deve emergere una conclusione motivata; se è richiesta una ricostruzione, devono risultare disciplina, ordine e distinzioni essenziali. Un elenco disconnesso fallisce in entrambi i casi. Una ricostruzione completa, invece, non è difettosa soltanto perché non difende una tesi originale.')
t=t.replace('L\'errore specifico del tema teorico è accumulare definizioni senza una tesi.','L’errore specifico del tema teorico è accumulare definizioni senza rispondere alla consegna.')
t=t.replace('Nella prima prova il correttore deve ricevere un tema con una tesi.','Nella prima prova il correttore deve ricevere una ricostruzione del rapporto fra istituti, con una conclusione motivata sul problema proposto.')
t=t.replace('Nel tema teorico l\'istituto viene ordinato in una tesi.','Nel tema teorico l’istituto viene ricostruito e discusso nei limiti richiesti.')
t=t.replace('C. Il testo accumula definizioni ma non sostiene una tesi.','C. Il testo accumula definizioni senza rispondere alla consegna.')
t=t.replace('Senza tesi, il correttore vede l\'argomento, non il ragionamento.','Se le definizioni non rispondono al quesito, manca il ragionamento richiesto; non è invece obbligatorio inventare una tesi controversa per una consegna ricostruttiva.')
t=t.replace('decreto ministeriale 16 dicembre 2025','decreto dirigenziale 16 dicembre 2025')
marker='## Domanda-trappola'
worked='''## Tre prodotti scritti a confronto

### 1. Tema teorico: un possibile svolgimento breve

L’autonomia privata comprende la libertà di avviare trattative e, in mancanza di un vincolo alla stipulazione, di non concludere il contratto. Questa libertà incontra però un limite nel modo in cui viene esercitata: l’art. 1337 c.c. assoggetta trattative e formazione del contratto alla buona fede. Il problema non si risolve quindi scegliendo fra libertà assoluta e obbligo generale di contrarre. Occorre distinguere l’esito della negoziazione dalla correttezza della condotta tenuta durante il suo svolgimento.

La buona fede richiede di considerare l’affidamento che la propria condotta può ragionevolmente suscitare. Non ogni aspettativa del negoziatore è tutelata: il semplice desiderio di stipulare o una previsione ottimistica non dimostrano che la controparte abbia agito scorrettamente. Diventano invece rilevanti lo stato delle trattative, le informazioni disponibili, le rassicurazioni date, la conoscenza di ostacoli alla conclusione e il momento in cui tali ostacoli sono comunicati. La valutazione deve collegare questi elementi alle decisioni effettivamente assunte dall’altra parte.

L’art. 1338 c.c. offre una specifica applicazione: chi conosce, o dovrebbe conoscere, una causa d’invalidità deve darne notizia, se l’altra parte rischia di confidare senza colpa nella validità del contratto. Il rimedio risarcitorio protegge dall’effetto dannoso della mancata informazione; non rende valido il contratto invalido. La distinzione fra validità dell’atto e correttezza del comportamento permette dunque di comprendere perché una trattativa possa essere fonte di responsabilità anche senza un contratto efficace.

La conclusione è che l’autonomia negoziale e la tutela dell’affidamento operano su piani coordinati. La prima lascia aperta la decisione di contrarre nei limiti di legge; la seconda impone di esercitarla senza condotte sleali che producano un pregiudizio causalmente dimostrato. Per risolvere un caso non basta affermare che le trattative si sono interrotte: occorre individuare il comportamento scorretto, l’affidamento meritevole, il danno e il loro collegamento. Questa sequenza evita sia l’automatismo “nessun contratto, nessuna responsabilità”, sia quello opposto “trattativa interrotta, risarcimento sempre dovuto”.

**Correzione della prima versione.** Laura aveva scritto: “La buona fede impone di concludere il contratto quando la controparte sostiene spese”. La frase confonde un dovere di comportamento con un obbligo generale di stipulare e tratta ogni costo come danno risarcibile. La riscrittura è: “Le spese possono concorrere a dimostrare il pregiudizio, ma occorre verificare se siano state causate da un affidamento meritevole indotto da una condotta contraria a buona fede”. Il miglioramento è giuridico e logico, non soltanto stilistico.

### 2. Comune Alfa e Beta: soluzione applicativa con varianti chiuse

La traccia originaria non indica data della procedura, ragione del recesso, rassicurazioni o documenti di spesa. Una risposta corretta deve esplicitare questi vuoti. Per svolgere l’esercizio si aggiungono ora **dati ipotetici dichiarati**: procedura avviata nel 2026 soggetta al d.lgs. 36/2023; nessuna aggiudicazione e nessun contratto; il Comune conosce dal 2 aprile un ostacolo finanziario decisivo, ma il 5 aprile invita Beta a preparare un progetto esecutivo specifico e la rassicura sulla prosecuzione. Comunica l’interruzione solo il 20 aprile. Beta documenta 2.000 euro di consulenza e 800 euro di rilievi successivi al 5 aprile, inutilizzabili altrove, e domanda anche 12.000 euro di utile atteso. Si assume, per questa variante, che i costi siano conseguenza provata della rassicurazione e che Beta non conoscesse né potesse rilevare l’ostacolo con l’ordinaria diligenza professionale.

La difesa non può limitarsi a negare ogni tutela perché manca l’aggiudicazione. L’art. 5, commi 1 e 2, del codice dei contratti impone correttezza reciproca e protegge l’affidamento sul comportamento amministrativo anche prima di quel momento. Va separata la possibilità di interrompere la procedura dalla condotta tenuta dopo la conoscenza dell’ostacolo. Sui fatti assunti, la rassicurazione tardivamente smentita costituisce il punto critico: il Comune deve riconoscerlo nell’analisi e non occultarlo dietro la legittimità astratta della decisione finale.

La linea argomentativa sostenibile contesta invece gli automatismi nella quantificazione. Nel caso, in cui a Beta non spetta l’aggiudicazione, l’art. 5, comma 3, limita il danno da affidamento ai pregiudizi effettivi e provati derivanti dall’interferenza sulle scelte contrattuali. I 2.800 euro di costi sono pertanto una voce sostenibile alle condizioni espressamente assunte; i 12.000 euro non diventano dovuti per il solo fatto di rappresentare l’utile sperato dal servizio non affidato. Un’eventuale diversa opportunità perduta richiederebbe fatti e prova propri, assenti qui. Il calcolo 2.000 + 800 = 2.800 è l’applicazione dei dati dell’esercizio, non una liquidazione valida per qualsiasi recesso.

**Variante decisiva.** Se il Comune comunica l’ostacolo il 2 aprile, prima di ogni rassicurazione, e Beta spende ugualmente il 5 aprile conoscendo che non si proseguirà, manca il collegamento ipotizzato fra la condotta scorretta e quei costi. La richiesta non regge sugli stessi presupposti. Cambiare il fatto deve cambiare la soluzione.

**Prima/dopo.** “Il Comune può interrompere, quindi non risarcisce nulla” diventa: “Il potere di interrompere non esclude l’autonomo esame della buona fede; sui fatti dati è difendibile contestare l’utile atteso, mentre i costi causalmente provati richiedono una valutazione distinta”. Prima di una difesa processuale occorrerebbe anche qualificare domanda, atti impugnati e giurisdizione: questi dati non sono forniti, perciò non si inventano giudice e termini del ricorso.

### 3. Testamento: clausole e condizioni della soluzione

La traccia di Tizio non precisa se Caio debba essere erede universale o ricevere soltanto l’immobile, né il valore del patrimonio, le donazioni o altri possibili legittimari. Il rapporto fra l’attribuzione e l’asse ereditario conta ai sensi dell’art. 588 c.c.; chiamare una disposizione “legato” non basta a determinarne la natura contro l’effettiva volontà. Per produrre una clausola univoca, l’esercizio assume esplicitamente che Tizio voglia istituire Caio unico erede dell’intero patrimonio e attribuire alla sorella un diritto reale vitalizio di abitazione sulla casa, nei limiti propri di quel diritto. Assume inoltre capacità del testatore, piena proprietà del bene, identificazione già completa nel fascicolo ed esito positivo del controllo delle quote riservate. Se una di queste condizioni manca, la soluzione va riesaminata.

**Clausole dispositive didattiche.** “Istituisco mio unico erede mio figlio Caio. Lego a mia sorella Sempronia, per tutta la durata della sua vita, il diritto di abitazione sulla casa di mia proprietà identificata nella descrizione immobiliare di questo testamento, nei limiti dei bisogni suoi e della sua famiglia previsti dall’articolo 1022 del codice civile. L’attribuzione ereditaria a Caio comprende la proprietà dell’immobile gravata da tale diritto.”

La prima disposizione attribuisce la qualità di erede; la seconda attribuisce un diritto determinato a titolo particolare. Sempronia riceve un diritto reale di abitazione, non la proprietà della casa e non una semplice promessa di ospitalità rimessa alla futura scelta del fratello o del nipote. La durata è legata alla vita della beneficiaria e la clausola non le concede genericamente qualsiasi impiego economico dell’immobile. Il controllo dei legittimari dell’art. 536 c.c. e delle quote riservate resta necessario: la qualifica di vedovo elimina il coniuge superstite dai dati iniziali, ma non dimostra da sola che ogni attribuzione sia immune da riduzione.

Queste sono clausole dispositive, non un testamento pubblico completo. La redazione dell’atto richiesto in prova deve comprendere anche le formalità dell’art. 603 c.c.: notaio e testimoni, dichiarazione e riduzione in iscritto della volontà, lettura, menzioni, luogo, data, ora e sottoscrizioni, con le regole ulteriori pertinenti al caso. Non si colmano identità, dati catastali o presenza dei testimoni inventandoli se la consegna non consente assunzioni.

**Prima/dopo.** “Lascio la casa a Caio, che farà abitare Sempronia” è ambiguo rispetto alla natura della posizione della sorella. La versione corretta separa istituzione ereditaria e legato del diritto di abitazione e precisa durata e contenuto. Se Tizio volesse solo un’obbligazione personale a carico di Caio, occorrerebbe una costruzione diversa: il redattore non può scegliere quel risultato contro la volontà chiarita nella variante.

'''
assert marker in t;t=t.replace(marker,worked+marker)
t=t.replace('- per il notariato: legge', '- per i casi di questo capitolo: codice civile, artt. 536, 588, 603, 1022, 1337 e 1338; d.lgs. 36/2023, art. 5;\n- per il notariato: legge')
p.write_text(t,encoding='utf8')
s=Path('wiki/sources/bandi-magistratura-avvocatura-notariato-m-sp03.md');x=s.read_text(encoding='utf8');x+='''

### Fonti dei casi svolti SP03/05

Il 3 ottobre 2026 sono stati acquisiti da Normattiva con sessione persistente gli articoli del Codice civile 1337, 1338, 1022, 588, 536, 602 e 603, tramite i link della struttura dell’atto (flagTipoArticolo=2). Testi completi in `wiki/raw/correzioni-collana-2026-10-02/cc-artNNNN-testo-20261003.html`; i file senza suffisso `testo` contengono la navigazione generale e non sono prova dell’articolo. Le risposte di errore iniziali sono state sostituite dai testi validi, letti per intero. Art. 536 nella versione dal 7 febbraio 2014; gli altri articoli usati risultano nel testo dal 19 aprile 1942.

Acquisito e letto anche l’art. 5 del [d.lgs. 36/2023 su Normattiva](https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:decreto.legislativo:2023-03-31;36~art5!vig=), quattro commi, raw `dlgs36-art5-20261003.html`. Il caso Alfa/Beta è originale e ipotetico, collocato nel 2026: non trasferisce indiscriminatamente il codice attuale a procedure pregresse. Gli importi sono dati didattici; non sono statistiche, liquidazioni giudiziali né tariffe. La clausola testamentaria è limitata alla parte dispositiva, con condizioni esplicite e richiamo alle formalità del testamento pubblico. Non si presenta come atto completo utilizzabile da un privato.
''';s.write_text(x,encoding='utf8');print('SP03/05 corrected')
