from pathlib import Path
import re,shutil
p=next(Path('wiki/books/moduli/m-sp03-magistratura-avvocatura-notariato/chapters').glob('03-*.md'))
a=Path('wiki/reviews/correzioni-collana-2026-10-02/archive/pre-correzioni-sp03-03.md');assert not a.exists();shutil.copyfile(p,a)
t=p.read_text(encoding='utf8')
t=t.replace('il magistrato decide,','il giudice ordinario decide,')
t=t.replace('il limite dei trentacinque anni non compiuti, da leggere nella clausola del bando e sulla data prevista','non aver superato il trentacinquesimo anno di età alla scadenza della domanda, tenendo conto degli eventuali benefici applicabili')
t=t.replace('la soglia anagrafica dei trentacinque anni non compiuti e tre temi teorico-pratici','il limite anagrafico previsto dal bando, il vincolo sui precedenti esiti e tre temi teorico-pratici')
t=t.replace('Ho verificato la data di riferimento per i trentacinque anni non compiuti?','Ho confrontato nascita e scadenza, verificando gli eventuali benefici di elevazione?')
marker='La finestra anagrafica modifica anche la decisione sul rinvio.'
insert='''Il limite si fonda sul D.P.C.M. 141/2000, art. 1, nel testo modificato nel 2011. La formula non significa poter concorrere per tutto l’anno dei trentacinque: secondo il criterio di computo richiamato dall’Adunanza plenaria 21/2011, il superamento decorre dal giorno successivo al compleanno. Considera tre candidati senza benefici di elevazione e con scadenza il 12 agosto 2025: chi è nato il 12 agosto 1990 compie trentacinque anni proprio quel giorno e non ha ancora superato il limite; chi è nato l’11 agosto 1990 lo ha superato; chi è nato il 13 agosto 1990 ha ancora trentaquattro anni. Eventuali elevazioni richiedono una specifica base normativa e la verifica dei relativi presupposti, non una concessione informale.

Anche il fascicolo degli esiti è decisivo. L’art. 4 esclude chi non abbia conseguito l’idoneità due volte in precedenti esami per procuratore dello Stato. Due domande presentate non equivalgono automaticamente a due esiti di non idoneità. Occorre ricostruire le procedure e i provvedimenti individuali: un candidato entro il limite d’età, ma già non idoneo in due precedenti esami, non risolve il problema allegando la laurea o un’ottima simulazione. Questo controllo precede la scelta di investire nella tornata.

'''
assert marker in t;t=t.replace(marker,insert+marker)
t=t.replace('È nata il 16 agosto 1990.','È nata il 16 agosto 1990, non invoca elevazioni del limite e non ha precedenti esiti di non idoneità in questo concorso.')
t=re.sub(r'Il bando della tornata richiama anche la legge 23 novembre 1966, n\. 1035\..*?(?=\n\n)', 'Il bando della tornata richiama anche la legge 23 novembre 1966, n. 1035. Il suo art. 1 è utile per comprendere l’accesso storico del laureato alla qualifica allora denominata procuratore aggiunto, ma non basta a ricostruire tutti i requisiti contemporanei. Per il limite anagrafico occorre il D.P.C.M. 141/2000, art. 1, modificato nel 2011; per l’applicazione alla procedura del 2025 si leggono insieme questa disciplina e il D.A.G. 114/2025. Il bando attua le regole della selezione, non cancella le fonti sovraordinate.',t,flags=re.S)
t=t.replace('La legge n. 1035/1966 resta utilizzata nel perimetro verificato, senza diventare contenitore generico di ogni affermazione sul concorso.','La legge n. 1035/1966 non diventa un contenitore generico di ogni regola del concorso: ciascuna affermazione richiede la disposizione pertinente, nella versione applicabile.')
t=t.replace('requisiti contemporanei che invece provengono dal D.A.G. n. 114/2025.','requisiti contemporanei senza controllare il regolamento di accesso e il bando applicativo.')
t=re.sub(r'Affermazione: "Il limite dei trentacinque anni deriva dalla legge n\. 1035/1966"\..*?(?=\n\n)', 'Affermazione: "Basta citare la legge n. 1035/1966 per dimostrare il limite attuale dei trentacinque anni". La risposta è no: la disposizione da indicare è l’art. 1 del D.P.C.M. 141/2000, nella versione modificata nel 2011, e poi l’art. 2 del D.A.G. 114/2025 per la tornata. Citare soltanto il bando identifica la clausola operativa, ma non ricostruisce da solo la sua base normativa. Una scheda corretta separa fonte dell’ordinamento, regolamento di accesso e atto della procedura.',t,flags=re.S)
t=t.replace('| Ho un documento o una dichiarazione per ogni requisito richiesto?','| Ho verificato che non ricorra il limite di due precedenti esiti di non idoneità? |  |  |\n| Ho un documento o una dichiarazione per ogni requisito richiesto?')
t=t.replace('So distinguere D.A.G. n. 114/2025, r.d. n. 1611/1933 e legge n. 1035/1966?','So distinguere bando, D.P.C.M. 141/2000 e fonti dell’ordinamento?')
t=t.replace('- Legge 23 novembre 1966, n. 1035, nel perimetro verificato dell\'art. 1 usato per il riferimento storico.','- Legge 23 novembre 1966, n. 1035, art. 1, per il riferimento storico.\n- D.P.C.M. 13 aprile 2000, n. 141, art. 1, nel testo modificato nel 2011.\n- Giustizia amministrativa, rassegna sull’ordinanza Consiglio di Stato 8154/2019, p. 5, per il criterio di computo dell’età richiamato dall’Adunanza plenaria 21/2011.')
t=t.replace('Per la tornata studiata, requisiti, età, prove, materie e soglie derivano dal D.A.G. n. 114/2025. Il r.d. n. 1611/1933 serve per l\'inquadramento ordinamentale.','Il D.A.G. 114/2025 è l’atto operativo della tornata. Il limite d’età ha anche la base regolamentare nel D.P.C.M. 141/2000. Il r.d. 1611/1933 inquadra l’ordinamento; la legge storica e le pagine organizzative non sostituiscono il bando.')
t=t.replace('Il limite anagrafico e le prove della tornata vanno ricondotti al D.A.G. n. 114/2025, non a fonti storiche usate per altro perimetro.','Per l’età occorre collegare il D.P.C.M. 141/2000 alla clausola applicativa del D.A.G. 114/2025. Distinguere sedi e funzioni è invece corretto: l’errore è attribuire una regola a una disposizione che non la dimostra.')
t=t.replace('poi tre temi teorico-pratici, poi orale e ordinamento','poi allenamento dei tre temi, mantenendo in parallelo richiami per orale e ordinamento')
p.write_text(t,encoding='utf8')
print('SP03/03 corrected')
