from pathlib import Path
import re,shutil
p=next(Path('wiki/books/moduli/m-sp03-magistratura-avvocatura-notariato/chapters').glob('07-*.md'));a=Path('wiki/reviews/correzioni-collana-2026-10-02/archive/pre-correzioni-sp03-07.md');assert not a.exists();shutil.copyfile(p,a);t=p.read_text(encoding='utf8')
t=t.replace('classifiche così','classificale così')
t=t.replace('senza indicare che l\'Avvocatura dello Stato è organo legale dello Stato, senza distinguere difesa in giudizio e consulenza, e senza collegare il profilo sostanziale alla strategia processuale.','senza individuare il motivo di esclusione, i fatti documentati, la domanda proposta e le possibili difese processuali. L’assenza di una presentazione istituzionale dell’Avvocatura non è il difetto: manca l’applicazione al caso.')
old='**Soluzione commentata.** La seconda versione deve partire dalla funzione:'
start=t.index(old);end=t.index('### Domanda-trappola',start)
t=t[:start]+'''**Soluzione commentata — dati aggiunti per chiudere il caso.** Nell’esercizio il bando di un concorso pubblico richiede il titolo X entro la scadenza della domanda. La clausola è chiara, applicabile e non contestata autonomamente; non esistono equipollenze o deroghe pertinenti. Il ricorrente consegue X dieci giorni dopo la scadenza ed è escluso per tale ragione. Il ricorso contiene solo la domanda di annullamento dell’esclusione, sostenendo che il titolo esiste ormai alla data del giudizio. Si assume il rito ordinario e si escludono sospensioni, rimessioni in termini o altri fatti modificativi del computo.

Una possibile apertura è: “Il conseguimento successivo del titolo non dimostra il possesso alla data richiesta dal bando. La difesa deve documentare la clausola, la scadenza e la data del titolo: sui fatti dati, l’esclusione applica il requisito temporale senza introdurne uno nuovo”. Questa è una tesi sul caso; la frase “l’Avvocatura è organo legale dello Stato”, pur corretta, non la sostituisce.

**Profilo processuale.** Se la notifica del ricorso avviene al settantesimo giorno dalla piena conoscenza documentata dell’esclusione, nelle condizioni ordinarie assunte, occorre prospettare la tardività rispetto al termine di sessanta giorni degli artt. 29 e 41 c.p.a. La conclusione processuale è l’irricevibilità per tardività, non l’infondatezza nel merito. Se la notifica avviene invece al quarantesimo giorno, questa eccezione non regge: si sviluppa la difesa sostanziale sul requisito temporale. Le due linee possono essere articolate in via principale e subordinata, ma non vanno confuse.

**Controargomento.** Il ricorrente afferma che il titolo ormai conseguito dimostra la sua capacità. La replica non nega questa capacità; osserva che la procedura controlla il possesso del requisito nel momento fissato dalla disciplina applicabile. Un dato successivo non modifica retroattivamente quello iniziale. Se invece la documentazione dimostrasse che il titolo era già conseguito entro il termine e soltanto il certificato fosse stato rilasciato dopo, la difesa andrebbe rivista: requisito e prova documentale non coincidono. In tale variante il fascicolo non sostiene più la stessa motivazione di esclusione.

**Controllo dell’incertezza.** Mancare della comunicazione dell’atto è un problema probatorio: non si può eccepire la tardività senza dimostrare la decorrenza. Discutere se un titolo estero rientri nella clausola, con fatti documentati ma disciplina interpretativamente controversa, è un problema giuridico diverso. Nel primo caso si acquisisce il documento; nel secondo si esaminano fonti e orientamenti e si motivano le alternative. Scrivere “da verificare” per entrambi senza distinguere la causa non produce una difesa.

**Seconda versione e prova differita.** Luca consegna un testo che collega tre documenti a tre passaggi: bando al requisito temporale, titolo alla data di conseguimento, comunicazione dell’esclusione alla decorrenza del ricorso. Una settimana dopo ripete il caso con certificato tardivo ma titolo tempestivo. La correzione è acquisita solo se cambia anche la conclusione sul merito, mentre il controllo processuale resta autonomo.

''' +t[end:]
t=t.replace('| Avvocatura dello Stato | Rientro nel limite di età e so scrivere temi teorico-pratici?','| Avvocatura dello Stato | Rientro nel limite di età, non ricorre il limite di due precedenti non idoneità e so scrivere temi teorico-pratici?')
t=t.replace('Non ha l\'abilitazione forense. È interessata','Non ha l’abilitazione forense e si assume che non abbia precedenti esiti di non idoneità nei concorsi considerati. Il confronto è retrospettivo fra tornate già pubblicate e non suggerisce che le tre finestre di domanda siano contemporaneamente aperte. È interessata')
t=t.replace('se il limite anagrafico è rispettato e se si può produrre','se il limite anagrafico e quello dei precedenti esiti sono rispettati, esiste una finestra di candidatura aperta e si può produrre')
t=t.replace('laurea / età / pratica / cittadinanza / altro richiesto dal bando','laurea / età e benefici / pratica / precedenti esiti / cittadinanza / altro richiesto dal bando')
t=t.replace('Titolo, età, pratica o altro requisito richiesto dal bando','Titolo, età e benefici, pratica, precedenti esiti e altri requisiti')
t=t.replace('6. Un elaborato per l\'Avvocatura dello Stato sviluppa solo principi generali di diritto amministrativo e non considera difesa, consulenza o contenzioso pubblico. Che errore mostra?','6. La traccia chiede di difendere un’esclusione. L’elaborato espone principi generali ma ignora requisito temporale, documenti e decorrenza del ricorso. Qual è il difetto?')
t=t.replace('L\'Avvocatura dello Stato richiede un registro proprio. La fonte ordinamentale e istituzionale la qualifica come organo legale dello Stato, con funzioni di difesa e consulenza. Un elaborato teorico-pratico deve far vedere quel collegamento.','Manca il collegamento fra fatti e conseguenze sostanziali e processuali richiesto dalla traccia. Aggiungere una definizione dell’Avvocatura non risolve il difetto. Il problema non è grafico e la comune materia amministrativa non rende sufficiente una rassegna astratta.')
t=t.replace('A. La pratica può mancare alla domanda, purché il certificato arrivi dopo.','A. La pratica può mancare alla scadenza della domanda, purché il certificato arrivi dopo.')
t=t.replace('decreto ministeriale 16 dicembre 2025','decreto dirigenziale 16 dicembre 2025')
t=t.replace('Per tutti e tre i binari, i dati operativi', 'Per il caso processuale: codice del processo amministrativo, artt. 29 e 41; Giustizia amministrativa, “Effetto conformativo del giudicato ultradecennale”, per la distinzione fra azioni e termine ordinario di annullamento.\n\nPer tutti e tre i binari, i dati operativi')
p.write_text(t,encoding='utf8')
s=Path('wiki/sources/bandi-magistratura-avvocatura-notariato-m-sp03.md');x=s.read_text(encoding='utf8');x+='''

### Fonte del caso processuale SP03/07

Controllato il termine ordinario degli artt. 29 e 41 c.p.a. sulla [scheda ufficiale Giustizia amministrativa “Effetto conformativo del giudicato ultradecennale”](https://www.giustizia-amministrativa.it/de/-/effetto-conformativo-del-giudicato-ultradecennale?_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_M2jdZL26fejg_viewSingleAsset=true), consultata il 3 ottobre 2026, e sulla rassegna ufficiale n. 12 del 30 marzo 2020 che la riporta. Il caso didattico assume rito ordinario, piena conoscenza documentata e nessun fatto sospensivo o modificativo. Non generalizza sessanta giorni a riti speciali o azioni diverse. I giorni 40/70, il titolo X e le condizioni del bando sono ipotesi originali, non dati di un contenzioso reale.
''';s.write_text(x,encoding='utf8');print('SP03/07 corrected')
