from pathlib import Path
import shutil,re
B=Path('wiki/books/moduli/m-sp04-prefettizia-diplomatica/chapters')
def read(n):
 p=next(B.glob(n+'-*.md')); a=Path('wiki/reviews/correzioni-collana-2026-10-02/archive/pre-correzioni-sp04-'+n+'.md');assert not a.exists();shutil.copyfile(p,a);return p,p.read_text(encoding='utf8')
p,t=read('01')
t=t.replace('comprendere il limite dei quattro tentativi della diplomatica','distinguere le quattro serie di prove scritte diplomatiche completate e non superate dalle altre partecipazioni')
t=t.replace('complessivamente almeno due anni','due anni').replace('| almeno due anni |','| due anni |')
t=t.replace('Elena ha una laurea magistrale, studia bene diritto amministrativo e parla inglese. Potrebbe presentare domanda per entrambe le carriere.','Elena ha una laurea magistrale in giurisprudenza, classe LMG/01, studia bene diritto amministrativo e parla inglese. Nell’esercizio possiede anche tutti gli altri requisiti di entrambi i bandi: potrebbe quindi presentare domanda per entrambe le carriere. Una laurea magistrale di altra classe, da sola, non autorizzerebbe questa conclusione per la prefettizia.')
s=t.index('Fai un calcolo qualitativo.');e=t.index('\n\nIl criterio corretto',s)
t=t[:s]+'''Separa due fogli. Nel primo verifica i requisiti con le risposte «sì», «no», «da chiarire»: cittadinanza, età ed elevazioni, titolo, ulteriori condizioni e precedenti scritti diplomatici. Un requisito mancante non si compensa con lingue eccellenti o più posti; un dato dubbio richiede una verifica documentale prima della decisione. Soltanto dopo avere accertato l’ammissibilità passa al secondo foglio. Qui attribuisci da zero a tre punti alla base giuridica, alla base storico-economica, alle lingue e alla compatibilità con la vita professionale, conservando una prova per ciascun giudizio. Non sommare questi valori ai posti: usa il numero dei posti come dato separato sull’offerta. Le valutazioni sono strumenti personali di confronto, non probabilità di successo né un criterio ufficiale di selezione.'''+t[e:]
t=t.replace('Un tentativo non serve soltanto a fare esperienza: consuma una delle quattro occasioni previste.','Una serie di prove scritte completata e non superata entra nel conteggio; la generica partecipazione non lo fa. Superare gli scritti e non superare l’orale non equivale a uno scritto fallito.')
t=t.replace('Non affidare a memoria una preclusione definitiva.','Non affidare alla memoria una causa di esclusione prevista dal bando considerato.')
t=t.replace('Imposta un gate prima della domanda:', 'Prima della domanda verifica requisiti e precedenti; prima degli scritti misura la preparazione con')
t=t.replace('la diplomatica il tentativo scritto è esplicitamente finito','la diplomatica quattro serie di scritti completate senza superarle determinano la preclusione prevista')
t=t.replace('Il limite non promette che aspettare produca un esito migliore; impedisce soltanto che quattro occasioni vengano consumate senza una decisione consapevole.','Esempio: tre serie di scritti completate e non superate, più una tornata con scritti superati e orale insufficiente, producono tre precedenti rilevanti, non quattro. Una quarta serie completata e non superata fa maturare il limite per una successiva candidatura secondo il bando 2026. Quattro sole domande non producono quel risultato.')
t=t.replace('numero documentato dei tentativi residui','numero documentato delle serie di scritti completate e non superate')
s=t.index('Il delta M-SP04 è però decisivo.');e=t.index('\n\nIl rinvio alla',s)
t=t[:s]+'''Il delta M-SP04 è decisivo. L’annuncio di una banca dati non equivale alla pubblicazione del file. Prima di usare il protocollo controlla il portale ufficiale della procedura, gli avvisi, la data e la versione dell’eventuale raccolta. Se il file è disponibile, registra l’impronta della versione che studi; se manca, prepara le sei materie su un perimetro aperto senza dichiarare copertura di una raccolta chiusa. La ricognizione storica del manuale non certifica lo stato corrente delle pubblicazioni.

> **Campo da aggiornare.** File ufficiale trovato: sì / no; data del controllo: ______; avviso e versione: ______; eventuali rettifiche: ______. Compila il numero dei quesiti solo dopo avere acquisito la raccolta effettiva.'''+t[e:]
t=t.replace('diritto internazionale, economia internazionale','diritto internazionale pubblico e dell’Unione europea, economia politica, politica economica, economia internazionale e finanziaria e commercio internazionale')
t=t.replace('quesiti annunciati ma non ancora pubblicati alla verifica','stato della banca dati da verificare sul portale ufficiale')
t=t.replace('Nella prefettizia, la raccolta dei quesiti non è disponibile alla data indicata.','Nella prefettizia, registra lo stato effettivo della raccolta alla data del tuo controllo.')
t=t.replace('I quesiti prefettizi non risultano pubblicati alla data di verifica; l\'insieme chiuso non esiste ancora.','Il protocollo richiede un file ufficiale effettivamente pubblicato, identificato per data e versione.')
t=t.replace('Alla data di verifica la raccolta non risulta pubblicata.','Occorre controllare il file effettivo e le sue rettifiche, senza dedurre la pubblicazione dall’annuncio.')
t=t.replace('Dati verificati al 13 agosto 2026.','Disciplina dei bandi verificata il 3 ottobre 2026; calendario e avvisi successivi si controllano sui portali ufficiali.')
p.write_text(t,encoding='utf8')
p,t=read('02')
s=t.index('Paolo compie trentasei anni');e=t.index('\n\nIl controllo termina',s)
t=t[:s]+'''La domanda del bando 2025 scade il 10 luglio alle 12. Paolo, nato il 1° luglio 1989, ha un figlio vivente e non possiede altri titoli di elevazione o deroghe. Il figlio porta il limite ordinario da trentacinque a trentasei anni; Paolo lo supera alla mezzanotte del suo trentaseiesimo compleanno, il 1° luglio 2025. Alla scadenza del 10 luglio è quindi oltre il limite elevato: il solo figlio non lo rende ammissibile. Se fosse nato il 20 luglio 1989, alla scadenza non avrebbe ancora raggiunto quel compleanno e, ferme tutte le altre condizioni, supererebbe il controllo anagrafico. Un ulteriore beneficio richiederebbe titolo, prova e verifica delle regole di cumulo; non si presume per correggere l’esito del caso. Compila quattro campi: nascita, scadenza, elevazione documentata, ultimo giorno utile rispetto al compleanno.'''+t[e:]
s=t.index('Il bando prevede comunicazioni sulla pubblicazione');e=t.index('\n\nI divieti d\'aula',s)
t=t[:s]+'''Il protocollo della banca dati ufficiale si applica dopo la pubblicazione effettiva della raccolta. Controlla avviso, versione e rettifiche sul portale della procedura. Prima di quel momento prepara materie e rapidità senza inventare un insieme chiuso; dopo, misura la copertura della versione acquisita. Il numero dei quesiti pubblicati e la distribuzione tematica si ricavano dal file, non dal solo annuncio.

**Rispondere oppure omettere: calcolo guidato.** Indica con p la probabilità stimata di risposta corretta, con G il premio, con E il punteggio negativo dell’errore e con O quello dell’omissione. Il valore atteso della risposta è pG + (1−p)E. Rispondere supera l’omissione quando p > (O−E)/(G−E). Con i valori del bando, le soglie sono 0,60/2,70 = 2/9 ≈ 22,22% per le facili; 0,50/2,50 = 1/5 = 20% per le medie; 0,40/2,30 = 4/23 ≈ 17,39% per le difficili. Alla soglia i valori attesi coincidono.

Supponi una domanda con quattro alternative equiprobabili, senza alcun indizio: p = 25%. Il valore atteso è −0,925 per una facile, −0,575 per una media e −0,025 per una difficile. Sono tutti superiori alle rispettive omissioni (−1; −0,70; −0,20), pur restando negativi. Non significa che la risposta vincerà: descrive una media teorica di molte ripetizioni. Il bando consente quattro o più alternative; con cinque equiprobabili p = 20%: la facile rende −1,06, peggio dell’omissione; la media pareggia −0,70; la difficile rende −0,14, meglio di −0,20.

Il calcolo presuppone di conoscere la classe attribuita alla domanda e di stimare p in modo attendibile. La difficoltà percepita non sostituisce la classificazione ufficiale. Se questa non è conoscibile in prova, non fingere di applicare una soglia puntuale: costruisci nelle simulazioni una strategia coerente con le informazioni realmente disponibili. Massimizzare il valore atteso non garantisce ammissione, controllo della variabilità o il miglior uso del tempo. Registra sicurezza prima della risposta ed esito dopo: cento risposte etichettate «sicure al 70%» ma corrette solo nel 45% dei casi mostrano una stima da correggere.'''+t[e:]
t=t.replace('Con 158 posti, il moltiplicatore definisce la scala dell\'ammissione','Con 158 posti, 7 × 158 = 1.106 definisce il contingente ordinario')
anchor='La tabella mostra perché non basta fare temi.'
t=t.replace(anchor,'''**Scrittura digitale.** L’articolo 10 prevede lo svolgimento mediante strumenti informatici. Allena quindi anche progettazione e revisione a schermo, non soltanto la calligrafia. Esercizio iniziale: in novanta minuti, trenta per scaletta e sessanta per stesura e controllo, produci al computer una risposta strutturata senza internet né materiali diversi da quelli ammessi. Conserva scaletta, versione consegnata e registro delle correzioni: omissioni, ripetizioni, riferimenti normativi e coerenza fra titolo e conclusione. Questo è un esercizio ridotto, non una simulazione integrale della piattaforma d’esame: interfaccia, salvataggio e istruzioni tecniche vanno appresi dalle comunicazioni ufficiali. Passa poi a prove digitali di durata completa. Una buona prestazione manoscritta non dimostra automaticamente la stessa tenuta sulla tastiera.

'''+anchor)
t=t.replace('rendere il significato in italiano controllato oppure rispondere al quesito secondo la traccia','rendere il significato nella lingua richiesta dalla traduzione oppure rispondere al quesito nella lingua straniera prescelta, secondo la traccia')
s=t.index("L'accesso avviene tramite concorso alla qualifica iniziale. La formazione presso");e=t.index('\n\nLa formazione iniziale mostra',s)
t=t[:s]+'''L’accesso avviene tramite concorso alla qualifica iniziale. L’articolo 5 del d.lgs. 139/2000 prevede il percorso biennale di formazione teorico-pratica e tirocinio operativo. Occorre distinguere la disciplina del percorso dal nome storico della struttura: la Scuola superiore dell’amministrazione dell’interno (SSAI) è stata soppressa dall’articolo 21 del d.l. 90/2014, con attribuzione delle funzioni alla Scuola nazionale dell’amministrazione (SNA). Non presentare dunque la SSAI come scuola oggi autonoma e operativa. La valutazione al termine del primo anno è un passaggio del percorso e non riduce l’intera formazione a dodici mesi.

> **Risposta ordinamentale.** Il percorso è biennale; la fonte storica va coordinata con la riorganizzazione del 2014 e con le indicazioni operative attuali della SNA.'''+t[e:]
t=t.replace('formazione teorico-pratica almeno biennale','formazione teorico-pratica biennale')
anchor='## Errori tipici da evitare'
t=t.replace(anchor,'''## Graduatoria: un calcolo completo

L’orale è superato con almeno 60/100. Dopo il superamento delle prove, l’articolo 13 costruisce il voto finale sommando la media dei cinque scritti al voto dell’orale. A questi si aggiungono gli incrementi previsti: 2,50 punti per il diploma di specializzazione almeno biennale pertinente nei termini del bando, 3 punti per il dottorato pertinente e fino a 1,50 punti per la lingua facoltativa, subordinati al relativo giudizio di idoneità. Titoli e scelta della lingua richiedono le dichiarazioni prescritte nella domanda; un corso qualsiasi o la sola partecipazione alla prova facoltativa non assegnano automaticamente punti.

**Caso risolto.** Scritti: 70, 72, 68, 75, 65. La somma è 350, la media 70; ogni prova raggiunge 60. Orale: 76. Voto prima degli incrementi: 70 + 76 = 146. La candidata possiede un dottorato valutabile e dichiarato (+3), nessuna specializzazione valutabile, e riceve 1 punto per la lingua facoltativa idonea. Totale: 150. La preselettiva non entra nel calcolo. Un titolo di preferenza dell’articolo 14 opera a parità secondo il suo ordine, senza trasformarsi in un punto aggiuntivo; la riserva è un ulteriore istituto distinto.

**Variante.** Sostituisci il 65 con 55: anche se gli altri voti salissero tanto da mantenere la media a 70, mancherebbe il minimo individuale. Non si calcola una graduatoria di merito compensando l’insufficienza con dottorato o lingua facoltativa.

'''+anchor)
p.write_text(t,encoding='utf8')
