from pathlib import Path
import re,json,hashlib
root=Path.cwd();audit=root/'wiki/reviews/audit-integrale-2026-10-02/VOL-03.md'
applied={1:'FC02/05b: regime 2026 D.Lgs. 545/546; TU dal 2027; vecchia fonte superata.',4:'FC02/05: danno grave e irreparabile.',5:'FC02/08: vigilanza e passaggio ad altro regime.',6:'FC02/08: abrogazione TULD.',7:'FC02/08: modifica dopo svincolo entro tre anni.',8:'FC02/08: A.TR, libera pratica e origine nel caso Turchia.',9:'FC02/14: definizione del dichiarante.',10:'FC02/09: divieto di detenzione sospensiva del destinatario registrato.',11:'FC02/09 e 14: EMCS a imposta assolta, e-DAS e soggetti certificati.',12:'FC02/11: immobilizzazioni ammortizzabili e finanziarie, terreni.',13:'FC02/11: minore costo/realizzo, due margini e calcoli.',27:'FC02/05b: termini, difesa personale, territorio e caso calendario.',31:'FC02/12: delegazione/espromissione/accollo, patologie e responsabilità societarie con casi.',32:'FC02/03: Collegio dei revisori e funzione dei tre organi.',44:'FC02/10: iscrizione costitutiva e tre procedimenti estimativi con calcoli.'}
applied.update({28: 'FC02/05a: soglie, condizioni, consumazione, calendario e imputazione sanzioni agli enti.', 29: 'FC02/05: cinque metodi, 60 giorni di contraddittorio, limiti autotutela e TCF 2026.', 30: 'FC02/06: criteri reddituali, pensioni, cassa allargata, calcolo e 90 giorni.', 43: 'FC02/07: fermo, circolazione, preavviso e strumentalità.', 45: 'FC02/13: tre etichette di svolgimento richiuse.', 47: 'FC02/13: D = Diario e relativa applicazione.', 52: 'FC02: accenti e apostrofi, Sara/stabilita/necessita e frase sui controlli corretti in contesto.', 54: 'FC02: apparati staff archiviati, bibliografia leggibile, rinvii alla produzione sostituiti da istruzioni di studio; tre ancore corrette.'})
rows=[]
applied.update({3:'FC01/09: residui attivi statali da riscuotere e da versare; caso 100/80/60 = 40.',33:'FC01/03: quattro aree, declaratorie essenziali e requisiti di base.',34:'FC01/05: responsabilità del Segretario, autonomia contabile e limite di durata delle missioni.',35:'FC01/06: Segretario generale e incompatibilità con modello dipartimentale, con verifica applicativa.',36:'FC01/07: patrocinio obbligatorio/autorizzato, competenza generale/distrettuale e foro dello Stato.',37:'FC01/08: quattro sezioni formali PIAO, durata, aggiornamento, ruoli e pubblicazione.',38:'FC01/09: due sezioni del bilancio, unità di voto, PSBMT/DFP/DPFP/DBP, due conti e parificazione.',39:'FC01/10: obblighi Consip/MePA, distinzione da procedura e digitale, caso e rinvii precisi al core.',40:'FC01/12: rimostranza, rinnovo scritto, eccezioni penale/amministrativa; astensione e casi.',46:'FC01/09/11/12: espansione canonica Bando, Aree, Nuclei, Diario, Output.',48:'FC01/08–15: 60 quiz riscritti, chiavi bilanciate e soluzioni separate; commenti allineati.',50:'FC01/15: cinque tabelle, organo/ente, competenza finanziaria/cassa/residui e 100 criteri di correzione.'})
applied.update({int(k):v for k,v in json.loads((root/'artifacts/correzioni-collana-2026-10-02/FC03-applied.json').read_text(encoding='utf8')).items()})
for line in audit.read_text(encoding='utf-8').splitlines():
 if re.match(r'\| V03-\d{3} \|',line):
  cells=[c.strip() for c in line.strip('|').split('|')]; n=int(cells[0][-3:]);rows.append({'id':cells[0],'position':cells[1],'diagnosis':cells[4],'correction':applied.get(n,'Da applicare secondo audit integrale.'),'status':'testo verificato e congelato; PDF candidato da verificare' if n in applied else 'aperto'})
out=root/'wiki/reviews/correzioni-collana-2026-10-02/VOL-03.md'
text='# Correzioni VOL-03 — testo verificato; produzione da completare\n\nMandato del 2 ottobre 2026, esecuzione 3 ottobre. Tutti i 57 rilievi restano tracciati; «applicato» non equivale a gate superato o pubblicabilità. Pipeline riaperta dal 14 nei tre moduli tramite CLI. Originali dei file modificati in `artifacts/correzioni-collana-2026-10-02/before-text/VOL-03/`.\n\n| ID | File / posizione | Correzione | Fonte / evidenza | Stato finale |\n| --- | --- | --- | --- | --- |\n'
for row in rows:text+='| '+row['id']+' | '+row['position'].replace('|','/')+' | '+row['correction']+' | '+('Source note e delta datati 3 ottobre; script di modifica e snapshot negli artefatti.' if row['status'].startswith('testo verificato') else 'Audit integrale VOL-03.')+' | '+row['status']+' |\n'
text+='\n## Verifiche ancora richieste\n\nTutti i 57 ID sono corretti; gate 14 e 15 superati nei tre moduli, freeze 16 manuali documentati con hash. I controlli includono fonti, quiz, rinvii e matrici. Restano figure, export e controllo visivo del candidato aggiornato, preflight e chiusura della pipeline di volume. Nessuna attestazione di pubblicabilità è anticipata.\n'
out.write_text(text,encoding='utf-8')
ledger={'volume':'VOL-03','updated':'2026-10-03','findings':rows,'files':[]}
for module in ['m-fc01-ministeri','m-fc02-agenzie-fiscali','m-fc03-enti-non-economici']:
 for p in sorted((root/'wiki/books/moduli'/module/'chapters').glob('*.md')):ledger['files'].append({'path':p.relative_to(root).as_posix(),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'textVerified':True,'finalVerified':False})
(root/'artifacts/correzioni-collana-2026-10-02/VOL-03-ledger.json').write_text(json.dumps(ledger,ensure_ascii=False,indent=2),encoding='utf-8')
print(len(rows),'rilievi;',len(applied),'applicati con verifica finale pendente')
