from pathlib import Path
import re,json,shutil,random
art=Path('artifacts/correzioni-collana-2026-10-02');vol=Path('wiki/books/vol-02-enti-locali-polizia-locale');back=art/'before-apparati-vol02';back.mkdir(exist_ok=True)
def read(p):
 dest=back/p.name
 if not dest.exists():shutil.copy2(p,dest)
 return p.read_text(encoding='utf-8')
def save(p,t):
 t=re.sub(r'^updated_at:.*$','updated_at: 2026-10-03',t,flags=re.M);p.write_text(t,encoding='utf-8')
def clean_refs(t,refs):
 t=re.split(r'^#{2,3} Riferimenti consolidati\s*$',t,flags=re.M)[0].rstrip()
 return t+'\n\n## Riferimenti e percorso di ripasso\n\n'+refs+'\n'
p=vol/'chapters/01-come-usare-vol-02-insieme-a-vol-01.md';t=read(p)
t=t.replace('Il modulo sulle Camere di commercio è incluso nel perimetro commerciale del volume, ma resta da validare prima della scrittura definitiva dei capitoli di dettaglio. Le fonti consolidate individuano un’area di possibile interesse: ordinamento camerale, registro delle imprese, servizi alle imprese, funzioni amministrative e rapporto con il sistema Unioncamere.', 'Il modulo sulle Camere di commercio sviluppa cinque capitoli: sistema camerale e Unioncamere; Registro delle imprese e REA; servizi alle imprese e regolazione del mercato; organizzazione e procedimenti; laboratorio per la prova. È il percorso specialistico per i candidati alle selezioni camerali.')
t=t.replace('Questa cautela è importante dal punto di vista editoriale e didattico. Un modulo non validato da bandi recenti non deve diventare un carico di studio ordinario per tutti.', 'La selezione dipende dal programma del concorso: i contenuti camerali sono disponibili nel volume, ma non diventano materia obbligatoria per chi prepara un diverso profilo.')
t=clean_refs(t,'- D.Lgs. 267/2000, Testo unico degli enti locali.\n- Legge 56/2014, Province e Città metropolitane.\n- Legge 65/1986, ordinamento della Polizia municipale.\n- Legge 580/1993, sistema camerale.\n- CCNL Comparto e Area Funzioni Locali 2022–2024, sottoscritti il 23 febbraio 2026, secondo il campo di applicazione.\n- Capitoli successivi «Bando Decoder territoriale» e «Piano 30/60/90 giorni per VOL-02», per tradurre la scelta del modulo in calendario e output.');save(p,t)
p=vol/'chapters/02-bando-decoder-territoriale.md';t=read(p);t=clean_refs(t,'Il documento decisivo è il bando della procedura, con allegati, rettifiche e avvisi pubblicati sul sito dell’ente e su inPA. Per il calendario usa il capitolo «Piano 30/60/90 giorni per VOL-02»; per la scelta del percorso, «Come usare VOL-02 insieme a VOL-01».');save(p,t)
p=vol/'chapters/03-piano-30-60-90-giorni-vol-02.md';t=read(p).replace('Tornare alla source note e registrare quando il riferimento è davvero utile','Rileggere nel capitolo pertinente la regola e il riferimento normativo; verificarne il testo su Normattiva o sulla fonte ufficiale indicata');t=clean_refs(t,'Usa il «Bando Decoder territoriale» per scegliere le materie e il capitolo «Simulazione finale VOL-02» per misurare gli output. Date, prove, materiali ammessi e rettifiche si controllano nel bando e negli avvisi ufficiali dell’ente. Il piano è didattico e si adatta al tempo effettivamente disponibile.');save(p,t)
p=vol/'chapters/50-simulazione-finale-vol-02.md';t=read(p);fm=t.split('---',2)[1];body=(art/'vol02-simulazione-body.md').read_text(encoding='utf-8')
body=re.sub(r'(?<=[a-zà-ÿ])(?=\d)',' ',body);body=re.sub(r'(?<=\d)(?=[a-zà-ÿ])',' ',body);body=re.sub(r'\b(art\.|L\.|D\.Lgs\.)\s*(?=\d)',r'\1 ',body)
body=body.replace('scolastica. Il dossier','scolastica. Il dossier').replace('Fontechiara,3','Fontechiara, 3').replace('competente.3','competente. 3').replace('definitivo.3','definitivo. 3')
keys={int(n):k for n,k in re.findall(r'^\| (\d+) \| ([A-D]) \|',body,re.M)};newkeys={};rng=random.Random(20261003)
def shuffle(m):
 n=int(m[2]);opts=re.findall(r'^([A-D])\. (.*)$',m[3],re.M);rng.shuffle(opts);newkeys[n]='ABCD'[[x[0] for x in opts].index(keys[n])];return m[1]+''.join('ABCD'[i]+'. '+x[1]+'\n\n' for i,x in enumerate(opts))
body=re.sub(r'(\*\*(\d+)\..*?\*\*\n\n)((?:[A-D]\. [^\n]+\n\n){4})',shuffle,body);assert len(newkeys)==20,len(newkeys)
body=re.sub(r'^(\| (\d+) \| )([A-D])( \|)',lambda m:m[1]+newkeys[int(m[2])]+m[4],body,flags=re.M)
sources=['vol-02-verifica-tuel-atti-statuti-2026-10-02','vol-02-contabilita-piao-verifica-2026-10-03','vol-02-regioni-statuti-competenze-verifica-2026-10-03','vol-02-area-vasta-organi-verifica-2026-10-03','vol-02-coesione-pnrr-verifica-2026-10-03','vol-02-scuole-espropri-spl-verifica-2026-10-03','vol-02-camerale-verifica-2026-10-03','vol-02-pl-qualifiche-sanzioni-verifica-2026-10-03','vol-02-pl-strada-verifica-2026-10-03','vol-02-pl-edilizia-ambiente-verifica-2026-10-03','vol-02-pl-pg-verifica-2026-10-03']
for k,vals in [('source_refs',['sources/'+x for x in sources]),('last_compiled_from',['wiki/sources/'+x+'.md' for x in sources])]:fm=re.sub(r'^'+k+r':.*$',k+': '+json.dumps(vals,ensure_ascii=False),fm,flags=re.M)
save(p,'---'+fm+'---\n\n'+body)
(art/'VOL-02-simulazione-key.json').write_text(json.dumps({'keys':newkeys,'quizCount':20,'points':{'quiz':10,'risposta':5,'caso':7,'documento':5,'orale':3},'note':'Chiavi rimescolate con le opzioni; contenuto normativo da riesaminare sulle soluzioni.'},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
p=vol/'chapters/51-conclusione-vol-02.md';t=read(p).replace('quarantasei capitoli isolati','cinquantuno capitoli isolati');save(p,t)
p=vol/'front-matter/05-premessa.md';t=read(p).replace('o, se confermato nel perimetro commerciale, una Camera di commercio','o una Camera di commercio');save(p,t)
p=vol/'front-matter/04-sommario.md';t=read(p).replace('Modulo di riconciliazione incluso: sistema camerale','Sistema camerale').replace('Bando locale integrato, quiz, risposta sintetica, caso pratico, verbale/atto, orale e diario degli errori.','Prova didattica con 20 quiz commentati e quattro percorsi a scelta: risposta sintetica, caso, documento svolto, orale e griglia di correzione.').replace('M-FL01 -','M-FL01 —').replace('M-FL02 -','M-FL02 —').replace('M-FL03 -','M-FL03 —').replace('M-FL04 -','M-FL04 —');save(p,t)
p=vol/'front-matter/06-indice.md';t=read(p);t=re.sub(r'> \[!NOTE\]\n> Questo file.*?\n\n','Il percorso comprende 51 capitoli: orientamento 1–3; Comuni 4–17; Regioni e area vasta 18–29; Camere di commercio 30–34; Polizia locale 35–49; simulazione 50 e conclusione 51.\n\n',t,count=1,flags=re.S)
t=t.split('## Appendici operative — non incluse nel volume pubblicato')[0].rstrip();t=re.sub(r'^\s+- (?:Nota di review:|Stato: modulo incluso).*\n','',t,flags=re.M);t=t.replace('Decodifica di bandi camerali 2026.','Decodifica di un bando camerale didattico composito.')
counter=[0]
def num(m):counter[0]+=1;return str(counter[0])+'. **'
t=re.sub(r'^\d+\. \*\*',num,t,flags=re.M);assert counter[0]==50,counter
t+='\n\n51. **[[books/vol-02-enti-locali-polizia-locale/chapters/51-conclusione-vol-02|Conclusione — Dal volume al bando]]**\n    - Risultati del percorso, scelta del modulo e riuso della preparazione.\n    - Dal Diario degli errori al successivo bando.\n'
t=t.replace('Parte finale - Simulazione, appendici e strumenti','Parte finale — Simulazione e conclusione');save(p,t)
for p in (vol/'modules').glob('*.md'):
 t=read(p);code=re.search(r'^module_code: (.*)$',t,re.M)[1];offset={'M-FL01':3,'M-FL02':17,'M-FL03':29,'M-FL04':34}[code];i=[0]
 def row(m):i[0]+=1;return '| '+str(offset+i[0])+' |'
 t=re.sub(r'^\| \d+ \|',row,t,flags=re.M);t=t.replace('| Cap. |','| Cap. volume |')
 if code=='M-FL03':t=t.split('> [!IMPORTANT]')[0].rstrip()+'\n\nIl modulo è destinato ai concorsi camerali e ai programmi che richiedono Registro delle imprese, ordinamento camerale e servizi alle imprese. Il laboratorio usa esempi didattici dichiarati e distingue i dati pubblici del Registro dai documenti dei singoli procedimenti.\n';t=t.replace(', "da-validare"','')
 save(p,t)
sp=art/'VOL-02-changes.json';s=json.loads(sp.read_text(encoding='utf-8'))
rows=[('V02-01',['chapters/01-come-usare-vol-02-insieme-a-vol-01.md'],'Percorso camerale descritto come cinque capitoli presenti, con destinatari; rimosso stato superato.','Confronto coi cinque capitoli FL03 congelati e con la promessa introduttiva.'),('V02-02',['chapters/03-piano-30-60-90-giorni-vol-02.md','chapters/50-simulazione-finale-vol-02.md'],'Rinvii al lettore indirizzati a capitoli, norme e siti ufficiali; rimossi source note e apparati interni.','Correzione della simulazione interamente su soluzioni stampate e capitoli nominati.'),('V02-52',['chapters/51-conclusione-vol-02.md'],'Aggiornato conteggio a cinquantuno capitoli.','3 introduttivi +14+12+5+15 moduli +simulazione+conclusione =51.'),('V02-FM1',['front-matter/05-premessa.md','front-matter/04-sommario.md'],'Eliminata condizionale commerciale e dicitura modulo di riconciliazione.','Presenza e freeze dei cinque capitoli camerali.'),('V02-FM2',['front-matter/04-sommario.md','chapters/50-simulazione-finale-vol-02.md'],'Promessa allineata a20quiz e quattro percorsi con tutti gli output e soluzioni.','Somma30punti; tempo70minuti; separazione famiglie dichiarata.'),('V02-FM3',['front-matter/06-indice.md'],'Indice1–51 e blocchi30–34/35–49; tolti piani interni e appendici non presenti.','Numerazione sorgente verificata; corrispondenza pagine da verificare sul nuovo PDF.'),('V02-FM4',[p.relative_to(vol).as_posix() for p in sorted((vol/'modules').glob('*.md'))],'Sommari con numerazione volume coerente; camerale attuale e senza note interne.','FL01 4–17, FL02 18–29, FL03 30–34, FL04 35–49; PDF successivo ancora da verificare.')]
for fid,paths,c,e in rows:s['changes'][fid]={'files':[(vol/x).as_posix() for x in paths],'change':c,'evidence':e,'status':'Applicato nel testo; riesame finale e PDF aperti'}
r=s['changes']['V02-20'];r['files'].append((vol/'chapters/50-simulazione-finale-vol-02.md').as_posix());r['change']+=' Simulazione integrata con20quiz, quattro dossier, risposte, casi, documenti e orale.';r['evidence']+=' Soluzioni specifiche e rubriche ancorate a ciascun percorso.';r['status']='Applicato in laboratori e simulazione; riesame finale aperto'
s['limitations']=['58/58 ID con intervento scritto; riesame finale dei nuovi apparati e simulazione in corso.','Step21 aperto: nuovo PDF e distribuzione in tomi ancora da produrre/verificare; nessuna pubblicabilità finale.','Gate14/15 dei quattro moduli passati; freeze16 manuali dichiarati per gate non implementato.']
sp.write_text(json.dumps(s,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print(json.dumps({'indexChapters':51,'simulationKeys':newkeys,'changes':len(s['changes'])}))
