from pathlib import Path
import re,json,hashlib
A=Path('artifacts/correzioni-collana-2026-10-02');B=Path('wiki/books/moduli/m-fc05-authority-indipendenti/chapters');data={}
def put(c,n,title,rows,note=''):
 data[c,n]={'title':title,'rows':[r.split('~',1) for r in rows.split('\n')],'note':note}
def bando(c,title,values):put(c,1,title,'\n'.join(k+'~'+v for k,v in zip(['B — Bando','A — Aree','N — Nuclei','D — Diario','O — Output'],values)))
bando(2,'Studiare l’ordinamento dell’ente',['Individua l’autorità e il programma.','Governance, personale e controlli.','Nomina, durata, incompatibilità e responsabilità.','Registra gli scambi fra enti e organi.','Tabella comparativa e risposta orale.'])
put(2,2,'Tre dimensioni dell’indipendenza','Funzionale~Il potere attribuito si esercita senza interferenze estranee.\nOrganizzativa~Strutture e risorse sostengono le funzioni secondo legge.\nDi giudizio~La decisione si fonda su fatti e regole, non su pressioni.','Nessuna dimensione elimina legalità, motivazione o controllo del giudice.')
put(2,3,'Organi, uffici e controlli','Organo collegiale~Assume le decisioni attribuite e ne risponde.\nUffici~Svolgono istruttoria e gestione nei rispettivi ruoli.\nControlli~Rendicontazione, Corte dei conti e giudice secondo la disciplina.','Le attribuzioni concrete sono quelle dell’ente: il modello non uniforma gli otto ordinamenti.')
put(2,4,'Tre nomine da non scambiare','AGCM~Presidente e due membri nominati d’intesa dai Presidenti delle Camere.\nGarante privacy~Quattro membri eletti dalle Camere; il Collegio elegge il Presidente.\nIVASS~Presidente è il Direttore generale della Banca d’Italia; distinguere Consiglio e Direttorio integrato.','Durata, rinnovo e incompatibilità sono nella tabella del capitolo, verificata al 3 ottobre 2026.')
put(2,5,'Accountability verificabile','Motivazione~Rende comprensibili fatti, regole e scelta.\nRendicontazione~Espone attività, risorse e risultati.\nTrasparenza~Permette conoscibilità nei limiti di legge.\nControlli e rimedi~Consentono valutazione e contestazione nelle sedi competenti.','È un obbligo di rendere conto, non soltanto una capacità comunicativa.')
bando(3,'Ragionare sul livello europeo',['Leggi fonti e cooperazione richieste.','Diritto UE e regolazione settoriale.','Atti, organismi e riparto dei poteri.','Segna gli errori fra rete, agenzia e gerarchia.','Mappa delle competenze e caso transfrontaliero.'])
put(3,2,'Fonti dell’articolo 288 TFUE','Regolamento~Obbligatorio in tutti gli elementi e direttamente applicabile.\nDirettiva~Vincola il risultato per gli Stati destinatari; richiede il raccordo nazionale.\nDecisione~Obbligatoria; se designa destinatari vincola questi.\nRaccomandazione e parere~Non vincolanti.','Atto delegato e atto di esecuzione seguono gli articoli 290 e 291, con funzioni diverse.')
put(3,3,'Dal fatto transfrontaliero alla competenza','Trattamento o servizio~Identifica attività, soggetti, stabilimenti ed effetti.\nFonte~Individua il meccanismo settoriale, senza presumere uno sportello unico.\nRiparto~Separa potere nazionale, europeo e cooperazione.\nEsito~L’istituzione competente decide secondo procedimento e garanzie.','La cooperazione non trasferisce automaticamente il potere di adottare l’atto finale.')
put(3,4,'Organismi distinti','ECN~Rete delle autorità di concorrenza e Commissione.\nBEREC~Organismo dei regolatori delle comunicazioni; distinguere l’Ufficio di supporto.\nACER~Agenzia UE dell’energia con poteri attribuiti, anche dopo REMIT II.\nEDPB~Comitato GDPR: orientamenti e decisioni vincolanti nei casi previsti.\nEBA, ESMA, EIOPA~Autorità europee del sistema finanziario; competenze settoriali proprie.')
put(3,5,'Verificare la forza di un documento','Progetto RTS/ITS~Proposta tecnica; non equivale all’atto adottato dalla Commissione.\nOrientamento~Guida l’applicazione con il regime pertinente; non è automaticamente un regolamento.\nDecisione vincolante~Richiede fonte, presupposto e destinatario identificati.','Nel diario annota l’errore preciso: forma dell’atto, fase di adozione o competenza.')
bando(4,'Allenare il ciclo regolatorio',['Individua se la prova chiede AIR, consultazione o valutazione.','Economia, procedimento e qualità della regolazione.','Problema, alternative, impatti e monitoraggio.','Registra confusione fra beneficio lordo e netto.','Mini-AIR e motivazione della scelta.'])
put(4,2,'Consultazione, AIR e VIR','Consultazione~Raccoglie dati e argomenti degli interessati.\nAIR~Confronta opzioni e impatti prima della decisione.\nVIR~Valuta effetti e adeguatezza dopo l’attuazione.','Sono strumenti coordinati; la consultazione non è un voto sull’opzione più popolare.')
put(4,3,'Un ciclo con riesame','Problema e baseline~Definisci scostamento, dati e situazione senza intervento.\nOpzioni~Confronta alternative realistiche, inclusa l’assenza di nuova misura.\nDecisione~Motiva costi, benefici, distribuzione e incertezza.\nAttuazione e monitoraggio~Misura risultati; la valutazione può richiedere una modifica.','Il riesame può riportare alla formulazione del problema: non è una sequenza irreversibile.')
put(4,4,'Leggere una mini-AIR','Costo~Risorse richieste, soggetto che le sostiene e periodo.\nBeneficio~Effetto stimato rispetto alla baseline.\nSaldo netto~Beneficio meno costo, senza nascondere la distribuzione.\nScenario avverso~Verifica se la preferenza cambia quando mutano le ipotesi.')
put(4,5,'Conclusione motivata','Scelta~Indica l’opzione e la ragione determinante.\nLimite~Dichiara dato mancante e sensibilità del risultato.\nIndicatore~Misura l’obiettivo effettivo, non solo l’attività svolta.\nRiesame~Definisci quando verificare gli effetti.','Usa le regole procedurali dell’autorità: il DPCM 169/2017 non si estende automaticamente alle authority.')
bando(5,'Costruire un’istruttoria',['Riconosci richiesta di nota, atto o caso.','Vigilanza, prova e garanzie.','Segnale, acquisizioni, ispezioni e valutazione.','Annota conclusioni anticipate e richieste eccessive.','Piano istruttorio e richiesta dati motivata.'])
put(5,2,'Quattro livelli dell’evidenza','Notizia~Segnala un possibile problema.\nIpotesi~Propone una qualificazione da controllare.\nEvidenza~Elemento acquisito, verificabile e pertinente.\nValutazione~Collega gli elementi alla regola e alle alternative.','Una segnalazione circostanziata non coincide con l’avvio formale antitrust.')
put(5,3,'Richiesta dati delimitata','Fonte e oggetto~Indica potere, fattispecie e finalità.\nPeriodo e campione~Seleziona dati pertinenti e proporzionati.\nFormato e termine~Rendi la risposta utilizzabile e tracciabile.\nGaranzie~Specifica riservatezza, interlocuzione e regole procedimentali.','Acquisire tutto non significa provare meglio.')
put(5,4,'Ispezioni: verificare il luogo','AGCM~Poteri antitrust e garanzie propri; locali non aziendali richiedono i presupposti e l’autorizzazione previsti.\nGarante~Accertamenti ex articoli 157–158; per domicilio verificare assenso o autorizzazione giudiziaria pertinente.\nAssistenza e tutela difensiva~Documentare le eccezioni nel rispettivo ambito, senza immunità generiche.','Non trasferire l’autorizzazione prevista per un’autorità al procedimento di un’altra.')
put(5,5,'Qualità del fascicolo','Autenticità~Il documento è ciò che dichiara di essere?\nTempo~Riguarda il periodo contestato?\nPertinenza~Dimostra il fatto rilevante o un dato diverso?\nContraddittorio~Le difese e gli elementi contrari sono valutati?','Una schermata autentica ma successiva alla campagna non prova da sola la versione precedente.')
bando(6,'Scegliere il rimedio corretto',['Identifica atto, autorità e data.','Sanzioni, garanzie e giurisdizione.','Impegni, cautela, ottemperanza e ricorso.','Registra scambi fra riti e termini.','Tabella atto–giudice e caso motivato.'])
put(6,2,'Strumenti con presupposti diversi','Sanzione~Reagisce alla violazione accertata secondo fattispecie e garanzie.\nImpegni~Misure rese obbligatorie nei presupposti, senza necessario accertamento dell’infrazione.\nRimedio correttivo~Rimuove o limita la criticità secondo il potere attribuito.\nCautela~Intervento provvisorio nei presupposti specifici.','Non ogni authority dispone di ogni strumento.')
put(6,3,'Esiti alternativi del procedimento','Accertamenti~Valuta fatti, regola e difese.\nNessuna violazione provata~Esito di chiusura nei termini della disciplina.\nViolazione accertata~Misura o sanzione proporzionata, se prevista.\nPercorso impegni~Solo nei presupposti, con obbligatorietà e monitoraggio.','La vigilanza non conduce necessariamente a una multa.')
put(6,4,'Due ottemperanze','Alla decisione amministrativa~Rispetto dell’ordine o degli impegni e relativo controllo.\nAlla decisione giudiziaria~Esecuzione del giudicato o dell’atto giudiziale nel rito pertinente.','Violazione di impegni e inosservanza di una sentenza hanno fonti e rimedi distinti.')
put(6,5,'Prima del ricorso','Oggetto~Distingui atto regolatorio, sanzione e misura individuale.\nGiudice e sede~Applica CPA o disciplina speciale.\nTermine e decorrenza~Verifica comunicazione, residenza e transitorio.\nCautela~Valuta presupposti; il ricorso non sospende sempre l’atto.','Privacy, TUB e TUF non seguono una formula processuale unica: usa la tabella aggiornata del capitolo.')
bando(7,'Usare i numeri nella prova',['Leggi il peso della parte quantitativa.','Mercato, incentivi, dati e contabilità.','Elasticità, regressione, controfattuale e costi.','Registra unità, segni e attribuzioni causali errate.','Calcolo con interpretazione e limiti.'])
put(7,2,'Concentrazione e potere di mercato','Quote e HHI~Descrivono struttura e concentrazione.\nSostituibilità~Contribuisce a definire il mercato pertinente.\nBarriere ed entrata~Aiutano a valutare la pressione competitiva.\nCondotta~Richiede una distinta qualificazione.','HHI elevato non dimostra da solo un abuso di posizione dominante.')
put(7,3,'Dal dato alla scelta','Descrizione~Indica unità, periodo, fonte e popolazione.\nStima~Esplicita modello, coefficiente e incertezza.\nCausalità~Motiva il controfattuale e le ipotesi.\nDecisione~Collega risultato, competenza e obiettivo.','Un coefficiente statisticamente significativo non prova automaticamente causalità o rilevanza regolatoria.')
put(7,4,'Tetto ai prezzi e ai ricavi','Price cap~Limita il prezzo; i ricavi variano anche con i volumi.\nRevenue cap~Limita il ricavo; il prezzo medio dipende dalla quantità.\nEsempio didattico~Prezzo 102 e volume 11: ricavi 1.122; ricavo vincolato 1.020 su 11: prezzo medio 92,73.','Controlla sempre il metodo settoriale effettivo e gli aggiustamenti previsti.')
put(7,5,'RAB, WACC e imputazione','RAB~Base patrimoniale ammessa dal metodo, non ricavo annuo.\nWACC~Tasso applicato alla base pertinente per la remunerazione.\nAmmortamento~Componente distinta dalla remunerazione.\nCosti comuni~Riparto con driver verificabile; riconciliazione fra attività.','Un calcolo corretto non sana un driver non causale.')
bando(8,'Qualificare il caso AGCM',['Separa programma antitrust e consumer.','Concorrenza, consumatore, rating e conflitti.','Intese, abuso, concentrazioni e pratiche.','Annota la fattispecie scambiata.','Nota istruttoria e risposta sul rimedio.'])
put(8,2,'Antitrust e consumatore','Intesa~Accordo o coordinamento da valutare ex articolo 101 e disciplina nazionale.\nAbuso~Condotta di impresa dominante, non semplice dimensione.\nConcentrazione~Modifica strutturale soggetta ai presupposti di controllo.\nPratica commerciale~Condotta verso il consumatore che può alterarne la scelta.','Lo stesso mercato non rende equivalenti queste fattispecie.')
put(8,3,'Il controllo AGCM','Competenza~Qualifica materia e dimensione nazionale/UE.\nIstruttoria~Acquisisci elementi e garantisci difesa.\nValutazione~Applica la fattispecie, considerando elementi contrari.\nEsito~Archiviazione, misura, impegni o sanzione nei rispettivi presupposti.','Il tipo di procedimento stabilisce scansioni e strumenti; non esiste un unico iter indistinto.')
put(8,4,'Pratiche scorrette','Clausola generale~Diligenza professionale e alterazione del comportamento economico.\nIngannevole~Informazione falsa o presentazione/omissione fuorviante.\nAggressiva~Molestia, coercizione o indebito condizionamento.\nListe~Pratiche sempre vietate quando ricorrono gli elementi descritti.','Per il prodotto presentato come gratis si controlla l’articolo 23, lettera v, non una lettera scelta per analogia.')
put(8,5,'Promessa e costo nascosto','Messaggio~Che cosa comprende il consumatore prima di acquistare?\nCondizioni~Quando e come emerge il costo?\nProva~Versioni, schermate, percorso e contratti.\nTutela~Enforcement pubblico distinto da rimborso e danni individuali.','La presenza di una clausola remota non dimostra da sola informazione chiara e tempestiva.')
bando(9,'Leggere il servizio regolato',['Individua energia, acqua, rifiuti o teleriscaldamento.','Tariffe, qualità e tutela utente.','Costi, metodo, standard e competenze.','Segna scambi fra tariffa, imposta e rimborso.','PEF didattico e percorso di tutela.'])
put(9,2,'Tre livelli del PEF rifiuti','Gestore~Predispone dati e documentazione del piano.\nETC~Valida e assume le determinazioni di competenza.\nARERA~Verifica coerenza e approva secondo il metodo.','Gli enti locali e il gestore non scompaiono dal procedimento; ARERA non determina ogni singola bolletta.')
put(9,3,'Costo, qualità e tariffa','Perimetro~Identifica servizio, attività e periodo.\nCosti~Verifica pertinenza, riconoscibilità e assenza di duplicazioni.\nQualità~Misura standard e scostamenti secondo metodo.\nTariffa~Applica componenti, limiti e procedimento pertinenti.','Un costo contabilizzato non è automaticamente un costo ammesso.')
put(9,4,'Tre separazioni','Contabile~Distingue conti e imputazioni delle attività.\nFunzionale~Presidia indipendenza gestionale e comportamenti nei regimi previsti.\nProprietaria~Separa assetti proprietari nei casi disciplinati.','Unbundling non è sinonimo della sola separazione contabile.')
put(9,5,'Reclamo, indennizzo e conciliazione','Reclamo~Chiede risposta all’operatore sul problema.\nIndennizzo automatico~Conseguenza prevista per specifiche violazioni di standard.\nConciliazione~Ricerca un accordo alle condizioni e nei termini del settore.\nRisarcimento~Segue i presupposti e la sede competente.','Usa la tabella settoriale: i tempi e gli effetti dell’accordo non sono identici per tutti i servizi.')
bando(10,'Separare comunicazioni e piattaforme',['Leggi il settore e la forma della prova.','CCE, TUSMA, utenti e servizi digitali.','SMP, Corecom, DSA e DMA.','Registra lo scambio fra designazioni e competenze.','Caso con percorso nazionale/UE motivato.'])
put(10,2,'Fonti e interessi','CCE~Reti e servizi di comunicazione elettronica.\nTUSMA~Servizi di media e interessi disciplinati, incluso pluralismo.\nDSA~Servizi intermediari e obblighi graduati per categoria.\nDMA~Gatekeeper designati e obblighi per contendibilità/equità.','Essere online non colloca ogni attività nella stessa disciplina.')
put(10,3,'Reclamo e controversia dell’utente','Operatore~Riceve reclamo su fatturazione o disservizio.\nConciliazione~Tentativo nel sistema competente alle condizioni previste.\nDefinizione~Procedimento successivo nei casi e termini applicabili.\nGiudice~Domande risarcitorie e tutela secondo disciplina.','Corecom esercita funzioni delegate; non gli si attribuisce ogni controversia digitale.')
put(10,4,'SMP, VLOP e gatekeeper','SMP~Posizione nel mercato rilevante e regolazione ex ante delle comunicazioni.\nVLOP/VLOSE~Designazione DSA e obblighi supplementari pertinenti.\nGatekeeper~Designazione DMA; criteri e obblighi distinti.','Una qualifica non implica automaticamente le altre.')
put(10,5,'Chi decide nel DSA','Capo III, sezione 5, VLOP/VLOSE~Commissione: competenza esclusiva ex articolo 56.\nAltri obblighi VLOP/VLOSE~Poteri Commissione e coordinatore secondo il riparto, evitando duplicazioni.\nCoordinatore nazionale~Vigilanza e cooperazione nei compiti attribuiti.','La cooperazione non attribuisce a un’autorità nazionale la decisione riservata alla Commissione.')
bando(11,'Studiare la tutela dell’investitore',['Individua emittenti, mercati o servizi richiesti.','TUF, MiFID, MAR e MiCAR.','Informazione, condotta e competenze.','Annota errori fra adeguatezza e appropriatezza.','Caso di investimento e scelta del rimedio.'])
put(11,2,'Tre soggetti del mercato','Emittente~Offre o emette strumenti e adempie gli obblighi pertinenti.\nIntermediario~Presta servizi nel proprio perimetro autorizzato.\nInvestitore~Riceve informazioni e tutele in base a servizio e categoria.','L’approvazione del prospetto non garantisce rendimento o adeguatezza per il singolo cliente.')
put(11,3,'Controllo e possibili esiti','Informazioni e fatti~Acquisisci documenti, condotta e contesto.\nValutazione~Verifica obblighi, difese e competenza.\nEsito senza violazione~Chiusura nei presupposti.\nEsito con criticità~Misura correttiva o sanzione, soltanto se prevista e motivata.','La sanzione è eventuale; il controllo non la rende inevitabile.')
put(11,4,'Tre valutazioni del servizio','Adeguatezza~Consulenza/gestione: esperienza, situazione finanziaria e obiettivi.\nAppropriatezza~Altri servizi: conoscenza/esperienza; avvertenza nei casi pertinenti.\nExecution only~Esenzione dalla verifica soltanto alle condizioni previste.','L’avvertenza non autorizza una raccomandazione senza informazioni necessarie all’adeguatezza.')
put(11,5,'Condotta e rimedi','Documenti~Profilatura, raccomandazione, costi, conflitti e registrazioni.\nVigilanza Consob~Controlla obblighi e adotta gli atti attribuiti.\nACF~Controversia retail nei requisiti, entro il valore previsto.\nGiudice~Tutela individuale con presupposti propri.','La perdita non prova da sola l’illecito e la sanzione non è il risarcimento del cliente.')
bando(12,'Leggere la prudenza e le tutele',['Verifica il peso di banca, assicurazione e diritto privato.','Capitale, liquidità, governance e clientela.','SSM, SREP, SCR/MCR/ORSA e ADR.','Registra scambi fra stock, flussi e requisiti.','Rapporti numerici e canale di tutela motivato.'])
put(12,2,'Vigilanza e controversia','Prudenza~Tenuta dell’intermediario, rischi, capitale e liquidità.\nCondotta~Obblighi verso cliente o assicurato.\nADR~Controversia individuale nel perimetro ABF/ACF/AAS.','Una banca può distribuire una polizza: il nome del venditore non decide da solo l’ADR.')
put(12,3,'Dalla segnalazione all’intervento','Dati~Bilanci, flussi prudenziali, reclami e controlli.\nAnalisi~Qualifica rischio, qualità del dato e responsabilità.\nMisura~Scegli potere e garanzie del regime.\nMonitoraggio~Verifica l’attuazione e gli effetti.','Redditività in calo non equivale automaticamente a dissesto o risoluzione.')
put(12,4,'Capitale e liquidità','Capitale~Capacità di assorbire perdite con fondi ammissibili.\nLiquidità~Capacità di sostenere deflussi e scadenze.\nLCR~Resistenza a stress di breve periodo.\nNSFR~Struttura stabile di finanziamento.','Patrimonio positivo non garantisce disponibilità di cassa per ogni scadenza.')
put(12,5,'Tre ADR, tre oggetti','ABF~Servizi bancari e finanziari, inclusi pagamenti nel perimetro.\nACF~Obblighi nei servizi di investimento verso retail.\nAAS~Controversie da contratto assicurativo concluso.','Reclamo, valori e termini sono nella tabella aggiornata; nel primo anno AAS opera il transitorio indicato.')
bando(13,'Applicare i poteri del Garante',['Individua GDPR, procedimenti e cooperazione nel programma.','Dati personali e tutela amministrativa/giudiziale.','Ruoli, poteri, reclamo e competenza.','Registra automatismi sullo sportello unico.','Istruttoria e misura proporzionata.'])
put(13,2,'Poteri e istanze non sono sinonimi','Indagine~Acquisisce dati e documenti per accertare.\nCorrezione~Avvertimenti, ammonimenti, ordini e limiti nei presupposti.\nReclamo~Istanza dell’interessato circostanziata.\nSegnalazione~Chiunque può sollecitare un controllo.','Reclamo e segnalazione non sono tipi di sanzione.')
put(13,3,'Il percorso del reclamo','Ricezione~Verifica regolarità, contenuto e competenza.\nIstruttoria preliminare~Valuta elementi e possibile chiusura.\nProcedimento eventuale~Contestazione e difesa per gli atti previsti.\nEsito~Archiviazione o misura motivata; non multa automatica.','Tre mesi per informare non coincidono con il termine di decisione del reclamo.')
put(13,4,'Avvertimento, ammonimento e danni','Avvertimento~Trattamento previsto che può violare il GDPR.\nAmmonimento~Violazione già commessa.\nSanzione~Importo determinato con criteri e categorie, non massimo automatico.\nRisarcimento~Domanda al giudice, non liquidazione del Garante.')
put(13,5,'Concorso pubblico e fornitore estero','Trattamento dell’ente italiano~Articolo 55(2): Garante; non si applica articolo 56.\nResponsabile estero~Il luogo del fornitore non sposta da solo la competenza sull’ente.\nRiuso autonomo del fornitore~Qualificazione separata, con eventuale riparto transfrontaliero.','La stessa piattaforma può ospitare trattamenti giuridicamente diversi.')
bando(14,'Qualificare prevenzione e whistleblowing',['Leggi materie e prova ANAC.','Prevenzione, trasparenza, contratti e canali.','RPCT, misure, tutele e competenze.','Annota errori fra motivi personali e oggetto.','Mappa del rischio e caso di ritorsione.'])
put(14,2,'Indirizzo e attuazione','PNA~Strategia e indirizzi nazionali.\nPIAO/PTPCT~Collocano la programmazione interna secondo il regime dell’ente.\nRPCT~Propone, coordina e monitora; gestisce il canale interno nei soggetti obbligati.\nDirigenti e uffici~Attuano le misure nei processi e ne rendono conto.','Il RPCT non assorbe ogni responsabilità organizzativa.')
put(14,3,'Protezione lungo il percorso','Segnalazione qualificata~Contesto, oggetto, fondati motivi e canale nei presupposti.\nGestione~Riservatezza e diligente seguito accompagnano l’esame.\nRitorsione eventuale~Comunicazione ad ANAC ex articolo 19, distinta dal canale esterno della violazione.\nTutela~Presunzioni nei limiti soggettivi; giudice per nullità, ripristino e danni.','La protezione non nasce soltanto dopo la conclusione dell’istruttoria.')
put(14,4,'Quattro distinzioni del caso','Oggetto/movente~Violazione pertinente; i motivi personali sono irrilevanti.\nArticoli 6/19~Segnalazione esterna della violazione e comunicazione di ritorsione.\nSegnalante/facilitatore~Tutele estese, presunzioni non automaticamente identiche.\nANAC/giudice~Accertamento e sanzioni amministrative distinti dai rimedi giudiziari.')
put(14,5,'Prova della ritorsione','Presupposti~Verifica segnalazione protetta e misura lamentata.\nPresunzione~Per il segnalante nel perimetro dell’articolo 17.\nProva contraria~Chi adotta la misura dimostra ragioni estranee.\nSoggetti collegati~Valuta la categoria; non estendere automaticamente l’inversione.','Una motivazione generica di servizio non sostituisce documenti e criteri verificabili.')
bando(15,'Trasformare lo studio in prova',['Rileva formato, tempo, soglia e programma.','Seleziona la materia della traccia.','Applica regola, fatti e competenza.','Registra errore e azione di recupero.','Elaborato, calcolo, memo o orale corretto.'])
put(15,2,'Tre percorsi integrabili','G — Giuridico~Potere, presupposto, procedimento e rimedio.\nE — Economico-regolatorio~Dati, metodo, impatto e incertezza.\nP — Giuridico-economico~Integra regola, mercato e decisione.','Il percorso prevalente orienta il tempo di studio, non elimina le competenze complementari.')
put(15,3,'Dalla traccia alla risposta','Decodifica~Verbo, oggetto, fatti certi e output.\nRegola e competenza~Applica il quadro pertinente, senza inventare dati mancanti.\nAnalisi~Collega documenti, calcoli e garanzie.\nConclusione~Proponi il passo operativo e il suo limite.\nCorrezione~Confronta la soluzione e ripeti la prova.','Dichiarare di non conoscere una norma richiesta non vale il punto fonte della rubrica.')
put(15,4,'Numeri da interpretare','E1~Media 14/26 giorni: controlla l’effetto composizione.\nE2~Netti 6.000/7.000 euro; scenario avverso B −5.000.\nE3~Driver 60/40: costi comuni 180.000/120.000; tariffa didattica 79.','I dati sono quelli dei dossier del laboratorio, non valori osservati di operatori reali.')
put(15,5,'Recupero programmato','Entro 30 giorni~Mappa, fondamentali e prime quattro prove.\nEntro 60 giorni~Verticale dell’ente e altre quattro simulazioni.\nEntro 90 giorni~Dieci tracce corrette, prova a tempo e rifinitura.\nDopo ogni prova~Errore preciso, causa, azione e nuovo tentativo.','Adatta il calendario al bando; non è una garanzia di preparazione universale.')
assert len(data)==70
snap=A/'vol05-native-snapshots';snap.mkdir(exist_ok=True);records=[]
for p in sorted(B.glob('*.md')):
 ch=int(p.name[:2])
 if ch==1:continue
 if (snap/p.name).exists():
  original=(snap/p.name).read_text(encoding='utf8')
 else:
  original=p.read_text(encoding='utf8');(snap/p.name).write_text(original,encoding='utf8')
 before=hashlib.sha256((snap/p.name).read_bytes()).hexdigest();seen=set()
 def render(n,image):
  d=data[ch,n];seen.add(n);native='#### Schema '+str(ch)+'.'+str(n)+' — '+d['title']+'\n\n| Elemento | Lettura operativa |\n|---|---|\n'+'\n'.join('| '+a+' | '+b+' |' for a,b in d['rows'])
  if d['note']:native+='\n\n'+d['note']
  raw=(p.parent/image).resolve() if image else None
  records.append({'file':p.as_posix(),'schema':str(ch)+'.'+str(n),'originalImage':image,'originalSHA256':hashlib.sha256(raw.read_bytes()).hexdigest() if raw and raw.exists() else None,'nativeText':native,'sourceEvidence':'source_refs del capitolo, note di verifica 3 ottobre 2026','sha256Before':before})
  return native
 pattern=r'!\[Figura (\d+)\.(\d+)[^\n]*\]\(([^\n)]+)\)'
 updated=re.sub(pattern,lambda m:render(int(m[2]),m[3]),original)
 updated=re.sub(r'^\*Figura '+str(ch)+r'\.\d+[^\n]*\*\s*\n','',updated,flags=re.M)
 if ch==13 and 3 not in seen:
  raw='../assets/chapter-13/03-flusso-garante-privacy-cooperazione.png';schema=render(3,raw);anchor='### Cooperazione europea: autorità capofila, autorità interessate ed EDPB';assert anchor in updated;updated=updated.replace(anchor,schema+'\n\n'+anchor)
 if ch==13 and 4 not in seen:
  raw='../assets/chapter-13/04-distinzioni-garante-privacy-cooperazione.png';schema=render(4,raw);anchor='### Trasparenza amministrativa e privacy: un bilanciamento, non un conflitto astratto';assert anchor in updated;updated=updated.replace(anchor,schema+'\n\n'+anchor)
 assert seen=={1,2,3,4,5},(ch,seen)
 updated=re.sub(r'asset_refs:\n(?:  - .*\n)+','asset_refs: []\n',updated)
 p.write_text(updated,encoding='utf8');after=hashlib.sha256(p.read_bytes()).hexdigest()
 for r in records:
  if r['file']==p.as_posix():r['sha256After']=after
assert len(records)==70
(A/'VOL-05-native-schemes.json').write_text(json.dumps({'date':'2026-10-03','count':70,'originalsPreserved':True,'method':'Sostituzione editoriale controllata con schemi Markdown, non modifica raster. Contenuto specifico derivato dal testo corretto.','records':records},ensure_ascii=False,indent=2),encoding='utf8');print('70 native schemes, 14 chapters; original assets preserved.')
