"""Controlled editorial replacement, not raster editing. Run once after CLI reopen14."""
from pathlib import Path
import re,json,hashlib
A=Path('artifacts/correzioni-collana-2026-10-02')
B=Path('wiki/books/moduli/m-fc02-agenzie-fiscali/chapters')
data={}
def put(ch,n,title,rows,note=''):
    data[(ch,n)]={'title':title,'rows':[r.split('~',1) for r in rows.split('\n')], 'note':note}
def bando(ch,title,values):
    put(ch,1,title,'\n'.join(k+'~'+v for k,v in zip(['B — Bando','A — Aree','N — Nuclei','D — Diario','O — Output'],values)))
bando(1,'Dalla selezione al percorso fiscale',['Ente, codice del profilo e prove.','Base comune e contenuti fiscali richiesti.','Tributi, dogane, riscossione e distinzioni essenziali.','Rischi di perimetro ed errori da correggere.','Piano, quiz, casi e risposte orali.'])
put(1,2,'Scegliere il perimetro','Dentro il percorso~AE tributario e territorio; ADM dogane, accise, giochi e monopoli; AdER riscossione.\nDa valutare~Profili gestionali, risorse umane o misti: pesare il programma effettivo.\nAltra specializzazione~ICT, appalti o tecnico puro richiedono il percorso corrispondente.','Sono categorie alternative: il nome dell’ente, da solo, non sceglie il programma.')
put(1,3,'Tre funzioni, tre preparazioni','AE~Tributi, servizi fiscali, accertamento, catasto e pubblicità immobiliare.\nADM~Dogane, accise, giochi, monopoli e controlli sui flussi.\nAdER~Riscossione, pagamenti, rateizzazione e relazione con il debitore.','Condividere materie generali non significa avere le stesse priorità.')
put(1,4,'Dalla base comune alla prova','Base~Amministrativo, pubblico impiego, trasparenza, privacy, inglese e digitale.\nApplicazione fiscale~Tributi, accertamento, dogane, riscossione o catasto secondo il bando.\nAllenamento~Quiz, caso, orale o attività di sportello nel formato richiesto.','Collega i tre livelli per costruire una risposta pertinente al profilo.')
put(1,5,'Scheda minima del Decoder','Ente e profilo~Annota amministrazione, codice e funzione.\nProve e materie~Distingui formato, programma comune e parte specialistica.\nRinvii~Individua eventuali parti ICT, appalti o tecniche.\nRischio~Segna perimetri incerti e materie decisive.\nOutput~Trasforma i dati in piano, diario e simulazione.')
bando(2,'Il Decoder fiscale',['Ente, codice, prove e scadenze ufficiali.','Base comune e parte fiscale.','Tributi, dogane, riscossione e catasto richiesti.','Dubbi da verificare ed errori ricorrenti.','Quiz, caso, orale o checklist coerenti con il bando.'])
put(2,2,'Dal codice al programma','1. Ente~Identifica AE, ADM o AdER.\n2. Codice~Leggi sigla e descrizione del profilo, senza dedurre tutto dalla sigla.\n3. Programma~Separa materie comuni, fiscali e di altra specializzazione.\n4. Percorso~Decidi se il percorso fiscale guida lo studio o offre solo un supporto.','La funzione richiesta e il programma verificano l’ipotesi suggerita dal codice.')
put(2,3,'Allenamento per tipo di prova','Quiz~Precisione, tempo, differenze tra istituti; diario degli errori.\nScritto~Definizione, funzione ed esempio; schema di risposta.\nCaso~Fatti, soggetti, vincoli e decisione; griglia ragionata.\nOrale~Lessico e collegamenti; risposta breve cronometrata.\nSituazionale~Ruolo, servizio e legalità; motivazione della scelta.\nTitoli~Documenti, requisiti e ricevute; checklist.','Le righe sono formati differenti, non fasi obbligatorie della stessa selezione.')
put(2,4,'Quattro priorità possibili','Studio subito~Nuclei decisivi per profilo, prova o comprensione delle altre materie.\nStudio dopo~Contenuti utili al completamento del programma.\nVerifico~Sigle, allegati, soglie, banca dati e avvisi ufficiali.\nCambio percorso~Il programma prevalente appartiene a ICT, contratti o ambito tecnico.','La priorità dipende dal bando concreto; nessuna materia è secondaria per definizione.')
put(2,5,'Tre esempi di Decoder','AE tributario~Tributi, accertamento e adempimenti; evitare una preparazione solo generale.\nADM~Dogane, accise, giochi e monopoli; evitare di copiare il piano AE.\nAdER~Riscossione, pagamenti e rateizzazione; distinguere dalla fase impositiva.','Una base comune sostiene tre piani specialistici differenti.')
bando(3,'Organizzazione e risposta d’esame',['Ente e profilo della selezione.','Entrate, dogane, monopoli e riscossione.','MEF, autonomie, organi e uffici.','Confusioni AE/ADM/AdER e accertamento/riscossione.','Risposta orale e scheda funzione-prova.'])
put(3,2,'Istituzioni e relazioni','MEF~Indirizzo e vigilanza secondo l’ordinamento.\nAE e ADM~Agenzie fiscali con autonomia e funzioni tecnico-operative proprie.\nAdER~Ente pubblico economico strumentale ad AE; AE esercita indirizzo operativo e controllo.\nProfilo concorsuale~Chiave per scegliere lessico, materie e prove; non è un ente dell’organigramma.','La relazione istituzionale non rende identiche le funzioni dei soggetti.')
put(3,3,'Lessico delle tre funzioni','AE~Contribuente, adempimento, controllo, accertamento, territorio.\nADM~Merce, operatore, dogana, accisa, gioco pubblico e vigilanza.\nAdER~Debitore, cartella, pagamento, rateizzazione e sospensione.','Prima identifica l’ente competente, poi usa il lessico della funzione.')
put(3,4,'Centro e articolazioni territoriali','Strutture centrali~Indirizzo organizzativo, coordinamento, supporto e controllo.\nRete AE~Servizi e atti verso contribuenti e professionisti.\nPresidi ADM~Operatori, merci e settori regolati.\nSportelli AdER~Posizioni debitorie, pagamenti, rate e sospensioni.','È un confronto funzionale tra enti distinti; l’organigramma concreto va verificato per ciascuno.')
put(3,5,'Pretesa e riscossione','Accertamento~L’ente competente verifica e determina o rettifica la pretesa.\nTitolo e affidamento~La disciplina del titolo stabilisce il raccordo con la riscossione.\nRiscossione~AdER gestisce i carichi affidati e le attività di propria competenza.','Non ogni accertamento conduce a una cartella: distinguere percorso ordinario e atti esecutivi.')
bando(4,'La teoria dell’imposta nella prova',['Tributi e fonti richiesti dal programma.','Principi, redditi e IVA.','Presupposto, soggetti e base imponibile.','Confusioni tassa/imposta e accertamento/riscossione.','Risposta orale, quiz e casi.'])
put(4,2,'Come leggere un rapporto tributario','Qualificazione~Fatto rilevante, presupposto e soggetto obbligato.\nDeterminazione~Base imponibile, aliquota e disciplina dell’imposta.\nAdempimenti~Documenti, dichiarazione e versamenti secondo il tributo.\nVerifiche eventuali~Controlli e atti nei presupposti; non tutti i rapporti subiscono accertamento.\nRiscossione~Adempimento spontaneo o forme previste per il recupero.','La tavola distingue funzioni: non impone controllo e recupero a ogni contribuente.')
put(4,3,'Specie del tributo','Imposta~Prelievo collegato alla capacità contributiva, senza uno specifico servizio individuale.\nTassa~Prelievo collegato a un’attività o servizio pubblico secondo la legge.\nContributo~Prelievo collegato a una posizione o a un vantaggio particolare nel quadro normativo.','Tributo è il genere; tassa non è un sinonimo universale di imposta.')
put(4,4,'Le domande prima del calcolo','Presupposto~Quale fatto, atto o situazione fa sorgere l’obbligo?\nSoggetto~Chi è obbligato, e con quale ruolo?\nBase imponibile~Su quale grandezza si calcola il tributo?\nAliquota e regole~Quale misura si applica e quali correttivi incidono?','La base imponibile non coincide con la somma finale da versare.')
put(4,5,'Dalle nozioni alle discipline','TUIR~Soggetti e categorie di reddito; studio negli adempimenti fiscali.\nIVA~Operazioni, rivalsa e detrazione; studio negli adempimenti fiscali.\nAccertamento~Poteri, garanzie e atti; studio di controlli e compliance.\nRiscossione~Titoli, cartella, pagamenti e rateizzazione; studio del lavoro AdER.','I titoli indicano ambiti di approfondimento, senza numeri locali che possano confondersi con quelli del volume.')
bando(5,'Dal dato alla verifica',['Accertamento, controllo e compliance nel programma.','Controlli e istruttoria.','Atto, motivazione e garanzie.','Confusioni su contraddittorio e riscossione.','Caso fiscale e checklist dell’atto.'])
put(5,2,'Controllo: passaggi ed esiti','Avvio~Dati, anomalie o altri presupposti attivano il controllo competente.\nIstruttoria~Si raccolgono e valutano elementi nel rispetto dei poteri e delle garanzie.\nConfronto~Il contraddittorio si svolge nei casi e modi previsti.\nEsito senza pretesa~Chiarimenti o archiviazione chiudono il rilievo quando ne ricorrono le condizioni.\nEsito impositivo~Se fondato, l’atto motiva fatti, regole e pretesa; tutela e riscossione seguono la propria disciplina.','Archiviazione e atto impositivo sono esiti alternativi: la prima non conduce obbligatoriamente al secondo.')
put(5,3,'Poteri e garanzie da collegare','Potere~Richiesta, accesso o analisi devono avere fonte, finalità e competenza.\nIstruttoria~Documenti e dati diventano elementi valutabili.\nGaranzie~Legalità, pertinenza, contraddittorio nei presupposti e tutela.\nEventuale atto~Motivazione, destinatario, pretesa e rimedi devono essere coerenti.','Il potere istruttorio non predetermina un esito sfavorevole.')
put(5,4,'Gestire il rischio fiscale','Prevenire~Comunicazioni e servizi favoriscono l’adempimento corretto.\nOrientare~Chiarimenti e strumenti di correzione aiutano a rimediare agli errori.\nSelezionare~L’analisi del rischio indirizza i controlli.\nAccertare~Le irregolarità fondate sono trattate con gli strumenti previsti.','Sono funzioni coordinate; compliance non significa rinuncia al controllo.')
put(5,5,'TCF e dialogo preventivo','Organizzazione~Individua operazioni complesse e responsabilità.\nTax Control Framework~Rileva e presidia i rischi; documenta controlli e responsabilità.\nInterlocuzione~Trasparenza e cooperazione preventiva nel regime applicabile.\nAccesso~Requisiti, soglie e certificazioni seguono la disciplina illustrata nel capitolo.','Il solo possesso di controlli interni non attribuisce automaticamente l’accesso al regime.')
bando(6,'Adempimenti da distinguere',['Redditi, IVA e obblighi richiesti.','Qualificazione, dichiarazione e pagamento.','Debito, credito e controllo.','Scambio delle fasi; IVA confusa con utile.','Mappa degli adempimenti e soluzione del caso.'])
put(6,2,'Redditi e IVA: confronto','Imposte sui redditi~Soggetto, periodo, categoria reddituale e regole di determinazione.\nIVA~Operazione, soggetto, territorio, rivalsa e detrazione; liquidazione e dichiarazione.','I due tributi possono interessare lo stesso fatto economico, ma uno non è una fase dell’altro.')
put(6,3,'Funzioni e tempi degli adempimenti','Documento e registri~Rappresentano operazioni e dati fiscalmente rilevanti.\nLiquidazione~Determina il risultato; nell’IVA periodica precede la dichiarazione annuale.\nVersamento~Esegue il pagamento alla propria scadenza; non è sostituito dalla dichiarazione.\nDichiarazione~Espone dati e risultanze del periodo; ha funzione e termine propri.\nAssistenza e controllo~Possono intervenire secondo esigenze e presupposti, senza una sequenza universale.','Non memorizzare “dichiarare → liquidare → versare” come calendario valido per ogni tributo.')
put(6,4,'Tre usi distinti del credito','Riporto~L’eccedenza è trasferita al periodo successivo alle condizioni previste.\nCompensazione~Il credito è utilizzato contro debiti con presupposti, limiti e controlli propri.\nRimborso~La restituzione richiede i presupposti e la procedura applicabili.','L’esistenza del credito non rende automatico nessuno dei tre esiti.')
put(6,5,'Assistenza, compliance e controllo','Servizi~Accesso ai dati, canali e assistenza all’adempimento.\nCompliance~Interlocuzione e correzione spontanea secondo gli strumenti disponibili.\nControllo~Verifica della coerenza e della legalità nei presupposti.','L’ufficio assiste entro competenza: il servizio non sostituisce una decisione né elimina i controlli.')
bando(7,'La funzione della riscossione',['AdER, selezione e attività richieste.','Ente creditore e agente della riscossione.','Titolo, carico e pagamento.','Confusioni tra potere, fase e atto.','Flusso ragionato e caso di sportello.'])
put(7,2,'Due funzioni collegate','Accertamento~L’ente competente determina o rettifica la pretesa con il relativo atto.\nRiscossione~Gestisce il pagamento e il recupero del credito secondo titolo e competenza.','Un problema sulla cartella non autorizza AdER a decidere qualsiasi questione sul merito del tributo.')
put(7,3,'Riscossione: due percorsi e più opzioni','Percorso ordinario~Formazione del ruolo, affidamento e cartella secondo la disciplina applicabile.\nAccertamento esecutivo~L’atto impositivo esecutivo precede l’affidamento; non occorre una nuova cartella.\nPagamento~Può estinguere il debito; la rateizzazione è un’opzione nei presupposti.\nTutela~Sospensione, sgravio e ricorso hanno condizioni, soggetti ed effetti distinti.\nRecupero~In mancanza di pagamento, misure cautelari o esecutive richiedono le condizioni previste.','Rateizzazione, sospensione e ricorso non sono tappe obbligatorie consecutive.')
put(7,4,'Parole vicine, effetti diversi','Cartella~Porta a conoscenza il carico e la richiesta di pagamento nel percorso ordinario.\nPagamento~Adempimento da effettuare con modalità tracciabili.\nRateizzazione~Distribuisce il pagamento nel tempo; non cancella il debito.\nSospensione~Arresta temporaneamente gli effetti nei presupposti; non coincide con lo sgravio.','Per scegliere il rimedio identifica atto, motivo, competenza e termine.')
put(7,5,'Checklist dello sportello AdER','Identità~Verifica soggetto e legittimazione.\nAtto e credito~Individua documento, ente creditore e posizione.\nRichiesta~Distingui pagamento, rate, sospensione e contestazione.\nDocumenti~Controlla ricevute, istanze e informazioni pertinenti.\nEsito~Indica il canale competente e registra l’azione, entro i limiti dell’ufficio.')
bando(8,'Dogane nella prova ADM',['Profilo, dogane e operazioni richieste.','UE, regimi e controlli.','Dichiarazione, classificazione, origine e valore.','Origine confusa con spedizione; valore con fattura.','Caso guidato e checklist della merce.'])
put(8,2,'Lettura della procedura doganale','Operatore e merce~Identifica ruolo, rappresentanza e caratteristiche tecniche.\nIngresso e presentazione~Colloca le formalità applicabili al movimento concreto.\nRegime e dichiarazione~Individua destinazione doganale, dati e documenti.\nControllo e svincolo~Le verifiche seguono rischio e presupposti; lo svincolo richiede le condizioni del regime.\nDopo lo svincolo~Restano possibili verifiche successive secondo la disciplina.','È una traccia per il caso: importazione, esportazione e transito non hanno tutte le stesse formalità.')
put(8,3,'La triade tecnica','Classificazione~Qual è la voce tariffaria della merce?\nOrigine~Qual è il suo legame economico con un Paese, secondo le regole applicabili?\nValore~Quale base economica si determina secondo le regole doganali?','Nome commerciale, Paese di spedizione e prezzo di fattura non risolvono automaticamente le tre domande.')
put(8,4,'Rischio, controlli e status AEO','Analisi del rischio~Orienta selezione e intensità delle verifiche.\nDati e documenti~Consentono riscontri sulle dichiarazioni e sulle operazioni.\nControlli fisici~Verificano le merci quando disposti; non attribuiscono lo status AEO.\nAEO~Autorizzazione basata su requisiti e affidabilità; può comportare facilitazioni e minori controlli.','AEO resta soggetto a controlli. L’autorizzazione è distinta dalla sequenza della singola operazione.')
put(8,5,'Checklist della dichiarazione doganale','Soggetto~Operatore, ruolo e rappresentanza.\nMerce e regime~Descrizione tecnica e destinazione doganale.\nTriade~Classificazione, origine e valore, ciascuno con i propri elementi.\nDocumenti~Prove, fatture, autorizzazioni e dati necessari.\nRischio~Controlli coerenti con merci, operatore e operazione.','Prima qualifica il caso; il calcolo del dazio viene dopo.')
bando(9,'Accise, giochi e monopoli',['Profilo ADM e settori richiesti.','Prodotti, giochi e monopoli.','Deposito, regime, titolo e controllo.','IVA/accisa e gioco legale/illecito.','Glossario settoriale e caso guidato.'])
put(9,2,'Seguire una filiera di accisa','Prodotto~Individua la categoria e la disciplina pertinente.\nSoggetto e luogo~Distingui qualifiche, deposito e autorizzazioni.\nRegime~Separa sospensione e prodotto già immesso in consumo.\nMovimento~Usa documenti e circuito corretti: e-AD ed e-DAS unionale non coincidono.\nEsigibilità~Individua il fatto rilevante secondo la disciplina, senza confonderlo con la mera circolazione.\nControllo~Verifica coerenza di merci, documenti e titoli.','Sospensione non significa esenzione; il destinatario registrato non acquista una generale facoltà di detenzione sospensiva.')
put(9,3,'Settori da riconoscere','Prodotti energetici ed energia~Prodotto, uso, fornitura, circolazione e regime.\nAlcole e bevande alcoliche~Filiera, soggetti e imposizione specifica.\nTabacchi~Prodotti regolati, rete e titoli.\nGiochi~Concessioni, legalità, dati e vigilanza.','La tavola confronta settori: non equipara tutti i giochi ai prodotti soggetti ad accisa.')
put(9,4,'Elementi del controllo ADM','Prodotto~Natura e quantità.\nLuogo~Deposito, punto vendita o altro luogo rilevante.\nSoggetto~Qualifica, titolo e attività.\nDocumenti e dati~Tracciati, coerenza e anomalie.\nEsito~Riscontro, verbalizzazione e conseguenze nei presupposti.','Prodotto, luogo, soggetto e dati si valutano insieme: non sono passaggi cronologici obbligati.')
put(9,5,'Checklist per la risposta settoriale','Materia e prodotto~Accisa, gioco o monopolio; categoria concreta.\nLuogo e soggetto~Rete, deposito, operatore e titolo.\nRegime e documenti~Sospensione o consumo; circuito e tracciati corretti.\nControllo~Rischio, legalità e riscontri.\nConseguenze~Qualifica la violazione e usa la norma vigente, evitando sanzioni presunte.')
bando(10,'Territorio e pubblicità immobiliare',['Profilo tecnico, catastale o SPI.','Catasto, cartografia, estimo, OMI e registri.','Dato, mappa, valore e formalità.','Visura/proprietà e rendita/mercato.','Glossario, caso e checklist.'])
put(10,2,'Quattro piani del territorio','Catasto~Identifica e classifica i beni.\nCartografia~Rappresenta territorio e particelle.\nEstimo e OMI~La stima valuta il bene; OMI offre dati di mercato di supporto.\nPubblicità immobiliare~Rende conoscibili vicende giuridiche tramite registri e formalità.','I piani dialogano, ma non coincidono.')
put(10,3,'Identificare e qualificare il bene','Identificativo~Comune, foglio, particella e, ove presente, subalterno.\nClassamento~Categoria, classe e consistenza secondo la disciplina del bene.\nRendita~Dato catastale risultante dal sistema applicabile.\nTitolo giuridico~Si ricostruisce con gli atti e i registri pertinenti.','La sequenza di lettura non trasforma l’identificativo o la rendita in prova della proprietà.')
put(10,4,'Scegliere il servizio','Visura~Consulta dati catastali per immobile o soggetto.\nPlanimetria e cartografia~Rappresentano l’unità o il territorio nei rispettivi sistemi.\nVoltura e rettifica~Aggiornano intestazioni o correggono dati nei presupposti.\nIspezione~Consulta registri e formalità di pubblicità immobiliare.\nOMI~Fornisce quotazioni utili al confronto, non una perizia individuale.','La domanda dell’utente determina quale servizio è pertinente.')
put(10,5,'Checklist del caso immobiliare','Ambito~Catasto, stima, cartografia o pubblicità immobiliare?\nIdentificativo e dato~Localizza il bene e distingue categoria, classe e rendita.\nServizio e mappa~Scegli consultazione o aggiornamento pertinente.\nValore e formalità~Separa stima e dati OMI da trascrizione o iscrizione.\nRisposta~Esplicita limite del dato e documento necessario.')
bando(11,'Bilancio e fisco',['Contabilità ed economia d’impresa nel programma.','Bilancio, scritture e raccordo fiscale.','Ricavi, costi e patrimonio.','Utile/reddito e ricavo/incasso.','Mini-caso numerico e risposta orale.'])
put(11,2,'Documenti del bilancio ordinario','Stato patrimoniale~Attività, passività e patrimonio netto alla chiusura.\nConto economico~Ricavi, costi e risultato dell’esercizio.\nRendiconto finanziario~Flussi delle disponibilità liquide.\nNota integrativa~Criteri, dettagli e informazioni esplicative.','Le forme abbreviate e per micro-imprese prevedono gli esoneri di legge: i quattro documenti descrivono il bilancio ordinario.')
put(11,3,'Competenza e movimento monetario','Piano economico~Ricavi e costi concorrono al risultato secondo competenza.\nPiano monetario~Incassi e pagamenti modificano la liquidità.\nVendita a credito~Un ricavo di dicembre può essere incassato a gennaio.\nPagamento anticipato~Il pagamento odierno può riferirsi a costi di periodi successivi.','Ricavo non significa incasso; costo non significa pagamento.')
put(11,4,'Dal risultato contabile al tributo','Operazioni e scritture~Ricostruisci fatti economici e documenti.\nBilancio~Determina utile o perdita secondo regole contabili.\nRegole fiscali~Applica variazioni e limiti per determinare il reddito imponibile.\nImposta e dichiarazione~Calcola e rappresenta le risultanze secondo la disciplina.\nControllo eventuale~Verifica documenti e coerenza nei presupposti.','Utile, reddito imponibile e imposta sono grandezze diverse.')
put(11,5,'Checklist bilancio-fisco','Documento~Bilancio, fattura, scrittura o altro dato?\nGrandezza~Ricavo, costo, credito, debito o flusso?\nPiano~Economico, patrimoniale, monetario o fiscale?\nRegola~Individua periodo e criterio pertinente.\nOutput~Spiega il calcolo o la distinzione e controlla l’errore tipico.')
bando(12,'Civile e commerciale nel caso fiscale',['Materie civilistiche richieste.','Obbligazioni e contratti.','Impresa, società e soggetti.','Piani confusi e automatismi sulla crisi.','Caso qualificato e checklist.'])
put(12,2,'La parola credito su tre piani','Rapporto privato~Contratto, fornitore, cliente e adempimento.\nObbligo tributario~Presupposto, soggetto, dichiarazione e pagamento.\nRiscossione~Ente creditore, titolo, posizione e tutela.','La parola comune non rende uguali fonti, competenze e rimedi.')
put(12,3,'Contratto, fattura, pagamento e scrittura','Contratto~Regola il rapporto e le obbligazioni.\nFattura~Documenta l’operazione secondo la disciplina fiscale.\nPagamento~È un flusso monetario, con un proprio momento.\nContabilità~Rileva i fatti secondo le regole; può precedere incasso o pagamento.\nFisco~Applica i propri presupposti e criteri.','Non è una cronologia universale: fattura e pagamento possono avere tempi diversi; la contabilità non attende sempre il pagamento.')
put(12,4,'La stessa impresa, domande diverse','Soggetto~Individua impresa o società, poteri e patrimonio.\nNel caso AE~Dichiarazioni, bilancio e controlli fiscali.\nNel caso ADM~Merci, operatore, titoli e documenti doganali.\nNel caso AdER~Posizione debitoria, pagamento e strumenti previsti.','Le righe confrontano applicazioni diverse, non una gerarchia fra enti.')
put(12,5,'Checklist civile-commerciale','Soggetto e poteri~Persona, società o ente; rappresentanza e delega.\nRapporto~Contratto o altra fonte dell’obbligazione.\nDocumento e patrimonio~Fattura, bilancio, beni, crediti e debiti.\nDisciplina~Separa civile, fisco, dogane e riscossione.\nCrisi e output~Verifica i presupposti senza automatismi e formula la risposta al caso.')
bando(13,'Dallo studio alla prestazione',['Formato, soglie, tempi e avvisi della prova.','Tributi, dogane e riscossione pertinenti.','Enti, atti, competenze e sequenze.','Errori di memoria, lettura o confusione dei piani.','Simulazione e piano di recupero 30/60/90.'])
put(13,2,'Quiz in quattro mosse','1. Leggi~Individua richiesta, negazioni e parole decisive.\n2. Escludi~Elimina opzioni incompatibili con soggetto, fase o istituto.\n3. Scegli~Confronta le alternative rimaste nel perimetro della domanda.\n4. Controlla~Rileggi assoluti e negazioni prima di confermare.','Con banca dati verifica versione e programma; senza banca dati allena i nuclei del bando. Nel diario annota causa dell’errore e azione correttiva.')
put(13,3,'Tre casi, una griglia di lettura','Caso AE~Dichiarazioni, controlli e compliance.\nCaso ADM~Merci, classificazione, origine, valore e controlli.\nCaso AdER~Titolo, pagamento, rateizzazione e sportello.\nGriglia comune~Fatto, soggetti, materia, istituto, fase e output.','AE, ADM e AdER sono contesti alternativi: non rappresentano tre tappe consecutive del caso.')
put(13,4,'Risposta orale da 90 secondi','Definizione e funzione~Spiega l’istituto e a che cosa serve.\nSoggetti e sequenza~Indica competenze e passaggi pertinenti.\nEsempio~Applica la distinzione al profilo fiscale.\nLimite~Chiudi precisando ciò che non va confuso.','Se la domanda contiene una premessa errata, correggila prima di sviluppare la risposta.')
put(13,5,'Simulazione e recupero','Quiz — 35 minuti~Registra punteggio e domande lente.\nCaso — 25 minuti~Compila griglia e conclusione.\nOrale — 20 minuti~Prepara, prova e riesamina tre risposte brevi.\nDiario — 10 minuti~Individua cause degli errori e azioni verificabili.\nPiano 30/60/90~Riorganizza fondamentali, casi, simulazioni e rifinitura secondo i risultati.','I tempi sono un allenamento proposto; il calendario della selezione resta quello del bando.')
bando(14,'Usare le appendici operative',['Parole-spia, peso e forma della prova.','Ciclo operativo cui appartiene il problema.','Definizioni e distinzioni del glossario.','Errori da recuperare e nuovi tentativi.','Canvas, checklist orale e piano di ripasso.'])
put(14,2,'Dalla domanda allo strumento','Definizione incerta~Appendice A: glossario ragionato.\nIstituti simili~Appendice B: tavole di confronto.\nTempi e passaggi~Appendici C e D: scadenziario e schemi di processo.\nApplicazione~Appendice E: canvas compilabili; F: sanzioni, reati, processo e UE.\nVerifica e recupero~Appendice G: checklist orale; H: piano di ripasso.','Scegli lo strumento, compilalo, confrontalo con l’esempio e annota l’errore: le lettere indicano queste appendici effettive.')
put(14,3,'Protocollo di front-office','Ascolta e identifica~Qualifica richiesta, urgenza, identità e legittimazione.\nDistingui la competenza~AE, ADM, AdER o altro soggetto; verifica atto e posizione.\nProteggi i dati~Usa soltanto informazioni necessarie e canali consentiti.\nOrienta~Indica documenti, termini e ufficio pertinente senza promettere esiti.\nChiudi e traccia~Registra l’azione e inoltra il caso quando eccede la competenza.','La protezione dei dati accompagna ogni passaggio, non inizia solo a pratica conclusa.')
put(14,4,'Qualificare condotte e conseguenze','Fatto~Identifica condotta, soggetto e documento.\nPiano~Distingui recupero del tributo, illecito amministrativo e fattispecie penale.\nRegola~Verifica elementi, condizioni e disciplina temporale applicabile.\nTutela~Collega procedimento e rimedio corretto.\nRisposta~Motiva la qualificazione, senza usare “reato” per ogni irregolarità.','Doveri del dipendente, responsabilità tributaria e responsabilità penale restano piani distinti.')
put(14,5,'UE, dogane e operatore','Cornice UE e CDU~Individuano regole comuni, regimi e formalità doganali.\nADM~Applica e controlla nell’ambito delle proprie attribuzioni.\nMerce~Dichiarazione, classificazione, origine e valore qualificano l’operazione.\nEORI~Numero di registrazione e identificazione dell’operatore nei rapporti doganali.\nAEO~Status autorizzato in presenza di requisiti; facilitazioni e controlli secondo la disciplina.','EORI non certifica affidabilità AEO. Lo status AEO non elimina il potere di controllo.')

assert len(data)==70
records=[];snap=A/'vol03-native-snapshots';snap.mkdir(exist_ok=True)
for p in sorted(B.glob('*.md')):
    ch=int(re.match(r'\d+',p.name).group())
    original=p.read_text(encoding='utf8')
    matches=list(re.finditer(r'!\[Figura (\d+)\.(\d+) - ([^\]]+)\]\(([^)]+)\)',original))
    if not matches:continue
    assert len(matches)==5,p
    (snap/p.name).write_text(original,encoding='utf8')
    before=hashlib.sha256(p.read_bytes()).hexdigest()
    def replace(m):
        key=(int(m[1]),int(m[2])); d=data[key]
        table='| Elemento | Lettura operativa |\n|---|---|\n'+'\n'.join('| '+a+' | '+b+' |' for a,b in d['rows'])
        result=f"**Schema {m[1]}.{m[2]} — {d['title']}**\n\n{table}"
        if d['note']:result+='\n\n'+d['note']
        records.append({'file':p.as_posix(),'schema':f'{m[1]}.{m[2]}','originalImage':m[4],'nativeText':result,'sourceNote':'wiki/sources/vol-03-schemi-fiscali-verifica-2026-10-03.md'})
        return result
    updated=re.sub(r'!\[Figura (\d+)\.(\d+) - ([^\]]+)\]\(([^)]+)\)',replace,original)
    updated=re.sub(r'asset_refs:\n(?:  - .*\n)+','asset_refs: []\n',updated)
    updated=updated.replace('source_refs: [','source_refs: ["sources/vol-03-schemi-fiscali-verifica-2026-10-03", ',1)
    # Reconcile a residual prose instruction with the corrected IVA diagram.
    if ch==6:
        old='La correzione è ripetere: fatto, soggetto, tributo, documento, dichiarazione, liquidazione, pagamento ed eventuale controllo. Se una risposta salta un passaggio, probabilmente sovrappone due fasi.'
        new='La correzione è distinguere fatto, soggetto, tributo, documento, liquidazione, dichiarazione, pagamento ed eventuale controllo. Colloca poi ogni adempimento nel suo tempo: nell’IVA periodica liquidazioni e versamenti precedono la dichiarazione annuale. Un elenco di funzioni non è una cronologia valida per ogni tributo.'
        assert old in updated
        updated=updated.replace(old,new)
    p.write_text(updated,encoding='utf8')
    for r in records:
        if r['file']==p.as_posix():r.update(sha256Before=before,sha256After=hashlib.sha256(p.read_bytes()).hexdigest())
assert len(records)==70
(A/'VOL-03-native-schemes.json').write_text(json.dumps({'date':'2026-10-03','count':70,'originalsPreserved':True,'method':'Native Markdown tables, individually authored after visual review of all originals. No raster editing.','records':records},ensure_ascii=False,indent=2),encoding='utf8')
print(json.dumps({'schemas':len(records),'chapters':len(set(r['file'] for r in records))}))
