from pathlib import Path
import json
A=Path(__file__).parent;D=A/'vol01-native';inv=json.loads((A/'VOL-01-native-inventory.json').read_text(encoding='utf8'));v=json.loads((A/'VOL-01-native-verifica.json').read_text(encoding='utf8'))
report=Path('wiki/reviews/correzioni-collana-2026-10-02/VOL-01-schemi-nativi.md')
parts=['# VOL-01 — Conversione degli schemi e verifica di stampa','', '## 1. Sintesi editoriale','', 'Le 133 figure residue dei capitoli 1–24 sono state esaminate una per una, leggendo l’immagine, i testi del relativo SVG e il contesto del capitolo. Sono tutte schemi di testo e relazioni: sono state sostituite con tabelle, sequenze e confronti Markdown. Le 19 immagini già ridisegnate per la stampa sono state conservate integralmente. La verifica della nuova impaginazione è in corso.', '', '## 2. Criteri applicati','', 'Preservati funzione didattica, ordine dei passaggi, confronti, esempi, dati e relazioni. Le divergenze tra vecchia grafica e testo corrente sono state risolte a favore del contenuto aggiornato. I titoletti usano H3; il numero e la descrizione dello schema sono all’apertura, per evitare didascalie isolate nella pagina successiva. Nessun asset raster è stato manipolato.', '', '## 3. Registro per apparato','', '| ID | Asset originario | Problema | Correzione | Verifica nel Book Studio / PDF | Esito |','|---|---|---|---|---|---|']
for r in inv:
 title=(D/(r['id']+'.md')).read_text(encoding='utf8').splitlines()[0].removeprefix('### ')
 parts.append(f"| {r['id']} | `{r['path']}` | Testo ridotto dentro immagine 1600 px; leggibilità a stampa insufficiente. | {title}. Tabella o sequenza nativa nel capitolo `{r['chapter']}`. | Originale e semantica verificati; impaginato in verifica. | Applicato; PDF pendente. |")
parts+=['','## 4. Osservazioni per capitolo','','Sono interessati tutti i 24 capitoli. I 133 testi sostitutivi sono conservati separatamente in `artifacts/correzioni-collana-2026-10-02/vol01-native/F001.md`–`F133.md`; i capitoli precedenti all’intervento sono in `vol01-native/before/`. L’inventario conserva testi SVG, contesto, asset, pagina precedente e hash.','','## 5. Coerenza globale','','La conversione mantiene la progressione BANDO. Sono stati precisati, dove necessario: categorie del Decoder; primato e competenze UE; silenzio e accessi; responsabilità; competenza e cassa; calcoli e percentuali del calendario; condizioni per saltare e rivedere un quiz; differenza tra durata di esercizio e durata obbligatoria della prova; filtri di scelta dei moduli. Le 19 immagini protette mantengono hash e riferimenti invariati.','','## 6. Evidenze','','`VOL-01-native-verifica.json`: 133 riferimenti originari assenti, 133 blocchi sostitutivi presenti una sola volta, hash dei 133 asset originari invariati, 19 asset protetti invariati con riferimenti invariati. `VOL-01-native-ledger.json`: registro delle modifiche. `M-PA01-freeze.json`: sezione aggiuntiva `controlledNativePrintCorrections`, senza sovrascrivere le evidenze storiche.','','## 7. Suggerimenti facoltativi','','Nessuna grafica decorativa aggiunta. I file originali restano disponibili per confronto e tracciabilità.','','## 8. Priorità degli interventi','','Completare la verifica visiva del PDF rigenerato su tutte le sostituzioni e sulle 19 immagini conservate. Ricontrollare il raccordo tra mini-esercizio e griglia nel capitolo 19.','','## 9. Giudizio di pubblicabilità','','Le sostituzioni testuali sono applicate e verificate rispetto all’inventario. Non è ancora attestata la qualità della nuova impaginazione; non si dichiara la pubblicabilità del volume e non si esegue il gate 24.','','## 10. Limiti','','La revisione semantica riguarda gli apparati e il loro contesto. Non costituisce una nuova certificazione normativa dell’intero volume. I controlli DOM e il PDF hanno mostrato una differenza di paginazione: la mappa degli apparati viene quindi costruita sul PDF effettivo, non sulle sole metriche del browser. La prova a schermo non sostituisce una prova fisica.','']
report.write_text('\n'.join(parts),encoding='utf8');print(report)
