from pathlib import Path
import re,json
B=Path('wiki/books/volumi/vol-06-scuola-universita-ricerca-cultura');A=Path('artifacts/correzioni-collana-2026-10-02')
p=B/'planning/01-indice-analitico.md';t=p.read_text(encoding='utf8').replace('Target editoriale complessivo: 135.100 parole, inclusi front matter e appendici. Ogni riga è un capitolo programmato, non ancora una dichiarazione di copertura completa o di review normativa conclusa.','Inventario corrente: 50 capitoli nei quattro moduli. Gli apparati indicati sotto sono integrati nei capitoli; non sono promesse appendici separate inesistenti. Il vecchio target di 135.100 parole è storico e non misura il testo attuale. Verifica del PDF e controlli finali restano necessari.').replace('Apparati progettuali storici, ora sviluppati nei capitoli 04–12: 4.800 parole. Target: 32.700 parole.','Apparati effettivi nei capitoli: bilancio numerico e missione nei 04–05; mini-proposta, h-index e piano tecnico nei 06–08; brevetto, DMP e budget nei 09–11; quattro elaborati risolti nel 12. Nessuna appendice separata promessa; il target storico non descrive la lunghezza corrente.').replace("Appendici: archivisti-bibliotecari; archeologia e storia dell'arte; restauro e architettura; quizario assistenti; atlante MiC e piano 30/60/90. Target: 35.000 parole.","Apparati effettivi nei capitoli: organigramma nel 02; casi del Codice nei 03–05; collaudo digitale e schede archivistica/bibliografica nei 06–08; stratigrafia e scheda d'opera nei 09–10; casi di conservazione, progettazione e sicurezza nei 11–13. Quiz presenti in ciascuno dei 13 capitoli. Non sono promessi atlante o piano 30/60/90 separati, né un corso completo per ogni specializzazione tecnica.")
links={
'- B-PA: [[books/il-metodo-bando/index|VOL-01]].':'- Per il procedimento amministrativo comune si usa il capitolo pertinente del VOL-01; l’indice di volume è una navigazione, non la dichiarazione di uno specifico rinvio didattico.',
'- Digitale specialistico e data science avanzata: VOL-08.':'- Modello relazionale: [[books/moduli/m-tr01-ict-trasformazione-digitale/chapters/04-basi-dati-sql-nosql-qualita-dato#N-TR01-04-01 · Dai requisiti al modello relazionale]]. L’indicazione non promette ogni dominio della data science.',
'- Procurement, fondi UE e PNRR avanzati: VOL-09.':'- Decisione di contrarre e fascicolo di gara: [[books/moduli/m-tr02-appalti-pnrr-fondi-ue/chapters/04-progettazione-gara-documenti#N-TR02-04-01 · Decisione di contrarre e documenti]]. Finanziamenti e rendicontazione assegnati al VOL-06 restano spiegati nei relativi capitoli.',
'- Progettazione tecnica e cantieri complessi: VOL-10.':'- Livelli della progettazione: [[books/moduli/m-tr03-tecnico-ingegneristico/chapters/07-progettazione-opere-pubbliche#N-TR03-07-03 · I livelli della progettazione]]. Non sostituisce la preparazione tecnica professionale richiesta dal singolo bando.'}
for old,new in links.items():assert old in t;t=t.replace(old,new)
t=t.replace('status: outline_ready','status: text-reconciled').replace('updated_at: 2026-07-29','updated_at: 2026-10-03');p.write_text(t,encoding='utf8')
for target in re.findall(r'\[\[([^\]|]+#[^\]|]+)',t):
 f,h=target.split('#',1);dest=Path('wiki')/(f+'.md');assert dest.exists() and any(l.lstrip('# ').strip()==h for l in dest.read_text(encoding='utf8').splitlines() if l.startswith('#')),target
p=B/'index.md';t=p.read_text(encoding='utf8').replace('status: publication-candidate','status: editorial_revision').replace('draft_stage: publication-candidate','draft_stage: corrections-applied').replace('review_required: false','review_required: true').replace('updated_at: 2026-08-23','updated_at: 2026-10-03').replace('ogni capitolo sviluppa esclusivamente il delta di comparto o di profilo e rinvia con destinazione precisa al [[books/il-metodo-bando/index|VOL-01]].','i capitoli sviluppano il delta di comparto o di profilo; i rinvii didattici puntuali sono verificati nel testo. [[books/il-metodo-bando/index|VOL-01]] resta l’indice di navigazione del manuale comune.').replace('Il dossier assume come riferimento il 24 luglio 2026. Bandi, CCNL, programmi, assetti organizzativi e fonti regolamentari devono essere verificati prima del text freeze di ogni modulo.','Il dossier storico assumeva il 24 luglio 2026. Le correzioni del 3 ottobre 2026 hanno aggiornato le fonti nei perimetri documentati e riconciliato 50 capitoli. Le verifiche normative sono selettive; il nuovo PDF e i controlli finali restano necessari. Gli stati della pipeline sono mantenuti dal CLI.');p.write_text(t,encoding='utf8')
p=B/'planning/00-scheda-pipeline.md';t=p.read_text(encoding='utf8').replace('status: publication-candidate','status: editorial_revision');p.write_text(t,encoding='utf8')
mods=['m-ir01-scuola','m-ir02-universita-afam','m-ir03-enti-ricerca','m-ir04-cultura-beni-culturali'];inv=[]
for mod in mods:
 for p in sorted((Path('wiki/books/moduli')/mod/'chapters').glob('*.md')):
  t=p.read_text(encoding='utf8');inv.append({'path':p.as_posix(),'title':re.search(r'^title: (.*)$',t,re.M)[1],'legacy':not bool(re.search(r'^format_version: 2$',t,re.M))})
assert len(inv)==50,len(inv)
(A/'VOL-06-inventory-corrected.json').write_text(json.dumps(inv,ensure_ascii=False,indent=2),encoding='utf8')
report='# VOL-06 — Inventario degli apparati e dei rinvii, 3 ottobre 2026\n\n50 capitoli effettivi; apparati integrati, nessuna appendice separata promessa. IR01 resta legacy, senza falsa promozione al formato 2. IR02/03/04 hanno 60/60/65 nuclei. Correzioni testuali e controllo PDF sono stati distinti.\n\n'
report+='| File | Titolo | Formato |\n| --- | --- | --- |\n'+'\n'.join(f"| [[{x['path'][5:-3]}]] | {x['title']} | {'legacy' if x['legacy'] else '2'} |" for x in inv)+'\n\nL’indice analitico corrente sostituisce le precedenti promesse di appendici contenute nei piani storici. I rinvii a SQL, fascicolo di gara e livelli di progettazione sono stati risolti a heading esistenti e letti nel loro ambito. Non sono rinvii totali a ogni materia delle altre famiglie.\n'
(B/'planning/04-inventario-apparati-correzioni-2026-10-03.md').write_text(report,encoding='utf8')
print('VOL06 inventario 50 capitoli e indici riconciliati')
